### ISSUE TITLE
是否支持k8s集群部署?

### ISSUE THREAD

**Issue by outshineamaze** [Tencent/bk-ci#10]
gitlab支持gke的集群部署模式,  bk-ci能否也支持一键集群部署上去

**Comment by irwinsun** [comment]
我们是有这计划，当前在优化部署的流程，固化流程之后会制作好镜像供大家下载使用。

**Comment by haitongz** [comment]
> 我们是有这计划，当前在优化部署的流程，固化流程之后会制作好镜像供大家下载使用。

期待

**Comment by irwinsun** [comment]
#4935
