### ISSUE TITLE
环境变量增加构件下载地址

### ISSUE THREAD

**Issue by xkelvinx666** [Tencent/bk-ci#1009]
### 作为
开发团队的前端，团队使用前后端分离方案

### 我希望
环境变量增加构件下载地址，并支持通过机器人消息发出

### 以便于
- 后端同学只需下载每次构件至本机环境，避免每次重新编译前端代码
- 大型前端项目，编译时间过久，减少等待时间

**Comment by fayewong-v5** [comment]
我们可以用下边的思路来实现这个需求：
1、平台提供插件SDK方法，方便插件开发者获取到上游产出的所有构件信息（包含下载地址）
2、你可以联系包含机器人消息功能的插件开发，一起协同完成这个功能

**Comment by xkelvinx666** [comment]
已联系机器人消息插件开发作者
