### ISSUE TITLE
bug: 没有对 ProjectUpdateBroadCastEvent 的 Exchange 做初始化

### ISSUE THREAD

**Issue by hingbong** [Tencent/bk-ci#1017]
**Describe the bug**
没有对 com.tencent.devops.project.pojo.mq.ProjectUpdateBroadCastEvent 的 Exchange 做初始化导致调用 com.tencent.devops.project.service.impl.AbsProjectServiceImpl.update() 方法时发生异常：
![image](https://user-images.githubusercontent.com/26398240/78102009-c5d17900-741b-11ea-8665-106128b7e97a.png)

**Comment by irwinsun** [comment]
蓝盾流水线评论: 开发已自测通过，已发布到测试服，请测试团队测试

**Comment by irwinsun** [comment]
蓝盾流水线评论: 已部署到灰度环境
