### ISSUE TITLE
支持跨项目拉取构件

### ISSUE THREAD

**Issue by eternalsea** [Tencent/bk-ci#1019]
### 作为
DevOps 的使用者，要实践持续部署流水线

### 我希望
支持跨项目 拉取构件 （可以采用授权 或者子项目的方式）

### 以便于
- 让 运行自动化测试 等下游环节可以脱离主项目独立管理

**Comment by zanyzhao** [comment]
现在有“推送至其它项目自定义仓库”插件，应该可以实现类似功能，如果满足不了，可以使用产物下载的API在流水线中调用
