### ISSUE TITLE
【优化】手工执行时禁止修改参数

### ISSUE THREAD

**Issue by xdc0209** [Tencent/bk-ci#1021]
### 作为
团队里的Dev，要实践持续部署流水线 

### 我希望
提供配置选项，可以在执行流水线页面禁止修改参数。必须去模板的实例页面修改。

流水线执行页面：错误。这里修改只对当次有效。下次手工执行或者是git事件触发还是用模板中的流线参数的。我们真实的事例：手工执行时改了参数，但是git自动触发用的老的参数，然后发布到现网就出问题了。
![image](https://user-images.githubusercontent.com/3997527/78109308-8448ca00-742b-11ea-9e01-6f95c1a691f8.png)

模板的实例页面修改页面：正确。
![image](https://user-images.githubusercontent.com/3997527/78110902-62047b80-742e-11ea-88b5-8db67537d152.png)

希望再此添加选项：手工执行时禁止修改参数。
![image](https://user-images.githubusercontent.com/3997527/78110919-67fa5c80-742e-11ea-9573-8ef286dc6243.png)

**Comment by iccengan** [comment]
> 提供配置选项，可以在执行流水线页面禁止修改参数。必须去模板的实例页面修改。

在1-1中配置变量在手动执行时不显示，是否能满足你的需求。
![image](https://user-images.githubusercontent.com/10875468/88778906-b12fa280-d1bb-11ea-805d-267b8c3d7ba5.png)

**Comment by iccengan** [comment]
> 流水线执行页面：错误。这里修改只对当次有效。下次手工执行或者是git事件触发还是用模板中的流线参数的。我们真实的事例：手工执行时改了参数，但是git自动触发用的老的参数，然后发布到现网就出问题了。

设计如此。只能通过模板来更改变量的默认值。如果需要覆盖默认值，则每次手动触发都需要填入新的值。
