### ISSUE TITLE
[Feature] 串行流水线复数任务排队时，希望加入功能自动跳过中间排队项。

### ISSUE THREAD

**Issue by YKZDY** [Tencent/bk-ci#1025]
### 我希望
当有N个在任务排队时，在当前流水线执行结束后，加入选项允许自动跳过正在排队的N-1个任务，直接执行当前最后一个排队任务。

### 以便于
- 流水线为Git事件自动触发，团队规模较大，导致触发相对频繁。
- 流水线内含有自动测试模块，测试较为复杂，单次流水线执行时间较长。
- 当有N个任务在排队时，项目只关心最新一次提交的发布结果，等待每一次中间流水线完成将极为耗时，很多时候需要管理员手动终止中间流水线。

### 期望的验收标准
- 在基础设置/运行锁定中加入一个新的选项，勾选后在任务完成后自动跳过所有中间排队任务。

**Comment by iccengan** [comment]
关联issue：#411
