### ISSUE TITLE
流水线支持导入/导出为JSON

### ISSUE THREAD

**Issue by taohuifa** [Tencent/bk-ci#1030]
### 作为
后台开发

### 我希望
流水线能支持配置导出和导入功能

### 以便于
跨项目, 跨蓝盾平台的流水线导入

### 期望的验收标准
- 在一个项目的流水线中有导出功能, 导出成一个文本或者文本内容.
- 切换成别的项目或者海外蓝盾平台, 新建一个流水线, 支持导入内容能快速创建出一样的流水线.

**Comment by iccengan** [comment]
注：如果支持使用yaml文件导入已存在流水线来覆盖编排，需确保已支持流水线历史编排版本管理功能：#671

**Comment by zanyzhao** [comment]
1. 流水线详情页“更多”按钮下增加“导出json”
2. 将现有的新建流水线按钮改为下拉框，增加导入流水线入口
![image](https://user-images.githubusercontent.com/1629409/91416348-d62e3880-e881-11ea-8625-565c56464829.png)
3. 点击导入后弹窗
![image](https://user-images.githubusercontent.com/1629409/91416387-e5ad8180-e881-11ea-9621-14ae3c2475a2.png)
4. 点击确定后进行如下操作：
  1. 创建空白流水线
  2. 进入流水线编辑页
  3. 根据json自动填充流水线编排（处于草稿状态，尚未保存）

**Comment by iccengan** [comment]
需考虑以下异常场景（待补充）：
1. A项目流水线插件在B项目内没有安装
