### ISSUE TITLE
希望提供一个能够等待当前节点完成再执行停止流水线功能

### ISSUE THREAD

**Issue by gaviviliu** [Tencent/bk-ci#1033]
### 作为
客户端开发

### 我希望
希望提供一个能够等待当前节点完成再执行停止流水线功能

### 以便于
一些脚本直接停止可能会影响到环境编译，希望能够提供一个能够等待当前节点完成再执行停止流水线功能

### 期望的验收标准
增加一个能够等待当前节点完成再停止当前流水线的功能

**Comment by zanyzhao** [comment]
Duplicate of #1156
