### ISSUE TITLE
希望能够提供一个子流水线设的变量在本次执行的主流水线上能获取到

### ISSUE THREAD

**Issue by gaviviliu** [Tencent/bk-ci#1034]
### 作为
客户端

### 我希望
希望能够提供一个子流水线设的变量在本次执行的主流水线上能获取到

### 以便于
子流水线产生的一些中间参数能够最后给到主流水线上去提交处理

### 期望的验收标准
提供一个子流水线设的变量在本次执行的主流水线上能获取到

**Comment by zanyzhao** [comment]
子流水线调用插件支持“output”

**Comment by helinjiang** [comment]
同求！我们现在的场景是子流水线可能是用第三方模板生成的，而在父流水线上，可能会针对子流水线的结果做自定义的处理，如果子流水线的变量无法在主流水线上获得的话，那么根本玩不下去啊。

**Comment by wuxin001** [comment]
父流水线中需要整合多个子流水线的构建信息，进行群通知等操作，因此需要获取到子流水线中执行的信息、设置的变量

**Comment by fayewong-v5** [comment]
1、增加通用的输出变量：sub_pipeline_buildId 和 sub_pipeline_url
2、当同步执行时，支持指定子流水线输出变量名，结束时作为当前插件输出
