### ISSUE TITLE
添加预计完成时间功能

### ISSUE THREAD

**Issue by caiznen** [Tencent/bk-ci#1041]
### 作为
DevOps 团队里的Dev，要实践持续部署流水线

### 我希望
能支持到具体具体节点的预计执行时间和整个流水线任务的预计完成时间，其它产品是有这个功能的，

### 以便于
- 方便其他人员能有个大概的估计版本什么时候构好

**Comment by zanyzhao** [comment]
根据历史耗时存在很大的偏差，比如：
- 构建机性能负载
- 构建机网络
- 执行的插件耗时

目前的进度是通过已运行成功的插件数量/总插件数得出的
