### ISSUE TITLE
GIT分支变量支持关联GIT仓库变量的功能

### ISSUE THREAD

**Issue by noonhorse** [Tencent/bk-ci#1050]
如图所示，希望能支持以下功能，

使用场景：
在模版编辑中，git仓库的地址是实例化后传地址的，所以GIT分支变量，这里需要指定的git仓库地址也应该是是个变量才对。

![image](https://user-images.githubusercontent.com/4952447/78768829-136f5800-79bf-11ea-9ddf-57619cfabed8.png)

**Comment by fayewong-v5** [comment]
GIT分支或TAG这种类型的变量，在模板里跨项目后确实体验不太好。我们研究下怎么优化。
可以先把变量类型改为字符串，传字符串进入

**Comment by noonhorse** [comment]
> GIT分支或TAG这种类型的变量，在模板里跨项目后确实体验不太好。我们研究下怎么优化。
> 可以先把变量类型改为字符串，传字符串进入

这个其实就级联下拉框的功能
