### ISSUE TITLE
同一时间最多只能运行一个构建任务 最大排队数量 可否自定义

### ISSUE THREAD

**Issue by onlyforyoumylove** [Tencent/bk-ci#1053]
### 作为
用户
### 我希望
同一时间最多只能运行一个构建任务 最大排队数量（目前最多20条） 可否自定义

### 以便于
可以对每个提交进行检查

### 期望的验收标准
每个提交都可以触发一次检查，而不是超过20条之后，就跳过提交的检查

**Comment by iccengan** [comment]
可以描述下在什么场景下需要取消这个限制吗？

**Comment by onlyforyoumylove** [comment]
> 可以描述下在什么场景下需要取消这个限制吗？

每天提交的改动比较多，有时编译时间比较长，希望可以每个提交都检查一遍 而不跳过。

**Comment by iccengan** [comment]
排队正常来讲是要添加数量限制的，你的情况 期望是限制多少数量左右呢

**Comment by onlyforyoumylove** [comment]
> > 每天提交的改动比较多，有时编译时间比较长，希望可以每个提交都检查一遍 而不跳过。
> 
> 排队正常来讲是要添加数量限制的，你的情况 期望是限制多少数量左右呢？

50个左右应该会好点

**Comment by irwinsun** [comment]
目前上限50个
