### ISSUE TITLE
流水线视图功能重构

### ISSUE THREAD

**Issue by zanyzhao** [Tencent/bk-ci#1055]
### 作为
DevOps 团队里的`流水线管理员`，要实践持续部署流水线

### 我希望
流水线能够提供更友好的管理方式

### 以便于
- 让 CI管理员 方便的管理多个流水线

#### 增加流水线组
- 不同流水线组下的流水线可重名
- 可根据流水线组设置权限
- 每个流水线默认继承流水线组的权限，但可以单独再设置
- 组内流水线可自定义拖拽排序

#### 视图功能重构
- 视图是跨越流水线组的一种搜索条件（就像Windows文件夹搜索条件）
- 项目下所有人共享”项目视图“

**Comment by kernal-jpg** [comment]
标签这里可以突破7个吗？

**Comment by zanyzhao** [comment]
> 标签这里可以突破7个吗？

可以，新版设计里，标签最多支持50个

**Comment by iccengan** [comment]
同时支持手动选择流水线 添加进视图

**Comment by iccengan** [comment]
关联需求：#2199

**Comment by 490861895** [comment]
！！！！！！！！！！！！！！强烈推荐这两个，特别影响用户体验！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！
1，视图适量太少了
2，不能自定义排序

**Comment by iccengan** [comment]
视图筛选条件支持精确/模糊匹配：#2626

**Comment by iccengan** [comment]
> ！！！！！！！！！！！！！！强烈推荐这两个，特别影响用户体验！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！
> 1，视图数量太少了
> 2，不能自定义排序

#1486 已支持

**Comment by kuangtoby** [comment]
希望能增加功能：
给每个用户组设置默认的流水线视图，只要这个用户组的同事打开流水线面板，就显示管理员给其设置的流水线视图，而不是每个人一打开流水线面板就显示所有的流水线
