### ISSUE TITLE
setEnv不支持换行符

### ISSUE THREAD

**Issue by TedaLIEz** [Tencent/bk-ci#1056]
我希望能够在流水线构建时实现类似ChangeLog的功能

```
TEST="$(git log 40a3a2a2..87d4a436 --grep='merge request' --pretty=tformat:'Title: %s%nMessage:%b%n%n')"
echo "$TEST"
setEnv "COMMIT_MESSAGE" "$TEST"
```

尝试将上述代码中的`COMMIT_MESSAGE`添加到流水线设置中通知的通知内容中，发现`COMMIT_MESSAGE`展示无换行。

如图所示:
![image](https://user-images.githubusercontent.com/8800730/78897616-09278980-7aa5-11ea-84fb-811213ad26e7.png)

在bash中打印结果如下:
![image](https://user-images.githubusercontent.com/8800730/78897696-28261b80-7aa5-11ea-9c1d-667cd9d42410.png)

**Comment by irwinsun** [comment]
我们在安全上有考虑过，受限于历史情况，短期内无法做到全面的验证，只能优先以安全第一，牺牲了一些功能的完整性。

模拟以下场景：
用户定义了一个变量var_1 , 然后在不知道的情况下接收了一个尝试攻击的commit信息值为  
It'\n rm -rf / \n echo 'hello world

Bash的变量输出定义变为 export a='It'\n rm -rf / \n echo 'hack'
格式化后:
```shell
export a='It'
rm -rf /
echo 'hack'
```
至此，攻击完成，用户的构建机上所有数据全丢了，并且用户完全不知问题出在哪。

为此我们目前是将\n和'号替换掉了，防止出现单引号提前结束变量定义，并用换行符产生命令拆分。

 这块如果没有做好全面的验证，是不会轻易修改。

**Comment by wxdao** [comment]
导致这个问题的应该不只在 ShellUtil.kt 的正则过滤部分，在 setEnv 的脚本中在写入 resultFile 时就已经丢失了换行。

测试脚本：
<img width="604" alt="image" src="https://user-images.githubusercontent.com/1405249/83852651-aec64480-a746-11ea-92bb-ca7fd6b0467e.png">

运行后的 resultFile 内容，发现已经丢失了换行：
<img width="974" alt="image" src="https://user-images.githubusercontent.com/1405249/83852718-cdc4d680-a746-11ea-9af2-6850ce7e79df.png">

而运行后的 stdout 输出发现换行在环境变量中还在。

在这一行：

```
echo $key=$val  >> resultFile
```

$val 没有两边加引号，使得输出的内容换行丢失。

不过看 ScriptEnvUtils.kt 中 resultFile 文件的用法，还非常原始只是通过 readLines 来读取，这个设计也是对换行不友好的。

我建议将 resultFile 文件设计的更结构化，如通过 json 保存信息，或者最次也可以先将 value 用 base64 编码一下再放文件里规避换行以及其他特殊字符问题。

**Comment by wxdao** [comment]
至于上文中提到的 ShellUtil.kt 129 行问题（现在最新代码应该是在 140 行），可以先在代码中将 value 先用 base64 之类转换一下，或先存到一个临时文件里，然后构造 export 的时候就可以用

```
export $name="`echo $enccodedValue | base64 -d`"
```

或者

```
export $name="`cat $tmpValueFile`"
```

的方式安全设置环境变量。

**Comment by irwinsun** [comment]
setEnv有大量的历史使用背景，无法再继续迭代兼容，请用最新的方式来拿来操作。

```shell

# 通过::set-variable命令字设置/修改全局变量(当前步骤不生效)
# echo "::set-variable name=var_name::var_value"
# 在后续的插件表单中使用${{variables.var_name}}引用这个变量

# 通过::set-output命令字设置当前步骤的输出(当前步骤不生效)
# echo "::set-output name=output_name::output_value"
# 在后续的插件表单中使用${{jobs.<job_id>.steps.<step_id>.outputs.output_name}}引用这个输出，其中job_id和step_id在对应的Job和Task上配置
```

**Comment by wxdao** [comment]
@irwinsun 新的这个 ::set-variable 支持设置带换行的值吗？

**Comment by irwinsun** [comment]
> @irwinsun 新的这个 ::set-variable 支持设置带换行的值吗？

@wxdao 我这边有个示例你看看，是可以的。 但windows比较特殊，如果要echo，可能\r\n是不行的。 但示例你可以看到换行符号是没有丢失的哦
