### ISSUE TITLE
希望能有地方展示Job排队等待的时间，以及构建中展示当前节点已经运行了多久

### ISSUE THREAD

**Issue by caiznen** [Tencent/bk-ci#1057]
### 作为
DevOps 团队里的Dev，要实践持续部署流水线

### 我希望
能有地方展示Job排队等待的时间，以及构建中展示当前节点已经运行了多久

### 以便于
- 分析构建时长，考虑进排队的时长
- 构建时能直接看到某个节点的执行时长

**Comment by iccengan** [comment]
关联需求：#619

**Comment by iccengan** [comment]
#1083 已上线。如果仍不能满足需求，移步至 #619 跟进。
