### ISSUE TITLE
希望可以考虑对于插件，能有一个设置，是执行时不允许反选

### ISSUE THREAD

**Issue by caiznen** [Tencent/bk-ci#1058]
### 作为
DevOps 团队里的Dev，要实践持续部署流水线

### 我希望
比如一些设置全局变量的插件，希望不管时什么情况下的构建，这些插件都一定要执行到，以保证后面依赖于这个插件的插件能构取到正确的变量

**Comment by zanyzhao** [comment]
我们在流水线高级流程控制中增加一个”禁止跳过“的开关

**Comment by iccengan** [comment]
这个是不是应该由项目组来制定流水线的执行规范，而不应由平台来提供配置功能来限制？

**Comment by irwinsun** [comment]
此功能应由项目组用户在编排时决定，尽量少一些强制性的控制，如需要项目上下统一处理，建议使用模板实例化流水线来给成员使用，
