### ISSUE TITLE
红线/模板和git触发事件的一些调整

### ISSUE THREAD

**Issue by linjun-ddddd** [Tencent/bk-ci#1061]
增加push事件before/after commit变量
增加push\tag事件 commits 变量列表
调整红线拦截模板一些逻辑, 已经一些依赖和异常的处理

**Comment by irwinsun** [comment]
蓝盾流水线评论: 开发已自测通过，已发布到测试服，请测试团队测试

**Comment by irwinsun** [comment]
蓝盾流水线评论: 已部署到灰度环境
