### ISSUE TITLE
希望codecc跑完的结果，可以以json之类的数据格式被使用者获取到

### ISSUE THREAD

**Issue by nichang15** [Tencent/bk-ci#1062]
### 作为
DevOps 团队里的Dev，要接入使用codecc检查代码质量。

### 我希望
codecc跑完的测试结果，可以以json之类的数据格式被使用者获取到。

### 以便于
- 使用者可以有一定的灵活处理空间，自定义要发出来的codecc测试结果。
- 使用者可以根据自己团队的要求，自行选择用“邮件报告or消息提醒or群机器人or运营机器人”的方式发出codecc的测试结果。

### 期望的验收标准
- 使用者获取到的json格式之类的测试结果，包含详情链接、每个使用到的测试项的总计告警信息、告警关联人信息。

**Comment by pennyisme** [comment]
搭车同求

**Comment by carrywang05** [comment]
CodeCC-New插件会将产出物报告的结果json归档到仓库，具体可见：
![image](https://user-images.githubusercontent.com/46527215/79766314-669bc000-835a-11ea-8698-17ec1ae005e6.png)
可以通过拉取构件-自定义仓库(new)插件获取到该json，以便进行进一步的处理。
