### ISSUE TITLE
插件开发里，字段依赖于复选框组件的值显/隐时，rely不生效

### ISSUE THREAD

**Issue by fayewong-v5** [Tencent/bk-ci#1063]
### 作为
蓝盾插件开发

### 我希望
插件字段间联动时，若依赖的字段是个复选框类型字段，也能正常使用rely来配置控制关系

### 以便于
条件显示/隐藏页面元素

**Comment by irwinsun** [comment]
蓝盾流水线评论: 开发已自测通过，已发布到测试服，请测试团队测试

**Comment by irwinsun** [comment]
蓝盾流水线评论: 已部署到灰度环境
