### ISSUE TITLE
bugfix: 检验错误时提示信息异常

### ISSUE THREAD

**Issue by hefushou** [Tencent/bk-ci#1064]
![image](https://user-images.githubusercontent.com/12457501/78973762-1dba5f00-7b43-11ea-8294-10c6f3e44adc.png)

**Comment by irwinsun** [comment]
蓝盾流水线评论: 开发已自测通过，已发布到测试服，请测试团队测试

**Comment by irwinsun** [comment]
蓝盾流水线评论: 已部署到灰度环境
