### ISSUE TITLE
构建触发设置的流水线变量在运行时设值带有特殊符号，Bash插件无法获取该变量值

### ISSUE THREAD

**Issue by ckanhw** [Tencent/bk-ci#1066]
### 作为
使用DevOps的团队

### 我希望
我们需要把流水线变量暴露出去，让没有流水线修改权限，但有运行权限的人员也可以配置变量，
控制构建流程，但是当前设置的流水线变量值带有特殊符号，例如竖线“|”，作为分隔符；DevOps会做校验，导致变量传递不到构建的中间插件，例如Bash插件，echo $变量名，输出为空值；我们希望DevOps可以对字符串类型的变量可以完整传递到中间插件。

### 以便于
- 在Bash插件中可以完整获取流水线变量的字符串值，完成后续构建任务

### 期望的验收标准
- 流水线变量类型为字符串，带有竖线“|”，在Bash插件echo $变量名，可以获取该值。

**Comment by zanyzhao** [comment]
变量中包含特殊字符会导致各种意外发生，即使bk-ci支持了特殊字符，也有可能在Bash引用变量的时候触发Bash的问题（Bash内管道符是特殊字符）所以不推荐大家在变量中设置特殊字符。
