### ISSUE TITLE
流水线变量支持datetime类型

### ISSUE THREAD

**Issue by zhao-jin** [Tencent/bk-ci#1067]
![image](https://user-images.githubusercontent.com/3895381/78985740-19e70680-7b5c-11ea-9a89-158435b1031d.png)
 目前的变量类型比较少，不支持datetime选择日期时间，而不用自己拼字符串

**Comment by iccengan** [comment]
@zhao-jin datetime类型用于什么场景，发送通知？

**Comment by irwinsun** [comment]
平台提供变量聚焦在 用户很难/无法自助操作类型上， 单纯为了方便手工操作选择日期，并没有太大的意义。 考虑下自动化，减少人工操作，释放人力。 可以用接口简化自己的操作。

**Comment by HUANGChaoLi** [comment]
在某些场景下，例如填写看板信息的时候，需要按照一定的格式填写时间，如果是以字符串的形式来处理的话，一方面格式很容易出错不好处理，另一方面输入体验也不好（无法判定时间是否有效，是周几，距离今天还有多长时间等）
