### ISSUE TITLE
新插件支持“源代码未更新时不触发”功能

### ISSUE THREAD

**Issue by linjun-ddddd** [Tencent/bk-ci#1070]

**Comment by iccengan** [comment]
关联需求：#996

**Comment by irwinsun** [comment]
蓝盾流水线评论: 开发已自测通过，已发布到测试服，请测试团队测试

**Comment by irwinsun** [comment]
蓝盾流水线评论: 已部署到灰度环境

**Comment by hypersl** [comment]
在多个git拉取插件的情况并未修复成功 @irwinsun @linjun-ddddd

**Comment by iccengan** [comment]
> 在多个git拉取插件的情况并未修复成功

@hypersl 使用的是什么git拉取插件？

**Comment by hypersl** [comment]
拉取GIT（命令行）
司内已反馈过@linjun-ddddd，场景是流水线存在多个git拉取插件，其中一个设置为跳过状态，因此认为是最新的而不断的触发构建了
