### ISSUE TITLE
safari兼容性bug: 定时触发插件，输入框失去焦点前直接关闭属性面板，会导致设置的值不生效

### ISSUE THREAD

**Issue by lockiechen** [Tencent/bk-ci#1071]
safari兼容性bug: 定时触发插件，基础规则内【触发于】输入框失去焦点前直接关闭属性面板，会导致设置的值不生效

**Comment by irwinsun** [comment]
蓝盾流水线评论: 开发已自测通过，已发布到测试服，请测试团队测试

**Comment by irwinsun** [comment]
蓝盾流水线评论: 已部署到灰度环境
