### ISSUE TITLE
Add a variable *BK_CI_REPO_GIT_WEBHOOK_COMMIT_MESSAGE*

### ISSUE THREAD

**Issue by Danielhu229** [Tencent/bk-ci#1072]
### As
a developer

### I hope that
adding a variable *BK_CI_REPO_GIT_WEBHOOK_COMMIT_MESSAGE* in "GIT事件触发公共变量"  

### To
- indicate the hook related last commit message of the hook branch. 

### Expects
- available under `无编译环境`

**Comment by iccengan** [comment]
场景：
目前代码提交日志 必须在【拉取Git】插件执行完毕后才可获取，但用户期望在不添加构建环境的情况下获取到代码提交日志。

**Comment by Danielhu229** [comment]
Don't change my title...
And can you should provide your issue template in English

**Comment by Danielhu229** [comment]
What's the progress now? It seems not complicated, I have to add an build environment just for lookup the latest commit, which is completely unnecessary

**Comment by iccengan** [comment]
@Danielhu229 Sorry for my late update. The variable you requested has already been added, but the way you use the variable might be a bit different from what you expected. Try this:

For either commit push or tag push event, which only includes one commit each, use this following variable to extract your pushed commit message.
```
BK_REPO_GIT_WEBHOOK_PUSH_COMMIT_MSG_1
```

For either merge request(MR) or MR accept event, which might include multiple commits each, use these following variables. Substituting the ending number with 1-32 to get your corresponding commit message. We only keep the latest 32 commits, if you have more than 32 commits in one MR, the redundant ones will be discarded.
```
BK_REPO_GIT_WEBHOOK_PUSH_COMMIT_MSG_1
BK_REPO_GIT_WEBHOOK_PUSH_COMMIT_MSG_2
BK_REPO_GIT_WEBHOOK_PUSH_COMMIT_MSG_n
```

Please let me know if you have any further questions with using them.

**Comment by Danielhu229** [comment]
Not work, the `BK_REPO_GIT_WEBHOOK_PUSH_COMMIT_MSG_1` is empty

**Comment by iccengan** [comment]
@Danielhu229 You might have used `%BK_REPO_GIT_WEBHOOK_PUSH_COMMIT_MSG_1%` instead of `${BK_REPO_GIT_WEBHOOK_PUSH_COMMIT_MSG_1}`. We did not make this variable compatible with `%xxx%` format. 
Change your expression to `${xxx}` and your problem will be solved.
