### ISSUE TITLE
我的收藏支持全局收藏

### ISSUE THREAD

**Issue by AnubisYe** [Tencent/bk-ci#1075]
目前我的收藏中是以项目维度隔离的，无法看到其他项目的流水线收藏，较为鸡肋
述求：增加全局流水线收藏功能，可以在我的收藏中看到历史收藏的所有流水线，可以增加项目小标题以区分不同项目的流水线

**Comment by iccengan** [comment]
新版控制台-项目列表首页：
我的项目页签添加【收藏流水线】页签，跨项目展示收藏的流水线。
#779

**Comment by AnubisYe** [comment]
> 新版控制台-项目列表首页：
> 我的项目页签添加【收藏流水线】页签，跨项目展示收藏的流水线。
> #779
