### ISSUE TITLE
feature: 流水线插件执行失败时通知功能

### ISSUE THREAD

**Issue by kinyoung1024** [Tencent/bk-ci#1080]
### 作为
DevOps 流水线的使用者

### 我希望
流水线插件的通用配置里，支持设置当插件执行失败时邮件通知指定的用户

### 以便于
精准提醒相关责任人，尽快定位问题并解决问题

### 期望的验收标准
![image](https://user-images.githubusercontent.com/38236140/79121873-ebba2e80-7dc8-11ea-9212-11746cf4aeba.png)

**Comment by irwinsun** [comment]
可以看下这个issue #750

**Comment by zanyzhao** [comment]
已支持 #3138
