### ISSUE TITLE
chore: 微服务模块请求返回状态码缺少对应的文字描述信息

### ISSUE THREAD

**Issue by hingbong** [Tencent/bk-ci#1085]
![image](https://user-images.githubusercontent.com/26398240/79203111-21b0ee80-7e6d-11ea-9f23-d03710a002af.png)
在这个 com.tencent.devops.common.api.constant.RepositoryMessageCode 中的错误码, 只有前 4 条有在 sql 文件中有, 其他的都缺失了, 是要手动添加到数据库吗

**Comment by irwinsun** [comment]
蓝盾流水线评论: 开发已自测通过，已发布到测试服，请测试团队测试

**Comment by irwinsun** [comment]
蓝盾流水线评论: 已部署到灰度环境
