### ISSUE TITLE
流水线执行历史可以展示自定义的变量

### ISSUE THREAD

**Issue by crazy-bit** [Tencent/bk-ci#1092]
### 我希望
流水线'执行历史'只能展示系统定义的列，希望可以展示自定义的变量，这样不用每条流水线自己去手动填写备注

**Comment by iccengan** [comment]
用`setEnv "BK_CI_BUILD_REMARK" "xxx"`的方式来设置备注，能解决你的问题吗？

**Comment by crazy-bit** [comment]
可以
