### ISSUE TITLE
feature:网关特定接口支持”X-Content-Type-Options“

### ISSUE THREAD

**Issue by freyzheng** [Tencent/bk-ci#1096]
### 作为
DevOps 团队里的Dev，要实践持续部署流水线

### 我希望
网关后台接口支持”X-Content-Type-Options: nosniff“

### 以便于
- 以防止XSS攻击。

### 期望的验收标准
- 蓝盾后台接口返回的时候带上X-Content-Type-Options: nosniff

**Comment by irwinsun** [comment]
蓝盾流水线评论: 开发已自测通过，已发布到测试服，请测试团队测试

**Comment by irwinsun** [comment]
蓝盾流水线评论: 已部署到灰度环境
