### ISSUE TITLE
插件执行日志优化

### ISSUE THREAD

**Issue by fayewong-v5** [Tencent/bk-ci#1098]
### 作为
流水线用户

### 我希望
插件执行失败时，不要打印如下所示的日志：
![image](https://user-images.githubusercontent.com/54432927/79311925-b7fa1880-7f30-11ea-9282-2b23b906dc6b.png)

/tmp/devops_scriptXXX.sh 这个sh，是执行时的临时文件，用户拿不到，提示让用户很困惑

### 以便于
用户能快速了解到失败信息

### 期望的验收标准
日志可以改为如： Fail to run the plugin because of error(Process exited with an error: 255)

**Comment by iccengan** [comment]
关联需求：#726

**Comment by iccengan** [comment]
> ### 期望的验收标准
> 日志可以改为如： Fail to run the plugin because of error(Process exited with an error: 255)

可以考虑添加日志信息：导致插件失败的指令以及其返回码

**Comment by iccengan** [comment]
红色字体的报错 Fail to execute the command(/tmp/xxx) 需要去掉。
平台的报错信息会干扰用户定位问题。
