### ISSUE TITLE
插件流程控制选项添加配置：失败时设置变量

### ISSUE THREAD

**Issue by iccengan** [Tencent/bk-ci#1102]
### 需求
插件执行失败时，可设置多个流水线变量。

### 场景：
插件执行失败后所设置的流水线变量，可用于后续执行插件的流程控制-自定义变量全部满足时才/不执行。

### 最佳实践：
流水线插件执行失败时通知。#1080
- A插件执行失败后，设置两个流水线变量 receiver=xxx，status=fail。然后添加通知插件，流程控制配置为：当${status}==fail时，通知人为${receiver}

**Comment by irwinsun** [comment]
可以看下这个issue https://github.com/Tencent/bk-ci/issues/750 已经实现
