### ISSUE TITLE
docs: 对代码issue类型进行扩充优化

### ISSUE THREAD

**Issue by irwinsun** [Tencent/bk-ci#1103]
CONTRIBUTING.md中针对一些比较长的标记进行修改

commit 注释将issue字眼简化：
原
> bugfix: 部分第三方构建机上出现worker-agent.jar进程延迟退出的问题 issue #29

简化为

> 'fix: 部分第三方构建机上出现worker-agent.jar进程延迟退出的问题 #29'

原有issue标志
改为：
> feature 缩写feat
> refactor 缩写 perf
> bugfix 缩写 fix/bug

| 标记     | 说明                                   |
| -------- | -------------------------------------- |
| feature/feat  | 新功能开发                             |
| bug/fix/bugfix   | bug修复                                |
| refactor/perf | 重构代码/优化配置&参数/优化逻辑及功能 |
| test     | 添加单元测试用例相关                   |
| docs     | 添加文档                               |
| info     | 添加注释类信息                         |
| format   | 不修改业务逻辑下，仅做代码规范的格式化 |
| merge    | 仅做分支合并同步                       |
| depend   | 对工程的依赖进行增删改                 |
| chore    | 构建脚本、任务等相关代码                 |
| del    | 删除可能仍然有人用到的功能、API等破坏性动作               |

**Comment by irwinsun** [comment]
蓝盾流水线评论: 开发已自测通过，已发布到测试服，请测试团队测试

**Comment by irwinsun** [comment]
蓝盾流水线评论: 已部署到灰度环境

**Comment by zhishanggao** [comment]
perf 是performance的缩写吗？
