### ISSUE TITLE
Job支持Depend On

### ISSUE THREAD

**Issue by zanyzhao** [Tencent/bk-ci#111]
比如2-1、2-2、2-3 这3个Job，依赖关系如下：
2-2的启动依赖2-1的成功
2-3的启动依赖2-1的成功

那需要在2-2、2-3里分别设置depend on 2-1，执行顺序如下：
1. 运行到Stage2时，运行2-1
2. 等2-1运行成功后，启动2-2、2-3

![image](https://user-images.githubusercontent.com/1629409/82670374-98f94f80-9c6f-11ea-8580-4617e32532ef.png)

**Comment by mingshewhe** [comment]
1. 不需要跨stage依赖，比如3-1依赖2-1，是不允许的
2. 如果2-1跳过，2-2，2-3状态置成失败
3. 如果2-2依赖2-1，2-1依赖2-1，造成循环依赖，在保存的时候验证

**Comment by zanyzhao** [comment]
假如c依赖a,b，b依赖a
--------
c的日志应该是：
Current Job depends on  a,b succed，current status：
  a running
  b waiting
Waiting...

Current Job depends on  a,b succed，current status：
  a succed
  b running
Waiting...

Current Job depends on  a,b succed，current status：
  a succed
  b succed
Begin

**Comment by irwinsun** [comment]
没有明确指明当DependON 与Job的流程控制条件 优先级顺序

**Comment by iccengan** [comment]
### 初步结论
b依赖于a：
如果a执行，b执行：a失败时，b为失败状态；a成功时，b执行。
如果a执行，b跳过：a失败时，b为失败状态；a成功时，b跳过。
如果a跳过，b执行：b为失败状态。
如果a跳过，b跳过：b为跳过状态。

#### 仍需进一步讨论

**Comment by iccengan** [comment]
### 最终结论
b依赖于a：
如果a执行，b执行：a失败时，b为跳过状态；a成功时，b执行。
如果a执行，b跳过：b无论如何都是跳过状态。
如果a跳过：b无论如何都是跳过状态。

#### 原则：只要没执行到b，b就只会是跳过状态。b的状态不受前置job影响，只跟自己的task有没有执行成功有关。
