### ISSUE TITLE
feature: 质量红线细节优化

### ISSUE THREAD

**Issue by hefushou** [Tencent/bk-ci#1111]
1、指标支持一次性多选，而不是每次点开侧边栏只能选中一个，侧边栏就会消失

2、接口传参调整

**Comment by irwinsun** [comment]
蓝盾流水线评论: 开发已自测通过，已发布到测试服，请测试团队测试

**Comment by irwinsun** [comment]
蓝盾流水线评论: 已部署到灰度环境
