### ISSUE TITLE
归档到流水线仓库支持归档目录

### ISSUE THREAD

**Issue by eternalsea** [Tencent/bk-ci#1112]
### 作为
DevOps 团队里的Dev，要实践持续部署流水线

目前归档到流水线仓库 不支持按文件夹归档，归档后是在同一个目录。这时候如果归档不同目录下的同名文件，后归档的就会覆盖前面归档的。导致无法归档不同目录下的同名文件。

### 我希望
归档到流水线仓库支持归档目录，或者其他等效方案可以归档多个同名文件

### 期望的验收标准
流水线仓库支持归档不同目录下的同名文件

**Comment by zanyzhao** [comment]
我们在插件SDK中新增“上传至流水线仓库”的能力，这样你就可以写一个【归档文件夹】的插件了
