### ISSUE TITLE
bug:网关代码启动失败

### ISSUE THREAD

**Issue by freyzheng** [Tencent/bk-ci#1116]
模板文件异常：gateway#core#devops.server.conf
`
  #代理
  includ vhosts/devops.proxy.conf;
`

**Comment by irwinsun** [comment]
蓝盾流水线评论: 开发已自测通过，已发布到测试服，请测试团队测试

**Comment by irwinsun** [comment]
蓝盾流水线评论: 已部署到灰度环境
