### ISSUE TITLE
子流水线未完成时 主流水线可以被锁定

### ISSUE THREAD

**Issue by wlxklyh** [Tencent/bk-ci#1125]
### 作为
DevOps 团队里的Dev，要实践持续部署流水线

### 我希望
子流水线未完成时 主流水线可以被锁定

### 以便于
主流水线和子流水线的 workspace是一个的时候  避免文件占用冲突 或者第二次构建的主流水线删除了文件

### 期望的验收标准
主流水线A1拉起子流水线B1  B1没有结束的时候不可以拉起 主流水线A2

**Comment by zanyzhao** [comment]
看起来像是你的`私有构建机`，你可以进行如下设置：
- 主流水线里设置`运行锁定`为“同一时间最大只能运行1个构建任务
- `子流水线调用`改为同步调用

**Comment by wlxklyh** [comment]
> 看起来像是你的`私有构建机`，你可以进行如下设置：
> 
> * 主流水线里设置`运行锁定`为“同一时间最大只能运行1个构建任务
> * `子流水线调用`改为同步调用

我设置子流水线异步 是为了 主流水线早点完毕 可以交付apk给测试  子流水线是处理符号上传很耗时所以异步调用，想锁定主流线二次调用是为了 不要让二次调用把构建产物删除了。  也有其他方案处理  比如子流水线先把产物复制一份再上传符号。

**Comment by zanyzhao** [comment]
异步任务的子流水线状态确实不会阻塞父流水线，算是设计如此。
