### ISSUE TITLE
按节点label选择构建机

### ISSUE THREAD

**Issue by zanyzhao** [Tencent/bk-ci#1129]
### 作为
DevOps 团队里的Dev，要实践持续部署流水线

### 我希望
能够支持`按节点label选择构建机`

### 以便于
- 流水线里可以按照构建集群选IP，同时又可以按需分配构建机

### 期望的验收标准
- 节点增加打标签功能
- Job详情增加按label过滤集群节点

**Comment by onlyforyoumylove** [comment]
同求啊，每条流水线保证从头到尾用集群里面的一台机器，而不是每个job都不同的机器

**Comment by davidruan13** [comment]
一个流水线如果分为N个steps，后面的step选节点的时候，有个选项是在stepN的节点上执行。
例：
1. 一个流水线分了3个step
2. 每个step生成一个label或者节点
3. 在step3选择节点是，可以选择必须在step1的机器上运行，或者必须在step2的机器上运行
4. 同一个step下的并行job同理

针对的问题：
设置构建集群后，我无法确保我执行自动化测试/deploy，和我构建编辑器的机器是一台
导致的结果是一条流水线只能指定分布给一台构建机，集群只能处理很简单的单线程job，比如我如果安卓做了分布式资源cook就不行。

个人感觉这个问题还挺严重的，如果不支持的话构建集群形同虚设，等于不支持自动化测试和自动化发布。如果理解有错误欢迎沟通指出。

**Comment by iccengan** [comment]
@davidruan13 你说的问题可通过 #1122 解决
