### ISSUE TITLE
[Feature] 建议流水线执行历史界面左侧的rebuild按钮点击后添加确认框

### ISSUE THREAD

**Issue by HahnSC** [Tencent/bk-ci#1140]
![image](https://user-images.githubusercontent.com/11287250/79627467-101c5f00-816b-11ea-87de-9be4d13f7743.png)
见图，左侧新增的rebuild按钮只要点一下就会重开任务，执行任务的参数不确定；这个界面的每个条目需要点多次才能展开，很容易误触，建议修改。

**Comment by zanyzhao** [comment]
下个版本我们把它去掉吧 #1162 

PS：执行历史表格里整行都是可点击的，不一定非得跑到构建号上点击
