### ISSUE TITLE
流水线变量支持Emoji

### ISSUE THREAD

**Issue by linjiex** [Tencent/bk-ci#1143]
### 作为
DevOps 团队里的Dev

### 我希望
流水线变量支持Emoji

### 以便于
流水线列表中识别特定流水线。

原因：目前的流水线列表中只能用文字区分， 不能支持颜色、logo等其它辅助元素， 因此希望能够支持Emoji，从而能从流水线列表中更方便的定位。

### 期望的验收标准
流水线支持Emoji，比如：♥

**Comment by irwinsun** [comment]
目前mysql的jdbc驱动对字段类型为varchar，text等类型是无法支持存储emoji
需要更改字段类型为blob/clob类型，改动较大，并数据迁移等问题，短期内不会考虑该特性。
但是常用的符号 ❌✔️是支持的， 请先结合自身业务特点想办法解决

**Comment by linjiex** [comment]
> 目前mysql的jdbc驱动对字段类型为varchar，text等类型是无法支持存储emoji
> 需要更改字段类型为blob/clob类型，改动较大，并数据迁移等问题，短期内不会考虑该特性。
> 但是常用的符号 ❌✔️是支持的， 请先结合自身业务特点想办法解决

谢谢答复，明白原因了， 通过解释已经找到合适的字符了。
