### ISSUE TITLE
流水线支持Stage

### ISSUE THREAD

**Issue by zanyzhao** [Tencent/bk-ci#115]
## 编辑流水线
- 编排
![image](https://user-images.githubusercontent.com/1629409/71353667-b341db00-25b4-11ea-97ed-5398b2c4b7cb.png)
- Stage详情
![image](https://user-images.githubusercontent.com/1629409/76293947-f1fe4c00-62ec-11ea-84c2-f8dbb1cd3269.png)
> 本Stage执行条件的下拉选项有：
- 前一个Stage成功时执行
- 自定义变量全部满足时才执行
- 自定义变量全部不满足时不执行

## 流水线执行历史
![image](https://user-images.githubusercontent.com/1629409/71357826-e2127e00-25c1-11ea-85b6-62348ce7894d.png)

## 任务详情
- Stage暂停
![image](https://user-images.githubusercontent.com/1629409/74620457-32e2c500-5174-11ea-8f61-7afbdc034f5f.png)

**Comment by irwinsun** [comment]
蓝盾流水线评论: 开发已自测通过，已发布到测试服，请测试团队测试

**Comment by irwinsun** [comment]
蓝盾流水线评论: 已部署到灰度环境

**Comment by irwinsun** [comment]
蓝盾流水线评论: 开发已自测通过，已发布到测试服，请测试团队测试

**Comment by irwinsun** [comment]
蓝盾流水线评论: 已部署到灰度环境

**Comment by irwinsun** [comment]
蓝盾流水线评论: 开发已自测通过，已发布到测试服，请测试团队测试

**Comment by irwinsun** [comment]
蓝盾流水线评论: 已部署到灰度环境

**Comment by irwinsun** [comment]
蓝盾流水线评论: 开发已自测通过，已发布到测试服，请测试团队测试

**Comment by irwinsun** [comment]
蓝盾流水线评论: 已部署到灰度环境
