### ISSUE TITLE
bk-ci编译报错

### ISSUE THREAD

**Issue by mzj520** [Tencent/bk-ci#1150]
![image](https://user-images.githubusercontent.com/29419822/79709544-045ca400-82f5-11ea-99a6-5411fc9cf585.png)
![image](https://user-images.githubusercontent.com/29419822/79709553-0c1c4880-82f5-11ea-8b50-51854790ca18.png)

**Comment by fayewong-v5** [comment]
可以先按照这个编译流程走一遍：
https://github.com/Tencent/bk-ci/blob/master/.github/workflows/frontend.yml

**Comment by lockiechen** [comment]
@mzj520 你好，目前新的部署流程是这样的
![image](https://user-images.githubusercontent.com/33082528/80051732-80e8c000-854b-11ea-8b9d-95b87b66b6da.png)
