### ISSUE TITLE
推送至其它项目自定义仓库-目标路径可以希望去掉  share-项目名，或者由使用者选择是否保留这样的目录结构

### ISSUE THREAD

**Issue by waterdorm** [Tencent/bk-ci#1152]
### 作为
跨项目文件发布的需求

### 我希望
推送至其它项目自定义仓库 节点可以完全自定义路径，避免一定在share/项目名称 这样的路径设置。

### 以便于
- 能够灵活的发布文件，保持发布目录统一

### 期望的验收标准
- 推送至其它项目自定义仓库，可以推送到目标项目的任意文件下

**Comment by fayewong-v5** [comment]
保留share目录，是避免多人操作时，项目下的文件被其他项目下的同名文件覆盖，导致异常问题出现。
