### ISSUE TITLE
feat: 流水线插件高级特性：即使前面有插件运行失败也运行，即使被取消也运行

### ISSUE THREAD

**Issue by zanyzhao** [Tencent/bk-ci#1156]
- [x] 前端插件设置： 即使前面有插件运行失败也运行，即使被取消也运行
  - additionalOptions 后台增加 PRE_TASK_FAILED_EVEN_CANCEL

- [x] 执行时间优化：
  - 执行详情detail接口后台返回 executeTime （毫秒）字段, 前端用该字段的值替换当前使用的endTime - startTime
  - 前端读取 执行历史列表new 当前已有executeTime (毫秒) 字段，替换当前使用的totalTime

**Comment by fayewong-v5** [comment]
如果插件本身问题卡住，只有等到插件/JOB/Stage/流水线超时才结束

**Comment by irwinsun** [comment]
依赖#3569
