### ISSUE TITLE
流水线列表页通过模板新建流水线 和 模板页实例化流水线 的设置不统一

### ISSUE THREAD

**Issue by iccengan** [Tencent/bk-ci#1160]
### 现象：
1. 新建流水线时，无法用上模板的基础设置（如运行锁定、通知等配置）
2. 新建流水线时，不应支持标签的选择。标签的配置是模板基础设置的子属性，如下图：
![image](https://user-images.githubusercontent.com/10875468/111761685-2121a300-88db-11eb-8110-7391b56ab7e8.png)

### 期望：
通过模板创建流水线时
1. 支持选择是否【同时应用模板设置】
![image](https://user-images.githubusercontent.com/10875468/111758597-a86d1780-88d7-11eb-92a8-50bc7220d503.png)
![image](https://user-images.githubusercontent.com/10875468/111758926-0699fa80-88d8-11eb-8048-c067dc1f56d5.png)
2. 去掉标签配置，与模板实例化流水线页面能力保持统一。
![image](https://user-images.githubusercontent.com/10875468/111761066-6abdbe00-88da-11eb-8161-891386b95c34.png)
3. 通过空白流水线创建时，保留标签配置。

**Comment by miusuncle** [comment]
我也遇到了类似的 bug，流水线模板发布到商店，从商店安装该模板到别的项目，`设置`中的`通知内容`使用了流水线的默认通知内容。

**Comment by iccengan** [comment]
> 我也遇到了类似的 bug，流水线模板发布到商店，从商店安装该模板到别的项目，`设置`中的`通知内容`使用了流水线的默认通知内容。

多谢反馈，我们已将这个bug加入到排期，尽快修复！

**Comment by iccengan** [comment]
关联需求：#763
