### ISSUE TITLE
代码库事件触发排除路径逻辑bug

### ISSUE THREAD

**Issue by zlvb** [Tencent/bk-ci#1163]
SVN事件触发插件有可能存在以下bug

假设指定代码库相对路径abc
则abc内有内容更新就会触发构建——这是正常的

假设指定代码库相对路径abc，并且排除abc/sub1
当abc/sub2有更新，且abc/sub1也有更新时，不会触发构建——这不正常

排除的含义我理解为本次更新仅包含abc/sub1时，不触发，而不是一旦abc/sub1有更新，连abc/sub2也一起忽略了

再举例，有abc三部分，其中c是被忽略的，而ab是需要监控的。当只有c更新时，则忽略。其他情况都不可忽略，如ab，abc，bc等。现在的情况是只要含有c则忽略。

就好比我关注手机的新产品，除了小米手机。
如果小米和华为同一天出了新产品，因为我不关注小米，所以我要一起忽略掉华为，
这个逻辑是不对的。

**Comment by iccengan** [comment]
这个需求我们再走读代码内部讨论一下，目前代码触发插件的监听逻辑的确可以优化下。

**Comment by zlvb** [comment]
我再举个更实际的例子
我有这样一个目录
server
    gamesvr
    common
    chatsvr
    tools
    document
server目录只要有更新，就要触发构建，但是document是跟代码无关的，这个目录更新的话，就忽略。我想这才是“忽略”目录的本意，我很难想象什么时候会出现相反的需求——某个目录只要更新就忽略全部——我找不到可能的例子

**Comment by zlvb** [comment]
> 这个需求我们再走读代码内部讨论一下，目前代码触发插件的监听逻辑的确可以优化下。
我再举个更实际的例子
我有这样一个目录
server
-- gamesvr
-- common
-- chatsvr
-- tools
-- document
server目录只要有更新，就要触发构建，但是document是跟代码无关的，这个目录的更新可以忽略，以免不必要的构建。我想这才是“排除”这个功能的本意，我很难想象什么时候会出现相反的需求——某个目录只要更新就忽略全部——我找不到可能的例子
所以我才把这个情况定为是bug

**Comment by iccengan** [comment]
> 我再举个更实际的例子
> 我有这样一个目录
> server
> -- gamesvr
> -- common
> -- chatsvr
> -- tools
> -- document
> server目录只要有更新，就要触发构建，但是document是跟代码无关的，这个目录的更新可以忽略，以免不必要的构建。我想这才是“排除”这个功能的本意（排除不必要的监控以免多余的构建），我很难想象什么时候会出现相反的需求——某个目录只要更新就忽略全部——我找不到可能的例子
> 所以我才把这个情况定为是bug

了解你的意思了，也就是说，只有 有且仅有 被排除的目录，才需要忽略构建对吧。
再延伸一下，如果我排除了 gamesvr、common和chatsvr，只有下面6种情况会忽略构建，其余情况都会触发构建：
-- 仅提交了gamesvr
-- 仅提交了common
-- 仅提交了chatsvr
-- 仅提交了gamesvr和common
-- 仅提交了gamesvr和chatsvr
-- 仅提交了common和chatsvr
-- 仅提交了gamesvr、common和chatsvr

**Comment by zlvb** [comment]
> > 我再举个更实际的例子
> > 我有这样一个目录
> > server
> > -- gamesvr
> > -- common
> > -- chatsvr
> > -- tools
> > -- document
> > server目录只要有更新，就要触发构建，但是document是跟代码无关的，这个目录的更新可以忽略，以免不必要的构建。我想这才是“排除”这个功能的本意（排除不必要的监控以免多余的构建），我很难想象什么时候会出现相反的需求——某个目录只要更新就忽略全部——我找不到可能的例子
> > 所以我才把这个情况定为是bug
> 
> 了解你的意思了，也就是说，只有 有且仅有 被排除的目录，才需要忽略构建对吧。
> 再延伸一下，如果我排除了 gamesvr、common和chatsvr，只有下面7种情况会忽略构建，其余情况都会触发构建：
> -- 仅提交了gamesvr
> -- 仅提交了common
> -- 仅提交了chatsvr
> -- 仅提交了gamesvr和common
> -- 仅提交了gamesvr和chatsvr
> -- 仅提交了common和chatsvr
> -- 仅提交了gamesvr、common和chatsvr

是的

**Comment by vissong** [comment]
+1 ，忽略了 readme 但是一次提交里有readme和程序文件，流水线也没有触发

**Comment by zlvb** [comment]
> +1 ，忽略了 readme 但是一次提交里有readme和程序文件，流水线也没有触发

是的，提交内容包含了被忽略文件后，整个提交就都被忽略了，这属于设计上的bug
