### ISSUE TITLE
蓝盾流水线的构建号支持重置，或者设置最大值内递增循环。

### ISSUE THREAD

**Issue by swoderheart** [Tencent/bk-ci#1168]
### 作为
DevOps 团队里的Dev，要实践持续部署流水线

### 我希望
蓝盾流水线的构建号支持重置，或者设置最大值内递增循环
目前问题是构建号一直持续递增，数值很大没有意义。

**Comment by iccengan** [comment]
推荐版本号能满足你的需求吗？

**Comment by swoderheart** [comment]
> 推荐版本号能满足你的需求吗？

推荐版本号是怎样的？  看起来是不满足的。

**Comment by iccengan** [comment]
![image](https://user-images.githubusercontent.com/10875468/80300777-1f865280-87d2-11ea-9686-9be401a6d34f.png)
这里构建号是支持重置的。
