### ISSUE TITLE
feat: 新增腾讯工蜂git.code.tencent.com的事件监听

### ISSUE THREAD

**Issue by Windeal** [Tencent/bk-ci#1180]

**Comment by zanyzhao** [comment]
看看可否用“扩展”的思路实现？

**Comment by irwinsun** [comment]
扩展是可行的，因为（触发器）本质上触发器就是一个 HTTP服务，提供一个回调接口通过注册到某个代码库的webhook设置中， 经由代码库触发时，调用这个触发器（HTTP服务）的回调接口，该接口处理完再调用流水线的构建启动接口来实现。 即使官方没有提供，第三方也仍然可以自行建设一个HTTP服务来自行达到目的

**Comment by ElvinYangGo** [comment]
希望早日实现这个功能，现在跨部门合作越来越多，急需git.tencent.com事件触发内网的流水线

**Comment by caterchong** [comment]
期待这个功能早日上线。

**Comment by kadinzhu** [comment]
期待早点排期这个功能，业务等着用

**Comment by savageli** [comment]
期待这个功能早日上线。

**Comment by jeremyxu2010** [comment]
期待这个功能早日上线。

**Comment by davytan** [comment]
期待这个功能早日上线。

**Comment by mingshewhe** [comment]
![image](https://user-images.githubusercontent.com/22971705/91689494-d2a6f400-eb96-11ea-8586-48a8102003d5.png)
1. TGit需要支持git.code.tencent.com
2. 第二步的接口api/user/credentials/mht/hasPermissionList?permission=USE&credentialTypes=USERNAME_PASSWORD需要变成api/user/credentials/mht/hasPermissionList?permission=USE&credentialTypes=USERNAME_PASSWORD,TOKEN_USERNAME_PASSWORD

**Comment by iccengan** [comment]
同时包含支持git.tencent.com的事件触发

**Comment by kimhou** [comment]
期待这个功能早日上线。

**Comment by mingshewhe** [comment]
## 使用方式
1. 代码库添加"工蜂外网版"仓库，仓库url可以是git.tencent.com和git.code.tencent.com两种,凭证必须是"用户名密码+私有token"类型
git.tencent.com Private token获取链接: [https://git.tencent.com/profile/account](https://git.tencent.com/profile/account)
git.code.tencent.com Private token获取链接:[https://git.code.tencent.com/profile/account](https://git.code.tencent.com/profile/account)
2. 在流水线编辑页面选择“TGit事件触发”事件，选择代码库
![image](https://user-images.githubusercontent.com/22971705/92488618-5f018880-f221-11ea-914f-20a6c16cb2d5.png)
3. 流水线保存后，在git.tencent.com或git.code.tencent.com的Settings->advanced settings->Web Hooks 验证webhook是否注册成功
![image](https://user-images.githubusercontent.com/22971705/92489297-375ef000-f222-11ea-8772-0220494ad7d0.png)

## Q&A
1. 如果注册失败，检查凭证是否是"用户名密码+私有token"，如果凭证类型正确，检查private token是否正确
