### ISSUE TITLE
因EPC 3.0需要加入对蓝盾流水线的规范性检查，故需在蓝盾流水线信息查询接口新增几个字段

### ISSUE THREAD

**Issue by leozlliang** [Tencent/bk-ci#1183]
### 作为
来自EPC度量平台组的需求，因为EPC 3.0需要加入对流水先的规范性检查

### 我希望
目前蓝盾提供的2个API里几个字段
1. app_pipeline_list接口：增加class和type
2. app_build_list接口：增加class和type字段,以及 各个子任务名称（taskName），任务类型(taskType)，及任务执行结果(status)。

### 以便于
满足 以EPC 3.0规范对流水线信息进行扫描检查

### 期望的验收标准
1. 访问app_pipeline_list接口，能查到新增的class和type
2. 访问app_build_list接口，能查到新增的class和type字段,以及 各个子任务名称（taskName），任务类型(taskType)，及任务执行结果(status)。

期望5月初能使用

**Comment by freyzheng** [comment]
ApigwPipelineResourceV3->getListByUser
