### ISSUE TITLE
流水线构建任务点击rebuild时并没有读取失败当时的commit ID

### ISSUE THREAD

**Issue by zanyzhao** [Tencent/bk-ci#1184]
使用新的拉代码插件，点击rebuild后拉取的代码跟失败当时的代码不一致

**Comment by deepjia** [comment]
感觉，如果拉代码的时候是用分支名，那么rebuild的时候严格用上次执行的分支名的最新代码似乎还挺合理的？

如果要保证 commit 一致，或者说如果要让拉的代码始终是触发时候的那个分支的，那么拉代码的时候，应该选择用触发分支触发时的 commitid 才比较合理？

**Comment by ErWeiWang** [comment]
这里的rebuild机制是否增加代码版本校验机制，若当前无对应版，则rebuild机制全新执行该流程，且真个显示过程中的代码版本应显示实际执行的代码版本号

**Comment by zanyzhao** [comment]
> 感觉，如果拉代码的时候是用分支名，那么rebuild的时候严格用上次执行的分支名的最新代码似乎还挺合理的？
> 
> 如果要保证 commit 一致，或者说如果要让拉的代码始终是触发时候的那个分支的，那么拉代码的时候，应该选择用触发分支触发时的 commitid 才比较合理？

不是按分支，是MR触发，平台应该记住第一次拉代码时的commit ID，不管配置的拉代码策略是否是按commit 拉，rebuild都应该传入失败时拉取的commit ID，已确认BUG

**Comment by linjun-ddddd** [comment]
已经实现，插件发布上线了
