### ISSUE TITLE
流水线执行历史的过滤项支持保存默认配置

### ISSUE THREAD

**Issue by eternalsea** [Tencent/bk-ci#1185]
### 作为
DevOps 团队里的Dev，要实践持续部署流水线

### 我希望
![image](https://user-images.githubusercontent.com/14304956/80056170-2c970d80-8556-11ea-8c69-28efb83d4ecd.png)

流水线执行历史的过滤项支持保存默认配置，背景是如上图所示，因为配置了mr触发构建以及排队数量。会出现大量自动取消的构建（这里其实还想有另外一个需求：对于git hook 等自动触发的构建能否复用上一个构建id，避免产生大量的自动取消，过滤掉后中间的构建id会出现大量断层），每次打开时满屏都是自动取消的构建，而目前列表页的过滤项不支持保存，每次打开时都默认展示所有，比较痛苦。所以希望可以设置默认过滤项，或直接应用上一次的过滤项

**Comment by zanyzhao** [comment]
你在流水线运行锁定里设置了“同时只能运行1个构建任务”并且开启最大排队数量是1？

**Comment by eternalsea** [comment]
> 你在流水线运行锁定里设置了“同时只能运行1个构建任务”并且开启最大排队数量是1？
是的，我的场景是设置git commit push 就触发构建，但实际上我又不需要每个commit都实际真实构建一次。所以设置同时只运行一个，并且最大排队数也是一，来保证每次构建都是构建最新的代码。

这样设置非常不好，但尝试了各种触发的设置方式，目前只有这样设置可以达到我想要的效：Jenkins 里的 “Poll SCM”

**Comment by irwinsun** [comment]
> > 你在流水线运行锁定里设置了“同时只能运行1个构建任务”并且开启最大排队数量是1？
> 
> 是的，我的场景是设置git commit push 就触发构建，但实际上我又不需要每个commit都实际真实构建一次。所以设置同时只运行一个，并且最大排队数也是一，来保证每次构建都是构建最新的代码。 这样设置非常不好，但尝试了各种触发的设置方式，目前只有这样设置可以达到我想要的效：Jenkins 里的 “Poll SCM”

过滤项支持保存默认设置虽然能解决你视图的问题，但构建号的断层仍然无法解决，在频繁的git commit 过程中还是会产生大量的构建，所以其实要解决你的问题最好的方式还是不想要的触发的就不要产生构建了，而不是视图过滤项的问题。

Jenkins的 “Poll SCM” 是采用定时拉取的方式，如果你希望这么用， 现有的 “定时触发” 也有 “源码未更新不触发“的功能，是一样的。
<img width="628" alt="image" src="https://user-images.githubusercontent.com/16686129/177715975-3838e15e-c1c9-46e5-b794-f0c61de9dfad.png">




所以在这过程中感觉还是开发模式存在可优化的。 在我看来，如果开发者不希望每一个commit都被 CI所构建，那至少可以证明他在开发的过程中，产生了大量无意义的commit， 而且开发者自己并没有意识到，只是职业习惯性的不断commit push 来保存自己的工作中间成果。  那么建议你在commit message中使用
```shell
git commit -m  " [skip ci] 这里是你的注释.. #xxx"
```
来提交这些中间commit push，  CI的git事件触发器如解析到   [skip ci]  会放弃本次触发行为，也就不会再产生被取消的构建了。
