### ISSUE TITLE
Bash脚本执行插件使用的解释器不透明

### ISSUE THREAD

**Issue by fayewong-v5** [Tencent/bk-ci#1187]
### 作为
流水线服务使用者

### 我希望
使用Bash脚本执行插件来编写命令，但发现很多bash语法没支持，发现使用了执行机上默认的sh

### 期望的验收标准
可以明确脚本执行插件的解释器
可以支持不同解释器

**Comment by irwinsun** [comment]
开源社区版已经将内置Bash更名为Shell
