### ISSUE TITLE
增加拉取其他项目构件的功能插件

### ISSUE THREAD

**Issue by Steven-GJHU** [Tencent/bk-ci#1193]
### 作为
在构建过程中需要调用其他项目的公共组件

### 我希望
有插件可以拉取其他项目流水线自定义仓库上的构件

### 以便于
- 构建过程中方便获取公共组件
- 可以配置拉取的公共组件版本，方便两边的升级和维护
- 公共组件在构建过程中不需要用插件推送给其他项目

### 期望的验收标准
- 在流水线上使用插件可以拉取其他项目流水线自定义仓库中的构件
- 最好可以直接拉取到构建机上

**Comment by Steven-GJHU** [comment]
0.0

**Comment by zanyzhao** [comment]
你这边依赖的产物是什么编译工具产生的，是不是放到对应编译工具的制品库中更合适，比如npm、pip、maven等

**Comment by Steven-GJHU** [comment]
> 你这边依赖的产物是什么编译工具产生的，是不是放到对应编译工具的制品库中更合适，比如npm、pip、maven等

Windows的VS。产物几乎是exe/dll/sys这些PE文件

**Comment by irwinsun** [comment]
已有，插件功能
