### ISSUE TITLE
feature: 网关服务发现支持服务后缀

### ISSUE THREAD

**Issue by freyzheng** [Tencent/bk-ci#1203]
### 作为
DevOps 团队里的Dev，要实践持续部署流水线

### 我希望
feature: 网关服务发现支持服务后缀

### 以便于
- 区分bkci服务和其他在同一个consul集群中服务名字相同的情况

### 期望的验收标准
- 服务发下在服务后面增加一个后缀

**Comment by zanyzhao** [comment]
#1132

**Comment by freyzheng** [comment]
已实现并发布
