### ISSUE TITLE
插件按条件执行时希望支持 不等于 条件 设置

### ISSUE THREAD

**Issue by eternalsea** [Tencent/bk-ci#1208]
### 作为
DevOps 团队里的Dev，要实践持续部署流水线

### 我希望
当有多条件控制时，目前只有全部 key==value 时执行或不执行。
我期望能设置 key1==value1，key2 != value2 时执行或不执行

**Comment by iccengan** [comment]
关联需求：#429

**Comment by iccengan** [comment]
Duplicate of #1747
