### ISSUE TITLE
建议在流水线列表这一级增加最新推荐版本号，目前有显示的是最新构件号，没什么用

### ISSUE THREAD

**Issue by defchen** [Tencent/bk-ci#1211]
由于构建流水太多，找版本非常困难！也没有提供全局搜索版本号的功能。强烈建议在流水线总列表这一级增加一列最新推荐版本号的显示，目前有显示的是最新构件号，这个没什么用。

**Comment by zanyzhao** [comment]
我在 #1055 中一并考虑
