### ISSUE TITLE
支持手动批量执行pipeline

### ISSUE THREAD

**Issue by zhangyafeikimi** [Tencent/bk-ci#1216]
场景: 手动执行10个pipeline.

目前需要挨个执行每个pipelein. 其中, 每个pipeline要点两次, 第一次点执行, 选择要执行的stage(其实没什么可选的, 因为我都要执行), 第二次再点执行.

10个pipeline操作下来耗时1-2分钟.

需要“手动批量执行pipeline”的功能.

**Comment by fayewong-v5** [comment]
> 目前需要挨个执行每个pipelein. 其中, 每个pipeline要点两次, 第一次点执行, 选择要执行的stage(其实没什么可选的, 因为我都要执行), 第二次再点执行.

--- 手动触发有个配置，可以让你少点一次，你看这样可以不？
![image](https://user-images.githubusercontent.com/54432927/80214663-d1583e80-866d-11ea-8cad-1221bcee8142.png)

**Comment by zhangyafeikimi** [comment]
还是需要批量的功能, 我们的pipeline会越来越多.

**Comment by fayewong-v5** [comment]
批量执行，希望如何处理启动参数呢

**Comment by zhangyafeikimi** [comment]
上面那个跳过插件的功能, 不能减少任何一次点击, 没人任何帮助.

启动参数用默认参数就可以.

**Comment by zanyzhao** [comment]
批量触发的难点在于整理触发时传递的参数，只考虑取默认值的场景不合理，万一有人不想用默认值呢。

目前已经有触发流水线的API了，你可以自己写个程序自己实现批量触发
