### ISSUE TITLE
编译环境支持无编译环境的插件

### ISSUE THREAD

**Issue by jerrybean** [Tencent/bk-ci#1222]
### 作为
DevOps 团队里的Dev，要实践持续部署流水线。我希望流水线的每个阶段都按照具体处理的逻辑来组织，而不是被插件的所属环境（编译环境、无编译环境）限制
作为与其他团队合作的Dev，我们依赖其他插件，可能并不支持编译环境如linux。

### 我希望
编译环境阶段可以运行无编译环境的插件。使得整个流程统一。如下图所示：
![image](https://user-images.githubusercontent.com/10786112/80296897-2e104200-87b1-11ea-9942-51cb0171d929.png)
stage-2 stage-3 stage-4 表示目前的流水线编排情况。
stage-5 表示期望的流水线编排情况。
其中流程1、流程3依赖构建环境-Linux，流程2依赖无编译环境。
期望在一个stage中执行流程1、流程2、流程3（如stage-5）。其中流程2的环境B因为其为无编译环境，则由蓝盾平台调度到相关环境执行即可。

### 以便于
- 让整个流程更加清晰，让流水线的编排按照相关stage的逻辑而非受限于构建环境。
- 让Dev观察流水线更能清晰知道所处流程。
- 让无编译环境的插件可以整合到任意编译环境的stage中。
### 期望的验收标准
- 创建一个流水线，创建一个Linux（或windows、macos）构建环境
- 在上步骤创建的stage中添加依赖构建环境的插件（如依赖Linux的插件 Bash脚本）和无构建环境的插件（如邮件通知）
- 流水线可以正常保存，执行

**Comment by zanyzhao** [comment]
#111 #848 
可以关注下这两个特性
