### ISSUE TITLE
希望可以成员自助退出项目

### ISSUE THREAD

**Issue by xiaohp** [Tencent/bk-ci#1223]
### 需求场景
在大型项目中，参与的开发人员多，一个人也参与多个项目，项目也会交接。时间一长，一个成员会在很多个项目组中。已经不再参与的项目也会受到通知

### 我希望
希望开发人员可以自主退出项目

### 以便于
聚焦在当前进行中的项目，不然每次进入都还需要选择项目，多了一步操作
同时也有很多不需要接收的通知

**Comment by xiaohp** [comment]
这个需求有评估么？

**Comment by iccengan** [comment]
@zanyzhao 是否与权限中心v3一起考虑

**Comment by zanyzhao** [comment]
https://github.com/Tencent/bk-ci/projects/11
请关注这里的issue，预计7月份可以上线，就可以支持退出
