### ISSUE TITLE
feature:新增变量获取触发本次构建的commit id（流水线触发方式为Merge Request Accept Hook）

### ISSUE THREAD

**Issue by shiyadonggithub** [Tencent/bk-ci#1227]
当前流水线是git merge request accepte事件触发，文档中的HEAD_COMMIT_ID获取的总是最新的COMMIT_ID，假如两次merge request accepte事件距离较近，事件A（先）和事件B（后）都触发了流水线构建，两次事件时间均在两次构建拉取git插件执行之前完成，那么两次构建的HEAD_COMMIT_ID均为事件B的ID
![image](https://user-images.githubusercontent.com/44150277/80300861-b8b56900-87d2-11ea-8cec-5ba6fa587d47.png)
诉求：增加变量获取触发本次构建的事件id

**Comment by zanyzhao** [comment]
拿到之后你想做什么？

**Comment by shiyadonggithub** [comment]
我这边一条流水线触发方式是merge request accept方式触发，当两次accept事件事件相差很小的时候（比如隔了1s，此时git拉取插件还没来得及执行），两次accept都会触发流水线执行，但是两次构建的commit id都是最后一次的commit id，这里可以不要两次构建之间的id，但是这个bug要修复

**Comment by shiyadonggithub** [comment]
我这边想根据commit id拉取git上本次修改的文件代码

**Comment by shiyadonggithub** [comment]
@zanyzhao

**Comment by zanyzhao** [comment]
`BK_CI_REPO_GIT_WEBHOOK_COMMITID`
试试这个

**Comment by shiyadonggithub** [comment]
> `BK_CI_REPO_GIT_WEBHOOK_COMMITID`
> 试试这个

这个不行的，一次merge request可能有多个commit 记录，这个变量指的是最后一次commit的id

**Comment by zanyzhao** [comment]
或者用`BK_CI_REPO_GIT_WEBHOOK_MR_ID`再请求工蜂API来获取MR对应的commit信息，以gitlab为例
https://docs.gitlab.com/ee/api/merge_requests.html#get-single-mr
```json
"diff_refs": {
    "base_sha": "c380d3acebd181f13629a25d2e2acca46ffe1e00",
    "head_sha": "2be7ddb704c7b6b83732fdd5b9f09d5a397b5f8f",
    "start_sha": "c380d3acebd181f13629a25d2e2acca46ffe1e00"
  }
```

**Comment by irwinsun** [comment]
这个需求过于定制化，不建议在CI核心主流程中实现，可自行通过与代码库平台联动扩展实现。
