### ISSUE TITLE
研发商店的模板支持手动升级

### ISSUE THREAD

**Issue by squirrel20** [Tencent/bk-ci#1255]
### 作为
DevOps 团队里的Dev，要实践持续部署流水线

### 现状

1. 项目A中的模板a上架到研发商店
2. 项目B在研发商店中安装了模板a
3. 项目A中的模板a更新了版本，项目B中的模板a就自动更新了

建议是类似镜像和插件一样，可以在研发商店的工作台这里手工操作升级下。

**Comment by fayewong-v5** [comment]
安装到B项目下的模板a，是不能编辑的。
源模板更新后，如果在B下加手动更新升级模板，只是增加了模板管理员的工作量，需要多点同步的步骤

目前在B项目下，流水线实例是不会自动升级的，可以自由选择使用模板的旧版本、还是新版本实例化流水线
