### ISSUE TITLE
代码库事件触发的流水线，各处展示的触发人不一致

### ISSUE THREAD

**Issue by iccengan** [Tencent/bk-ci#1258]
### 现象：
A提交了代码，构建详情里展示的触发人是B，构建历史列表展示的触发人是C。

**Comment by irwinsun** [comment]
正确的应该是：用户A提交代码，构建历史列表展示的触发人是A， 构建详情里展示的触发人是B（流水线最后保存人），

**Comment by drakzhu** [comment]
场景：
    修改过某一条流水线，后续该流水线执行成功的通知都发给我
最后保存人被当作执行人了

**Comment by iccengan** [comment]
触发人和执行人的含义有歧义，产品侧先思考文案等优化，开发再启动

**Comment by iccengan** [comment]
Duplicate of #4065
