### ISSUE TITLE
增加变量，支持仅获取本次MR改动代码

### ISSUE THREAD

**Issue by Zxiaoxue** [Tencent/bk-ci#1262]
### 作为
DevOps 团队里的Dev，要实践持续部署流水线

### 我希望
用 git 提交代码并实现 单一主干发布分支

### 以便于
- 让 Ops 通过 Master 分支发布
- 让 Dev 在开发分支上开发
- 让 QA 可以选择对应的提交进行部署测试

### 期望的验收标准
- 创建一个 Job，跟踪代码库 Master 分支的变化
- Master 分支如果有变化，自动立即构建并部署到开发环境。
- 测试环境和生产环境不能直接部署。

**Comment by iccengan** [comment]
方便描述下具体的需求场景吗？
该变量是不是指mr目标分支的基准commit id，然后你希望通过head commit id和基准commit id来获取两次commit间的改动代码，是这样吗？

**Comment by Zxiaoxue** [comment]
我的需求是仅获取触发本次流水线构建的 MR 的代码改动，是不是用变量形式都可以接受

**Comment by zanyzhao** [comment]
有个`BK_CI_REPO_GIT_WEBHOOK_COMMITID`变量可以获取MR变更的Commit ID，看下可否满足你需求

**Comment by iccengan** [comment]
BK_REPO_GIT_WEBHOOK_PUSH_ADD_FIEL_n
BK_REPO_GIT_WEBHOOK_PUSH_MODIFY_FILE_n
BK_REPO_GIT_WEBHOOK_PUSH_DELETE_FILE_n

BK_REPO_GIT_WEBHOOK_PUSH_ADD_FILE_COUNT
BK_REPO_GIT_WEBHOOK_PUSH_MODIFY_FILE_COUNT
BK_REPO_GIT_WEBHOOK_PUSH_DELETE_FILE_COUNT

目前仅提供了git push触发的变更文件变量。
注：n取值范围为1-32。

如不能满足要求，只能通过git原生指令 git diff 来满足你目前需求了。
