### ISSUE TITLE
后面提交的MR不要自动取消前面提交的check，按顺序执行

### ISSUE THREAD

**Issue by pecywang** [Tencent/bk-ci#128]
![image](https://user-images.githubusercontent.com/13653036/64138611-3dacd600-ce30-11e9-940c-4fc197253b25.png)

**Comment by irwinsun** [comment]
因为排队队列的容量是有限的，当超过容量之后，后面入队的构建会把前面排队的构建踢出，如果不踢出的话，后面的无法进入排队，所以这种情况你可以把队列设置大一些。
