### ISSUE TITLE
流水线添加多个相同git触发类型插件会在对应代码库上生成多个webhook

### ISSUE THREAD

**Issue by iccengan** [Tencent/bk-ci#1290]
### 现象：
流水线触发方式如果添加多个【git触发】插件，且触发类型一样（如，都是push触发或tag触发），会在代码库上生成多个触发类型相同的webhook。导致git触发事件会同一时间触发多次流水线构建。

### 临时解决办法：
到代码库将相同类型的webhook删剩1个即可。

**Comment by linjun-ddddd** [comment]
跟https://github.com/Tencent/bk-ci/issues/1456重复了
