### ISSUE TITLE
运行锁定，默认请改成 同一时间最多只能运行一个构建任务

### ISSUE THREAD

**Issue by zhenlinyang** [Tencent/bk-ci#1308]
构建安装包的流水线，几乎不可能使用**可同时运行多个构建任务**。每个任务都要手动改成**同一时间最多只能运行一个构建任务**，如果忘了改会非常麻烦。希望把默认选项改成**同一时间最多只能运行一个构建任务**。

**Comment by iccengan** [comment]
@zhenlinyang hello，你上面说的 “几乎不可能使用**可同时运行多个构建任务**”并不是所有用户的场景哈。因为在部分构建场景里，是可以支持**同时运行多个构建任务**的。他们在并发执行构建任务时，能隔离不同构建任务的工作空间，从而做到并发执行而不相互影响构建结果。
