### ISSUE TITLE
建议流水线删除按钮，放置到在流水线设置页面内； 构建任务详情页面删除改为删除“单条集成执行”的功能

### ISSUE THREAD

**Issue by outshineamaze** [Tencent/bk-ci#1315]
### 我希望

1. 流水线列表的“删除”按钮其实可以隐藏， 作为不经常用的功能， 应该隐藏在设置中去， 例如github仓库删除也是在setting的最下面，还有二次输入邮箱确认的过程（如果有回收站功能， 可以忽略本条建议）
![image](https://user-images.githubusercontent.com/8246792/80796292-68267d00-8bd1-11ea-8bfe-9f613dedabca.png)

2. 在流水线集成任务的详情页， 这个删除按钮会给人以为是 “删除本次构建任务” 的误导， 而流水线的执行记录在蓝盾中是没有可以删除的入口的。   建议在执行详情的页面里面把这个删除流水线的选项去掉， 或者改为删除单次集成记录的操作
![image](https://user-images.githubusercontent.com/8246792/80796356-8db38680-8bd1-11ea-8de3-57fd3b8564b6.png)

**Comment by iccengan** [comment]
> 流水线列表的“删除”按钮其实可以隐藏， 作为不经常用的功能， 应该隐藏在设置中去， 例如github仓库删除也是在setting的最下面，还有二次输入邮箱确认的过程（如果有回收站功能， 可以忽略本条建议）

传送门：#542 
但你的需求也很合理，删除按钮作为"破坏性"功能，理应加深入口。确认操作时的交互也应有强提醒效果（如你提到的二次输入repo名称）。

**Comment by zanyzhao** [comment]
已增加 #542 ，这里可以关闭了
