### ISSUE TITLE
流水线预设变量类型支持上传文件至自定义仓库

### ISSUE THREAD

**Issue by zanyzhao** [Tencent/bk-ci#133]
### 需求：
添加一个文件类型的流水线变量：上传至自定义仓库。
变量配置区域包括：
- **变量类型：文件。** 文案：文件 / File
- **变量名：自定义仓库路径的变量名。** 文案：名称 / Name
- **变量值：自定义仓库路径。** 文案：自定义仓库路径+文件名 / Custom artifactory path + File name
- **上传按钮：导入文件和填好自定义仓库路径后，将文件上传至自定义仓库。** 文案：上传文件 / Upload
- **上传文件规则说明。** 文案：最大上传10M的文件 / Maximum file size: 10M
- **已上传文件：已从本地上传至自定义仓库的文件，展示文件logo、文件名、文件大小。**

流水线预览界面也可对该变量进行更改：
- 更新上传的文件（导入文件后，立即将文件上传至自定义仓库）
- 自定义仓库路径
- 上传按钮：更新文件和自定义仓库路径后，将文件上传至自定义仓库

支持通过【拉取构件-自定义仓库】插件来将上传的文件下载到构建环境。
注：文件限制大小 10MB，不限制文件类型

### 报错
 - 文件大小不能超过10M / File size exceeds limit(10M)
 - 非法自定义仓库路径 / Invalid custom artifactory path

### 编辑页
![image](https://user-images.githubusercontent.com/1629409/91295450-af162f00-e7cd-11ea-8e32-e8075f5d3657.png)

### 执行预览页
![image](https://user-images.githubusercontent.com/1629409/91295802-319eee80-e7ce-11ea-8be9-a77fb1b3fad1.png)

**Comment by shandianling** [comment]
求实现。很需要。

**Comment by linjiex** [comment]
同需要这个功能， 场景： 用于将产品人员的文件上传到服务器上。

**Comment by shandianling** [comment]
求支持下。

**Comment by irwinsun** [comment]
需要提供开源版的实现
