### ISSUE TITLE
bug: 在工作台删除某个插件后，无法重复创建同名插件

### ISSUE THREAD

**Issue by zanyzhao** [Tencent/bk-ci#1334]
![image](https://user-images.githubusercontent.com/1629409/80898912-dab36c00-8d3b-11ea-9f1c-965c13fd2bcf.png)

**Comment by fayewong-v5** [comment]
优化流水线插件删除逻辑：
1、已有流水线在使用的插件，不允许删除

2、可以删除的插件：
- 清理 DB 中关联的所有数据
- 清理仓库中的插件包
- 清理插件关联的代码库
