### ISSUE TITLE
gradle clean build 报错，项目路径问题吗？

### ISSUE THREAD

**Issue by mzj520** [Tencent/bk-ci#1340]

**Comment by zanyzhao** [comment]
路径错了，再往下进一级，到ci目录

**Comment by irwinsun** [comment]
@mzj520 
友情提醒，在公网发截图时小心不要暴露了机密信息

**Comment by mzj520** [comment]
侬好，有没有docker镜像可以部署呢，https://hub.docker.com/r/blueking/bk-ci这个是纯体验版吧，不能账号管理，请问有其他可用的镜像吗？
另外我在ci目录操作也报错，
> Task :core:plugin:codecc-plugin:common-codecc:compileTestKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core:plugin:codecc-plugin:common-codecc:compileTestKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log o
utput. Run with --scan to get full insights.
* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 3m 56s
503 actionable tasks: 503 executed

**Comment by zanyzhao** [comment]
https://hub.docker.com/r/blueking/bk-ci
这个镜像确实没有账号管理功能，我们会在下个大版本中内置一个简化版的权限管理模块 #1346
