### ISSUE TITLE
bug: environment权限判断中，节点的资源类型是否有误？

### ISSUE THREAD

**Issue by Ben-zl** [Tencent/bk-ci#1368]
**Describe the bug**
![image](https://user-images.githubusercontent.com/5083068/81252591-df886080-9058-11ea-8a89-8348dfe41410.png)

环境权限判断中，节点的资源类型应该是`env_node`才对吧?

**Comment by irwinsun** [comment]
是有问题，但目前不影响开源版使用，当接入权限中心可能会造成在权限中心选择了环境节点后发现不生效。

**Comment by Ben-zl** [comment]
我们参照现在的权限设计实现了权限中心功能，原先把这个代码改了，合并代码之后发现了这个问题
