### ISSUE TITLE
性能优化建议

### ISSUE THREAD

**Issue by pkusdyd** [Tencent/bk-ci#1378]
项目下面流水线比较多时，当前我们项目1000+条，
1，打开流水线列表页面非常慢，一般要十几秒，而这个页面的打开频率还比较高。
2，打开后在这个页面上的各种操作也比较卡，反应比较慢。
3，在这个页面上用浏览器的ctrl+F搜索关键词，有时候会失效。用蓝盾自己的搜索也是比较慢。通过关键词搜索是我们比较高频的操作。
4，打开单个流水线也越来越慢，各种操作也比较卡。

总之，就是页面越来越慢和卡
我们可以接受ui效果简陋些换取更流畅的体验，只要能清晰展示状态即可。

**Comment by irwinsun** [comment]
可以关注下 已经有类似Issue #1032 
当前处于验证阶段，可留意issue状态
