### ISSUE TITLE
流水线构建任务排队优化

### ISSUE THREAD

**Issue by zanyzhao** [Tencent/bk-ci#141]
参考CPU队列，按阶段执行

前一个pipeline instance的A stage完成后，继续执行Bstage，同时，下一个pipeline的A stage才开始执行。

**Comment by irwinsun** [comment]
StageA(Build)与StageB(Test) 从名字上来看确实可能是做不一样事，但目前CI无法预测用户到底是不是真的就如用途所说这么干了。 比如StageA 与 StageB 可能共用的是同一台第三方构建机，仍然会存在竞争关系。

所以这种情况其实交给用户决定是最好的方式， 让有需要的用户通过定义Job互斥组来实现运行的互斥执行。

如果放大到Stage上（多个Job），其实在Stage上加上互斥组可以实现。

**Comment by zanyzhao** [comment]
通过Job互斥组实现更精准的控制，此issue挂起
