### ISSUE TITLE
请修改容易误操作的Rebuild按钮

### ISSUE THREAD

**Issue by gracieyangs** [Tencent/bk-ci#1414]
### 作为
逆战项目的PM
### 我希望
修改“执行历史”界面中的容易误操作的Rebuild按钮！！

### 以便于
- 减少失误
### 期望的验收标准
1、Rebuild点击后多一个二次确认弹框，不要直接执行。
2、干掉Rebuild小按钮

**Comment by iccengan** [comment]
关注下这个issue：#1162
已经在灰度，下个版本上线。
