### ISSUE TITLE
优化手动执行界面流水线变量描述的布局展示

### ISSUE THREAD

**Issue by iccengan** [Tencent/bk-ci#1425]
### 现状
手动执行时，流水线变量的描述位于输入框下，和下方的流水线变量名粘在一起，容易产生歧义（如下图，用户有可能误以`参数1的描述`是`param3`的描述）。
![image](https://user-images.githubusercontent.com/10875468/81537654-1daaba80-93a0-11ea-97f2-ae96fb2b9e10.png)

### 期望的验收标准
用户能够简单辨别哪个描述属于哪个流水线变量。建议将流水线名称、输入框、描述用如分割线的方式group在一起。

**Comment by soongao** [comment]
每个选项，加个border
屏幕那么大，
---------------------------------------
param1:   option  可以放在一行   --
这里放描述                                   --
---------------------------------------
