### ISSUE TITLE
希望显示自定义的版本号

### ISSUE THREAD

**Issue by zhao-jin** [Tencent/bk-ci#143]
我们自己实现了一个版本系统， 版本号是在我们自己的脚本里获取的，希望有方法能把脚本获取的版本号回传蓝盾显示在页面上！
以前soda有这个功能，是把版本号字符串写到一个workspace特殊文件实现的

**Comment by irwinsun** [comment]
我们当前支持 BK_CI_BUILD_REMARK 变量，这个变量是用于在执行历史中备注字段展示：
![image](https://user-images.githubusercontent.com/16686129/71004802-6aee6d00-211d-11ea-89d2-18a35b5ac219.png)

使用方式：Bash插件中使用如下命令
setEnv "BK_CI_BUILD_REMARK"  "你的版本号"
