### ISSUE TITLE
提供中断流水线的能力

### ISSUE THREAD

**Issue by sachielxsuo** [Tencent/bk-ci#1430]
### 我希望
提供中断流水线的能力，并使流水线的状态为 `成功`

### 需求
某一步通过某些条件判断是否需要继续执行后续的步骤，如果不需要执行后续的步骤，希望可以中断当前流水线，并使当前流水线的状态为 `成功` 。
目前使用非0退出码可以中断流水线，但是流水线的执行状态会标为 `失败` 。

### 期望的验收标准
使用特定的非0退出码中断流水线，并使流水线的状态为 `成功` 
例如： `exit 87`

**Comment by fayewong-v5** [comment]
判断是否继续的步骤，输出变量，后续步骤由变量控制是否执行
