### ISSUE TITLE
流水线获取插件日志

### ISSUE THREAD

**Issue by LeeGone** [Tencent/bk-ci#1431]
### 作为
DevOps 团队里的Dev，要实践持续部署流水线

### 我希望
开发一个接口，能够获取流水线输出日志或其中的插件输出日志。或者将流水线插件log日志直接保存在服务器本地。

### 以便于
开发流水线失败日志自动分析插件。（较为急迫！）

**Comment by fayewong-v5** [comment]
openapi 有接口支持获取日志， 接口名：app_log_list
