### ISSUE TITLE
“归档构建” 任务希望有个异步传输选项

### ISSUE THREAD

**Issue by zhao-jin** [Tencent/bk-ci#144]
目前我们平时构建时间大概在1~2分钟，但是归档构建就要2分钟，时间有点长，
希望这种非关键路径的task可以有个异步选项
我们自己上传云石的任务也是异步的

**Comment by irwinsun** [comment]
归档构件任务是在构建机上运行的（因为构件在构建机）， 并不是提交到服务器做后台处理。
如果是异步的话，一方面则是构建机无法关闭，仍然需要占用构建机直到构建任务结束。另外为避免后续的任务与当前构建机异步任务的互相影响，比如意外删除了构件，导致构件归档失败等等复杂的情况发生，尽量是线性的去执行。

如果你说的「归档构件」是非关键路径（没有后续的部署），那么你完全可以移除掉这个任务。
