### ISSUE TITLE
归档构件 插件希望增加一个无论前面成功还是失败都执行的选项，执行后不改边流水线的成功/失败的状态

### ISSUE THREAD

**Issue by eternalsea** [Tencent/bk-ci#1448]
归档构件 插件希望增加一个无论前面任何插件成功还是失败都执行的选项。
如果前面是有插件失败走到归档的，归档完后保持失败状态直接结束流水线；如果前面是成功走到归档的，归档后保持成功继续往下执行。

目前何时执行插件的选项无法满足这样的设置。

**Comment by eternalsea** [comment]
保活

**Comment by fayewong-v5** [comment]
归档插件前边的步骤，是Bash吗？ Bash本身是可以设置脚本返回非零时归档指定文件的。
如果不是Bash，自定义的插件失败时也可以归档的

**Comment by eternalsea** [comment]
用其他方法可解决我的问题
