### ISSUE TITLE
希望增加从自定义仓库归档到自定义仓库功能

### ISSUE THREAD

**Issue by larryhou** [Tencent/bk-ci#1451]
### 作为
DevOps 团队里的Dev，要实践持续部署流水线

### 我希望
能够把另外一个构建已经归档到自定义仓库的文件，拉倒当前构建显示下载链接，但是不希望通过下载到本机再上传的方式实现，因为文件很大的话下载上传都会耗费很多时间。这个需求可以通过两种方式实现：
1. 把另外一个构建的归档文件拷贝到当前构建自定义仓库并提供下载链接
2. 把另外一个构建的归档文件下载链接显示到当前构建下载页面

### 以便于
- 把子流水线的构件归档到父级以及多级父级流水线，方便下载管理

### 期望的验收标准
- 有两个自定义仓库输入框
- 一个输入框传入待归档自定义仓库文件路径
- 一个输入框传入目标自定义仓库归档路径
- 运行结束在当前构建页面提供下载链接

**Comment by larryhou** [comment]
麻烦评估排期

github-actions[bot] <notifications@github.com>于2020年7月12日 周日08:08写道：

**Comment by zanyzhao** [comment]
抱歉，回复晚了。

目前有个“自定义仓库-移动文件”的插件，看下是否满足？

**Comment by larryhou** [comment]
> 抱歉，回复晚了。
> 
> 目前有个“自定义仓库-移动文件”的插件，看下是否满足？

插件“自定义仓库-移动文件”解决的需求是把自定义仓库的文件移动到另外一个自定义仓库，并且已经归档的文件是不能移动的，跟本需求目标不匹配。

本需求要解决的问题是：把一个构建的归档文件外链或者复制到另外一个构建的归档里面，并提供下载链接，并且下载链接为需求最终目的，麻烦再评估下本需求，谢谢！

**Comment by irwinsun** [comment]
从描述里来讲，是最终其实只是想要拿到下载链接， 那么这个目前是不需要通过归档插件来解决，可以直接调用api接口生成下载链接即可。 目前已经有这类api接口， 不知道问题 是否已经解决了？
