### ISSUE TITLE
研发商店涉及托管代码服务的组件，上架升级时增加代码扫描

### ISSUE THREAD

**Issue by fayewong-v5** [Tencent/bk-ci#1461]
### 作为
研发商店产品

### 我希望
插件、扩展等涉及托管代码服务的组件上线时，经过codecc代码扫描

### 以便于
- 提高代码质量
- 保证代码安全

**Comment by fayewong-v5** [comment]
1、构建前加代码扫描步骤，扫描结果通知到开发者
2、扫描完毕，根据标准要求，检查是否合规，检查结果打印到日志。如果不合规，需邮件知会

一期不合规仅知会和警告
后续再考虑是否强制要求

**Comment by fayewong-v5** [comment]
待发布

**Comment by carlyin0801** [comment]
已上线
