### ISSUE TITLE
优化日志显示速度

### ISSUE THREAD

**Issue by eternalsea** [Tencent/bk-ci#1468]
目前我们再 bash 插件中执行编译任务，编译完会产生10W+行的日志，在遇到编译失败要查看日志时，bash插件的日志是全量从头开始加载，要加载显示到最后的失败日志，往往要等上很长时间。

希望能优化成查看日志时，优先加载最后N行日志（出错信息一般都是在最后的N行里），然后再慢慢加载全量。

**Comment by zhanxu33** [comment]
你好，目前我们在日志二期对加载速度做过一次优化，10W+行加载不会等待很长时间 #678

**Comment by eternalsea** [comment]
@zhanxu33 昨天更新完，我们15W+行加载到最后出错的日志，需要1分钟，可否优化成先加载最后部分N行，再加载全量
