### ISSUE TITLE
Batch Script插件中使用start /b命令拉起后台程序，导致Batch Script阻塞3分钟

### ISSUE THREAD

**Issue by SKYSCRAPERS1999** [Tencent/bk-ci#1479]
**Describe the bug**
我在流水线Windows环境中的一个Batch Script插件中写入如下代码，其中start /b负责拉起一个后台进程。期望的结果是后台进程拉起后Batch Script便结束执行，但事实上Batch Script会阻塞三分钟，影响正常的测试。

```
set DEVOPS_DONT_KILL_PROCESS_TREE=true
start /b FileAgent\ApisFileAgent.exe 1>NUL 2>&1
```

**To Reproduce**
1. 在蓝盾中流水线创建一个Windows类型的Job
2. 在这个Job中添加一个Batch Script插件的task，在里面添加拉起后台进程的代码。
3. 运行流水线

**Expected behavior**
期望的结果是后台进程拉起后Batch Script便结束执行。

**Screenshots**
![image](https://user-images.githubusercontent.com/30188987/81901167-aa4bb780-95f0-11ea-9b03-48b6e6d7219d.png)

**Comment by carlyin0801** [comment]
这个应该和你的exe执行程序有关，类似那种安装的exe程序是没法真正做到后台运行的（会弹出安装确认框什么的）导致操作系统一直没有断开输出流或者错误流，后台为了分支操作系统没有关闭流做了一个主动关闭流的兜底策略（关闭流的超时时间是**三分钟**），以下是我运行一个可以真正能后台运行的exe程序，可以很快执行完的：
![image](https://user-images.githubusercontent.com/5268164/94510677-eacb6b00-0249-11eb-8e4a-4883f7abf419.png)
![image](https://user-images.githubusercontent.com/5268164/94510715-059ddf80-024a-11eb-8072-70d3fc00bb67.png)
