### ISSUE TITLE
增加git触发代码【锁定提交】选项的判断

### ISSUE THREAD

**Issue by hkhl** [Tencent/bk-ci#1480]
### 作为
插件使用者

### 我希望
关于git事件触发插件的的子功能
![image](https://user-images.githubusercontent.com/31461295/82042703-eeb48180-96dc-11ea-8772-8a993d477c99.png)

增加一个过滤条件， 根据行数来过滤。

### 以便于
可以根据行数来判断是否去执行覆盖率流水线。
如果提交行数小于5行，那么过滤git触发
如果提交代码行数大于5行，那么执行git触发

### 期望的验收标准
可以提供一个过滤行数的条件， 例如
“过滤最少行数：”
填写x，则x行数以内的提交不会触发到git

**Comment by fayewong-v5** [comment]
场景比较特殊，可以自定义一个插件来实现，插件里获取代码变更量，根据规则判断是否执行后续步骤

**Comment by irwinsun** [comment]
Git触发器的逻辑过于复杂，不适合提供过多配置项，该需求可使用插件实现，
