### ISSUE TITLE
视图数量太少，不能自定义排序

### ISSUE THREAD

**Issue by 490861895** [Tencent/bk-ci#1486]
1，任务比较多时，7个视图数量严重不够用
2，不能自由排序任务，导致任务顺序很难控制。相对来说，soda的自由排序，体验就好很多

**Comment by onlyforyoumylove** [comment]
同求 而且最好可以自定义字段

**Comment by iccengan** [comment]
### 用户角色：
项目管理
### 用户需求：
1. 增加自定义排序
2. 增加手动增加备注信息，且备注信息能外显 或者理解为，增加一个字段，自定义的，我自己来设置 ， 比如说，提示这台构建机器位置在哪儿，出问题了 其他值班人员好定位到，增加当前任务备注信息，比如说当前xxx开发正在修改构建脚本，勿动
3. 增加单个任务管理员锁定xx时间功能， 有时候特殊情况，不容许其他人启动构建的，需要锁定几个小时。

**Comment by iccengan** [comment]
Duplicate of #1055

**Comment by iccengan** [comment]
添加支持至30个，可横向滚动
