### ISSUE TITLE
子任务执行失败，流水线却显示成功

### ISSUE THREAD

**Issue by runzhiwang** [Tencent/bk-ci#1497]
问题：设置了“失败时继续”，子任务执行失败，流水线却显示成功。预期，在"能失败时继续"情况下，如果子任务执行失败，流水线应该显示失败。

子任务执行失败
![image](https://user-images.githubusercontent.com/51938049/82004873-7cb94980-9696-11ea-9312-80a1aa803165.png)

流水线显示成功
![image](https://user-images.githubusercontent.com/51938049/82004934-a8d4ca80-9696-11ea-97b4-336d8fe258d4.png)

**Comment by fayewong-v5** [comment]
#1527

**Comment by iccengan** [comment]
目前是设计如此，配置了【失败时继续】会忽略插件的失败状态，流水线状态是成功的。
