### ISSUE TITLE
希望【人工审核】插件能够允许用户选择不发送通知。

### ISSUE THREAD

**Issue by zhuhongwei1989** [Tencent/bk-ci#1498]
### 作为
微服务产品中心的研发。

### 我希望
【人工审核】插件能够允许用户选择不发送通知。

### 以便于
- 减少垃圾信息。
- 我们会使用其他通知方式（例如企业微信通知，邮件通知等手段），发送更加明确和便捷的指引。

### 期望的验收标准
- 【人工审核】插件能够允许用户选择不发送通知。

**Comment by fayewong-v5** [comment]
加是否关闭通知选项，默认不选中

**Comment by fayewong-v5** [comment]
已支持选择通知方式，可以不选
