### ISSUE TITLE
Job准备构建环境需要支持重试机制

### ISSUE THREAD

**Issue by MikeoPerfect** [Tencent/bk-ci#1507]
### 作为
DevOps 团队里的Dev，要实践持续部署流水线，

### 问题
但是执行流水线的时候，Job构建机器偶尔有时间会出现无法成功运行构建环境的情况，如下是使用DevCloud Docker构建机资源的例子，没有成功运行构建环境导致的Job失败
![image](https://user-images.githubusercontent.com/37768864/82047371-46ef8180-96e5-11ea-8a06-ca0344f6dfa9.png)

### 现状
目前task是支持重试机制的，但Job似乎不支持，
![image](https://user-images.githubusercontent.com/37768864/82047386-4fe05300-96e5-11ea-8e5b-d8861c360be8.png)

### 期待
我希望能够保证Job的成功运行构建环境，所以希望Job也能够支持重试机制

### 验收标准
Job支持重试机制，确保一定运行成功构建环境

**Comment by MikeoPerfect** [comment]
rebuild我理解似乎需要人工操作，请问可否有自动执行的rebuild

**Comment by irwinsun** [comment]
考虑下自动重试

**Comment by iccengan** [comment]
构建资源启动失败是短期的问题，应通过解决启动失败的问题来根治，而不应由平台方来解决。

**Comment by zanyzhao** [comment]
> 构建资源启动失败是短期的问题，应通过解决启动失败的问题来根治，而不应由平台方来解决。

而且盲目的自动重试会增大构建集群故障期间的压力，已经在构建集群分配构建机的流程里增加了“自动重试”逻辑，就不在CI Job上再加了。
