### ISSUE TITLE
增加复制流水线所有原子插入到另一流水线或者模版

### ISSUE THREAD

**Issue by FuXH** [Tencent/bk-ci#1513]
需要支持复制流水线的所有/部分插件原子，插入到另外一条流水线/模版里面的功能，并不会影响另一流水线原有的插件原子。

**Comment by TianzhuQin** [comment]
有时在两种不同业务中对于构建有不同需求，形成了两种目的不同的流水线，我们会希望让两条流水线合并，如前后跑两条流水线。此时会希望能无损且无影响的把一条流水线中的所有/部分插件原子插入到另一条中。

**Comment by zanyzhao** [comment]
这种情况是不是用子流水线调用会好一些？
