### ISSUE TITLE
希望公共构建机能够够广泛支持第三方镜像

### ISSUE THREAD

**Issue by hingbong** [Tencent/bk-ci#1514]
### 作为
DevOps 团队里的Dev，要实践持续部署流水线
比如我要构建 Golang 编写的东西, 最方便的就是在第三方镜像里选择 golang:latest, 但这些镜像不是都有 jre 环境的, 所以无法启动 work-agent, 于是希望能有较为方便的解决方法能够对这种镜像进行支持

**Comment by fayewong-v5** [comment]
可以看下 tlinux_ci 这个镜像是否满足需求，内置了golang 1.14，以及其他常用的开发依赖。
如果不满足需求，可以在研发商店中查找下，或者参考Dockerfile自己打一个镜像使用
