### ISSUE TITLE
使用集群构建的时候，等待构建机超时可否自定义，目前是10分钟

### ISSUE THREAD

**Issue by onlyforyoumylove** [Tencent/bk-ci#1517]
当使用集群进行构建的时候，因为每个流水线构建时间都比较长，而且流水线比较多，很多时候，后面提交的改动触发的流水线就需要等待构建资源，这种情况下，就很容易超过10分钟拿不到资源而失败，跟helper确认过，说10分钟是蓝盾整体的设置，所以能不能把这个10分钟的超时可以根据项目或者流水线自定义。

**Comment by iccengan** [comment]
Duplicate of #3575
