### ISSUE TITLE
【蓝盾】【产品-无需评审会】流程控制选项支持“自定义变量满足任一条件时就运行”

### ISSUE THREAD

**Issue by MikeoPerfect** [Tencent/bk-ci#1522]
### 作为
DevOps 团队里的Dev，要实践持续部署流水线

### 现状
Job执行的时候只有这几个选项，

![image](https://user-images.githubusercontent.com/37768864/82194420-5fe87480-9929-11ea-994b-485af6d46a15.png)
![image](https://user-images.githubusercontent.com/37768864/82194544-8dcdb900-9929-11ea-9c2a-e0a7aaa4dff9.png)

，我想让Job执行的时候，可以满足任一条件即可执行，即支持或条件变量

### 以便于
- 让 Ops 通过 Master 分支发布
- 让 Dev 在开发分支上开发
- 让 QA 可以选择对应的提交进行部署测试

### 期望的验收标准
Job执行支持或条件变量

-------------------------

### 我作为：
       使用流程控制选项的蓝盾流水线用户

### 我希望：
        1. 流程控制选项当中，增加“自定义变量任一满足时就运行”
 
### 这样我就可以：
        1. 当该task有多个准入值时就可以执行步骤，比如: 「游戏中QQ服、微信服、游客服、互通服」中只有「QQ服、微信服」是task的准入值，但自定义变量只需要是QQ服，就可以执行。

### 期望的验收标准：
        1. “何时运行Job”中增加“自定义变量任一条件满足时就运行”选项；
        2. 增加条件时，允许条件的key值重复；
        3. “何时运行Job”中增加“添加范围：Stage(除去Stage1)、Job、Task
        4. 满足任一条件后，该步骤可以正常运行

**Comment by iccengan** [comment]
后面可以使用pipeline script满足。
目前可以先通过前置bash插件做逻辑判断来满足。

**Comment by reggieisrunning** [comment]
我作为：
       使用流程控制选项的蓝盾流水线用户

我希望：
        1. 流程控制选项当中，增加“自定义变量任一满足时就运行”
 
这样我就可以：
        1. 当该task有多个准入值时就可以执行步骤，比如: 「游戏中QQ服、微信服、游客服、互通服」中只有「QQ服、微信服」是task的准入值，但自定义变量只需要是QQ服，就可以执行。

期望的验收标准：
        1. “何时运行Job”中增加“自定义变量任一条件满足时就运行”选项；
        2. 增加条件时，允许条件的key值重复；
        3. “何时运行Job”中增加“添加范围：Stage(除去Stage1)、Job、Task
        4. 满足任一条件后，该步骤可以正常运行

**Comment by EchoQT** [comment]
任一条件或全部条件，这些都只是极端情况。此处的需求程度取决于该流水线对用户实际场景的覆盖程度，也就是越复杂的流水线，进入标准就有各种逻辑组合的可能。与其做两个极端，不如直接做通用的条件设定，交互形式上是玩表单也好，伪代码也罢，都是从通用逻辑表达出发的。

重新设计一下，然后在例会上过一下。

**Comment by reggieisrunning** [comment]
该issue将合并至 #7313 进行设计
