### ISSUE TITLE
插件设置“失败时继续”后，若执行超时，流水线状态不正确

### ISSUE THREAD

**Issue by fayewong-v5** [Tencent/bk-ci#1526]
**Describe the bug**
插件设置“失败时继续”后，若执行超时，流水线状态不正确

**To Reproduce**
1、JOB 下有 A 插件，JOB 上设置超时时间为 1 分钟
2、A 插件勾选“失败时继续”
3、启动执行，超时后，A 插件和 Job状态都为成功，没有体现出超时失败

**Comment by mingshewhe** [comment]
当task超时，设置构建详情的状态不对,原来设置会一直时running状态，那为什么没有设置“失败时继续”没有问题，因为在BuildEndControl会对running状态的task置为失败.
![image](https://user-images.githubusercontent.com/22971705/84477169-cdd25280-acc1-11ea-8241-d7342770a54b.png)
