### ISSUE TITLE
[Feature requests] Pipeline variables for git branch should pull the recent edited branches 流水线变量 Git 分支选择应当优先拉取最近修改过的分支

### ISSUE THREAD

**Issue by ziofat** [Tencent/bk-ci#1546]
## Note  
To boot a pipeline, we can specify a git branch with pipeline variables. However, for git repository with more than 100 branches, only 100 branches are pulled and listed for selection.

Currently the 100 branches are randomly chosen as I have been told (I doubt it). I thought it just pulled the latest 100 branches by creation time. For some branches which created long before but committed recently, it should also be pulled for selection.

启动流水线时，我们可以通过流水线变量来指定一个分支。然而，对于拥有超过 100 个分支的仓库来说，启动流水线的选择界面只会拉取 100 个分支供选择。

据说，目前这 100 个分支是随机拉取的。而我感觉是基于创建时间获取的最新 100 个分支。而对于一段时间以前创建的，最近又有更新的分支，我认为应当也被列入选择范围。

## Required Information
Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

## Issue Description
What I expected:

The 100 branches available for selection are chosen by committed time.

期待功能：

100 个供选择的分支应根据最新提交时间来优先拉取。

**Comment by KylinHuang7** [comment]
另外，不在供选择的100个范围内的分支，希望也能可以输入。
如果可以，能够校验一下分支是否存在。
如果校验不了，直接允许输入也可以接受，毕竟如果不存在后面拉取的时候也会报错。

**Comment by iccengan** [comment]
1. 工蜂已提供分支搜索的接口，需支持从全量的分支里搜索出目标分支。
2. 默认列表仅展示最近更新过的100条分支。
