### ISSUE TITLE
构建再次确认有超时功能

### ISSUE THREAD

**Issue by 337240552** [Tencent/bk-ci#1563]
点击流水线执行按钮后，还会弹出一个确认框
![image](https://user-images.githubusercontent.com/329210/82628626-e51ca380-9c1f-11ea-92af-1963bb75ba03.png)

**经常会忘记点**这里的执行。

建议：第二次确认有个超时机制，如果30s没编辑，或者取消定时器， 就开始执行构建。

**Comment by zanyzhao** [comment]
万一你不想执行默认值呢

**Comment by 337240552** [comment]
> 万一你不想执行默认值呢

所以我提到了超时机制，以及可以取消定时器，大部分情况下都会用默认参数

**Comment by zanyzhao** [comment]
执行预览页的目的有2个：
- 收集参数
- 选择性跳过某些插件

我在想：
- 如果这两个特性你都不需要，可以把执行预览的开关关掉；
- 如果你希望达成其中任何一个目的，我们都不能帮你做决定（我们无法承担决定错了的风险）。
