### ISSUE TITLE
流水线执行失败时，TASK上进行重试不应该受到触发方式限制

### ISSUE THREAD

**Issue by fayewong-v5** [Tencent/bk-ci#1564]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

## Required Information
Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

## Issue Description
目前如果流水线触发方式为hook触发，没有允许手动触发。当执行失败想进行单步重试时，会提示流水线不能手动启动

需优化，支持这种情况下的单步重试

**Comment by irwinsun** [comment]
#2175
