### ISSUE TITLE
feature: Git事件触发，支持返回自定义检测结果

### ISSUE THREAD

**Issue by sherlockZ** [Tencent/bk-ci#1568]
##  #描述
![image](https://user-images.githubusercontent.com/7531339/82638727-12764b00-9c3a-11ea-8980-0fa741b7c2cd.png)
现在下面的描述都只是说流水线成功与否，但是鉴于检查的多样性，我们希望可以自定义返回的检查结果，而不是单纯的只告诉你流水线执行成功与否
![image](https://user-images.githubusercontent.com/7531339/82638885-39cd1800-9c3a-11ea-9582-9aa8303f43dc.png)
现在的情况是，解释我在流水线运行过程中修改了检查结果，流水线运行完毕之后也会用默认的结果覆盖我的自定义结果，十分不便

**Comment by zanyzhao** [comment]
> 在流水线运行过程中修改了检查结果

我不理解你是如何做到的，流水线一旦启动是无法人工干预结果的
