### ISSUE TITLE
fix: 重试可能导致无法启动的问题

### ISSUE THREAD

**Issue by irwinsun** [Tencent/bk-ci#1576]
## Note  
在[PR 1006](https://github.com/Tencent/bk-ci/pull/1006/files#diff-9d0e9112efd3f699c30fc5917c6859b0)
issue #678
之后，引出了一个问题，修改了启动构建机的TaskId，将导致在修改之前的构建点击重试时，引发构建机启动插件找不到的问题，进而引起重试/rebuild任务无法正常启动。 

## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Comment by MikeoPerfect** [comment]
所以我觉得应该要支持Job级别的自动化retry，至少得保证构建机器的正常启动

https://github.com/Tencent/bk-ci/issues/1507

**Comment by zanyzhao** [comment]
> 所以我觉得应该要支持Job级别的自动化retry，至少得保证构建机器的正常启动

如果是平台问题导致的失败，即使加上了自动重试，在不做任何调整的情况下大概率也是会失败，只能人工干预了

**Comment by irwinsun** [comment]
此问题仅影响
