### ISSUE TITLE
支持可编程的（或可高度定制）构建容器调度能力

### ISSUE THREAD

**Issue by cateatcatx** [Tencent/bk-ci#1582]
希望蓝鲸提供支持可编程的（或可高度定制）构建容器调度能力。

**使用场景：**
项目组是Unity项目，现在的流水线只能绑定某台机器的某个工作空间，但如果待构建工程的Svn差异不太的话，完全可以多条流水线复用同一个工作空间，然后通过Svn Switch的方式切换工作空间的内容。这样可以充分利用构建机空间。

**抽象描述：**
上面的使用场景是一个具体示例。示例抽象一下的话，可以认为我们需要的是一个可编程的Job调度器，然后蓝鲸可以提供一些基础的调度策略（CPU负载、磁盘空间等）。

**额外好处：**
这样将Job的工作空间解耦开之后，会有一个额外的好处，就是项目组成员可以自己创建自己的构建私线（通过模版），创建时不需要关心具体所在的构建机和工作空间（构建机和工作空间是只有构建管理员才清楚的信息）。

**Comment by irwinsun** [comment]
抛开实际场景，我的理解这个问题其实是工作空间动态切换的问题？

是否可以通过自定义一个工作空间的变量的方式设置工作空间来解决这个问题？
而变量的值应当由触发的时候在某个插件来做判断给予不同的值。

![image](https://user-images.githubusercontent.com/16686129/82802437-79ea0000-9eb1-11ea-9941-e4dc0ed764ca.png)

**Comment by cateatcatx** [comment]
嗯，如果有这种插件的话，也可以满足我的需求

**Comment by zanyzhao** [comment]
我们来提供构建机的CPU、MEM、磁盘等最新数据，但这个插件得是你来写

**Comment by irwinsun** [comment]
此问题可以用户自主可控决定
