### ISSUE TITLE
feat:git触发的锁定希望可以针对部分人生效

### ISSUE THREAD

**Issue by JackStronger** [Tencent/bk-ci#1600]
**Feature**  
git触发的锁定目前是全局的，希望锁定提交这个选项可以针对部分人生效，或部分分支生效，最好可以自定义条件来控制是否生效。

**Comment by zanyzhao** [comment]
具体是哪个功能？可以截个图看下

**Comment by JackStronger** [comment]
![image](https://user-images.githubusercontent.com/13563024/83753042-22f7de00-a69c-11ea-826a-bfb166836356.png)
这个锁定想针对一部分人锁定

**Comment by zanyzhao** [comment]
后续这个开关有可能会被去掉，默认不锁定
