### ISSUE TITLE
执行历史增加触发信息字段

### ISSUE THREAD

**Issue by zanyzhao** [Tencent/bk-ci#1644]
**Question, Bug, or Feature?**  
*Type*: Feature

## Required Information
我希望执行历史列里增加“触发信息“字段，用来表示这次任务产生时对应的Commit Message或者MR/PR Message

- [ ] 执行历史里增加`触发信息`字段
- [ ] 触发信息列的位置替代原来的“源材料”字段
- [ ] 源材料字段默认隐藏

**Comment by mingshewhe** [comment]
增加”触发仓库“、”触发分支“、”触发事件“和”触发类型几个字段“
```
"webhookInfo": {
  "webhookRepoUrl": "", // 触发url
  "webhookBranch": "", // 触发分支
  "webhookType": "", // 触发类型：github/svn/gitlab
  "webhookEventType": "", // 触发事件类型 
  "webhookMessage": "" // 触发信息
}
```
触发事件类型:[CodeEventType](https://github.com/Tencent/bk-ci/blob/master/src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/trigger/enums/CodeEventType.kt])
