### ISSUE TITLE
希望可以将流水线上几个连续的插件组合起来保存成组件，便于重用与升级

### ISSUE THREAD

**Issue by guanwenbogit** [Tencent/bk-ci#1645]
**Question, Bug, or Feature?**  
*Type*: Feature

## Required Information
将流水线中几个连续使用的插件组合保存起来，可以到其他流水线中应用，比起写插件，用已有的插件组合出新组件会更灵活高效。
例如，bash其实是灵活性最高的插件，但不易于转移。
例如，bash+其他类型插件也可衍生出大量的其他功能。

如果平台本意是不提倡bash，但不可否认的是，在流水线上使用bash是最直接衍生新插件的方式，只是要解决维护和重用的问题

**Comment by iccengan** [comment]
#938 可以满足你的需求哈 @guanwenbogit
