### ISSUE TITLE
可以编写在流水线成功或失败时执行的job

### ISSUE THREAD

**Issue by crazy-bit** [Tencent/bk-ci#165]
可以编写在流水线成功或失败时执行的job

**Comment by irwinsun** [comment]
目前流水线是支持这类功能的， 不过是task级别（插件）。 
![image](https://user-images.githubusercontent.com/16686129/67189026-0e721880-f420-11e9-9cd5-b34cfaa7c501.png)

**Comment by irwinsun** [comment]
> 嗯，需要的是一个流水线任意一步失败都能执行的job，类似try{}catch{}，可以写一个catch动作
> 当前如果需要在流水线失败时做一些操作，需要在每个stage的每个job去写这个失败操作

其实你可以理解为job就是一个最小粒度的流水线。
try->catch->finally 一般是用业做清理补偿动作，多少与构建机/工作空间绑定在一块的，因此才设计为以job为中心。 因每个job都是用不同构建机/工作空间来处理，否则就容易出现冲突问题， 所以是尽量避免给大家带来使用上冲突的设计。

**Comment by irwinsun** [comment]
后面会实现stage即使失败了仍然能继续执行下一个stage的job，由用户自己决定。

**Comment by zanyzhao** [comment]
#510
