### ISSUE TITLE
流水线环境变量 在实例化时 可以添加一个执行时锁定功能

### ISSUE THREAD

**Issue by facemao3** [Tencent/bk-ci#1662]
**Question, Bug, or Feature?**  
*Type*: here

## Required Information
Entering this information will route you directly to the right team and expedite traction.

**Comment by facemao3** [comment]
流水线环境变量 在实例化时 可以添加一个执行时锁定功能：执行时 锁定不能修改，即实例化后，执行时可以指定某些变量不能被修改（显示还是需要，防止不知道自己执行的是什么），主要针对pm 策划等操作 防止出错。类似于执行时不显示一样的选项，可以显示但不能修改，只读就好

**Comment by iccengan** [comment]
@facemao3 也就是模板常量功能对吧？
