### ISSUE TITLE
蓝盾流水线支持变量名一键修改替换

### ISSUE THREAD

**Issue by AllenHuai** [Tencent/bk-ci#167]
比如我在构建触发那里改了某个变量名.  流水线中使用这个变量名的插件中,这个名称可以自动替换成新的.

**Comment by irwinsun** [comment]
1. 因为变量在使用上非常便捷灵活可见，基于让用户输入变量名的方式来引用变量，并非使用UI的选择绑定方式或者是ID的关联，所以如果是进行遍历流水线编排上各种插件参数内容做一一替换，是比较差的一种方式，而且也无法做到100%替换（因变量可在插件执行自己构建机上的外置脚本中使用到）。
2. 修改变量名这类行为是低频动作，建议在命名上精确些，减少往复的修改操作，提高效率会更好。
