### ISSUE TITLE
拉取Git插件支持用变量指定拉取方式

### ISSUE THREAD

**Issue by iccengan** [Tencent/bk-ci#1679]
**Question, Bug, or Feature?**  
*Type*: Feature

### 现象：
目前【指定拉取方式】配置项填入变量时，【分支/Tag/Commit Id】配置项会被隐藏。使用变量配置【指定拉取方式】无法使用。

### 期望：
【分支/Tag/Commit Id】常驻。
（可能需要用插件大版本来支持）

**Comment by iccengan** [comment]
并添加支持 -depth 和 -recursive 配置

**Comment by mingshewhe** [comment]
推荐使用checkout插件,支持通过变量的【指定拉取方式】
