### ISSUE TITLE
在Job中可以配置局部变量

### ISSUE THREAD

**Issue by gitpaladin** [Tencent/bk-ci#168]
# 起因
![image](https://user-images.githubusercontent.com/8654635/67373798-d18a5b00-f5b2-11e9-8679-9ef252052871.png)
如图两个Job1，Job2，在J1-1和J2-1中定义一些变量的配置，然后J1和J2的后续Task中使用这些变量的配置，但由于J1和J2在同一个容器是并行配置的，所以J1和J2的后续Task中的变量是会冲突的。
而Job之间是并行跑的，所以非常有必要在Job级中支持局部变量这一特性，以便在Task中传递数据

# 解决办法
bash脚本中可是使用诸如 `setLocalEnv <variable> <value>` 这样的命令设置Job范围内的局部变量，而在Task中使用`${local_variable}` 获取局部变量的值，Task中的变量可以设置为Job局部内的，或全局的

**Comment by irwinsun** [comment]
变量名称是完全可以自定义的， 不同的Job可以定义不同名称的变量即可， 这部分自由交给用户来。
${local_variable}  本质上相当于用一个前缀区分开了（变量名不同了），如果是这样，我可以根据用户的场景分析一下当前如何解决：
场景： Job1与Job2 下所有插件任务全部相同，区别的是插件中用到的变量的值不同
解决办法 ： Job1和Job2 可以理解为程序上的代码冗余，那么可以将这部分Job抽离成流水线，在Job1和Job2 做子流水线引用他即可，定义好变量输入即可。例如：
![image](https://user-images.githubusercontent.com/16686129/69208970-7d15d380-0b90-11ea-91c0-a9a8dd57c73c.png)
