### ISSUE TITLE
产出物报告-第三方报告支持去重

### ISSUE THREAD

**Issue by hunterno44** [Tencent/bk-ci#1682]
**Question, Bug, or Feature?**  
*Type*: Feature

现象：
目前【产出物报告-第三方报告】当同一条流水线中，使用了多个同一插件时，若每个插件都输出一个第三方报告URL，且报告URL的名称和链接均相同时，蓝盾在产出物报告-第三方报告中会显示多个跳转链接，这几个链接都指向相同的报告链接

期望：
【产出物报告-第三方报告】当这多个报告链接完全相同时，可以去重

**Comment by zanyzhao** [comment]
我的问题是，为什么要在同一条流水线里生成3份一模一样的报告？
