### ISSUE TITLE
Stage审核人配置的流水线变量为空时，无法审核

### ISSUE THREAD

**Issue by iccengan** [Tencent/bk-ci#1687]
**Question, Bug, or Feature?**  
*Type*: Bug

### 现象：
Stage审核的审核人配置为变量时，如果该变量为空，任何人均无法触发审核。只能等待审核超时以结束流水线状态。
![image](https://user-images.githubusercontent.com/10875468/83593396-38cbad00-a58f-11ea-832a-39bb91793d41.png)
![image](https://user-images.githubusercontent.com/10875468/83593526-89430a80-a58f-11ea-9018-d783dcbf6624.png)

**Comment by iccengan** [comment]
且目前不能支持流水线变量

**Comment by loveLeiTing** [comment]
急需这个功能，求解决

**Comment by iccengan** [comment]
> 且目前不能支持流水线变量

已支持。变量为空时，不应允许审核。设计如此。
