### ISSUE TITLE
插件输入敏感信息隐藏

### ISSUE THREAD

**Issue by LeeGone** [Tencent/bk-ci#1689]
**Question, Bug, or Feature?**  
*Type*: Feature
插件输入的敏感信息填过之后变星号，或者查看流水线历史记录的时候变星号。
![image](https://user-images.githubusercontent.com/40971816/83611619-ce793380-a5b3-11ea-9193-339114eba841.png)

**Comment by fayewong-v5** [comment]
输入字段 isSensitive 配置为 true 时，页面展示******

**Comment by LeeGone** [comment]
已尝试，但无效。效果见下图。









------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"fayewong-v5"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月3日(星期三) 下午4:32
收件人:&nbsp;"Tencent/bk-ci"<bk-ci@noreply.github.com&gt;;
抄送:&nbsp;"李刚毅"<974749051@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Tencent/bk-ci] 插件输入敏感信息隐藏 (#1689)





 
输入字段 isSensitive 配置为 true 时，页面展示******

**Comment by fayewong-v5** [comment]
@LeeGone ，可以修改下输入字段配置，使用 vuex-input 组件时，加上 inputType 属性，示例：
![image](https://user-images.githubusercontent.com/54432927/83622238-43ec0080-a5c2-11ea-9dc3-c73fc2379d29.png)
