### ISSUE TITLE
[BUG][BE]流水线模板变量描述修改后在更新时未能同步

### ISSUE THREAD

**Issue by irwinsun** [Tencent/bk-ci#170]
![image](https://user-images.githubusercontent.com/16686129/67734018-e9daf980-fa3a-11e9-81b9-f39c0120ed79.png)
![image](https://user-images.githubusercontent.com/16686129/67734036-f65f5200-fa3a-11e9-9dfe-b80b895e3663.png)
![image](https://user-images.githubusercontent.com/16686129/67734059-05de9b00-fa3b-11e9-90c3-5f22a001fa42.png)
![image](https://user-images.githubusercontent.com/16686129/67734096-17c03e00-fa3b-11e9-8d67-a607c8e79481.png)
实例化更新请求没有协带desc内容

**Comment by royalhuang** [comment]
此前已经修复
