### ISSUE TITLE
希望更新模板实例化流水线的时候可以支持原子化

### ISSUE THREAD

**Issue by SpeCialmark** [Tencent/bk-ci#1705]
**更新模板后更新下游实例只能全量更新**  
## 公共模板更新时下游实例希望支持原子化更新

**具体场景:**
新建了一个公共模板, 在模板中配置了多个插件, 其中某些插件是需要下游在实例化之后进行自定义的, 在模板中这些插件的内容是空的.
**当前情况:**
在下游自定义了那些空插件后模板发生更新, 下游实例同步更新模板时这些自定义的内容会被强制覆盖为模板中的内容
**需求:**
在下游实例同步模板更新时, 希望可以选择性的更新实例中的某个或多个插件, 而不是强制性的全量更新

**Comment by zanyzhao** [comment]
如果插件的顺序发生变化怎么办？
