### ISSUE TITLE
【feature】跳转链接和批量操作的功能建议

### ISSUE THREAD

**Issue by noonhorse** [Tencent/bk-ci#1707]
**Feature**  
*Type*: here

## Required Information
Entering this information will route you directly to the right team and expedite traction.

1、所有连接跳转建议通过url的形式跳转。比如
      a、调试按钮，js处理跳转经常失败无法跳转，但是看url路径其实可以是通过url链接拼接出来。
      b、在打开流水线时，不能通过链接快速打开和鼠标右键标签打开。

2、在管理界面增加批量管理功能，在给流水线打标签的时候可以批量操作。
    a、希望可以快速的将多个流水线规整到一个视图下，希望现在的视图条件这里可以直接按流水线来选择添加到视图下；
    b、标签也可以批量设置所属流水线，现在只能通过一个一个的流水线去设置标签

**Comment by zanyzhao** [comment]
1已经有类似issue #872 正在开发中
2 会有一个整体计划，后续会增加一个流水线组的功能 #1055 我正在规划
