### ISSUE TITLE
模板实例化，选中旧版本实例化后，实例关联的版本信息不正确

### ISSUE THREAD

**Issue by fayewong-v5** [Tencent/bk-ci#1719]
**Question, Bug, or Feature?**  
*Type*: BUG

## Required Information
Entering this information will route you directly to the right team and expedite traction.

比如模板A当前版本是2.0，选中1.0创建实例B后，B内容正确，但关联的模板版本信息显示的是2.0

**Comment by iccengan** [comment]
回归仍有此问题，重新打开修复。
