### ISSUE TITLE
构建历史的bash插件配置中，选中输入框内容后无法复制

### ISSUE THREAD

**Issue by iccengan** [Tencent/bk-ci#1720]
**Question, Bug, or Feature?**  
*Type*: Bug

### 现象：
![image](https://user-images.githubusercontent.com/10875468/132793192-c414d7fd-c04f-4384-9145-b57c185a3e58.png)

如上图所示，选中红框区域后，Ctrl + C后，没有成功复制到剪切板。

### 期望：
能对任意输入框内容进行选中并复制。

**Comment by iccengan** [comment]
> 请问这个issue有进展吗，选中后右键--复制选项也是灰的，只能点击编辑流水线才能复制，但这样操作很怕误操作修改了流水线的内容，且相当于只能复制最新版本的内容，复制不了历史版本的

已排期

**Comment by lockiechen** [comment]
已经修复
