### ISSUE TITLE
私有构建机下线提醒

### ISSUE THREAD

**Issue by osblow** [Tencent/bk-ci#1728]
现在添加的私有构建机在agent停止工作或者网络断开后没有企业微信提醒
希望在机器下线时可以有提醒

**Comment by alexcheney** [comment]
同求，这个功能非常有用！ 急求！

**Comment by larryhou** [comment]
基本每台构建机都会隔一段时间就会掉线，希望尽快排期实现

**Comment by irwinsun** [comment]
> 基本每台构建机都会隔一段时间就会掉线，希望尽快排期实现

掉线是不可避免的吗， 构建机上是否有代理或人为误操作导致agent受到影响， 如果次数太多，可能会让通知变成无效，对通知人也有大量骚扰，是否有排查是什么原因掉线，尽量地避免需要人工收通知再干预。
