### ISSUE TITLE
建议 /support-files/templates/ 下配置文件的文件名修改一下

### ISSUE THREAD

**Issue by Ben-zl** [Tencent/bk-ci#173]
建议 /support-files/templates/ 下配置文件的文件名修改一下，不然执行完render_tpl，配置会放在/etc/ci目录下，需要手工拷贝到/etc/bkci

<img width="273" alt="WX20191029-220531@2x" src="https://user-images.githubusercontent.com/5083068/67774618-a616dd00-fa98-11e9-89b6-b1be143a2619.png">

**Comment by irwinsun** [comment]
确认下你是不是在/根目录下安装的吧，假设你的安装目录是/data/bkce。
那么#etc/#ci 以#号开头的，在替换完成会会自动被迁移到/dat/bkce/etc/ci目录下

**Comment by Ben-zl** [comment]
> 确认下你是不是在/根目录下安装的吧，假设你的安装目录是/data/bkce。
> 那么#etc/#ci 以#号开头的，在替换完成会会自动被迁移到/dat/bkce/etc/ci目录下

好的，谢谢

**Comment by irwinsun** [comment]
你好，问题是否解决了

> > 确认下你是不是在/根目录下安装的吧，假设你的安装目录是/data/bkce。
> > 那么#etc/#ci 以#号开头的，在替换完成会会自动被迁移到/dat/bkce/etc/ci目录下
> 
> 好的，谢谢
