### ISSUE TITLE
call:setEnv对特殊字符的处理有问题

### ISSUE THREAD

**Issue by tangcat123** [Tencent/bk-ci#1738]
**Question, Bug, or Feature?**  
*Type*: here
call:setEnv "s" a&b
对特殊字符&的解析有问题
即使写成a^&b仍然会有问题，应该是setEnv内部处理有bug

## Required Information
Entering this information will route you directly to the right team and expedite traction.

**Comment by irwinsun** [comment]
setEnv是一个非常早期的设计，太多历史用户使用，改动上存在风险，所以不不推荐使用， 

目前可以使用

echo "::set-variable name=key::a&b"

使用 ${{variables.key}} 获取变量
