### ISSUE TITLE
质量红线openAPI

### ISSUE THREAD

**Issue by zanyzhao** [Tencent/bk-ci#1739]
**Question, Bug, or Feature?**  
*Type*: Feature

## Required Information
增加质量红线open API

**Comment by jerrybean** [comment]
急需

**Comment by jerrybean** [comment]
目前的质量红线 API 支持查询列表，查询拦截记录，增加、更新、删除。缺少根据 ID 获取质量红线详情 API。目前列表API返回的缺少部分信息  @zanyzhao
