### ISSUE TITLE
质量红线的审批人能够支持流水线变量

### ISSUE THREAD

**Issue by zanyzhao** [Tencent/bk-ci#1745]
**Question, Bug, or Feature?**  
*Type*: Feature

### 作为
团队CI负责人

### 我希望
质量红线的审批人能够支持流水线变量

### 以便于
对于多条流水线生效的质量红线，审批人能够通过流水线变量传进来。这对于大型项目非常有益处

### 期望的验收标准
1. 创建一个 质量红线，设置对于多条流水线生效，审批人设置为某个流水线变量
2. 执行流水线，通过变量传入一个用户英文名，比如：AAA
3. 观察流水线被红线拦截后，AAA是否如预期收到审核通知

**Comment by terlinhe** [comment]
质量红线前端的审批人填写是支持输入变量的，后端支持解析替换就可以了，前端应该不需要修改

**Comment by irwinsun** [comment]
已经在别的issue中实现
