### ISSUE TITLE
流程控制条件运行特性支持Operation

### ISSUE THREAD

**Issue by zanyzhao** [Tencent/bk-ci#1747]
**Question, Bug, or Feature?**  
*Type*: Feature

## Required Information
![image](https://user-images.githubusercontent.com/1629409/84018746-f2bd8180-a9b2-11ea-8ca6-48bf09a7e210.png)

**Comment by iccengan** [comment]
`不等于`：#1208
`包含`：#429

**Comment by iccengan** [comment]
变量间是否也可考虑添加Operation。目前变量间是"与"的关系，可考虑添加"或"关系。

**Comment by yong1026** [comment]
为了通用，建议增加一种“自定义函数”模式，通过脚本的返回值来判断

**Comment by iccengan** [comment]
> 为了通用，建议增加一种“自定义函数”模式，通过脚本的返回值来判断

关注下 #155，是否能满足你的需求。

**Comment by iccengan** [comment]
### 参考：
![image](https://user-images.githubusercontent.com/10875468/140288752-779df0f7-7878-4315-a5cc-03dece6c39a7.png)

**Comment by chen3286822** [comment]
这个需求还会支持吗？这样可以更快捷地控制流水线执行过程，而不需要先跳到某个机器下的batch或者shell去做判断

**Comment by reggieisrunning** [comment]
该issue将合并至 #7313 进行设计
