### ISSUE TITLE
显示资源别名的字段显示错误

### ISSUE THREAD

**Issue by zanyzhao** [Tencent/bk-ci#1750]
**Question, Bug, or Feature?**  
*Type*: Bug

## Required Information
问题1：目前显示的具体资源IP，而不是别名，期望显示别名

**Comment by iccengan** [comment]
![image](https://user-images.githubusercontent.com/10875468/88372126-e86f0f80-cdc7-11ea-9bba-535172743ee4.png)
${加壳机器}的值不为【构建机器显示器】，别名展示错误

**Comment by mingshewhe** [comment]
偶尔会出现这种问题，当多个job并发的运行的时候，就会出现。原因在com.tencent.devops.process.engine.service.PipelineRuntimeService#saveBuildVmInfo 这个方法没有控制并发，当两个job同时运行的时候，可能会覆盖model数据
![image](https://user-images.githubusercontent.com/22971705/94400234-51de1680-019b-11eb-9a5c-d08024e65a47.png)
应该调用com.tencent.devops.process.engine.service.PipelineBuildDetailService#update进行更新
