### ISSUE TITLE
构建执行成功后即可以删除构建中的一些信息

### ISSUE THREAD

**Issue by zanyzhao** [Tencent/bk-ci#1753]
**Question, Bug, or Feature?**  
*Type*: Feature

## Required Information
当构建执行成功后（不会重试），以下数据没有存在的必要：

T_PIPELINE_BUILD_VAR  这些信息仅在重试时需要使用上一次执行的参数数据，执行成功后就可以安全删除掉了。

**Comment by fayewong-v5** [comment]
已加清理策略，仅保留最近两个月的数据
