### ISSUE TITLE
建议“重试”支持从stage开始重试

### ISSUE THREAD

**Issue by PhantomQi** [Tencent/bk-ci#1778]
**Feature**  
*Type*: here

假设一个stage有好几个步骤，1拉代码→2一些准备工作→3执行脚本→4……。假设在步骤3失败了，流水线提供的重试功能只能从步骤3开始重试，但前面的步骤1和2可能也需要重新执行，才能保障3能正常执行。在这种情况下只从步骤3开始重试就没有任何意义了，所以需要从stage开始重试的能力。

**Comment by zanyzhao** [comment]
#1566 已开发完毕，准备发布

**Comment by zanyzhao** [comment]
已上线
