### ISSUE TITLE
建议项目管理增加收藏功能

### ISSUE THREAD

**Issue by kinyoung1024** [Tencent/bk-ci#178]
当个人有权限的项目越来越多时，切换项目的下拉选择会变得很多，选择常用项目的操作会变得比较麻烦（要么是滚动查找，要么是输关键字过滤），希望可以增加项目收藏功能，已收藏的项目在下拉列表中置顶，实现常用项目的快速选择和切换。

**Comment by irwinsun** [comment]
@zanyzhao

**Comment by zanyzhao** [comment]
已经规划了一个全新的控制台服务，可以支持项目收藏等功能 @iccengan

**Comment by iccengan** [comment]
新版控制台的【最近访问项目】是否可以满足需求。通常需收藏的项目是高频操作的项目，【最近访问项目】会展示最近6次访问的项目，应可覆盖【收藏】功能的需求。

**Comment by zanyzhao** [comment]
可以关注下 https://github.com/Tencent/bk-ci/projects/6
