### ISSUE TITLE
“可运行多个构建任务”选项可以定义具体是几个

### ISSUE THREAD

**Issue by davidruan13** [Tencent/bk-ci#1780]
Feature  
“可运行多个构建任务”选项可以定义具体是几个
我们有第三个开始排队或者第四个开始排队的需求
## Required Information

![image](https://user-images.githubusercontent.com/66678009/84223272-2102a480-ab0c-11ea-9b8a-3abec7003a1d.png)

**Comment by zanyzhao** [comment]
Duplicate of #1018
