### ISSUE TITLE
Stage准入

### ISSUE THREAD

**Issue by zanyzhao** [Tencent/bk-ci#1790]
**Question, Bug, or Feature?**  
*Type*: Feature

## Required Information
将目前的Stage审核抽离到Stage准入侧边栏内

- 审核人支持变量
- 最大超时1440小时

**Comment by iccengan** [comment]
### 准入图标状态：
#### 编辑流水线：
1. 自动触发（即关闭准入）
2. 手动触发（即启用准入），同时配置正确
3. 手动触发，但配置有误

#### 已执行流水线：
1. Stage被跳过（自动触发）
2. Stage被跳过（手动触发）
3. 未执行到的Stage（自动触发）
4. 未执行到的Stage（手动触发）
5. Stage正常执行（自动触发）
6. 拒绝准入的Stage
7. 通过准入的Stage
8. 等待Stage owner准入的Stage

### 注意：
Stage owner和非Stage owner看到的图标状态一致。但非Stage owner点开准入图标的侧滑栏中，准入按钮置灰不可点击。

**Comment by iccengan** [comment]
### Stage准入侧滑弹窗：
#### 准入方式 / Trigger（单选）：
- 人工审核 / Manual Approvals
- 自动 / Automation

---
【当准入方式为人工审核时】
#### Stage审核人 / Stage Owner（输入框）：
1. 审核人必填，当审核人为空时，红色文案：请输入至少一名审核人。 / Enter at least one approver.
2. 关联issue：#1687

#### 审核最长等待时间 / Timeout（输入框）：
1. 单位：小时 / Hours
2. 取值范围为数字1-720，当输入内容包含非数字字符 || 数字小于1 || 数字大于720 时，红色文案：请输入1-720之间的整数。 / Please specify an integer from 1 to 8760.
