### ISSUE TITLE
「执行历史」交互问题和Bug

### ISSUE THREAD

**Issue by panmingyang2009** [Tencent/bk-ci#1812]
**Bug & Feature**  

## 问题背景

某天出了疑难 Bug，需要回溯蓝盾上的构建记录，因此需要翻大量的执行历史。
但是发现蓝盾上「执行历史」的交互体验较差，不便于查找较久前的记录。

## 复现场景

在打包记录较多的流水线上，打开「执行历史」，向前翻阅五百条左右记录，展开其中几条的二维码，用手机扫码安装。

## 使用环境

浏览器：Safari
网络环境：在家使用 VPN 接入内网 或 在公司使用内网

## 遇到的问题

1、【性能】执行历史页面巨卡无比（特别是有转菊花的时候），翻页困难，被 Safari 提示网页消耗大量能耗
2、【体验】翻页操作不太友好，需要逐页滚动加载，效率低。建议支持正常翻页，并能够选择每页展示数量
2、【体验】执行历史进入详情后再返回，就回到列表顶部，要找刚刚又要再次翻页，再卡一次 
3、【Bug】执行历史页面，往下滚动几页之后，点击某次执行，大概率点不动（无法展开详情）

**Comment by zanyzhao** [comment]
目前已经增加了搜索功能，可否满足你的需求？

**Comment by irwinsun** [comment]
长期无回复，暂时关闭
