### ISSUE TITLE
【FE】如何进行定制化开发

### ISSUE THREAD

**Issue by ChenSimin0103** [Tencent/bk-ci#182]
请问对于前端frontend文件夹下的多个前端工程，应该如何方便的进行二次开发和功能调试呢？
我尝试装完依赖后单独启动每个工程，只有 devops-nav 这个工程是能正常打开调试的，其他几个目录下的工程该如何调试呢

**Comment by Roy9102** [comment]
@ChenSimin0103 devops-nav是我们的主入口，其他子服务以单独的前端资源文件(js|css)的形式存在，通过devops-nav异步加载渲染，所以如果需要进行定制化开发，需要先启动devops-nav，然后通过采用反向代理的方式，将对应服务的文件路径指向本地打包后的文件

**Comment by ChenSimin0103** [comment]
多谢指导 !
本地打包后的文件目录应该是 bk-ci\src\frontend\frontend 下的每个子文件夹吧
请问每个子服务运行yarn dev生成的文件存放在哪里呢

**Comment by Roy9102** [comment]
都是存放在bk-ci\src\frontend\frontend下的哈，每个子服务有自己的目录
