### ISSUE TITLE
流水线预设变量支持分组

### ISSUE THREAD

**Issue by iccengan** [Tencent/bk-ci#1829]
**Question, Bug, or Feature?**  
*Type*: Feature

### 需求
可在`Job1-1`配置流水线变量时，对变量进行分组，并设置组名。在手动执行/模板实例化界面，同一组别的变量放在一起，考虑使用虚线分隔。

### 场景
当流水线变量太多：
1. 利于不同角色手动启动流水线时，关注对应角色所需要配置的参数
2. 利于不同角色实例化流水线模板时，关注所需配置的参数

![image](https://user-images.githubusercontent.com/10875468/84742698-73980100-afe3-11ea-99f8-4777f46f6609.png)

**Comment by iccengan** [comment]
Duplicate of #2017

**Comment by evanzzcao** [comment]
依赖的代码库越来越多，需要分组来独立逻辑
