### ISSUE TITLE
[流水线] CI支持SBT构建工具

### ISSUE THREAD

**Issue by carbonshow** [Tencent/bk-ci#1866]
**Feature**  
*Type*: CI支持SBT构建工具

## Required Information

Scala是运行在jvm上的集面向对象和函数式编程于一身的语言，广泛应用于分布式系统和大数据处理中。比如spark，flink，kafka，akka等。Scala的主流编译工具链是sbt。

需求：
- 希望在流水线中支持基于sbt的构建，简化scala语言的集成成本。

**Comment by carbonshow** [comment]
另外补充下，sbt功能非常强大，通过读取工程的配置，可以在线更新plugin实现很多功能，包含：docker的镜像制作和推送。

所以，如果要实现该功能，建议提供：
- sbt的基础功能
- 良好的外网代理访问，便于在线拉取plugin
- 对第三方镜像的访问接口
- 完善的基础镜像，构建业务镜像，所以来的基础镜像，一般都是jdk xxx。

其他的就交给sbt自己和业务工程配置即可。

**Comment by zanyzhao** [comment]
感谢carbon的反馈，我们先研究下这个编译工具。

**Comment by 826837680** [comment]
![image](https://user-images.githubusercontent.com/26375510/86074157-f1660d00-bab7-11ea-93ce-c294534f0927.png)
![image](https://user-images.githubusercontent.com/26375510/86074199-09d62780-bab8-11ea-8a24-fa00ae66b94c.png)
流水线的依赖编译环境有可用的sbt和scala的版本可选择，carbon可以试试是否满足。

**Comment by carbonshow** [comment]
> ![image](https://user-images.githubusercontent.com/26375510/86074157-f1660d00-bab7-11ea-93ce-c294534f0927.png)
> ![image](https://user-images.githubusercontent.com/26375510/86074199-09d62780-bab8-11ea-8a24-fa00ae66b94c.png)
> 流水线的依赖编译环境有可用的sbt和scala的版本可选择，carbon可以试试是否满足。

谢谢，我尽快测试，看看主流程能否通过。
