### ISSUE TITLE
Support displaying custom variable in pipeline execution history list

### ISSUE THREAD

**Issue by jianzhongli** [Tencent/bk-ci#1877]
**Feature Request**  
*Type*: The information in "material" column is not enough for us to identify what the artifacts are built on. We would like to show custom pipeline variable values in the execution list.

## Required Information
![image](https://user-images.githubusercontent.com/5278523/84994914-f8b71d80-b17d-11ea-8643-4cb687a76bb6.png)

**Comment by zanyzhao** [comment]
you can set a system built-in variable `BK_CI_BUILD_REMARK `, it will display as "Remark" column.
