### ISSUE TITLE
给每个job/stage一个独立的状态图标

### ISSUE THREAD

**Issue by fatfatson** [Tencent/bk-ci#1882]
**Question, Bug, or Feature?**  
*Type*: Feature

## Required Information
Entering this information will route you directly to the right team and expedite traction.

我有一个工程，里面有5个目标程序，每个目标都要编4个平台，如果我想在首页用一个表格显示每个目标在每个平台的最后构建状态（通过引用流水线图标url），那我就要建立5x4=20个流水线，既难于管理，又浪费空间。
如果一条流水线里，每个job或是stage都有独立的状态，那我只要一条流水线就能做到了。

**Comment by zanyzhao** [comment]
你创建一个包含1个Stage、20个Job的流水线不就行了?

**Comment by fatfatson** [comment]
> 你创建一个包含1个Stage、20个Job的流水线不就行了?

一个流水线只有一个状态图标，我要分别获取每个job的结果的状态图标表示

**Comment by irwinsun** [comment]
是一把梭行云流水将5000行代码写在一个函数里，还是重构成20个子函数分散在不同的文件，这个根据不同场景有不同的取舍，没有绝对好坏之分。 但前者一定是更简单，后者则是需要花费一定思考提炼总结才能做好的。
平台目前选择的设计是期望大家尽量缩小单个流水线的复杂度，通过子流水线的方式去拆分不同的构建逻辑。
可以有一个主流水线：包含20个子流水线插件，触发20条子流水线，而这20条子流水线又可以通过流水线模板去实例出来，通过模板做统一管理，差异化的用流水线变量来解决。
