### ISSUE TITLE
极速安装好后无法登录

### ISSUE THREAD

**Issue by steelxiang** [Tencent/bk-ci#190]
极速安装好后无法登录，登录没法反应，ubuntu系统

**Comment by irwinsun** [comment]
开源版没有对接任何登录系统，请问你说的登录是蓝鲸社区版吗？

**Comment by steelxiang** [comment]
是的，那应该怎么进去呢

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Yi<mailto:notifications@github.com>
发送时间: 2019年12月2日 18:06
收件人: Tencent/bk-ci<mailto:bk-ci@noreply.github.com>
抄送: steelxiang<mailto:steelxiang@live.com>; Author<mailto:author@noreply.github.com>
主题: Re: [Tencent/bk-ci] 极速安装好后无法登录 (#190)


开源版没有对接任何登录系统，请问你说的登录是蓝鲸社区版吗？

―

**Comment by steelxiang** [comment]
是的，那应该怎么进去呢

**Comment by irwinsun** [comment]
bk-ci 是不需要登录的，我说的是蓝鲸社区版的话，可以加入蓝鲸社区版交流1群：495299374
