### ISSUE TITLE
支持通过输出 ##[set-output key=value] 指定变量

### ISSUE THREAD

**Issue by lockiechen** [Tencent/bk-ci#1914]
我希望能通过如下约定的格式，CI可以从标准输流里识别变量，自动放入到我们的变量列表中，方便后续流程引用

##[set-output key=value]

此约定来自 Github Actions。

Example：
假设你使用的编程语言为 Node.js，可以在自身的build流程中通过console.log输出对应的变量。
示例代码如下：
```
console.log(`##[set-output currentVersion=1.0.0]`);
```

**Comment by irwinsun** [comment]
见 #4123 已经上线，
feat: 根据输出日志::set-variable name=<my-var-1>::<my-var-value-1> ，刷新变量 #4123

**Comment by irwinsun** [comment]
@lockiechen
