### ISSUE TITLE
Feature: 希望远程触发插件支持使用默认参数

### ISSUE THREAD

**Issue by justinyanme** [Tencent/bk-ci#1927]
## Feature Request: 希望远程触发插件支持使用默认参数

目前远程触发插件需要填写参数才能使用，如果不填写，则会报错失败，如果填写为空，则真的用空作为参数触发流水线任务。

e.g.

```
curl -X POST http://example.com/your/pipelines/some-id/build -H "Content-Type: application/json" -d "{\"param1\":\"param1\",\"param2\":\"param2\"}"
```

实际上 `param1`/`param2` 在手动触发时都有默认参数，希望能复用该默认参数。

**Comment by zanyzhao** [comment]
Duplicate of #985
