### ISSUE TITLE
支持默认不展示debug日志，可手动打开

### ISSUE THREAD

**Issue by fayewong-v5** [Tencent/bk-ci#1934]
**Question, Bug, or Feature?**  
*Type*: here

## Required Information
Entering this information will route you directly to the right team and expedite traction.

**Comment by fayewong-v5** [comment]
增加 “显示全量日志”入口，默认不展示debug日志，点击“显示全量日志”后，展示包括debug的所有日志
![image](https://user-images.githubusercontent.com/54432927/96539108-dc162800-12cc-11eb-8a8e-beeab1e8977b.png)

**Comment by royalhuang** [comment]
提供可拓展的多种日志类型，前端构建日志支持分级查看，已录新单 #3524
