### ISSUE TITLE
agent编译的build_linux.sh没有在根目录下找到。

### ISSUE THREAD

**Issue by She1d0n** [Tencent/bk-ci#1948]
**Question**  
*Type*: agent编译的build_linux.sh没有在根目录下找到。

## Required Information
在编译构建的时候到agent的编译，按照文档在Linux下可以执行build_linux.sh脚本，但是目录下没有找到啊。

**Comment by irwinsun** [comment]
可以参考下我们的action是如何对agent进行编译的
https://github.com/Tencent/bk-ci/blob/master/.github/workflows/agent.yml
