### ISSUE TITLE
Bug: 界面错乱

### ISSUE THREAD

**Issue by Bacra** [Tencent/bk-ci#1950]
**Question, Bug, or Feature?**  
*Type*: Bug

## Required Information

流水线列表，复制流水线，弹窗UI界面有问题
![image](https://user-images.githubusercontent.com/3293588/86091790-102bca00-badf-11ea-8509-08d341ae2420.png)

**Comment by iccengan** [comment]
具体是什么UI界面问题？

**Comment by Bacra** [comment]
截图里面，“应用设置” 文案应该没有了，取而代之的，应该是“流水线描述”

弹窗触发方式是：
流水线列表，点击具体流水线的“复制流水线”

**Comment by iccengan** [comment]
> 截图里面，“应用设置” 文案应该没有了，取而代之的，应该是“流水线描述”

了解了，“应用设置”应改为“流水线描述”

**Comment by terlinhe** [comment]
开源版本不存在这个问题，内部版这个问题已在其issue解决处理
