### ISSUE TITLE
模版流水线中去掉推荐版本号之后，在更新实例的时候，依然有推荐版本号的流水线变量出现

### ISSUE THREAD

**Issue by Bacra** [Tencent/bk-ci#1951]
**Question, Bug, or Feature?**  
*Type*: Bug

## Required Information

更新实例的时候多出来构件号这个变量，新增实例是没有的

![image](https://user-images.githubusercontent.com/3293588/86093934-5df60180-bae2-11ea-9240-0f0cb755f5a0.png)

**Comment by irwinsun** [comment]
问题目前已无法复现
