### ISSUE TITLE
bug: openJDK下project微服务在创建项目出错

### ISSUE THREAD

**Issue by irwinsun** [Tencent/bk-ci#1957]
当使用OPENJDK运行微服务时， 会导致创建项目时调用graphAPI来默认生成的图片失败，
![image](https://user-images.githubusercontent.com/16686129/86143609-3b3a0c00-bb27-11ea-9b03-6f1ce238ff9f.png)

**Comment by irwinsun** [comment]
需要确认下是使用的操作系统（OS)版本，环境， JDK版本等信息

**Comment by stubenhuang** [comment]
project项目依赖宋体 (下载地址: https://github.com/stubenhuang/bkci_k8s/raw/master/code_image/backend/font/simsun.ttc)

需要在缺失该字体的系统中安装该字体

举个例子, 在centos7中:
1. 新建目录/usr/share/fonts/chinese , 并将该字体复制到该目录下 
2. 执行 rpm --rebuilddb \
    &&yum -y install fontconfig ttmkfdir \
    && chmod -R 755 /usr/share/fonts/chinese \
    && ttmkfdir -e /usr/share/X11/fonts/encodings/encodings.dir \
    && fc-cache
