### ISSUE TITLE
feature: Git分支变量类型支持非必填

### ISSUE THREAD

**Issue by Bacra** [Tencent/bk-ci#1958]
**Question, Bug, or Feature?**  
*Type*: Feature

## Required Information

Git分支变量类型，是不是不需要一定填写呢？
已经在后续流水线Bash命令中，对变量进行更多的默认值判断

![image](https://user-images.githubusercontent.com/3293588/86201306-c6e88280-bb91-11ea-8437-54ff29c199b2.png)

**Comment by iccengan** [comment]
关注下更通用的需求：#900
