### ISSUE TITLE
feat: 建议非最新构建的测试插件也支持重试按钮

### ISSUE THREAD

**Issue by qianfanblue** [Tencent/bk-ci#1962]
**Question, Bug, or Feature?**  
*Type*: Feature

## Required Information
建议非最新构建的测试插件也支持重试按钮
目前只有最新且失败的构建会支持stp的插件重试，但如果有多次构建中间一次出错需要重试定位时没有入口重试，希望仅依赖构建产物的非最新构建的测试插件也可以支持重试按钮

**Comment by irwinsun** [comment]
将开放配置项，由用户自行决定，见 #2175
