### ISSUE TITLE
BKCI的backend编译出错

### ISSUE THREAD

**Issue by Johgjc** [Tencent/bk-ci#1965]
> Task :core:artifactory:model-artifactory:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':core:artifactory:model-artifactory:compileClasspath'.
> Could not find org.jetbrains.kotlin:kotlin-stdlib-jdk8:.
Required by:
project :core:artifactory:model-artifactory
> Could not find org.jetbrains.kotlin:kotlin-reflect:.
Required by:
project :core:artifactory:model-artifactory

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.8/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 3s

环境：

# gradle -v

------------------------------------------------------------
Gradle 4.8
------------------------------------------------------------

Build time: 2018-06-04 10:39:58 UTC
Revision: 9e1261240e412cbf61a5e3a5ab734f232b2f887d

Groovy: 2.4.12
Ant: Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM: 1.8.0_252 (Oracle Corporation 25.252-b09)
OS: Linux 4.18.0-147.8.1.el8_1.x86_64 amd64

**Comment by irwinsun** [comment]
看下gradle.properties文件的Maven仓库依赖源的地址是否修改过？
![image](https://user-images.githubusercontent.com/16686129/87565680-8b52ca00-c6f4-11ea-8a80-5be2cc3e61cb.png)

看起来像是网络问题无法从远程Maven仓库下载需要的依赖包。
能否使用以下命令重试一下？ 
```shell
gradle classes --debug
```
