### ISSUE TITLE
Job和Stage状态添加【局部成功】

### ISSUE THREAD

**Issue by iccengan** [Tencent/bk-ci#1970]
**Question, Bug, or Feature?**  
*Type*: Feature

### 场景：
当插件流程控制选择【失败时继续】，且插件状态为失败时，所属Job的状态应为【局部成功】。

### 需求：
当Job状态为【局部成功】时，该Stage状态也为【局部成功】。后面Stage不再执行（可配置流程控制）。
可理解为，【局部成功】是【失败】状态的一种子类型。

**Comment by irwinsun** [comment]
#4315
