### ISSUE TITLE
子流水线调用输出子流水线执行信息到流水线变量

### ISSUE THREAD

**Issue by jerrybean** [Tencent/bk-ci#1971]
**Question, Bug, or Feature?**  
*Type*: Feature

## Required Information
Entering this information will route you directly to the right team and expedite traction.
子流水线调用插件执行结束后（无论是否成功），输出子流水线的链接到流水线变量，供下游插件使用。

**Comment by iccengan** [comment]
能描述下具体的需求场景吗？如用于发送通知？

**Comment by fayewong-v5** [comment]
Duplicate of #1034
