### ISSUE TITLE
refactor: 移除获取代码库BUILD无用接口

### ISSUE THREAD

**Issue by ddlin0719** [Tencent/bk-ci#1981]
替换掉RepositoryService#buildGet的方法，没必要多做一次projectId查询

**Comment by irwinsun** [comment]
- [ ] 移除BuildRepositoryResource.getV2 (已经无用）
- [ ] 移除BuildRepositoryResource.get (已经无用）
- [ ] getByType增加 AUTH_HEADER_DEVOPS_PROJECT_ID 头参数
