### ISSUE TITLE
添加流水线触发条件

### ISSUE THREAD

**Issue by iccengan** [Tencent/bk-ci#199]
添加流水线触发条件：监听mr状态，当mr状态从待合入变更为可自动合入时，触发流水线。

场景：mr状态为可自动合入时，触发流水线，利用【GIT分支和MR操作】插件自动将源分支合入目标分支。

**Comment by zanyzhao** [comment]
@linjun-ddddd 关注一下

**Comment by zanyzhao** [comment]
其实可以在代码库服务里做个ci-robot来实现，本身跟流水线关联性不大
