### ISSUE TITLE
bugfix: 准入后的stage重试时取消判断

### ISSUE THREAD

**Issue by royalhuang** [Tencent/bk-ci#2022]
目前stage会被卡在待审核状态，而构建机已经进入准备状态，待修复
![image](https://user-images.githubusercontent.com/58923885/86877353-4b4e7e80-c119-11ea-8ec1-7f0083f94f50.png)

同时需要确认：
配有审核的stage在重试时，是否还需要再次审核？

**Comment by zanyzhao** [comment]
> 配有审核的stage在重试时，是否还需要再次审核？

不需要，准入之后的重试，不应该再触发准入判断
