### ISSUE TITLE
bugfix:远程触发和openapi启动流水线会遇到能”流水线: 不能太频繁启动构建“的错误

### ISSUE THREAD

**Issue by freyzheng** [Tencent/bk-ci#2027]
远程触发和openapi启动流水线会遇到能”流水线: 不能太频繁启动构建“的错误

原因是这两种触发方式使用的都是使用手动触发的方式，这里需要去掉频率限制。

**Comment by irwinsun** [comment]
不管何种请求都需要有频率限制，不允许无限频率的请求操作
见需求#2434
