### ISSUE TITLE
构建触发条件支持变量控制

### ISSUE THREAD

**Issue by jolanxiao** [Tencent/bk-ci#2048]
**Question, Bug, or Feature?**  
*Type*: here

## Required Information
Entering this information will route you directly to the right team and expedite traction.
同一个模板有不同的实例。
实例1 希望是自动触发
实例2 希望是MR触发

希望能够支持变量控制触发

**Comment by iccengan** [comment]
在后面的流程控制中，通过流水线触发方式的变量`${BK_CI_START_TYPE}`来判断能满足你的需求吗？
可取值为：
```
MANUAL        //手动触发
TIME_TRIGGER  //定时触发
WEB_HOOK      //钩子回调
SERVICE       //内部的服务间调用，目前系统外部暂时不会用到
PIPELINE      //子流水线调用
REMOTE        //远程触发
```

**Comment by irwinsun** [comment]
> 在后面的流程控制中，通过流水线触发方式的变量`${BK_CI_START_TYPE}`来判断能满足你的需求吗？
> 可取值为：
> 
> ```
> MANUAL        //手动触发
> TIME_TRIGGER  //定时触发
> WEB_HOOK      //钩子回调
> SERVICE       //内部的服务间调用，目前系统外部暂时不会用到
> PIPELINE      //子流水线调用
> REMOTE        //远程触发
> ```

变量控制触发行为，用户从自身业务角度出发，可在流水线增加一个Bash插件根据上述变量来控制流程，自行实现。
