### ISSUE TITLE
构建集群功能不支持设置排队超时时间

### ISSUE THREAD

**Issue by osblow** [Tencent/bk-ci#2068]
现有问题：
流水线使用构建集群作为执行环境，在所有机器都跑满任务时会进入排队，但是10分钟后会排队超时而失败。
问过小助手，说这个时间是写死的，没有开放接口来配置。
而我们的任务一般比较重，一次执行5个小时都是有可能的，10分钟的等待时间根本不够。

期望功能：
在构建集群中可以提供选项来配置排队超时时长

**Comment by zanyzhao** [comment]
我们先内部评估下

**Comment by iccengan** [comment]
Duplicate of #3575
