### ISSUE TITLE
加入流水线回滚功能以及删除流水线历史构建同时删除产生的二进制文件

### ISSUE THREAD

**Issue by qihaooo** [Tencent/bk-ci#207]
**Is your feature request related to a problem? Please describe.**
基于代码发布一个版本有错误或者是想回滚到某个提交的代码版本

**Describe the solution you'd like**

**Describe alternatives you've considered**
加入流水线回滚功能以及删除流水线历史构建同时删除产生的二进制文件

**Additional context**

**Comment by irwinsun** [comment]
@zanyzhao

**Comment by zanyzhao** [comment]
流水线并不适合做线上版本管理功能，可以通过自定义插件或者部署服务来实现，比如K8S原生就支持rollback操作，只需要在流水线中增加对应的K8S调用插件即可。

流水线构建记录永不清理且无法删除，二进制文件会有一定的清理策略。
