### ISSUE TITLE
bug: 插件已运行失败，但Job状态一直在运行中

### ISSUE THREAD

**Issue by zanyzhao** [Tencent/bk-ci#2074]
**Question, Bug, or Feature?**  
*Type*: Bug

## Required Information
- 插件已经运行失败，但Job还是显示执行中
- Job超时时间也到了，但还是显示执行中
- 手动点击终止后结束
![image](https://user-images.githubusercontent.com/1629409/87530076-73fae900-c6c2-11ea-856e-252667e53dc4.png)

**Comment by irwinsun** [comment]
原因见 #2043
