### ISSUE TITLE
bug: Agent构建日志logback在对日志文件进行按日期或按大小分割时可能会导致Java死锁

### ISSUE THREAD

**Issue by irwinsun** [Tencent/bk-ci#2075]
# 现象：
java -jar worker-agent.jar 启动之后，java进程处理无响应，堆栈如下：
[7556.log](https://github.com/Tencent/bk-ci/files/4924461/7556.log)

**Comment by pop0505** [comment]
agent主线程有如下一段代码：
```
private fun showMachineLog(vmName: String) {
		// ...
    System.getProperties().forEach { k, v ->
        // forEach内部会持有Properties对象锁                            
        LoggerService.addNormalLine("$k: $v") // ① 写入到队列中，由异步线程去写入日志服务                
        logger.info("$k: $v") // ② 打印日志      
    }
    // ...
}
```
`Properties`继承`HashTable`，是线程安全的类，提供了`forEach`方法，注意这个`forEach`并不是Kotlin语法糖，而是一个同步方法。在代码①处主线程持有了环境变量`Properties`对象锁，而LoggerService会开启异步线程写日志到日志服务，当异步线程logback日志打印时，持有到`SizeAndTimeBasedRollingPolicy`对象锁，并尝试获取`Properties`对象锁，而主线程②处logback日志打印又会去竞争`SizeAndTimeBasedRollingPolicy`对象锁，形成两个线程相互竞争导致死锁。
