### ISSUE TITLE
Feature:节点支持查看所有指定了该机器的流水线

### ISSUE THREAD

**Issue by chen3286822** [Tencent/bk-ci#2086]
**Question, Bug, or Feature?**  
*Type*: Feature

## Required Information
Entering this information will route you directly to the right team and expedite traction.
在环境管理->节点中，希望能查看到某个节点上具体应用了哪些流水线，现在节点里有一个分页显示了构建任务，但是这里只是流水线执行的历史记录，不能方便地查看所有流水线。

**Comment by iccengan** [comment]
如：
![image](https://user-images.githubusercontent.com/10875468/87648818-82a8d500-c782-11ea-8e53-2258c30874b5.png)

**Comment by zanyzhao** [comment]
可以考虑在构建机详情页增加Job分配信息，包含已分配的Job，和正在运行的Job两种视图

**Comment by irwinsun** [comment]
该issue与 #3795 一样，合并为一个issue跟进

**Comment by iccengan** [comment]
通过 #3843 满足
