### ISSUE TITLE
Feature:插件支持配置异步运行方式

### ISSUE THREAD

**Issue by chen3286822** [Tencent/bk-ci#2087]
**Question, Bug, or Feature?**  
*Type*: Feature

## Required Information
Entering this information will route you directly to the right team and expedite traction.
希望插件可以提供异步运行方式功能，类似于 **子流水线调用** 插件
这样在构建流水线上将更加灵活，还能节省一些时间

**Comment by fayewong-v5** [comment]
是否可以异步，由插件逻辑控制的，可以和具体的插件开发者一起讨论下

**Comment by chen3286822** [comment]
> 是否可以异步，由插件逻辑控制的，可以和具体的插件开发者一起讨论下

和插件作者讨论过，同时也拉了蓝盾助手讨论过，蓝盾助手给出的结论是除了子流水线调用这个插件以外，其他插件都不支持，蓝盾能否提供一种通用接口，供插件作者来实现异步

**Comment by fayewong-v5** [comment]
要看从助手那里得到的结论是基于什么具体场景。

子流水线调用的异步，也是这个插件自己实现的。插件里根据是否异步，来决定调起子流水线后是否轮询结果，直到子流水线运行完毕。异步就是不轮询，调起成功则视为插件执行成功。

同理，如果你们使用到的工具，有自己的执行后台，支持类似的逻辑，即可实现异步效果。
