### ISSUE TITLE
Feature:归档构件插件支持不归档文件通配符匹配

### ISSUE THREAD

**Issue by chen3286822** [Tencent/bk-ci#2089]
**Question, Bug, or Feature?**  
*Type*: Feature

## Required Information
Entering this information will route you directly to the right team and expedite traction.
现在归档构件可以用通配符匹配要归档的文件，比如 bin/*
但是bin下面可能有不想归档的文件，比如 abc.log
希望能提供一个归档目录下的不归档通配符来过滤掉 abc.log

**Comment by zanyzhao** [comment]
Duplicate of #2113
