### ISSUE TITLE
feat: 第三方构建机 Agent 支持任意 HTTPS 证书

### ISSUE THREAD

**Issue by hingbong** [Tencent/bk-ci#2096]
**Question, Bug, or Feature?**  
*Type*: Feature

## Required Information
Entering this information will route you directly to the right team and expedite traction.

**Comment by irwinsun** [comment]
安全建议：Agent负责构建一切处理，安全与保密有要求，不建议默认支持任意证书，如确实需要信任，需要在构建机进行导入。
或者单独为用户构建出特殊安装包， 但主干不推荐进行此类整改。
