### ISSUE TITLE
Question 项目中的的同事为什么没有查看流水线权限？

### ISSUE THREAD

**Issue by xiaohp** [Tencent/bk-ci#2100]
**Question** 
背景：
在项目管理-用户管理中，添加了同事为【开发人员】角色。但是该同事查看流水线权限，还需要另外如此，这是设计如此还是一个 bug ？

**Comment by xiaohp** [comment]
搞清楚了，还需要在流水线里面的权限设置，可以关联用户组，这里能否默认关联上，项目里面的成员，查看流水线日志的权限还是需要的，因为会收到通知，需要查看日志。

**Comment by zanyzhao** [comment]
系统内置的默认组都是有默认权限的，只有新增组的时候才会置空（我们不确定你是否真的需要为新组授权流水线权限）
