### ISSUE TITLE
Feature:字符串类型的流水线变量支持换行

### ISSUE THREAD

**Issue by h3r3x3** [Tencent/bk-ci#2116]
**Question, Bug, or Feature?**  
*Type*: Feature

## Required Information
Entering this information will route you directly to the right team and expedite traction.
个别流水线的插件支持输入信息，比如Release插件，需要输入本次release的标题，描述等信息。
业务测每次发版本都去修改流水线配置，所以想在流水线变量中传递，但是现在变量不支持换行，这样对于比如前面提到的release描述就没法支持
![企业微信截图_34136b82-2a61-4383-8f90-936ac6f5297f](https://user-images.githubusercontent.com/2006134/87923161-a4ba9400-caaf-11ea-8618-11c1f5d5eff0.png)

**Comment by dasinlsb** [comment]
是否可以在文本框右端加入按钮  点击弹出对话框或类似组件

原文本框样式不变  弹框支持换行展示

**Comment by zerolyd** [comment]
同样有需求，场景有：
1、提交git时，附带注释
2、刷新配置时，希望直接将配置贴在变量值里
