### ISSUE TITLE
bug: 同一项目不同流水线模版的同名"GIT分支或TAG"类型变量读取错误问题

### ISSUE THREAD

**Issue by yeehone** [Tencent/bk-ci#2125]
## BUG
如下图所示：
同一个项目中的两个流水线模版，都有同一个叫做`manualTriggerBranch`的`"GIT分支或TAG"`类型变量，但是选择的Git仓库不同。
在他们分别进行实例化时，第二个流水线模版（om移动接入层omproxy模版所拉取的分支列表不符合预期，拉取到了第一个流水线模版对应变量的分支列表）

![image](https://user-images.githubusercontent.com/971327/88019428-5d3e1180-cb5c-11ea-9a34-3840a5cc6306.png)
![image](https://user-images.githubusercontent.com/971327/88019562-aa21e800-cb5c-11ea-98e4-55599b5daff0.png)
![image](https://user-images.githubusercontent.com/971327/88019756-0f75d900-cb5d-11ea-9f28-3b01bc7667cc.png)
![image](https://user-images.githubusercontent.com/971327/88019835-32a08880-cb5d-11ea-9cf5-6238c57bf2b8.png)

修改同名变量为其他的命名后拉取正常。ps. 其中一个模版是另一个模版复制出来的。
![image](https://user-images.githubusercontent.com/971327/88019977-6c718f00-cb5d-11ea-990a-12cbf65aa475.png)

**Comment by iccengan** [comment]
@yeehone 尝试了下没法复现，后面还有遇到过这个问题吗？
