### ISSUE TITLE
蓝盾独立消息通知通道支持

### ISSUE THREAD

**Issue by Ariel20180710** [Tencent/bk-ci#2141]
蓝盾原子发送企业微信消息都是通过消息通知的，没有其他通道。消息通知那个通道往往也有其他消息，容易被其他消息淹没。建议提供独立消息通知通道

**Comment by fayewong-v5** [comment]
在研发商店搜索下 企业微信机器人推送， 可以推送通知到指定群里，看看是否满足您的使用场景。

**Comment by Ariel20180710** [comment]
> 在研发商店搜索下 企业微信机器人推送， 可以推送通知到指定群里，看看是否满足您的使用场景。

不符合的，这样需要有固定群聊，里边要拉很多人，消息依旧容易被淹没。还是觉得蓝盾有独立消息通道会好很多

**Comment by deepjia** [comment]
还有个方式是「企业微信群聊助手」这个插件

**Comment by deepjia** [comment]
还有个方式是「企业微信群聊助手」这个插件，我们用它每次拉新群通知触发人

**Comment by zanyzhao** [comment]
> 还有个方式是「企业微信群聊助手」这个插件，我们用它每次拉新群通知触发人

感觉这个方法应该可以满足。另外，我想到一种独立通知的通道，比如浏览器自带的通知，就像Gmail一样
