### ISSUE TITLE
git/svn触发插件的路径希望增加模糊

### ISSUE THREAD

**Issue by hao1032** [Tencent/bk-ci#2142]
**Question, Bug, or Feature?**  
*Type*: Feature

## Required Information
Entering this information will route you directly to the right team and expedite traction.
项目中有多个androidTest文件夹，希望监控所有包含androidTest的路径，当前路径不支持模糊匹配，只能一个一个写，希望可以模糊匹配
![image](https://user-images.githubusercontent.com/4860962/88175420-6d3b1b80-cc58-11ea-8f52-d5cf1b6e0616.png)

**Comment by iccengan** [comment]
支持通配符匹配。需考虑是否通过开关方式。

**Comment by iccengan** [comment]
通过微扩展兼容老数据

**Comment by ZezhongWang** [comment]
同求
