### ISSUE TITLE
feat: 插件流程控制支持设置允许失败后手动重试开关

### ISSUE THREAD

**Issue by KylinHuang7** [Tencent/bk-ci#2175]
**Question, Bug, or Feature?
*Type*: Feature

## Required Information
有些步骤不涉及环境问题上的失败（例如审批），允许重试可能会引发一些风险。
例如多个审批人，审批人A发现发布内容有风险给拒绝了；但审批人B也许没有发现到这个风险，点了重试后又通过了。
（当然，假如一开始就被审批人B通过了，也一样会将风险发布出去；但毕竟可以在风险已经被部分人员发现的情况下减少影响。）

因此，希望可以设置某些步骤“禁止重试”

**Comment by zanyzhao** [comment]
嗯嗯，人工审核的插件确实特殊，可以考虑去掉重试功能，你这边还有没有其它的必须“禁止重试”的插件？

**Comment by KylinHuang7** [comment]
我觉得包含非幂等操作步骤的环境都应该可以设置禁止重试

**Comment by irwinsun** [comment]
可为每个插件的控制流程新增一个开关： “禁止手工重试”
![image](https://user-images.githubusercontent.com/16686129/97677570-69c3f580-1acd-11eb-81f9-c84658eec8a1.png)

复用当前后台为前端操作有一个canRetry的字段判断，当执行失败流程结束后，可以在失败的插件中展示“重试”按钮
必须满足：
- 插件执行失败了
- 未开启“禁止失败后手动重试”
- 未开启“失败时继续”

**Comment by zanyzhao** [comment]
再结合 #4245 就完美了

**Comment by Toplife** [comment]
请支持下原子插件关闭重试的功能

**Comment by iccengan** [comment]
同 #933

**Comment by zanyzhao** [comment]
Duplicate of #4245
