### ISSUE TITLE
流水线日志中加上重试相关log

### ISSUE THREAD

**Issue by loveLeiTing** [Tencent/bk-ci#2223]
**流水线构建历史中存在构建时间很长的case，可能是因重试导致的**  
*Type*: Feature

## Required Information
了解到构建历史的时常是通过最新完成时间和流水线第一次执行时间来计算统计的，如果中间有重试就会导致构建时间显示很长，但是目前没有重试相关的日志

预期：
希望能在流水线日志中补充重试相关log，明确重试触发的时间点和触发人，方便能了解一次构建的完整生命周期

**Comment by zanyzhao** [comment]
刚好在重新设计流水线任务详情页，可以关注下 #1742
