### ISSUE TITLE
feature:流水线Dashboard期望添加最新执行时间排序

### ISSUE THREAD

**Issue by MikeoPerfect** [Tencent/bk-ci#2228]
**Feature**  
*Type*: feature

**背景**
流水线 dashboard，很多流水线，在查看具体某个流水线时，无法通过最新执行时间筛选出最新执行的流水线
![image](https://user-images.githubusercontent.com/37768864/88766232-40cc5580-d1aa-11ea-9aa0-3377ee1fd39e.png)

**现状**
无法通过最新执行时间筛选出最新执行的流水线

**期望**
可以通过最新执行时间排序，筛选出最近的流水线信息

**Comment by zanyzhao** [comment]
刚好正在重新设计流水线列表页面，可以关注下 #1055

**Comment by buendia27** [comment]
一般有问题的时候，点进去是想看最新执行的一条流水线结果，所以这里希望加一下按执行时间排序的功能；

按名称、创建时间排序，目前这两个个功能基本不用，在流水线多的时候，基本都是需要搜索的

**Comment by iccengan** [comment]
@buendia27 合理需求。需求已规划，重新设计流水线列表页面时会一起考虑。

**Comment by yhaoyan** [comment]
迫切需要这个能力，请看下这个排期到什么时候能够解决呢？能否快速上线，这里改动量应该非常小，效果非常好吧

**Comment by irwinsun** [comment]
已完成上线
