### ISSUE TITLE
stage的审批希望审批人有权限转单

### ISSUE THREAD

**Issue by Ariel20180710** [Tencent/bk-ci#2232]
此处指stage的审批。
审批人通常都是根据某些通用规则去拉取的，但是偶尔还是会有例外，会有同学反馈那个单子已经转给其他同学了，需要别人来审批。目前平台貌似没有这种能力，希望可以优化一下~

**Comment by iccengan** [comment]
> 审批人通常都是根据某些通用规则去拉取的

某些通用规则拉取是指？



> 会有同学反馈那个单子已经转给其他同学了，需要别人来审批

审核人需要移交审核权限给另一个非审核人吗？

**Comment by Ariel20180710** [comment]
通用规则是指拉取审批人的规则，这种规则一般是所有项目用同一个规则。但是偶尔还是会出现某些项目不能用这个规则，这个时候就需要把审核权转移给其他合适的同学。所以有这样的需求。流水线一般用于发布，其实主要就是发布权限的转移，这个还是蛮重要的

**Comment by irwinsun** [comment]
devops流程上推荐轻量的审核。 
一般在发布前就需要明确由该来负责审核， 并且已经支持变量指定，是能够满足不同流水线需求

你这种属于因组织架构，人员岗位调整等导致的需要变更审批人，基本上不是一种常见的场景， 实现该功能的意义不大，而且会导致整个审批流加重，还要增加切换人员等等操作入口。 不建议实现。
