### ISSUE TITLE
openresty 1.13.6.2 + openssl 1.1.0 与网关 jwt 模块不兼容

### ISSUE THREAD

**Issue by hingbong** [Tencent/bk-ci#2277]
**Question, Bug, or Feature?**  
*Type*: bug

## Required Information
Entering this information will route you directly to the right team and expedite traction.
openssl 1.1.0 应该是去掉了 EVP_MD_CTX_create
![image](https://user-images.githubusercontent.com/26398240/89269546-94d4af80-d66c-11ea-8efc-3d82e0070095.png)
[参考](https://github.com/openresty/openresty/issues/372)

**Comment by irwinsun** [comment]
#5736
