### ISSUE TITLE
质量红线中需要支持展示结果链接，目前使用代码分析扫描，无法在红线中看到对应的结果链接，极不友好。

### ISSUE THREAD

**Issue by runrunbian** [Tencent/bk-ci#2279]
![image](https://user-images.githubusercontent.com/5801934/89271314-1c232280-d66f-11ea-8e62-0e853cc9c107.png)

**Comment by carrywang05** [comment]
可在插件代码库根目录下，通过名为quality.json的文件，定义质量红线指标的链接。具体如下：
"logPrompt": "xxx" # 红线日志输出提示。展示在拦截日志后。
可以使用html的写法，例如：
xxxxx

**Comment by irwinsun** [comment]
本功能需要跟对接质量红线的相关插件开发者提需求，
平台侧已经支持该功能，例如CodeCC的检查结果已经按质量红线的规范输出
![image](https://user-images.githubusercontent.com/16686129/97683532-65024000-1ad3-11eb-9508-7bbee11f451b.png)
