### ISSUE TITLE
质量红线中支持展示结果链接

### ISSUE THREAD

**Issue by acetang-tencent** [Tencent/bk-ci#2281]
质量红线中需要支持展示结果链接，目前使用代码分析扫描，无法在红线中看到对应的结果链接，极不友好。
<img width="837" alt="企业微信截图_04205f35-64a3-4267-8dc5-26260de57947" src="https://user-images.githubusercontent.com/69192144/89273352-006d4b80-d672-11ea-9a68-5a0f0d0fda50.png">

**Comment by zanyzhao** [comment]
Duplicate of #2279
