### ISSUE TITLE
文档该更新了

### ISSUE THREAD

**Issue by wenhao** [Tencent/bk-ci#2317]
**Question, Bug, or Feature?**  
*Type*: here

## Required Information
Entering this information will route you directly to the right team and expedite traction.

**Comment by iccengan** [comment]
@wenhao 具体是指哪里的文档吗？

**Comment by wenhao** [comment]
> @wenhao 具体是指哪里的文档吗？

我看实际上加了很多的服务，但架构图和每个服务的描述都没更新呢?
