### ISSUE TITLE
bugfix: 获取日志为空问题

### ISSUE THREAD

**Issue by fayewong-v5** [Tencent/bk-ci#2318]
**Question, Bug, or Feature?**  
*Type*: bug

## Required Information
表现：流水线偶现日志为空，拉取不到

原因：worker打日志的executeCount获取全局重试次数并直接+1，而前端是基于detail内的重试次数来查日志，导致前面某container重试后面没有执行两次的container也按+1来打日志

**Comment by irwinsun** [comment]
Stage 重试存在该问题
