### ISSUE TITLE
人工审核，支持修改默认审核结果

### ISSUE THREAD

**Issue by Bacra** [Tencent/bk-ci#2319]
**Question, Bug, or Feature?**  
*Type*: Feature

## Required Information

![image](https://user-images.githubusercontent.com/3293588/89604713-6b02cf00-d89e-11ea-8cbe-c03f06c6d22a.png)

审核结果的默认选项，希望改成“驳回”

**Comment by iccengan** [comment]
具体需求场景是？担心误点吗？

**Comment by Bacra** [comment]
嗯，担心污点，审批的时候，希望默认是不通过的

**Comment by iccengan** [comment]
@Bacra 鉴于倾向默认同意/默认驳回两种场景的用户都有，这边建议的方案是默认不选。这样也能满足你的需求
