### ISSUE TITLE
人工审核配置BK_CI_START_USER_NAME问题

### ISSUE THREAD

**Issue by iccengan** [Tencent/bk-ci#2331]
**Question, Bug, or Feature?**  
*Type*: Bug

### 现象
人工审核插件的审核人配置为${BK_CI_START_USER_NAME}
![image](https://user-images.githubusercontent.com/10875468/89773260-285b2400-db36-11ea-9604-7440c1fecc26.png)
A执行流水线，当所含【人工审核】插件的Job执行失败时，B点了Stage重试。A视角点击审核按钮报错：
![image](https://user-images.githubusercontent.com/10875468/89773242-1ed1bc00-db36-11ea-9fbf-ee490308688e.png)
B视角也无法审核：
![image](https://user-images.githubusercontent.com/10875468/89773439-7b34db80-db36-11ea-80cf-df0a0c6edf68.png)

### 期望
待商榷

**Comment by royalhuang** [comment]
原因：后端使用编排信息检查审核人，应使用和前端一致的构建详情信息
