### ISSUE TITLE
perf: 模板实例化/更新时代码库分支变量支持切换代码库

### ISSUE THREAD

**Issue by iccengan** [Tencent/bk-ci#2339]
**Question, Bug, or Feature?**  
*Type*: Feature
### 现象
模板配置"GIT分支或TAG"类型的流水线变量
![image](https://user-images.githubusercontent.com/10875468/89974216-04fabb00-dc95-11ea-90d2-9308975ec4ec.png)
实例化时，没有入口选择代码库
![image](https://user-images.githubusercontent.com/10875468/89974276-278cd400-dc95-11ea-9512-4d7d68fcb7b8.png)
执行时也无法修改代码库
![image](https://user-images.githubusercontent.com/10875468/89974439-b00b7480-dc95-11ea-909b-eba51d779652.png)

**Comment by iccengan** [comment]
目前逻辑设计如此，一个流水线变量仅输出一个变量值。【GIT分支或TAG】变量需预先选择好代码库后，在流水线执行过程中通过其变量名获取分支/tag值。这个变量是用于【拉取代码插件】使用固定代码库的场景。
如果需要动态选择代码库，需使用【代码库】变量类型，用于【拉取代码插件】配置动态代码库的场景。

**Comment by yun-percy** [comment]
@iccengan 
你说的是流水线这样设计我认为是ok的。
注意下issue反馈的是模板啊！
一个模板是会套用十几个git仓库的，如果模板里面提前指定了git库，那模板还有啥意义？

**Comment by iccengan** [comment]
> @iccengan
> 你说的是流水线这样设计我认为是ok的。
> 注意下issue反馈的是模板啊！
> 一个模板是会套用十几个git仓库的，如果模板里面提前指定了git库，那模板还有啥意义？

这个和是不是模板没有关系，模板内的变量逻辑应和流水线的变量逻辑是一致的。
这个变量的作用是锁定git仓库的情况下输出仓库的分支/tag名。如果git仓库是需要被修改的，则需要利用另一个变量来支持，即代码库变量/字符串变量。
如果A变量可以根据B变量的值来输出不同值（即输入仓库，返回该仓库的分支/tag），是违背目前流水线变量的设计的（即变量间有逻辑关系），间接导致的问题是变量功能过于开放变得使用过于复杂。
这个问题后面可以通过pipeline as code的方式解决，通过代码库内的流水线yaml配置文件配置流水线模板，即可将流水线绑定于目标仓库。
