### ISSUE TITLE
【流水线插件】前端下拉框数据通过接口获取，且依赖于其他字段时的实现优化

### ISSUE THREAD

**Issue by fayewong-v5** [Tencent/bk-ci#2373]
**Question, Bug, or Feature?**  
*Type*: Feature

## Required Information
Entering this information will route you directly to the right team and expedite traction.

目前逻辑：若依赖的字段为空，则不触发拉取数据请求
需求：
1、若依赖的字段为插件自定义字段，根据 task.json中对应字段的是否必填、是否隐藏属性判断，若非必填或者已被隐藏，则没值时也需触发拉取数据请求
2、若依赖的字段为系统内置字段（如pipelineId、 projectId），则无论是否有值，需触发拉取数据请求
如子流水线插件中的流水线列表拉取接口，在流水线中使用时，需排除当前流水线，但在模版中使用时，没有当前流水线。

**Comment by lockiechen** [comment]
增加参数可选规则，若url当中包含的参数为可选参数，则在参数后加上英文 '?'表示
例如：以?结尾代表可选参数，其他规则不变
  /a/b/{option_param?}/{param1}/?c={param2}
