### ISSUE TITLE
部署文档中的一些疑惑

### ISSUE THREAD

**Issue by tiffany199410** [Tencent/bk-ci#2376]
大佬们：关于部署文档中的一些疑惑，麻烦指点下：
疑惑一：
拷贝渲染后的模板文件到nginx代码目录
cp -rf {{code}}/ci/gateway/core/* {{code}}/src/gateway/core/
第一个{{code}}指的是部署目录的路径？第二个{{code}}指的是源码的路径吗？

疑惑二：
将nginx配置文件复制到项目目录下
cp -rf {{code}}/src/gateway/core/* __INSTALL_PATH__/gateway

__INSTALL_PATH__/具体指的是什么路径

疑惑三：
./sbin/nginx     # 启动nginx，启动nginx成功后
在浏览器中打开显示的是：Welcome to OpenResty!这个页面，麻烦在文档上加一下，或者告知下，配置完这个网关部署成功后，最终显示的是哪个界面代表启动成功。

**Comment by zanyzhao** [comment]
1、2可以参考我们的release pipeline：
https://github.com/Tencent/bk-ci/blob/bafe3535ed7306ef9685d2f9f22e1b5abcf29044/.github/workflows/release.yml#L100

如果nginx配置正确，应该看到如下页面
![image](https://user-images.githubusercontent.com/1629409/90490988-e6ebf980-e171-11ea-9995-f7412a004d21.png)

**Comment by tiffany199410** [comment]
@zanyzhao 非常感谢回复。
1、2的中的{{code}}都指的bkci的路径话，我有个疑问。
![image](https://user-images.githubusercontent.com/49472715/90495302-06395580-e177-11ea-9d16-b747a173419d.png)
cp -rf {{code}}/ci/gateway/core/* {{code}}/src/gateway/core/
![image](https://user-images.githubusercontent.com/49472715/90495881-b6a75980-e177-11ea-810a-2c0b98b20d5a.png)
bkci的下一个目录是有src目录的，但是并没有ci目录，在命令行中运行是会报错找不到路径的

**Comment by freyzheng** [comment]
> @zanyzhao 非常感谢回复。
> 1、2的中的{{code}}都指的bkci的路径话，我有个疑问。
> ![image](https://user-images.githubusercontent.com/49472715/90495302-06395580-e177-11ea-9d16-b747a173419d.png)
> cp -rf {{code}}/ci/gateway/core/* {{code}}/src/gateway/core/
> ![image](https://user-images.githubusercontent.com/49472715/90495881-b6a75980-e177-11ea-810a-2c0b98b20d5a.png)
> bkci的下一个目录是有src目录的，但是并没有ci目录，在命令行中运行是会报错找不到路径的

1、{{code}}是指我们githu上的工程根目录
2、{{code}}/ci目录是执行`sh ./render_tpl -m ci ../support-files/templates/gateway*`之后根据scripts/bkenv.properties文件中的变量渲染出来的template文件目录。
3、 INSTALL_PATH是我们渲染完成后运行代码所在的根目录，一般我们会把源码和渲染后的运行代码分开存放。
4、启动nginx之后提示“ Welcome to OpenResty!”，是因为你还没有部署和配置前端页面的目录，找不到对应的静态资源，所以返回了Openresty的默认页面。

**Comment by tiffany199410** [comment]
@freyzheng ，感谢大佬指导。
4、启动nginx之后提示“ Welcome to OpenResty!”，是因为你还没有部署和配置前端页面的目录，找不到对应的静态资源，所以返回了Openresty的默认页面。我已经部署了和配置了前端页面的目录，但是也一直返回的Openresty的默认页面，这个是我按照部署文档，配置后的Openresty/nginx目录
![image](https://user-images.githubusercontent.com/49472715/90599977-5e7c6000-e228-11ea-8266-89e1174fa122.png)
但是最终启动：http://127.0.0.1:8005之后还是进入到了，如下页面，这个问题困惑了我好多天。
![image](https://user-images.githubusercontent.com/49472715/90600138-9be0ed80-e228-11ea-8322-eb599dfadbe1.png)
麻烦再帮忙看看，nginx里还有什么需要配置的吗。

**Comment by tiffany199410** [comment]
@freyzheng 感谢指导。4、启动nginx之后提示“ Welcome to OpenResty!”，是因为你还没有部署和配置前端页面的目录，找不到对应的静态资源，所以返回了Openresty的默认页面。
我已经部署了和配置了前端页面的目录，微服务也可以正常启动了，但是也一直返回的Openresty的默认页面。
这个是我Nginx.conf是我的配置,完全没有看到任何指向蓝鲸ci的记录，这个index网页就是这个默认页面
![image](https://user-images.githubusercontent.com/49472715/90757767-a1196780-e310-11ea-9dac-ce05646d3644.png)

![image](https://user-images.githubusercontent.com/49472715/90757549-5992db80-e310-11ea-828f-49b59c891259.png)



http://127.0.0.1:8005
麻烦您是否可以提供下网关配置正确，软链到nginx.conf的正确模版是怎样的。

**Comment by mikeeastin** [comment]
[root@jszx-test nginx]# ls
conf  html  logs  run  sbin
[root@jszx-test nginx]# cd sbin/
[root@jszx-test sbin]# ./nginx  -t
nginx: [emerg] invalid number of arguments in "upstream" directive in /usr/local/openresty/nginx/conf/vhosts/devops.bkrepo.upstream.conf:1
nginx: configuration file /usr/local/openresty/nginx/conf/nginx.conf test failed
[root@jszx-test sbin]# cat /usr/local/openresty/nginx/conf/vhosts/devops.bkrepo.upstream.conf
upstream  {
    server ;
}

**Comment by mikeeastin** [comment]
[root@jszx-test scripts]# ./render_tpl -m ci ../support-files/templates/*
render ../support-files/templates/boot-service.sh -> /data/bkee/ci/boot-service.sh
render ../support-files/templates/#etc#ci#application-agentless.yml -> /data/bkee//etc/ci/application-agentless.yml
render ../support-files/templates/#etc#ci#application-artifactory.yml -> /data/bkee//etc/ci/application-artifactory.yml
render ../support-files/templates/#etc#ci#application-assembly.yml -> /data/bkee//etc/ci/application-assembly.yml
render ../support-files/templates/#etc#ci#application-auth.yml -> /data/bkee//etc/ci/application-auth.yml
render ../support-files/templates/#etc#ci#application-buildless.yml -> /data/bkee//etc/ci/application-buildless.yml
render ../support-files/templates/#etc#ci#application-dispatch-docker.yml -> /data/bkee//etc/ci/application-dispatch-docker.yml
render ../support-files/templates/#etc#ci#application-dispatch.yml -> /data/bkee//etc/ci/application-dispatch.yml
render ../support-files/templates/#etc#ci#application-dockerhost.yml -> /data/bkee//etc/ci/application-dockerhost.yml
render ../support-files/templates/#etc#ci#application-environment.yml -> /data/bkee//etc/ci/application-environment.yml
render ../support-files/templates/#etc#ci#application-image.yml -> /data/bkee//etc/ci/application-image.yml
render ../support-files/templates/#etc#ci#application-log.yml -> /data/bkee//etc/ci/application-log.yml
render ../support-files/templates/#etc#ci#application-misc.yml -> /data/bkee//etc/ci/application-misc.yml
render ../support-files/templates/#etc#ci#application-monitoring.yml -> /data/bkee//etc/ci/application-monitoring.yml
render ../support-files/templates/#etc#ci#application-notify.yml -> /data/bkee//etc/ci/application-notify.yml
render ../support-files/templates/#etc#ci#application-openapi.yml -> /data/bkee//etc/ci/application-openapi.yml
render ../support-files/templates/#etc#ci#application-plugin.yml -> /data/bkee//etc/ci/application-plugin.yml
render ../support-files/templates/#etc#ci#application-process.yml -> /data/bkee//etc/ci/application-process.yml
render ../support-files/templates/#etc#ci#application-project.yml -> /data/bkee//etc/ci/application-project.yml
render ../support-files/templates/#etc#ci#application-quality.yml -> /data/bkee//etc/ci/application-quality.yml
render ../support-files/templates/#etc#ci#application-repository.yml -> /data/bkee//etc/ci/application-repository.yml
render ../support-files/templates/#etc#ci#application-sign.yml -> /data/bkee//etc/ci/application-sign.yml
render ../support-files/templates/#etc#ci#application-store.yml -> /data/bkee//etc/ci/application-store.yml
render ../support-files/templates/#etc#ci#application-ticket.yml -> /data/bkee//etc/ci/application-ticket.yml
render ../support-files/templates/#etc#ci#application-websocket.yml -> /data/bkee//etc/ci/application-websocket.yml
render ../support-files/templates/#etc#ci#common.yml -> /data/bkee//etc/ci/common.yml
render ../support-files/templates/gateway#core#auth.conf -> /data/bkee/ci/gateway/core/auth.conf
render ../support-files/templates/gateway#core#devops.server.conf -> /data/bkee/ci/gateway/core/devops.server.conf
render ../support-files/templates/gateway#core#lua#init.lua -> /data/bkee/ci/gateway/core/lua/init.lua
render ../support-files/templates/gateway#core#server.common.conf -> /data/bkee/ci/gateway/core/server.common.conf
render ../support-files/templates/gateway#core#vhosts#devops.bkrepo.upstream.conf -> /data/bkee/ci/gateway/core/vhosts/devops.bkrepo.upstream.conf
render ../support-files/templates/op#application-local.properties -> /data/bkee/ci/op/application-local.properties
render ../support-files/templates/op#application.properties -> /data/bkee/ci/op/application.properties
[root@jszx-test scripts]# cd /data/bkee/etc/ci/
