### ISSUE TITLE
Codecc与流水线结合建议

### ISSUE THREAD

**Issue by Jason-Ye-Fenghan** [Tencent/bk-ci#2445]
作为CodeCC的使用者，且将CodeCC作为流水线中的一环时，希望可以获取Codecc的某些扫描结果，当做变量传入流水线的后续环节进行使用。 祝安。

**Comment by irwinsun** [comment]
目前不希望代码检查与流水线的场景过度复杂化，
当前仅通过质量红线插件作为中间者，对接各类代码检查平台的扫描结果来控制流水线后续执行流程
