### ISSUE TITLE
BUG: PR/MR触发的流水线，在运行的时候把流水线删除或者修改流水线名称，状态回写失败

### ISSUE THREAD

**Issue by mingshewhe** [Tencent/bk-ci#2469]
目前当流水线触发执行后，执行还没结束时，删除流水线或者修改流水线名字，会导致流水线执行状态回写失败，导致mr/pr被锁，希望流水线删除或者改名都能回写

问题原因:
com.tencent.devops.plugin.service.git.CodeWebhookService#addGitCommitCheck
![image](https://user-images.githubusercontent.com/22971705/175451789-73ec65f6-b3e2-48e5-b7b5-0e50773efa9c.png)
回写时会查询流水线执行变量，
com.tencent.devops.process.service.builds.PipelineBuildFacadeService#getBuildVars
![image](https://user-images.githubusercontent.com/22971705/175451879-2a013a21-072c-4858-a5a9-6c075490eb8c.png)
当流水线被删除时，获取流水线信息就会失败，导致报错，获取流水线信息是为了得到流水线名称，流水线名称可以从allVariable中获取，改成
![image](https://user-images.githubusercontent.com/22971705/175452239-dccc7b56-8fae-4117-9442-c68398bc9a98.png)

**Comment by irwinsun** [comment]
合理

**Comment by irwinsun** [comment]
需要新增 一键终止所有正在运行/排队/排队预处理的构建

**Comment by mingshewhe** [comment]
在“git事件触发”插件上输出回写开始和回写结束的日志
