### ISSUE TITLE
BUG: com.tencent.devops.process.service.scm.GitScmService#getMergeRequestInfo应该支持重试

### ISSUE THREAD

**Issue by mingshewhe** [Tencent/bk-ci#2511]
如果MR调用失败，会导致MR触发事件的参数为空，应该支持重试，重试3次，每次延迟1s

**Comment by irwinsun** [comment]
有种场景需要考虑， 如果目标代码库服务挂了/用户权限过期， 可能怎么重试都无法恢复。

**Comment by mingshewhe** [comment]
1. 如果代码库服务挂了，增加重试，重试3次还是失败，构建失败，发送邮件通知用户
2. 如果用户权限过期，直接构建失败，发送邮件通知用户
