### ISSUE TITLE
同一个stage下有多个job在运行时如果单个job出现失败可以即时重试

### ISSUE THREAD

**Issue by qianfanblue** [Tencent/bk-ci#2533]
**What would you like to be added**:
同一个stage下有多个job在运行时如果单个job出现失败可以即时重试：
如A还在运行中，B出现失败可以即时重试B
![image](https://user-images.githubusercontent.com/33210320/92678024-a5590380-f357-11ea-8d6a-fc6a17a0d562.png)

**Why is this needed**:
有多个job并行时如果B失败必须等全部job都跑完才能重试，会从并行变成串行

**Comment by yong1026** [comment]
点赞点赞，我的两个job执行时间都是40分钟起，其中一个失败了，另一个正常的话，失败的那个只能等正常的执行完才能重试

**Comment by irwinsun** [comment]
已在此需求完成， https://github.com/Tencent/bk-ci/issues/6400
