### ISSUE TITLE
父流水线显示子流水线的构件

### ISSUE THREAD

**Issue by dezhaoli** [Tencent/bk-ci#2536]
如题，
我们有一个流水负责生成所有的平台，所有分支的构件
然后有很多父流水调用它，
然后希望父流水直接显示在子流水里归档的构件。不用再跳转过去下载，或者在父流水重复归档

**Comment by iccengan** [comment]
#2061 可满足。价值流是流水线之上的一个视图，可以查看流水线间的调用链，以及调用链中生成的构件、报告等。
但由于功能比较大，目前还在设计阶段，需要耐心等待下。
