### ISSUE TITLE
部署release 1.2版本后端微服务时启动失败

### ISSUE THREAD

**Issue by runningbeanxl** [Tencent/bk-ci#2538]
单体包boot-assembly.jar无法启动，日志文件还有配置文件已经上传

![图片](https://user-images.githubusercontent.com/42364672/92719503-ca6c6700-f395-11ea-85c2-cf8b9d075fcd.png)
[bk-ci.log](https://github.com/Tencent/bk-ci/files/5201099/bk-ci.log)
[bootstrap.log](https://github.com/Tencent/bk-ci/files/5201100/bootstrap.log)

[common.txt](https://github.com/Tencent/bk-ci/files/5201104/common.txt)
[application-assembly.txt](https://github.com/Tencent/bk-ci/files/5201105/application-assembly.txt)

**Comment by sunshinejdq** [comment]
我也是用单体包启动，和你的错误相同

**Comment by sunshinejdq** [comment]
日志见附件
[bk-ci.log](https://github.com/Tencent/bk-ci/files/5253201/bk-ci.log)

**Comment by runningbeanxl** [comment]
你找到原因了吗

**Comment by sunshinejdq** [comment]
没有，请求帮助

**Comment by runningbeanxl** [comment]
求帮助

**Comment by irwinsun** [comment]
你好，请问common.yml 配置的
auth:
    idProvider 你配置的是什么， 有修改为sample吗
![image](https://user-images.githubusercontent.com/16686129/95656619-2c112400-0b42-11eb-8b7e-d50c3a2d8e1a.png)
