### ISSUE TITLE
为什么模板流水线只有管理员才能修改

### ISSUE THREAD

**Issue by zuttersw** [Tencent/bk-ci#2548]
**What would you like to be added**:

**Why is this needed**:
这个很不合理，项目是保密项目，人员很多，不能每个人都是管理员的。流水线里面的模板流水线，应该是大家都能够修改的，至少执行者创建者这些可以执行，但是一定要管理员权限就很不合理，希望能够修改下。

**Comment by iccengan** [comment]
Duplicate of #2548
