### ISSUE TITLE
添加自增型流水线预设变量

### ISSUE THREAD

**Issue by iccengan** [Tencent/bk-ci#2655]
### 需求：
Job1-1处流水线变量添加支持 自增型变量。
![image](https://user-images.githubusercontent.com/10875468/95700241-181c0e00-0c79-11eb-8019-b4f6391b3aa2.png)

### 功能：
每次启动流水线构建时，变量加1。确保非人为干预的情况下，该变量值唯一。
变量支持两种属性（单选）：启动构建时+1；锁定自增变量。

### 关联需求：
1. 此需求可解决 #2126 的问题。用自增变量代替推荐版本号。
2. 结合 #2451，支持在构建历史列表界面展示 自增变量，方便用户利用自增变量快速定位目标构建。
3. 此需求可解决 #469 的问题。流水线预设变量的值机制就是允许在流水线执行过程中被修改。

**Comment by irwinsun** [comment]
关联需求另外评审实现
本issue只需要新增一种流水线变量类型

**Comment by iccengan** [comment]
不采用 添加变量类型的方式 实现这个需求。变量类型应保持输入输出一致，变量类型不作特殊逻辑。
