### ISSUE TITLE
蓝盾开源版本有提供OpenAPI文档吗或者命令行工具？

### ISSUE THREAD

**Issue by JerryGinger** [Tencent/bk-ci#2659]
蓝盾是否提供了OpenAPI，方便业务获取流水线的度量数据（CI/CD耗时、成功率等），构建蓝盾基础之上的SaaS应用。

**Comment by irwinsun** [comment]
有提供，在内部有使用一序列的开放接口供平台使用， 有计划迁移到github。目前在代码层面已经提供了一部分v3接口
