### ISSUE TITLE
使用公共账号执行流水线

### ISSUE THREAD

**Issue by scutlzk** [Tencent/bk-ci#2679]
**What would you like to be added**:

**Why is this needed**:
希望能添加公共账号执行流水线的功能。

因为我们有一个CGI服务，服务需要调用流水线。目前由于无法使用公共账号去调用流水线，所以是使用私人账号去调用，虽然能用但不太符合常识。希望贵司能添加公共账号执行流水线的功能。

**Comment by irwinsun** [comment]
> **What would you like to be added**:
> 
> **Why is this needed**:
> 希望能添加公共账号执行流水线的功能。
> 
> 因为我们有一个CGI服务，服务需要调用流水线。目前由于无法使用公共账号去调用流水线，所以是使用私人账号去调用，虽然能用但不太符合常识。希望贵司能添加公共账号执行流水线的功能。

希望贵司能添加公共账号执行流水线的功能。
---------------------
请问您是自搭建服务的社区用户，还是在用腾讯CI的内部用户？

可能有误解，CI平台是不提供帐号注册管理，用户的登录认证是与企业自身帐号系统对接的，只要对接认证的系统判断是合法用户就可以。
 开源版可对接蓝鲸社区/企业版，帐号可在蓝鲸平台上管理创建，如是自已公司在使用，则可以确认下你所在公司有没有公共帐号。
