### ISSUE TITLE
Bash任务支持在环境里所有编译机上执行

### ISSUE THREAD

**Issue by rickyma** [Tencent/bk-ci#2681]
**What would you like to be added**:
bash脚本，可以在【环境】里的所有编译机上执行，而不是目前的调度到某一台上执行。

**Why is this needed**:
我们的场景下需要，机器多，脚本更新频繁，需要每次执行流水线最开始，提前批量将【环境】里的所有脚本更新一遍。

**Comment by irwinsun** [comment]
可能对流水线的定位错了，流水线调度编译机用进行编译，不是用来做批量文件分发操作。

这个需求可以通过 蓝鲸作业平台 等自动化平台来实施。
