### ISSUE TITLE
希望在后面的job里面可以获取审核人名称

### ISSUE THREAD

**Issue by Realybig** [Tencent/bk-ci#2692]
![image](https://user-images.githubusercontent.com/10878451/94528514-1874dc00-026b-11eb-9a66-0cc12ac37d76.png)

希望可以在后面job里面获取到这个审核人的名称，可以用于输出通知等其他用处，非常有用，感谢。

**Comment by fayewong-v5** [comment]
#1860

**Comment by Realybig** [comment]
什么时候可以实现呢？急求~

**Comment by iccengan** [comment]
@Realybig 急的话，楼上 fayewong 提到的 #1860 可以暂时解决该问题。
【人工审核】插件先配置输出变量
![image](https://user-images.githubusercontent.com/10875468/96411650-61d99b00-121b-11eb-9533-2e01477835c7.png)

然后在审核时，修改变量的值。在楼主的场景下，则可以将值更改为审核人的名称。流水线后文便可以通过 `${reviewer}`获取审核人名称。
![image](https://user-images.githubusercontent.com/10875468/96411855-bda42400-121b-11eb-8a1a-7a548877c782.png)

**Comment by fayewong-v5** [comment]
人工审核插件，已支持输出 MANUAL_REVIEWER，值为实际的审核人
