### ISSUE TITLE
可以配置流水线获取第三方构建机资源的超时时间。

### ISSUE THREAD

**Issue by luckscx** [Tencent/bk-ci#2705]
** 背景 **
我们使用一个私有构建集群进行项目的日常CI任务，每次构建大概需要10-25分钟不等。
每台机器使用了专门的磁盘，进行增量拉取。

高峰期提交ChangeList的频率大概是一分钟一次。
每一次提交我们都希望可以触发一次构建。 可以接受排队。
目前的现状是，有太多的触发构建，同时有多个构建任务开始后，新的构建等待10分钟，依然无法拿到构建资源，就直接失败了。

**What would you like to be added**:
希望可以配置这个10分钟的超时时间，比如修改到24小时。

**Why is this needed**:
对于每一个ChangeList我们都希望有一个明确的构建结果，可以明确到具体哪一个ChangeList破坏了构建结果。
所以希望可以利用有限的机器资源，支持较长时间的排队。

**Comment by irwinsun** [comment]
- 在Job设置界面提供相应设置超时时间的交互UI，
- 流水线后端保存该配置（已有该项配置但未开放）编排。
- 调度服务后端根据该配置进行超时监控处理。

具体产品形态需要进行评审～@iccengan@fayewang-v5

**Comment by luckscx** [comment]
激活一下 请问 这个需求有进展吗？

**Comment by irwinsun** [comment]
当前处于需求产品原型评审阶段(review),  完成会后排入开发实现。 请关注milestone

**Comment by iccengan** [comment]
需考虑支持排队机制。

**Comment by iccengan** [comment]
Duplicate of #3575
