### ISSUE TITLE
代码库服务下，支持展示代码库的当前授权人和重置授权

### ISSUE THREAD

**Issue by fayewong-v5** [Tencent/bk-ci#2787]
**What would you like to be added**:

**Why is this needed**:

- [ ] 1. 可以明确知道代码库的授权人

- [ ] 2. 可以在授权人离职或更换负责人时自助重置授权

**Comment by iccengan** [comment]
上述两点分两个阶段处理。先完善第一点，能满足部分第二点场景。第一点上线后，再根据用户反馈确定第二点是否需要开发。

### 期望：
代码库列表展示授权人
![image](https://user-images.githubusercontent.com/10875468/105445120-187d6980-5caa-11eb-8ce0-baa9af378516.png)
