### ISSUE TITLE
流水线列表列宽支持拖拽调整

### ISSUE THREAD

**Issue by iccengan** [Tencent/bk-ci#2809]
### 现象：
流水线名称过长时，无法拖拽列宽展示流水线全名。
![image](https://user-images.githubusercontent.com/10875468/96551083-5f8f4380-12e4-11eb-810b-64320ebdbe4b.png)

### 期望：
列宽支持横向拖拽。

**Comment by buendia27** [comment]
关注，group太长，看起来所有的流水先名称都一样，体验不友好
