### ISSUE TITLE
流水线任务状态没重置，流水线卡死

### ISSUE THREAD

**Issue by rickyma** [Tencent/bk-ci#2824]
**What happened**:
![image](https://user-images.githubusercontent.com/13834479/96852322-96ec2480-148b-11eb-82ee-63759bc05245.png)

**What you expected to happen**:
流水线应该停下来，不应该卡在那里，且还没执行下一个任务，却已经变成红色了

**How to reproduce it (as minimally and precisely as possible)**:
不停的重试流水线

**Anything else we need to know?**:
看日志此时git插件执行，应该是失败的

**Environment**:
- bk-ci version (use `cat VERSION` in installed dir):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
NAME="Tencent tlinux"
VERSION="2.2 (Final)"
ID="tlinux"
ID_LIKE="rhel fedora centos"
VERSION_ID="2.2"
- Kernel (e.g. `uname -a`):
GNU/Linux
- Install tools:
- Others:

**Comment by irwinsun** [comment]
与网络中断导致 #3769 解决此类问题
