### ISSUE TITLE
构建机没有来领取任务，导致流水线卡死

### ISSUE THREAD

**Issue by rickyma** [Tencent/bk-ci#2825]
**What happened**:
如下两种卡死场景，不确定是否是同一个问题，现象是相同的：
![image](https://user-images.githubusercontent.com/13834479/96852510-c733c300-148b-11eb-9e7c-521c9828b510.png)
![image](https://user-images.githubusercontent.com/13834479/96852582-dfa3dd80-148b-11eb-807d-f0c336823b0d.png)

**What you expected to happen**:
希望不卡死，能够继续执行下去

**How to reproduce it (as minimally and precisely as possible)**:
不停的重试流水线

**Anything else we need to know?**:
irwinsun提供定位思路：“服务器调度是正常了，现在看到是构建机没有来领取任务”

**Environment**:
- bk-ci version (use `cat VERSION` in installed dir):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
NAME="Tencent tlinux"
VERSION="2.2 (Final)"
ID="tlinux"
ID_LIKE="rhel fedora centos"
VERSION_ID="2.2"
- Install tools:
- Others:

**Comment by irwinsun** [comment]
与网络中断导致 #3769 解决此类问题
