### ISSUE TITLE
流水线查看执行时的配置快照页面，链接点击不了（如tips组件中加的链接）的问题fix

### ISSUE THREAD

**Issue by fayewong-v5** [Tencent/bk-ci#2847]
统一遮罩的方式导致：
- 链接无法点击
- 提示信息无法查看

示例如图：
![image](https://user-images.githubusercontent.com/54432927/97159154-67a02500-17b5-11eb-9baf-e188e8020828.png)

**Comment by oyc502** [comment]
请尽快修复吧，有好几个使用我们插件的用户在反馈这个问题了
