### ISSUE TITLE
git事件触发路径匹配异常

### ISSUE THREAD

**Issue by mingshewhe** [Tencent/bk-ci#2864]
当监听路径为a,如果修改的路径是ab，流水线也会触发，期望流水线不触发

**Comment by iccengan** [comment]
路径前缀匹配的规则不是bug，而是设计如此。当初没有使用通配符的规则进行匹配，考虑的其中一点是对非研发同学而言配置成本稍高，用户需要了解通配语法。所以采用了最直接的前缀匹配方式。
添加开关的方式在这个场景下不太合适，触发插件本身是比较轻量的，配置项不宜过于复杂。插件配置项中添加子配置项（路径匹配提供两种规则）入口一旦打开，其他用户也会对插件配置提出延伸需求，最终导向是插件的配置越来越重。
提出这个需求的人非常少，用户覆盖度不高，属于比较业务定制化的需求。后面考虑开放触发插件的微扩展点，提供业务以自定义改造触发插件，能满足业务方定制化的触发诉求。

**Comment by iccengan** [comment]
Duplicate of #2142
