### ISSUE TITLE
关于docker环境是如何执行任务的

### ISSUE THREAD

**Issue by zhanghaohao** [Tencent/bk-ci#2884]
如果任务被调度到docker环境执行的话，流程是不是这样的：
服务端找到一个合适的节点
在这个节点上启动docker容器，容器起来后会运行agent和worker程序，同时构建参数也被传入到容器
容器里面的worker领取任务执行，执行完成后会把结果和日志发送到服务端和数据库
一段时间后该容器被服务端删除

不知道上面的理解对不对，请指教！

**Comment by irwinsun** [comment]
差不多是这样， 不过执行完毕后，容器即会被关闭(stop)

**Comment by zhanghaohao** [comment]
感谢！
