### ISSUE TITLE
bug: okhttp3 状态码为301时会把post请求转换成get请求

### ISSUE THREAD

**Issue by mingshewhe** [Tencent/bk-ci#2894]
如果gitlab服务端配置http请求重定向https请求，注册的webhook不会报错，但是webhook并没有注册上。这是因为请求http协议gitlab服务端会把http跳转成https，返回码为301，okhttp3把状态码为301、302的post请求转换成get请求

**Comment by mingshewhe** [comment]
okhttp3本就支持重定向，当http请求被重定向https，服务端会返回301状态码，并且把post请求转换成get请求，可以查看：https://github.com/square/okhttp/issues/2262#issuecomment-251699960

**Comment by hingbong** [comment]
> 
> 
> okhttp3本就支持重定向，当http请求被重定向https，服务端会返回301状态码，并且把post请求转换成get请求，可以查看：[square/okhttp#2262 (comment)](https://github.com/square/okhttp/issues/2262#issuecomment-251699960)

根据状态码, 307, 308才会保持原有的请求方式继续请求, 而okhttp在4.6.0才支持307, 308状态码[okhttp 4.6.0](https://square.github.io/okhttp/changelog/#version-460)

**Comment by mingshewhe** [comment]
目前自搭建gitlab可能是http协议也可能是https协议，如果关联代码库使用http授权方式，请求gitlab api时能知道使用的协议，但是如果关联使用的是git协议，就不知道用什么协议，目前如果推导不出代码库url使用的协议，默认使用http，获取协议的代码com.tencent.devops.scm.utils.code.git.GitUtils#getGitApiUrl
<img width="809" alt="image" src="https://user-images.githubusercontent.com/22971705/158572034-ec9dc8e8-6024-41d3-ad08-a1cb18a17d38.png">
但是使用http，如果服务端使用https就会出现okhttp重定向的问题

## 解决方案
关闭okhttp的重定向跳转，自定义重定向方式,com.tencent.devops.common.api.util.OkhttpUtils
```
// 服务端返回301、302状态码，okhttp会把post请求转换成get请求，导致请求异常,通过followRedirects设置关闭跳转，自定义重定向
private val redirectOkHttpClient = OkHttpClient.Builder()
    .connectTimeout(connectTimeout, TimeUnit.SECONDS)
    .readTimeout(readTimeout, TimeUnit.SECONDS)
    .writeTimeout(writeTimeout, TimeUnit.SECONDS)
    .sslSocketFactory(sslSocketFactory(), trustAllCerts[0] as X509TrustManager)
    .followRedirects(false)
    .hostnameVerifier { _, _ -> true }
    .build()

fun doRedirectHttp(request: Request): Response {
        doHttp(redirectOkHttpClient, request).use { response ->
            if (
                request.method() == "POST" &&
                (response.code() == HttpURLConnection.HTTP_MOVED_PERM ||
                    response.code() == HttpURLConnection.HTTP_MOVED_TEMP)
            ) {
                val location = response.header("Location")
                if (location != null) {
                    val newRequest = request.newBuilder().url(location).build()
                    return doHttp(okHttpClient, newRequest)
                }
            }
            return response
        }
    }
```
