### ISSUE TITLE
chore: 子流水线轮询判断运行状态优化

### ISSUE THREAD

**Issue by mingshewhe** [Tencent/bk-ci#2928]
目前子流水线状态轮询，会查下流水线详情，负载很大

优化方案:
1. 当子流水线调用的时候，设置redis，key为subpipeline:build:$buildid:status，值为running状态。过期时间900分钟
2. 当子流水线运行完后，监听流水线结束事件，设置redis的值为流水线最终状态，过期时间10分钟
3. 当流水线查询状态为结束时，删除redis的key，如果流水线查询redis状态为空，则查数据库

**Comment by irwinsun** [comment]
补充下，目前取消构建时的连带取消子流水线功能有局限性。
目前局限于 无编译环境， 如果使用者在编译环境的构建机上使用子流水线插件，则在取消构建时，子流水线插件不会被跟着取消

![image](https://user-images.githubusercontent.com/16686129/99528425-3e03a380-29d9-11eb-852b-e6108eb65f41.png)

**Comment by irwinsun** [comment]
此块代码可移出if/else

**Comment by mingshewhe** [comment]
测试用例，期望结果：子流水线插件运行状态正常
1. 子流水线运行成功
2. 子流水线运行失败，(执行失败、取消、终止)
3. 父流水线取消，父流水线取消redis的key不会删除，会在redis中保留10分钟
4. 父流水线轮询间隔设置10分钟，使key过期
