### ISSUE TITLE
在 git 上面的构建链接能否直接跳转到产出物报告？

### ISSUE THREAD

**Issue by youngdze** [Tencent/bk-ci#2975]
### 现象
现在 BK-CI 在 git 上的构建链接只支持跳转到对应的构建页面。
![image](https://user-images.githubusercontent.com/2606650/98902973-a17d6500-24f1-11eb-9cd4-06157b676de0.png)

### 具体场景
有一些构建是有一个产出物报告的，现在 git 上的构建链接并不能直接跳到产出物报告，或允许配置前往产出物报告。

### 希望
是否能支持配置直接从 git 的构建链接跳转到产出物报告页面，有时候流水线触发的主要目的就是为了这个报告，比如代码检查。

**Comment by irwinsun** [comment]
这里存在一个众口难调的问题，因为有人关注构件产物 ，也有人关注构建报告，更多人关心构建详情，比如任务的状态和日志。
所以目前是跳转的是流水线的构建默认页面（详情），更换成构件，报告都不合适，也不够通用。

目前对于你的需求来说，就是进入详情页面后多点击一次“产出物报告”Tab。 并不会对于用户造成太多的操作成本。相反如果开启了配置，这块会增加流水线配置项的复杂度，目前需求也并不强烈。

![image](https://user-images.githubusercontent.com/16686129/98913646-97179700-2502-11eb-950b-6a5a0694c250.png)
