### ISSUE TITLE
单个流水线中支持 stage 并行

### ISSUE THREAD

**Issue by piratf** [Tencent/bk-ci#3015]
**What would you like to be added**:
希望单个流水线中支持 stage 级别的并行。如下图：
![image](https://user-images.githubusercontent.com/9389616/99477131-d889c580-298c-11eb-97ef-5a2b6496f2a5.png)

**Why is this needed**:
流水线中出现分叉 S2-S3 和 S4-S5，其中 2 和 3 需要使用不同的环境，因此需要两步，4 和 5 也同理。

当前：由于不支持 Stage 并行，2 和 4 实际是同一个 Stage 下的不同任务组，虽然可以并行，但是必须相互等待都完成，然后同时开始 3 和 5 任务，导致额外的等待时间。
支持后：如果 2 先完成可以直接发起 3，4 - 5 同理，节约等待时间，6 则会等待 3，5 都完成后再启动。

为什么不用子流水线：
1. 麻烦，要新建流水线，维护要切换页面，维护难度高。
2. 项目流水线数量爆炸，简单功能不想通过新建流水线完成。

**Comment by irwinsun** [comment]
如果流水线不复杂规模不大，你可以试试DependOn 功能。实际上差不多，也能满足一条流水线梭哈到底。 不过要注意，单条流水线未来会有明确大小限制
Stage数量，Job数量等等。 跟写代码一样，不希望流水线越加越复杂，如果过于复杂还是要做下适量拆分。
![image](https://user-images.githubusercontent.com/16686129/105323438-19a88b00-5c05-11eb-9ffa-26f2173621ab.png)
