### ISSUE TITLE
各个搜索入口 trim下首尾空白

### ISSUE THREAD

**Issue by xdc0209** [Tencent/bk-ci#3084]
**What would you like to be added**:
![image](https://user-images.githubusercontent.com/3997527/100446354-9decff00-30e9-11eb-90e5-dcc8c2de41e9.png)

**Why is this needed**:
搜索时去掉 “开始的空格和结束的空格“，增强搜索体验。其他搜索框也有类似的问题。

**Comment by reggieisrunning** [comment]
input样式如此
