### ISSUE TITLE
代码库相对目录-需支持多个目录填写

### ISSUE THREAD

**Issue by wenchy** [Tencent/bk-ci#3095]
**What would you like to be added**:
![image](https://user-images.githubusercontent.com/4188052/100704629-c2debc00-33e0-11eb-884c-a6de6fc46fc1.png)
**代码库相对目录**，暂时支持1个目录。而我们想填写多个子目录参数，比如:`temp_branch1,temp_branch2,temp_branch3`

**Why is this needed**:
方便管理多个目录下的分支

**Comment by irwinsun** [comment]
此类功能受限于svn的api单路径实现，以及svn平台的性能及稳定性大多比较差。 多目录需要进行循环遍历搜索再返回，不具备在大工程下稳定的使用条件。
