### ISSUE TITLE
流水线插件中的“引用变量”显示不全，产生误导

### ISSUE THREAD

**Issue by shanehou** [Tencent/bk-ci#3097]
只显示了这些：

![image](https://user-images.githubusercontent.com/863379/100717285-d136d300-33f4-11eb-95d5-0ab40fd0662d.png)

但实际上有更多：

---------敏感信息

建议显示全部变量，或者给出全部变量的链接。

**Comment by irwinsun** [comment]
上述都是能用的变量， 内部文档是有大量和代码库相关的变量，仅在有相应的触发器才会出现，但如果全放在这里，又会带来展示和搜索的问题，考虑将这些变量放到 触发器 插件外来实现。 此需求不处理，另起需求
