### ISSUE TITLE
【人工审核】插件能否支持下审核结果输出？

### ISSUE THREAD

**Issue by xiangxiaoxiao** [Tencent/bk-ci#3122]
人工审核插件现在支持，审核人，审核意见的输出，能否支持下审核结果的输出？

当前场景：
需要统计流水线中审核结果的信息，想在人工审核后面加一个插件进行数据上报，后续进行进一步分析。

**Comment by iccengan** [comment]
### key：
${MANUAL_REVIEW_RESULT} 
### value：
PROCESS - 通过
ABORT - 驳回
