### ISSUE TITLE
feat: finally stage

### ISSUE THREAD

**Issue by zanyzhao** [Tencent/bk-ci#3138]
_**As a**_ developer
_**I wish**_ The pipeline can run some tasks that I want to execute automatically at the end of the run (whether successful or failed)
_**To**_: clean up the pipeline process products

## 与普通Stage的差异
- 一条流水线只有一个 Finally Stage
  - Finally Stage 之前可以添加 stage， 之后不可以添加 stage
  - Finally Stage可以配置多个 job
  - finally stage 属于必定会执行的阶段，所以和普通 stage 不同的是，不再需要执行条件以及fast-kill
- Finally Stage 下可以获取到失败的 jobs / tasks 的信息，提供一个内置上下文 #3997 ，包含如下信息：
  - 失败步骤的名称、id、插件标识、错误码、错误信息、输出参数，所属 job id、名称
  - 失败的 job id、名称、使用的镜像、启动失败的原因等
  - 取消执行时的job、以及未完成的task信息
- Finally Stage 的 job 运行条件有以下四种（不支持自定义）：
  - 当前 Stage 开始时 JobRunCondition.STAGE_RUNNING
  - 上游 Stage 成功时 JobRunCondition.PREVIOUS_STAGE_SUCCESS
  - 上游 Stage 失败时 JobRunCondition.PREVIOUS_STAGE_FAILED
  - 上游 Stage 取消时 JobRunCondition.PREVIOUS_STAGE_CANCEL
- 无Stage审核
- 对失败Stage下的重试所有失败Job功能做了适配FinallyStage
![image](https://user-images.githubusercontent.com/16686129/117382607-7b210b00-af11-11eb-9368-aa3aeff73e4f.png)

  - 当失败Job重试不属于FinallyStage， 则对于FinallyStage下的Job，所有Job（成功的）被重置成排队待执行状态
  - 当失败Job重试属于FinallyStage， 则只重置上一次执行失败的Job为排队待执行状态
## Stage状态
上游Stage成功的两种情况：
- 上游Stage处于跳过等同于成功  BuildStatus.isSuccess()
- 上游Stage处于StageSucess（Stage审核取消执行）等同于成功  BuildStatus.STAGE_SUCCESS

## 流水线状态：
- 如果上游Stage失败，不管 finally 成功还是失败，流水线最终状态为失败
- 如果上游Stage成功，当finally失败时，整个流水线失败

## 交互补充
- hover至+号时显示下拉框
- 下拉框样式参考[这里](https://magicbox.bk.tencent.com/static_api/v3/components_vue/2.0/example/index.html#/dropdown-menu)

**Comment by rhinel** [comment]
when？

**Comment by mario206** [comment]
when?

**Comment by GarrickY** [comment]
when?

**Comment by zanyzhao** [comment]
已加入4月份迭代，各位大佬稍等

**Comment by fayewong-v5** [comment]
- 一条流水线只有一个 Finally Stage
  - Finally Stage 之前可以添加 stage， 之后不可以添加 stage
  - Finally Stage可以配置多个 job
- Finally Stage 下可以获取到失败的 jobs / tasks 的信息，提供一个内置变量 BK_CI_FAILURE_CONTEXT，包含如下信息：
  - 失败步骤的名称、id、插件标识、错误码、错误信息、输出参数，所属 job id、名称
  - 失败的 job id、名称、使用的镜像、启动失败的原因等
  - 取消执行时的job、以及未完成的task信息
- Finally Stage 的 job 运行条件有：
  - 当前 Stage 开始时
  - 上游 Stage 成功时
  - 上游 Stage 失败时
  - 上游 Stage 取消时

**Comment by yun-percy** [comment]
@zanyzhao 
4月快过去了，搞完了没？

**Comment by rhinel** [comment]
上线了！还愿！
