### ISSUE TITLE
根据分支名搜索流水线

### ISSUE THREAD

**Issue by DingYong4223** [Tencent/bk-ci#3149]
项目上流水线太多了，每次新建git分支后，不知道在哪条流水线构建，希望可以提供直接通过git分支搜索关联的流水线

**Comment by irwinsun** [comment]
@iccengan

**Comment by iccengan** [comment]
@DingYong4223 能详细描述下你们业务的流水线使用场景吗？为什么需要通过git分支来搜索流水线？是否一条流水线对应一条分支，可否通过流水线名称来解决这个问题？
