### ISSUE TITLE
流水线并发执行后插件重试时文件数据不正确

### ISSUE THREAD

**Issue by hingbong** [Tencent/bk-ci#3173]
流水线并发执行后, 插件执行失败, 使用插件重试时, workspace对应的路径从 1_2 到 1, 目录下的文件数据不正确导致后面插件执行失败

**Comment by irwinsun** [comment]
插件的重试无法解决此类问题，因为上下文被复用带来的灾难是存在的，所以业界CI基本上都不提供插件重试功能是有这个原因的。

蓝盾提供的插件重试功能建议用在非依赖workspace的场景，比如CD场景等。
