### ISSUE TITLE
对增量流水线变量名进行规范限制

### ISSUE THREAD

**Issue by iccengan** [Tencent/bk-ci#3284]
### 现象：
目前流水线变量名称没有作格式校验，非法流水线变量可能会影响后续插件的使用。
![image](https://user-images.githubusercontent.com/10875468/102218442-e9d8da00-3f18-11eb-9994-012bb6b4545f.png)
![image](https://user-images.githubusercontent.com/10875468/102218411-df1e4500-3f18-11eb-8299-b4acb82bfcb4.png)

### 期望：
流水线变量名称需要添加校验，提示用户该变量名为非法格式。

### 问题：
会伤害存量用户，已配置非法流水线变量名的用户可能需要改动很多配置。

**Comment by irwinsun** [comment]
规范的目的 无非是要解决一些会影响用户正常使用的情况，从目前来看插件用的变量冲突属于极少数情况，并且碰到后用户能自我去调整 
但限制过多的代价是大家都没法玩，不建议开启
