### ISSUE TITLE
质量红线支持传入审核人变量

### ISSUE THREAD

**Issue by jagerzhang** [Tencent/bk-ci#3287]
目前质量红线不支持使用变量作为审核人，在模板化使用方式上得把所有相关审核人都写到质量红线才能用起来，但是一旦触发审核，就会给很多不相干的人带来骚扰。
![image](https://user-images.githubusercontent.com/9711651/102316294-a03bce00-3fb0-11eb-9f1f-140f35be1416.png)
希望质量红线这个位置可以支持从流水线传入审核变量，这样就能在实例化的时候将审核人独立区分了。

**Comment by irwinsun** [comment]
此问题已经解决 #4354
