### ISSUE TITLE
质量红线批量对流水线生效

### ISSUE THREAD

**Issue by readyhe** [Tencent/bk-ci#3312]
质量红线目前只能针对流水线一个一个的添加，希望能通过正则匹配做到批量处理l.就不需要每一个都做添加。

**Comment by irwinsun** [comment]
质量红线支持单流水线或模板的方式， 模板更适合大批量的操作。

质量红线的添加修改理应当是一个低频操作，与流水线的绑定是具体的，正则匹配会存在不确定性和流水线修改带来的冲突，建议思考下，是不是真的有这么高频的操作。


![image](https://user-images.githubusercontent.com/16686129/103859145-7fb8ec80-50f4-11eb-843d-bc5a031a4fc0.png)
