### ISSUE TITLE
SVN 拉取插件 revert update 失败经常需要手动处理，希望提供选项自动处理

### ISSUE THREAD

**Issue by piratf** [Tencent/bk-ci#3322]
**What would you like to be added**:
希望 SVN 拉取插件针对 revert update 提供一个选项：失败后尝试 fresh checkout

**Why is this needed**:
可以自动解决大多数编辑外链、目录冲突导致的 svn 拉取失败。

**Comment by irwinsun** [comment]
svn 插件 可以通过 选择 fresh checkout
![image](https://user-images.githubusercontent.com/16686129/123193397-50960c00-d4d7-11eb-92fc-9d15a1945c46.png)
解决
