### ISSUE TITLE
期待流水线增加备注功能

### ISSUE THREAD

**Issue by thay777** [Tencent/bk-ci#3325]
**What would you like to be added**:
对于一个有几十条服务器流水线的团队，由于缺乏一个备注描述字段，游戏策划对于服务器的用途常常感到难以准确理解
**Why is this needed**:
现在仅仅靠流水线名称来向大家广播当前服务器流水线是做什么用的，很受限制

**Comment by iccengan** [comment]
流水线核心页面将重新设计，支持展示流水线基本信息。
Duplicate of #1023
