### ISSUE TITLE
支持只监听某个branch下的tag

### ISSUE THREAD

**Issue by Young200808** [Tencent/bk-ci#3332]
![image](https://user-images.githubusercontent.com/3414477/102840682-59315b00-443e-11eb-91c5-d65416ca740e.png)
Git事件触发这里，如果我选择的是tag触发，现在是全部branch都一起监听，
能指定只监听某个branch的tag吗，不然容易误操作，比如说有同事错误的在test分支(他以为自己在release分支)打了个tag, 发布了测试代码到生产线。

**Comment by iccengan** [comment]
关联需求：#3452

**Comment by mingshewhe** [comment]
当从客户端创建的tag，并没有带上从哪个分支创建，无法监听分支下的tag

**Comment by iccengan** [comment]
### 期望：
tag push 事件添加配置项：
`仅监听目标分支`
添加叹号图标，hover提示：
`注意：git客户端创建的tag不会含带创建分支的信息，该种情况无法监听目标分支`

**Comment by irwinsun** [comment]
> ### 期望：
> tag push 事件添加配置项： `仅监听目标分支` 添加叹号图标，hover提示： `注意：git客户端创建的tag不会含带创建分支的信息，这种情况下创建的tag无法监听目标分支`

搜索了下gitlab、github 目前均没有该功能，只有工蜂有此功能，但此功能极容易引起二义性， 比如在DevOps自动化下，用户使用自动化脚本命令方式创建tag，都无法享受到此功能。

**Comment by iccengan** [comment]
> 搜索了下gitlab、github 目前均没有该功能，只有工蜂有此功能，但此功能极容易引起二义性， 比如在DevOps自动化下，用户使用自动化脚本命令方式创建tag，都无法享受到此功能。

@mingshewhe 仅针对内网工蜂事件触发插件进行调整
