### ISSUE TITLE
“Job依赖”与“何时运行本Job”优先级问题

### ISSUE THREAD

**Issue by ceynri** [Tencent/bk-ci#3336]
**What happened**:
先描述一下场景：在一个Task里存在Job A与Job B，它们俩都被设置了“自定义变量全部满足时不运行”，且自定义变量条件是相同的。当我满足该条件时，这两个Job应该都会被正常跳过。
但是当我使用了Job依赖特性，让Job B依赖于Job A，在其他条件相同的情况下，当Job A因为满足自定义变量条件而被跳过时，Job B却因为Job A未执行而直接报错。
下面是一个实例：
![image](https://user-images.githubusercontent.com/37040496/102861350-7aa83c00-446a-11eb-88da-cdf5dd3256f5.png)

**What you expected to happen**:
我认为问题应该是判断“Job依赖”的优先级高于“何时运行本Job”导致的。但我已经满足跳过条件了，那其实本来就不期望运行Job B，自然不会关心该Job B依赖的Job A是否执行成功或者是被跳过。

**Comment by iccengan** [comment]
Depends On和跳过逻辑 判断先后顺序的问题。评估后给出结论

**Comment by mingshewhe** [comment]
#3340 类似需求

**Comment by iccengan** [comment]
### 期望
b依赖于a：
如果a执行，b执行：a失败时，b为跳过状态；a成功时，b执行。
如果a执行，b跳过：b无论如何都是跳过状态。
如果a跳过：b无论如何都是跳过状态。

#### 原则：只要没执行到b，b就只会是跳过状态。b的状态不受前置job影响，只跟自己的task有没有执行成功有关。
