### ISSUE TITLE
插件切换版本后，流程控制的配置应被继承

### ISSUE THREAD

**Issue by iccengan** [Tencent/bk-ci#3338]
### 现象：
原插件版本为1.0.26，配置了多项流程控制。
![image](https://user-images.githubusercontent.com/10875468/102866720-b0512300-4472-11eb-8319-f200cd029ea7.png)

切换版本至1.0.28后，流程控制配置被重置了
![image](https://user-images.githubusercontent.com/10875468/102866765-c3fc8980-4472-11eb-89a0-f1403610e13b.png)

### 期望：
切换插件版本应继承流程控制的配置。
重选插件的情况则保持重置流程控制配置的逻辑。

**Comment by fayewong-v5** [comment]
#4304 中完成
