### ISSUE TITLE
agent 机器性能监控为空

### ISSUE THREAD

**Issue by AntSworD** [Tencent/bk-ci#3348]
agent 现在机器性能监控的代码现在是没开源是么？
没有 influxdb 存储这块的接口实现
/ms/environment/api/buildAgent/agent/thirdPartyAgent/agents/metrix

**Comment by irwinsun** [comment]
安装目录\gateway\core\influxdb.conf

网关处直接对接influxdb读写metrix

配置在init.lua文件中有关于INFLUXDB的配置项， 这块在安装时，需要仔细阅读相关配置项，有可能你配置空了

**Comment by AntSworD** [comment]
> 安装目录\gateway\core\influxdb.conf
> 
> 网关处直接对接influxdb读写metrix
> 
> 配置在init.lua文件中有关于INFLUXDB的配置项， 这块在安装时，需要仔细阅读相关配置项，有可能你配置空了

@irwinsun 发现 influxdb.conf 并没有被引用，应该是```bk-ci/support-files/templates/gateway#core#devops.server.conf``` 这个文件里没有 include
