### ISSUE TITLE
发起多个任务构建失败后, 再重新开始任务很容易超时

### ISSUE THREAD

**Issue by xoyojank** [Tencent/bk-ci#3354]
重现步骤: 假设发起了构建任务A和B, 由于某些原因构建失败了, 过了一天, 在状态旁边的重新开始构建再启动A和B, B会直接断定超时.
原因: 计算排队时间的时候，计算的是当前时间与创建任务时间的差值, 而不是当前时间与触发任务时间的差值
影响: 超过一天的merge request的触发构建任务重试全会超时

**Comment by irwinsun** [comment]
已无此问题
