### ISSUE TITLE
【流水线变量】流水线变量中自定义变量文件的大小限制为10M,能否提高？

### ISSUE THREAD

**Issue by lxmanutd** [Tencent/bk-ci#3359]
**What would you like to be added**:
流水线变量中自定义变量文件的大小限制为10M,能否提高？ 
**Why is this needed**:
现在文件大小普遍偏大，需要传几张图片，每张大概3-5M,压缩完合在一块超过10M, 能否提高到30M?

**Comment by irwinsun** [comment]
此功能用于传递一些简易文本或二fjrm配置信息类的文件， 10MB已经大大满足。 空间有限是为了保护运行和规范使用，
图片多的话，建议分成几个变量即可。
