### ISSUE TITLE
项目logo生成方式优化

### ISSUE THREAD

**Issue by iccengan** [Tencent/bk-ci#3396]
### 现象：
目前项目logo由后台随机生成：
![image](https://user-images.githubusercontent.com/10875468/103207046-489a4c80-4938-11eb-8747-aeda4a5d67eb.png)

#### 创建项目时：
- 从平台提供的n个项目logo中选择（类似研发商店），后台存入图片指向的链接。
且需支持用户上传自定义项目logo。
-  后台移除生成图片逻辑

**Comment by irwinsun** [comment]
后台移除生成图片逻辑
