### ISSUE TITLE
开源版流水线变量，变量类型为代码库时，代码库类型和代码库服务未对齐

### ISSUE THREAD

**Issue by fayewong-v5** [Tencent/bk-ci#3422]
![image](https://user-images.githubusercontent.com/54432927/103393593-5f21ed00-4b5e-11eb-98ee-efd92cd53686.png)
![image](https://user-images.githubusercontent.com/54432927/103393867-07848100-4b60-11eb-86c6-08248dd3136e.png)

**Comment by zanyzhao** [comment]
保留如下三个：
- Gitlab
- TGit
- GitHub
