### ISSUE TITLE
支持对其他流水线添加备注

### ISSUE THREAD

**Issue by MonoUser** [Tencent/bk-ci#3457]
**What would you like to be added**:
对流水线产出物的自动化测试时间较长，通常采用异步方式调起另一条流水线。希望在自动化测试执行完后可以对原构建流水线进行备注，产出物是否可用
**Why is this needed**:
目前只支持改当前流水线的备注，如果为了要填备注自动化测试只能设置为同步进行，会让出包流水线的执行时间变得很久

**Comment by yongyiduan** [comment]
该问题将在 #7595 解决 ，后续子流水线可以通过调取api更改当前流水线的备注
