### ISSUE TITLE
希望提供【QTA自动化测试】 插件重试失败用例

### ISSUE THREAD

**Issue by jingmishen** [Tencent/bk-ci#3468]
希望能优化一下当前场景：
执行流水线中的【QTA自动化测试】插件，执行用例假设100个耗时3小时+，其中失败了2个用例
失败的用例是因为环境导致，修复环境后，希望重试执行这2个失败的用例即可
当前的情况是平台侧重试后，是重新发起所有测试，此时重新执行100个用例耗时3小时+，研发测试效率低，希望能够在这方面进行优化，只重试失败的用例。谢谢~

**Comment by irwinsun** [comment]
非平台问题，属于插件与测试平台自己的验证交互逻辑
