### ISSUE TITLE
bug：当最新版本下架后，使用latest版本的插件不应该再用到已下架的版本

### ISSUE THREAD

**Issue by fayewong-v5** [Tencent/bk-ci#3476]
当最新版本下架后，使用latest版本的插件不应该再用到已下架的版本
若当前大版本下，所有小版本均已下架，则执行时报错，日志提示如： 2.latest 下没有可用的插件版本
若整个插件已下架，则使用对应大版本下最新的可用版本

**Comment by carlyin0801** [comment]
已经修复上线了，故关闭
