### ISSUE TITLE
支持 Merge request 评论(comment) 触发

### ISSUE THREAD

**Issue by maobaolong** [Tencent/bk-ci#3511]
支持 Merge request 评论(comment) 触发

![image](https://user-images.githubusercontent.com/17329931/104400597-ae6c1280-558d-11eb-874e-fde6fc76666e.png)

类似于

![image](https://user-images.githubusercontent.com/17329931/104400622-b9bf3e00-558d-11eb-9b9b-918d90fe756e.png)

![image](https://user-images.githubusercontent.com/17329931/104400633-bcba2e80-558d-11eb-808e-95ffb5b9b231.png)

可以指挥 蓝盾，做自己设定的工作

比如 测试，指定参数测试，合并 merge request，提交新的 Merge request 等等，非常有用，在开源社区广泛使用。

**Comment by mingshewhe** [comment]
"git事件触发"已支持对评论事件进行触发，Merge request 评论可以选择“对评审进行评论”评论类型
![image](https://user-images.githubusercontent.com/22971705/170908222-d190a6f7-bde6-451d-93ab-cdb5acdb5f6a.png)
