### ISSUE TITLE
流水线名称hover展示流水线描述

### ISSUE THREAD

**Issue by iccengan** [Tencent/bk-ci#3517]
### 现象：
流水线列表hover至流水线名称时，浮窗展示的是流水线名称。现列表页的列宽已支持调整，不存在流水线名称过长时，用户无法看到流水线全称的情况。可以考虑将hover浮窗的信息更改为流水线描述。
![image](https://user-images.githubusercontent.com/10875468/104428574-9a410900-55bf-11eb-9360-664c240b5d4c.png)

### 期望：
如果流水线设置了描述信息，hover浮窗展示描述内容；
如果流水线没有设置描述信息，hover浮窗展示流水线全称。

**Comment by iccengan** [comment]
结合 #1023 一起考虑

**Comment by xiongquani66** [comment]
当流水线较多时，项目团队成员无法通过流水线名称快速分辨流水线的作用，需要获得进一步的解释。

所以建议在流水线列表页能够增加描述的显示功能。不必常态显示，可以鼠标悬停后展示。
