### ISSUE TITLE
Stage标签希望可以支持更多自定义标签

### ISSUE THREAD

**Issue by jagerzhang** [Tencent/bk-ci#3545]
目前Stage标签只能支持 Test/Build/Deploy，我们希望通过标签来统计流水线各个阶段耗时或者成功失败数据。如果只能填写这3种标签，那么一些人工审核插件的数据也会统计进去，造成数据不准确。

建议支持更多自定义标签，比如加入：
审核：Approve
其他:  Other

或者，支持留空也行，目前标签不允许为空。

![image](https://user-images.githubusercontent.com/9711651/104700186-bde68980-574e-11eb-82fd-d632e71fab95.png)

**Comment by zanyzhao** [comment]
通过管理端配置，不涉及代码，已增加Approve
