### ISSUE TITLE
希望编辑MR信息后能触发流水线

### ISSUE THREAD

**Issue by Lurh** [Tencent/bk-ci#3565]
需求场景：Code Review 实践相关
具体描述：
1. 为了避免一次CR及MR大量代码，考虑将一个MR拆成多个
2. 具体实现方式：
  1）创建分支1，提交MR到master
  2）在分支1基础上，创建分支2继续开发，开发完毕，提交MR到分支1
  3）分支1MR完毕后，分支2的MR需要编辑为合并入master
通过分支1，分支2 的划分，减少每次CR的代码量，提高CR质量
问题：只有直接创建合入master的MR才会触发流水线，2.2 及 2.3 中的操作均不触发流水线，导致合入前未经过流水线检验，存在隐患。
现在自己的解决方案：关闭MR重新打开实现触发。
希望能够支持：编辑为合入master后，也能触发流水线
进一步需求：通过配置控制合入哪些分支需要触发流水线

**Comment by zanyzhao** [comment]
目前的git事件触发本来就支持分支过滤，你可以针对不同的源分支设置不同的流水线

**Comment by iccengan** [comment]
> 进一步需求：通过配置控制合入哪些分支需要触发流水线

如@zanyzhao所说，这个功能目前已支持。

> 希望能够支持：编辑为合入master后，也能触发流水线

这个依赖工蜂添加webhook返回的action类型。已给工蜂提需求。

**Comment by iccengan** [comment]
转内部跟进
