### ISSUE TITLE
feat: 在Job中增加排队超时时间的设置

### ISSUE THREAD

**Issue by zanyzhao** [Tencent/bk-ci#3575]
**What would you like to be added**:
当Job中的资源类型选择“私有构建机“or”私有构建集群”时增加排队超时时间的设置
**Why is this needed**:
目前业务的私有构建机器不够用，不足以支持业务并发构建的峰值，但又不希望丢失commit检查

**Comment by iccengan** [comment]
Job的配置中，只有构建资源选择了“私有构建集群”时才展示`构建机最长等待时间`
