### ISSUE TITLE
Pipeline Stage Review Support Variables

### ISSUE THREAD

**Issue by zhlinh** [Tencent/bk-ci#3584]
**What would you like to be added**:
Currently stage review doesn't support variables, i.e. ${BK_CI_PIPELINE_ID} or other varibles which have been setEnv

**Why is this needed**:
For more information can be show to the reviewer while doing stage review

![image](https://user-images.githubusercontent.com/7844628/105650226-0ee44380-5eee-11eb-9596-958defd9e584.png)

**Comment by zanyzhao** [comment]
Duplicate of #3395
