### ISSUE TITLE
Artificial Review Plugin Support Var Types and Annotation

### ISSUE THREAD

**Issue by zhlinh** [Tencent/bk-ci#3585]
**What would you like to be added**:
Currently the  variables of artificial review plugin only support sigle line vars. If in stage-1 manual trigger, the types of vars can be bool, checkbox, multiple lines, etc. I hope the Artificial Review Plugin can support these var types, and support annotation, which same with stage-1 manual trigger.

**Why is this needed**:
Very handy to reviewers to input vars and comprehend vars, same with the effect on stage-1 manual trigger.

![image](https://user-images.githubusercontent.com/7844628/105650670-6f27b500-5eef-11eb-8a6a-2da4f58716ec.png)
![image](https://user-images.githubusercontent.com/7844628/105650729-9f6f5380-5eef-11eb-9623-022292835ee4.png)

**Comment by irwinsun** [comment]
all  done like this
![image](https://user-images.githubusercontent.com/16686129/139531957-3a0b1847-b2dc-49f8-b976-129a6098983c.png)

#4180
