### ISSUE TITLE
setEnv Support multiple lines(LF)

### ISSUE THREAD

**Issue by zhlinh** [Tencent/bk-ci#3586]
**What would you like to be added**:
when setEnv muliple lines like `setEnv "$desc" which "$desc" is a multile lines text, the LF will be replaced with space. I hope setEnv can support LF which can pass to another plugins to update multiple lines info, like file, git release changelog info or wiki, etc.

**Why is this needed**:
plugins needs multiple lines(LF) vars to update info.

**Comment by irwinsun** [comment]
setEnv有大量的历史使用背景，无法再继续迭代兼容，请用最新的方式来拿来操作。
echo "::set-variable name=变量名::变量值"

```shell
# 通过::set-variable命令字设置/修改全局变量(当前步骤不生效)
# echo "::set-variable name=var_name::var_value"
# 在后续的插件表单中使用${{variables.var_name}}引用这个变量

# 通过::set-output命令字设置当前步骤的输出(当前步骤不生效)
# echo "::set-output name=output_name::output_value"
# 在后续的插件表单中使用${{jobs.<job_id>.steps.<step_id>.outputs.output_name}}引用这个输出，其中job_id和step_id在对应的Job和Task上配置
```
