### ISSUE TITLE
质量红线原子支持输入一些日志信息并打印

### ISSUE THREAD

**Issue by yi279095547** [Tencent/bk-ci#3598]
![image](https://user-images.githubusercontent.com/11883560/105705069-a1b2cb80-5f4a-11eb-9bec-dd2bccc53f29.png)
当插件支持红线功能时，期望能输出一些日志信息到质量红线原子打印。如上图中的1号插件输出一些日志字符串到2，然后2打印。因为用户使用插件时，如果红线没过，报红拦截的是质量红线原子，用户大部分都会点击查看质量红线原子，而不是支持红线的插件，导致一些动态信息无法直观看到。
支持红线的插件既然能输出阈值信息到质量红线原子，那么希望增加输出打印信息。

**Comment by irwinsun** [comment]
嗯，目前质量红线已经具备该能力
