### ISSUE TITLE
【feature】希望加入微信审批支持交互式功能，类似OA审批

### ISSUE THREAD

**Issue by leoswing** [Tencent/bk-ci#3611]
**What would you like to be added**:
目前通过人工审核插件，会推送一个消息到微信中，但是没办法直接在微信内完成审批，需要下载安装蓝盾APP才能进行。
期望能够形成如下特性增强支持：
- 微信审批的功能，支持在微信推送消息内完成审核。支持确认框这种方式的交互消息推送，例如 “审批通过” ---“版本回退”这种的交互式增强处理。
- 能通过这个“审批通过” 或者 “版本回退”触发后续回调，回调里面根据输入的结果执行不同的条件stage 处理。

**Why is this needed**:

基于上面的特性增强，可以让审批变得更加灵活了。
- 对于业务端可以无需额外下载蓝盾APP
- 对于审批者，审批和回退处理十分方便，不需要额外的操作，用户体验较佳

**Comment by iccengan** [comment]
设计如此。审批功能的设计初衷是审批人检查流水线编排和执行情况后再作审核决定。
之前有用户提过批量审批的需求，同理也是不合理的，在不清楚审批内容的情况下审批 会带来潜在风险。如果允许通过微信侧等第三方服务方式审批或允许批量审批，有违审批功能的设计初衷哈。
