### ISSUE TITLE
【研发商店】容器镜像上架时，适用机器和流水线JOB支持的机器对齐

### ISSUE THREAD

**Issue by fayewong-v5** [Tencent/bk-ci#3614]
![image](https://user-images.githubusercontent.com/54432927/105969335-190b6b00-60c3-11eb-8c82-1343995cb91a.png)

![image](https://user-images.githubusercontent.com/54432927/105969377-245e9680-60c3-11eb-82b6-43f3865c6340.png)

PS：验证失败的日志里：
1、不要出现 docker vm，改为用户能理解的内容，比如JOB里用户看到的是“Docker公共构建机”，那这里提示 “找不到 Docker公共构建机”
2、也不要出现 tlinux 2.2，显示用户配置的镜像
![image](https://user-images.githubusercontent.com/54432927/105969506-4bb56380-60c3-11eb-8681-4b1d04ffb1cd.png)

**Comment by irwinsun** [comment]
#3817 与此类似
