### ISSUE TITLE
agent安装目录文案优化

### ISSUE THREAD

**Issue by iccengan** [Tencent/bk-ci#3658]
### 现象：
在执行安装命令时，会直接把 当前执行安装命令的位置作为Agent安装目录。
![image](https://user-images.githubusercontent.com/10875468/106714537-f33c1400-6636-11eb-9492-741543f4c453.png)

### 期望：
Agent安装路径描述需优化为：

> 请在合适的位置为Agent创建工作目录，并在该目录下执行安装命令：

确保用户不会随意在任意目录下安装。引导用户创建一个专门给Agent安装的目录，与用户数据，根目录，数据盘分开，避免Agent产生的日志数据对用户的磁盘空间造成影响

**Comment by chainji** [comment]
是的，遇到过几次随便找个路径执行，才发现创建了很多文件，搞乱了目录结构，需要重新创建。
其实这里一般都是新机器，提示创建工作目录一般是合理的，比如这样提示：
“请在合适的位置为agent创建工作目录，并在该目录执行初始化命令：”
