### ISSUE TITLE
希望流水线变量支持tgit的分支

### ISSUE THREAD

**Issue by 2089764** [Tencent/bk-ci#3660]
背景：已关联了git.code.tencent.com的代码库
但在流水线变量里面无法查出来，如下图
![image](https://user-images.githubusercontent.com/1099115/106983600-213d6780-67a1-11eb-923f-4ff516aaf3c1.png)

希望增加tgit分支或tag 功能。谢谢

**Comment by leohzhuang** [comment]
同样有此需求；我们这边的场景是：

1. 有个项目是由外包同学配合着一起开发的，为了外包同学能访问项目代码，项目只能放置在外网工蜂上
2. 现在已经支持编译外网工蜂上的项目，但是在编译时，没法指定代码分支，只能编译固定分支，如果想编译不同分支的代码，只能每次都修改流水线编译的命令，或者建立多个不同的流水线，不是很方便

**Comment by fayewong-v5** [comment]
不仅tgit，所有git类型代码库，如gitlab、github都需支持

**Comment by chenyurou** [comment]
今天也碰到这个问题了，什么时候能支持呢？

**Comment by mingshewhe** [comment]
> 今天也碰到这个问题了，什么时候能支持呢？
已在开发中了
