### ISSUE TITLE
希望 bk-ci gitlab插件可以支持监听指定的事件

### ISSUE THREAD

**Issue by huanghongguang** [Tencent/bk-ci#3664]
目前gitlab事件触发插件，不支持监听指定事件，我们公司用的是gitlab， 希望可以支持下，谢谢！

**Comment by mingshewhe** [comment]
# 简介
"GitLab仓库代码提交触发"用于配置gitlab事件触发，接受gitlba发送的Webhook触发蓝盾构建。
# 目前支持的特性
- push代码到gitlab时，由配置的Webhook触发蓝盾任务构建
- 提交Merge Request到gitlab时，由配置的webhook触发蓝盾任务构建，支持PR动作：新建，更新，通过
- 提交tag到gitlba时，触发蓝盾任务构建
- 按分支名过滤触发器，多个分支名用,分割。分支名匹配规则使用的是AntPathMatcher规则，规则举例如下:

  路径 | 描述
  -- | --
  master| 匹配master分支
  feature/**| 匹配feature/分支
  master,feature/**|匹配master和feature/分支

- 按路径名过滤触发器，多个路径用,分割，路径过滤的规则是使用前缀过滤，不能使用*，规则举例如下：
 
   路径|描述
  -- | --
  aa|匹配aa开头的文件,aa和aaa都会触发
  aa/|匹配aa目录
  aa，bb| 匹配aa和bb开头的文件

- 按用户名过滤

# 插件使用
1. 新增凭证，在凭证管理->新增凭证，增加accessToken类型凭证
![image](https://user-images.githubusercontent.com/22971705/115655366-bfcf7280-a365-11eb-9021-e8208547f8c6.png)
2. 新增gitlab代码库，在代码库->关联代码库->gitlab代码库，新增代码库
![image](https://user-images.githubusercontent.com/22971705/115655543-0e7d0c80-a366-11eb-8aee-215cc7e5d129.png)
3. 在需要触发的流水线上，增加"GitLab仓库代码提交触发"插件，输入代码库ID，或者代码库别名，代码库别名是在代码库创建时的别名，支持通过参数${}传递。

# 环境变量
在接受gitlab发送的webhook消息时，会对消息体进行解析，将解析的参数传递到环境变量中，可以通过${xxx}引用。gitlab不同事件发送的消息体在https://docs.gitlab.com/ee/user/project/integrations/webhooks.html#webhooks 可以查到。其中不同的 WebHook 触发可能导致有些变量为空。在运行的时候在插件的日志上也能看到变量

## 触发公共变量

Variable | Description |
-- | -- | 
BK_CI_REPO_WEBHOOK_REPO_TYPE | 触发的代码库类型，为GITLAB | 
BK_CI_REPO_WEBHOOK_REPO_URL | 触发的代码库URL |  
BK_CI_REPO_WEBHOOK_NAME | 触发的代码库名称 |  
BK_CI_REPO_WEBHOOK_ALIAS_NAME | 触发的代码库在蓝盾的别名 |  
BK_CI_REPO_WEBHOOK_HASH_ID | 触发的代码库在蓝盾的HASH ID |  
BK_CI_REPO_GIT_WEBHOOK_COMMITID | 触发对应的COMMIT ID |  
BK_CI_REPO_GIT_WEBHOOK_EVENT_TYPE | 触发的事件类型 PUSH,TAG_PUSH,MERGE_REQUEST,MERGE_REQUEST_ACCEPT
BK_CI_REPO_GIT_WEBHOOK_INCLUDE_BRANCH | 触发插件的监听的分支 |  
BK_CI_REPO_GIT_WEBHOOK_EXCLUDE_BRANCH | 触发插件的排除的分支 |  
BK_CI_REPO_GIT_WEBHOOK_INCLUDE_PATHS | 触发插件的监听的路径 |  
BK_CI_REPO_GIT_WEBHOOK_EXCLUDE_PATHS | 触发插件的排除的路径 |  
BK_CI_REPO_GIT_WEBHOOK_EXCLUDE_USERS | 触发插件的排除的人员 |  
BK_CI_GIT_WEBHOOK_FINAL_INCLUDE_BRANCH | 触发匹配的分支 |  
BK_CI_GIT_WEBHOOK_FINAL_INCLUDE_PATH | 触发匹配的路径 |  
BK_REPO_GIT_WEBHOOK_PUSH_COMMIT_MSG_n | 触发的Commit日志。对于push事件n只等于1；对于mr事件n取值范围为1-32 

## Push Hook事件触发

Variable | Description |
-- | -- | 
BK_CI_REPO_GIT_WEBHOOK_PUSH_USERNAME | PUSH的用户 |  
BK_CI_REPO_GIT_WEBHOOK_BRANCH | PUSH对应分支 |  
BK_REPO_GIT_WEBHOOK_PUSH_BEFORE_COMMIT | 本次PUSH前的commit id |  
BK_REPO_GIT_WEBHOOK_PUSH_AFTER_COMMIT | 本次PUSH后的commit id |  
BK_REPO_GIT_WEBHOOK_PUSH_ADD_FILE_n1_n2 | 本次PUSH所添加的文件。n1表示第几个提交，n2表示提交中第几个文件，n取值范围为1-32 | 
BK_REPO_GIT_WEBHOOK_PUSH_MODIFY_FILE_n1_n2 | 本次PUSH所变更的文件。n1表示第几个提交，n2表示提交中第几个文件，n取值范围为1-32 | 
BK_REPO_GIT_WEBHOOK_PUSH_DELETE_FILE_n1_n2 | 本次PUSH所删除的文件。n1表示第几个提交，n2表示提交中第几个文件，n取值范围为1-32 | 
BK_REPO_GIT_WEBHOOK_PUSH_ADD_FILE_COUNT | 本次PUSH所添加的文件数量 |  
BK_REPO_GIT_WEBHOOK_PUSH_MODIFY_FILE_COUNT | 本次PUSH所变更的文件数量 |  
BK_REPO_GIT_WEBHOOK_PUSH_DELETE_FILE_COUNT | 本次PUSH所删除的文件数量 |  

## Merge Request Hook 或 Merge Request Hook Accept事件触发
Variable | Description
-- | --
BK_CI_REPO_GIT_WEBHOOK_MR_AUTHOR | Merge Request的作者或提交者
BK_CI_REPO_GIT_WEBHOOK_TARGET_URL | Merge Request的目标代码库URL
BK_CI_REPO_GIT_WEBHOOK_SOURCE_URL | Merge Request的源代码库URL
BK_CI_REPO_GIT_WEBHOOK_TARGET_BRANCH | Merge Request的目标分支
BK_CI_REPO_GIT_WEBHOOK_SOURCE_BRANCH | Merge Request的源分支
BK_CI_REPO_GIT_WEBHOOK_MR_CREATE_TIME | Merge Request的创建时间
BK_CI_REPO_GIT_WEBHOOK_MR_UPDATE_TIME | Merge Request的创建时间戳
BK_CI_REPO_GIT_WEBHOOK_MR_CREATE_TIMESTAMP | Merge Request的更新时间
BK_CI_REPO_GIT_WEBHOOK_MR_UPDATE_TIMESTAMP | Merge Request的更新时间戳
BK_CI_REPO_GIT_WEBHOOK_MR_ID | 触发的Merge Request Id
BK_CI_REPO_GIT_WEBHOOK_MR_NUMBER | 触发的Merge Request Number
BK_CI_REPO_GIT_WEBHOOK_MR_DESC | Merge Request的描述
BK_CI_REPO_GIT_WEBHOOK_MR_TITLE | Merge Request的标题
BK_CI_REPO_GIT_WEBHOOK_MR_ASSIGNEE | Merge Request负责人
BK_CI_REPO_GIT_WEBHOOK_MR_URL | Merge Request的URL
BK_CI_REPO_GIT_WEBHOOK_MR_REVIEWERS | Merge Request的评审人（包括必要评审人）
BK_CI_REPO_GIT_WEBHOOK_MR_MILESTONE | Merge Request的里程碑名称
BK_CI_REPO_GIT_WEBHOOK_MR_MILESTONE_DUE_DATE | Merge Request的里程碑时间
BK_CI_REPO_GIT_WEBHOOK_MR_LABELS | Merge Request的标签
BK_CI_REPO_GIT_WEBHOOK_COMMITID | Merge Request的ID
BK_REPO_GIT_WEBHOOK_MR_LAST_COMMIT | Merge Request最后一个提交的commitId
BK_REPO_GIT_WEBHOOK_MR_LAST_COMMIT_MSG | Merge Request最后一个提交的提交信息

##  Tag Push Hook事件触发
Variable | Description
-- | --
BK_CI_REPO_GIT_WEBHOOK_TAG_NAME | 提交的TAG名字
BK_CI_REPO_GIT_WEBHOOK_TAG_OPERATION | TAG操作：创建或删除(create/delete)
BK_CI_REPO_GIT_WEBHOOK_TAG_USERNAME | 提交的TAG的作者
BK_REPO_GIT_WEBHOOK_TAG_CREATE_FROM | 从哪个分支或者commit点创建，如果从客户端创建的tag，值为空

# FAQ
1. 事件是怎么注册到gitlab的
在保存流水线时，会解析流水线中配置的“GitLab仓库代码提交触发”插件，获取配置的代码库，然后拿到代码库配置的凭证，再调https://docs.gitlab.com/ee/api/projects.html#add-project-hook 接口注册
2. 配置了插件但是没有触发？
排查思路：https://github.com/Tencent/bk-ci/issues/3670#issuecomment-782530390

**Comment by fayewong-v5** [comment]
待正式后，再修改前端配置
