### ISSUE TITLE
pref:【流水线插件】插件执行环境初始化

### ISSUE THREAD

**Issue by fayewong-v5** [Tencent/bk-ci#3666]
如：
1、python插件，支持用户指定python版本，支持包安装到非系统目录
2、nodejs插件，支持用户指定nodejs版本，在windows下时，自带tar工具解压
3、golang插件，支持不同OS
4、解决用户配置的 demands 不生效的问题
5、插件执行前，检测环境是否满足需求，如：
     - 执行python 插件之前，检测环境中是否有 pip 或者 pip3

方案：
nodejs：
- 用预定版本的方式支持
  - task.json中支持开发者指定版本
  - 从 10 开始每个大版本下支持一个稳定版
- 构建和执行时，均使用开发者指定的版本
  - 第三方构建机也一样，执行时需自动下载对应的node版本
  - 当开发者未指定版本时，使用系统指定版本构建

golang：
- 在linux构建机上交叉编译
  - 根据用户选择的 os，编译出对应的包
- task.json中指定支持的 cpu 架构
  - 目前可以支持少数几个常用的

python：
- 支持开发者在task.json中指定使用 python2 or python3

**Comment by kianfang** [comment]
希望插件支持用户指定nodejs版本能早点提上日程，当前版本`v10.11.0`(截止20220511)已经不够用了，默认打包工具rollup较新版本已无法正常运转：
![image](https://user-images.githubusercontent.com/16569491/167756020-69e6d4ca-c28e-4b38-ab11-f78a3b53cc75.png)
![image](https://user-images.githubusercontent.com/16569491/167756120-150ab5a0-512c-4260-b30f-0144dfed17ed.png)
