### ISSUE TITLE
gitlab事件触发插件无法触发事件

### ISSUE THREAD

**Issue by huanghongguang** [Tencent/bk-ci#3670]
**What happened**:  流水线触发器选择了gitlab， 指定了代码库，然后分支名称不填（默认监听所有分支）， 仓库  push后没有触发流水线

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- bk-ci version (use `cat VERSION` in installed dir):  v1.2.5
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): CentOS Linux 7 (Core)
- Kernel (e.g. `uname -a`):  Linux VM-55-16-centos 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by mingshewhe** [comment]
1. 查看下devops_ci_process.T_PIPELINE_WEBHOOK表是否有注册这条流水线，
    SELECT * FROM devops_ci_process.T_PIPELINE_WEBHOOK WHERE pipeline_id = ${pipeline_id}，${pipeline_id}可以从url地址获取
2. 如果没有注册，查看process服务到gitlba的网络是否能通，gitlab仓库的权限是否是master权限，
3. 如果上面都没问题，请提供下process的运行日志。

**Comment by huanghongguang** [comment]
用提供 的SQL能查到记录， 提示process的运行日志， 具体是哪个日志？

**Comment by mingshewhe** [comment]
> 用提供 的SQL能查到记录， 提示process的运行日志， 具体是哪个日志？

process运行路径在：$BK_HOME/logs/ci/process中，$BK_HOME默认是/data/bkce，文件名是process.log

**Comment by huanghongguang** [comment]
问题已查明， gitlab机器没有Devops域名解析
