### ISSUE TITLE
需求：流水线history接口支持返回stage标签字段

### ISSUE THREAD

**Issue by jagerzhang** [Tencent/bk-ci#3685]
目前部门需求统计流水线各阶段的耗时数据，主要是通过流水线stage关联的Buid、Deploy、Test标签来确定阶段，但是蓝盾接口查询流水线历史记录时，只返回了stage和耗时，不包含stage的标签，因此要统计就得再结合单次构建详情接口，加重了客户端逻辑，也耗费了蓝盾接口性能，希望可以支持在总的历史详情接口中直接返回stage关联的标签，主要涉及的接口如下：

- V*应用态-获取流水线构建历史：/prod/v*/apigw-app/projects/{projectId}/pipelines/{pipelineId}/builds
- V*用户态-获取流水线构建历史：/prod/v*/apigw-user/projects/{projectId}/pipelines/{pipelineId}/builds

![image](https://user-images.githubusercontent.com/9711651/108670224-7dcab180-7519-11eb-9278-8c1b6c42457a.png)

**Comment by royalhuang** [comment]
> 目前部门需求统计流水线各阶段的耗时数据，主要是通过流水线stage关联的Buid、Deploy、Test标签来确定阶段，但是蓝盾接口查询流水线历史记录时，只返回了stage和耗时，不包含stage的标签，因此要统计就得再结合单次构建详情接口，加重了客户端逻辑，也耗费了蓝盾接口性能，希望可以支持在总的历史详情接口中直接返回stage关联的标签，主要涉及的接口如下：
> 
> * V_应用态-获取流水线构建历史：/prod/v_/apigw-app/projects/{projectId}/pipelines/{pipelineId}/builds
> * V_用户态-获取流水线构建历史：/prod/v_/apigw-user/projects/{projectId}/pipelines/{pipelineId}/builds
> 
> ![image](https://user-images.githubusercontent.com/9711651/108670224-7dcab180-7519-11eb-9278-8c1b6c42457a.png)

我们将增加stageStatus中增加每个stage的所有标签id的字段，需要配合获取所有stage tags信息（id与标签名）的接口一起使用，将在下一次发版上线

**Comment by jagerzhang** [comment]
@royalhuang 收到，感谢支持。
