### ISSUE TITLE
支持：根据实例化出来的流水线反向查找模板的功能

### ISSUE THREAD

**Issue by iccengan** [Tencent/bk-ci#370]
### 背景
模板比较多的情况下，当要修改当前实例化流水线的模板时，无法快速定位到对应模板

### 需求
方案一：
流水线编辑->基础设置 添加侧边栏页签【模板】。展示该模板基本信息并支持跳转
![image](https://user-images.githubusercontent.com/10875468/71332357-d9de2280-2570-11ea-8dc7-89c0af111c64.png)
![image](https://user-images.githubusercontent.com/10875468/71332306-a602fd00-2570-11ea-862d-e76d4b2ece22.png)

方案二：
模板实例化的流水线，编辑直接跳转至模板编辑界面
![image](https://user-images.githubusercontent.com/10875468/89252494-81195100-d64c-11ea-8431-c6ccea9d8747.png)

方案三：
点击编辑直接跳转至对应模板编排编辑页面。流水线的通知、权限、基础设置则放入独立入口单独配置，不与编排混在一起。
![image](https://user-images.githubusercontent.com/10875468/94430686-e316b280-01c6-11eb-8ff8-ca38c3b2ff11.png)
![image](https://user-images.githubusercontent.com/10875468/94430862-23763080-01c7-11eb-80db-9723bdc77537.png)

**Comment by tyuyu** [comment]
项目组其他成员创建的流水线，出现了问题，无法从流水线找到对应的模版修改，只能删掉重建

**Comment by iccengan** [comment]
> 项目组其他成员创建的流水线，出现了问题，无法从流水线找到对应的模版修改，只能删掉重建

@tyuyu 不需要删掉重建，可以进入模板管理界面，对模板进行修改后再对实例进行更新，即可完成实例化流水线的更改。
后面会做个优化：#846，应该可以规避掉你描述的歧义。

**Comment by fayewong-v5** [comment]
通过扩展支持

**Comment by taohuifa** [comment]
目前我们模板太多, 导致生成出来的流水线完全找不到模板所在, 改个流水线要找半天

**Comment by taohuifa** [comment]
目前最简单的诉求是能通过实例化的流水线找到对应的模板

**Comment by taohuifa** [comment]
求支持

**Comment by zanyzhao** [comment]
在以下页面的更多选项内增加“跳转至模板”的入口：
- 流水线执行历史
- 流水线详情页
- 流水线编辑页
![image](https://user-images.githubusercontent.com/1629409/121315523-ffb0e000-c93a-11eb-830c-bddd24960fc9.png)
