### ISSUE TITLE
bash插件在一个脚本有多行输出时不保证顺序

### ISSUE THREAD

**Issue by KylinHuang7** [Tencent/bk-ci#3725]
**What happened**:
<img width="823" alt="企业微信截图_306b75dd-97ea-45ba-a597-56bfd0996860" src="https://user-images.githubusercontent.com/7699477/109275195-5d6b6180-784f-11eb-8177-c58d945bb640.png">
<img width="688" alt="企业微信截图_409beff0-1ad3-4072-88ae-03c97dddd52f" src="https://user-images.githubusercontent.com/7699477/109275203-60665200-784f-11eb-96fc-d0aa36130561.png">

如上图所示，当使用bash插件时，如果同一毫秒有多行输出，在日志中显示时不保证顺序

**What you expected to happen**:
期望能够保证日志中展示的输出顺序与实际输出顺序一致

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- bk-ci version (use `cat VERSION` in installed dir):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by royalhuang** [comment]
已在#3661中解决，并发布现网
