### ISSUE TITLE
batch 脚本执行 python 脚本无实时日志

### ISSUE THREAD

**Issue by AntSworD** [Tencent/bk-ci#3726]
py 脚本里 print 了日志
在 batch 插件执行了 py 脚本，只能在执行完成后才能看到日志内容，不能实时输出到网页上
麻烦问下这个是什么原因？有什么办法解决么🤗

**Comment by fayewong-v5** [comment]
动态脚本语言一般都有I/O缓冲机制。
可以用 python 解释器提供的 -u 参数：
python -u <xxx.py>
或者在print之后刷新缓冲区：
sys.stdout.flush()
或者设置环境变量：
export PYTHONUNBUFFERED=1

**Comment by AntSworD** [comment]
> 动态脚本语言一般都有I/O缓冲机制。
> 
> 可以用 python 解释器提供的 -u 参数：
> python -u <xxx.py>
> 
> 或者在print之后刷新缓冲区：
> sys.stdout.flush()
> 
> 或者设置环境变量：
> export PYTHONUNBUFFERED=1

谢谢
