### ISSUE TITLE
模板实例过多时升级较慢

### ISSUE THREAD

**Issue by vissong** [Tencent/bk-ci#373]
1. 实例升级页面，默认一页10个实例，如果切换显示更多实例时，无法保存，升级后会都是页码定位
2. 升级实例时，选择10个实例时最快的，如果选择多个实例，升级很慢
3. 模板超过 100 个实例时，全部升级到最新版本，需要聚焦1小时以上来进行操作。

**Comment by irwinsun** [comment]
目前模板的操作性能依赖于模板上的定义的流水线变量的类型，比如流水线变量是GIT/SVN分支，代码库， 版本仓库 等类型的， 涉及到向这些第三方系统查询，受到这些系统接口响应速度的影响比较大。

**Comment by vissong** [comment]
流水线模板上已经定义了变量，实例化的时候也填写过变量，如果在升级的时候直接沿用变量，然后排队进行升级，是否就可以提升操作的速度，而全部流水线的升级依赖排队异步完成，实际上异步与同步处理，应该有相同的失败率吧

**Comment by irwinsun** [comment]
1. 比如GIT/SVN 分支这类变量， 是动态的，目前产品上的设计是允许实例化时，操作者可以去为每个实例选择变更的值，所以这个变量值就必须同步拉取出来，否则无法选择。
2. 异步与同步都有相同的失败率，但同步时失败时会停止实例化的流程，就不会出现数据是不完整的实例. 而异步的方式目前通知上比较麻烦，需要通知操作者失败了，比如我们一直在优化的websocket通知，但操作者可能会直接操作完关掉浏览器。出现数据错误再来排查就会复杂许多。
