### ISSUE TITLE
凭证管理的密码只能在bash获取，不能在插件中直接引用。麻烦补齐这个功能。

### ISSUE THREAD

**Issue by Star-Lordxing** [Tencent/bk-ci#3733]
凭证管理的密码只能在bash获取，不能在插件中直接引用。麻烦补齐这个功能。

大量用户反馈，在插件中填写密码的话，需要填写明文 不符合安全规范。而凭证管理中的需要 在bash中转存一个变量 然后在插件中才能获取到。大部分插件都是非bash插件，不是所有人都会这么使用。请补齐这个功能吧，感谢！

--From PCG

**Comment by fayewong-v5** [comment]
自定义插件，可以让用户选凭据而不是让用户填用户名密码，插件通过SDK方法获取凭据内容
