### ISSUE TITLE
feat：邮件插件支持文件附件

### ISSUE THREAD

**Issue by SingerStone95** [Tencent/bk-ci#3738]
2021-03-02
目前流水线上的发送邮件插件都不支持携带附件
比如携带.apk .html（源文件）等

望支持！感谢

**Comment by zanyzhao** [comment]
这个受限于每个公司的邮件服务器限制吧，默认最大附件好像也就10M

更合理一点的做法是：在发邮件之前加一个【上传至COS】等云存储上，返回一个链接，附到邮件内容里

**Comment by SingerStone95** [comment]
对，这个方案上没啥问题。
但是我的理解，邮件附件功能是流水线<邮件插件>的通用能力，即使配置的邮件服务器不支持，也是由服务器返回错误信息吧。

**Comment by zanyzhao** [comment]
目前邮件附件的需求不多，我们最近正在整理将这部分插件脱敏开源出来，等开源后再启动

**Comment by irwinsun** [comment]
基础的邮件插件仅用于发通知，不考虑这类特殊场景。
