### ISSUE TITLE
想要获取执行次数、成功率等插件统计信息

### ISSUE THREAD

**Issue by Erin513** [Tencent/bk-ci#3770]
**What would you like to be added**:
希望能获取到蓝盾插件的以下统计信息：
1.执行次数
2.想要能获取到蓝端插件在用户侧的成功率（去除作者自身在插件未发布时对插件测试执行时的执行情况 ）
3.执行成功时的平均耗时、最长耗时和对应log
4.使用用户对应项目信息和流水线信息

**Why is this needed**:
1.对插件运营情况能更好的了解
2.能帮助对插件进行优化

**Comment by fayewong-v5** [comment]
#1619 
#1621 
#1856
