### ISSUE TITLE
增加取消时自动归档的功能

### ISSUE THREAD

**Issue by alexcheney** [Tencent/bk-ci#3792]
希望： 希望增加取消构建时，能把build目录下的文件也能自动归档。

现状：异常停止时，会继续执行后面的归档的步骤。但如果手动取消时，无法执行。但这个时候有些有用的log文件已经生成了。

**Comment by iccengan** [comment]
几个问题想再明确下哈：
1. 能再详细描述下期望吗？是把build目录下的所有文件自动归档？
2. “异常停止时，会继续执行后面的归档的步骤”。流水线执行失败时，应该不会继续执行后续步骤的，你这里指的具体场景是？

**Comment by irwinsun** [comment]
目前取消/失败/成功/一直 执行 可以使用FinallyStage 进行处理 #3138 
![image](https://user-images.githubusercontent.com/16686129/119109799-11961600-ba54-11eb-9c8a-5f937e761993.png)



有4个场景可选择
![image](https://user-images.githubusercontent.com/16686129/119109696-f7f4ce80-ba53-11eb-8cbc-306f329e43b4.png)
