### ISSUE TITLE
codecc代码检查是ci工具中自带的吗？

### ISSUE THREAD

**Issue by kevinsingapore** [Tencent/bk-ci#38]
codecc代码检查是ci工具中自带的吗？

**Comment by irwinsun** [comment]
codecc是单独的一个代码检查平台，将会以插件的方式集成进ci的流水线，由流水线触发

**Comment by JerryGinger** [comment]
开源版本的蓝盾有集成codecc的时间计划表吗？ @irwinsun

**Comment by irwinsun** [comment]
有、目前正在处理。 预计下个月会有版本出来
