### ISSUE TITLE
下架微信通知功能

### ISSUE THREAD

**Issue by carrywang05** [Tencent/bk-ci#3804]
主要包括以下位置的微信功能下架：
1、【流水线-通知】设置页面
![image](https://user-images.githubusercontent.com/46527215/121168297-5e1b8700-c885-11eb-9490-411463bbbe74.png)
2、【质量红线-红线规则-编辑】页面
![image](https://user-images.githubusercontent.com/46527215/121168952-16e1c600-c886-11eb-8e1f-5e3152aaaf98.png)

同时需要提前对用户进行公告通知。

**Comment by carrywang05** [comment]
另外需要考虑微信通知插件下架。

**Comment by vhwweng** [comment]
改内部需求跟进
