### ISSUE TITLE
bug: 工蜂触发流水线运行多次情况下，流水线结果回传工蜂不正确

### ISSUE THREAD

**Issue by mingshewhe** [Tencent/bk-ci#3805]
【问题描述】 
操作如下：
1、工蜂上发起MR，触发蓝盾流水线构建a
2、reopen MR/重新Commit，触发蓝盾流水线构建b
3、手动终止构建a，结果会回传到工蜂，此时工蜂显示流水线构建失败，链接到构建a。实际的构建应该是b

【期望的结果】
1、cancel/失败，希望不希望之前的流水线回传到MR里面。

**Comment by xuthief** [comment]
同样遇到如下类似问题：
【问题描述】
操作如下：
1、工蜂上发起MR1到分支1，触发蓝盾流水线构建a
2、相同的commit提交MR2另外的mr到其他分支2，此分支2没有被监听，有mr_hook到蓝盾但是不会触发构建（监听分支中没有分支2）
3、MR2中的流水线会直接关联到MR1的流水线构建a

【期望的结果】
1、MR2中不应该关联流水线构建a

**Comment by mingshewhe** [comment]
> 同样遇到如下类似问题：
> 【问题描述】
> 操作如下：
> 1、工蜂上发起MR1到分支1，触发蓝盾流水线构建a
> 2、相同的commit提交MR2另外的mr到其他分支2，此分支2没有被监听，有mr_hook到蓝盾但是不会触发构建（监听分支中没有分支2）
> 3、MR2中的流水线会直接关联到MR1的流水线构建a
> 
> 【期望的结果】
> 1、MR2中不应该关联流水线构建a

这个问题跟这个issue没有关系，因为commit check(MR界面看到的流水线)是跟commitId绑定，只要这个commitid发起过MR1，如果这个commitId再向另外分支发MR2，那么在MR2也能看到MR1触发的流水线，工蜂的设计就是如此的.
