### ISSUE TITLE
希望在新建流水线的时候选择某个模板后看到更详细的信息

### ISSUE THREAD

**Issue by Yuliang-Lee** [Tencent/bk-ci#381]
**Describe the solution you'd like**
希望在新建流水线的时候选择某个模板后看到更详细的信息

**Additional context**
现在在选择模板的时候只能看到模板名字，在模板比较多时可能会有名字比较类似的，希望可以展示模板的简介等信息

**Comment by irwinsun** [comment]
![image](https://user-images.githubusercontent.com/16686129/71362428-f8740600-25d0-11ea-94c0-6a9275acb557.png)
第1个问题目前可以在这操作展示

**Comment by zanyzhao** [comment]
![image](https://user-images.githubusercontent.com/1629409/83393411-50892100-a429-11ea-804f-c6ed8136960b.png)
其实有个模板预览页面

**Comment by zanyzhao** [comment]
> 其实有个模板预览页面

这个页面缺少模板的详细信息，比如：简介/更新时间等 @fayewong-v5

**Comment by Yuliang-Lee** [comment]
这个预览好像也是提这个 issue 之后才有的

**Comment by royalhuang** [comment]
> 这个预览好像也是提这个 issue 之后才有的

这个功能已经实现，可能当时没及时同步过来，确认一下可以关闭issue了呢 @fayewong-v5
