### ISSUE TITLE
Job与Job间的连线展示优化

### ISSUE THREAD

**Issue by iccengan** [Tencent/bk-ci#3832]
### 现象：
如下图，Job2-2、Job2-3被禁用时，Job2-1与Job2-4之间的连线被断开。
![image](https://user-images.githubusercontent.com/10875468/111312764-96526580-869a-11eb-8817-b6d790af2a8e.png)

### 期望：
同个Stage下应连接至最后一个启用的Job

**Comment by zanyzhao** [comment]
连线全部改为统一的蓝色，不需要判断Job是否禁用而显示不同颜色
