### ISSUE TITLE
fix: “Job依赖”与“何时运行本Job”优先级问题

### ISSUE THREAD

**Issue by irwinsun** [Tencent/bk-ci#3850]
**1. 明确Job依赖检测优先级**:
原#111没有详细说明此类场景的优先级顺序，实现上默认以DependOn为最高优先级。
#3336 问题在于打破该规则，只是简单将条件判断优先级提高导致了问题：比如 b依赖于a所产生的条件值才运行，并且设置了依赖a，因启动时a和b是并行的，如果先判断该条件，则一开始b就不会满足执行条件而直接跳过。

**现修复为：** 
b依赖于a：
- 如果a执行，b执行：a失败时，b为跳过状态；a成功时，b执行。
- 如果a执行，b跳过：b无论如何都是跳过状态。
- 如果a跳过：b无论如何都是跳过状态。

**Environment**:
- bk-ci version v1.4.0, v1.3

**Comment by iccengan** [comment]
### 期望
b依赖于a：
如果a执行，b执行：a失败时，b为跳过状态；a成功时，b执行。
如果a执行，b跳过：b无论如何都是跳过状态。
如果a跳过：b无论如何都是跳过状态。

#### 原则：只要没执行到b，b就只会是跳过状态。b的状态不受前置job影响，只跟自己的task有没有执行成功有关。
