### ISSUE TITLE
bug: shell 脚本grep为空 时报错

### ISSUE THREAD

**Issue by sawyersong2** [Tencent/bk-ci#3855]

**Comment by iccengan** [comment]
设计如此。bash插件执行成功与否的判断，是根据执行指令返回码是否非0。当返回码非0时，插件报错是预期结果。
grep不到内容时，指令返回非0，所以bash插件执行失败。
![image](https://user-images.githubusercontent.com/10875468/112087953-e749e880-8bc9-11eb-9d87-b355ee93a830.png)
