### ISSUE TITLE
feat: 流水线复杂度限制

### ISSUE THREAD

**Issue by zanyzhao** [Tencent/bk-ci#3872]
**What would you like to be added**:
目前的流水线编排数据只有DB层面的16MB限制，我希望能在产品上针对流水线做进一步的编排复杂度限制：
- 每个Pipeline最多包含20个Stage
- 每个Stage最多包含20个Job
- 每个Job最多包含50个Task
- 每个Task最多包含100个输入参数、100个输出参数
- 每个输入参数也有对应的大小限制

组件类型 | 大小限制
-- | --
input | 1KB
checkbox | 1KB
textarea | 16KB
code_editor | 16KB

- 每个输出参数最多4KB大小

** 希望展现的页面有：
### 针对历史数据（部分功能实现成本过高，暂时去掉）
- 流水线编辑页/模板编辑页
  - ~~打开流水线编辑页时~~
  - 保存流水线时
- ~~流水线列表页~~
- ~~流水线通知模板~~
- ~~模板实例化页面~~
### 针对新增数据
- 流水线及流水线模板编辑页
  - Task输入参数时：
  - Task右划框折叠时：
  - 单pipeline超过Stage数量限制时：
  - 单Stage超过Job数量限制时：
  - 单Job超过Task数量限制时：
- 模板安装页面
- 模板实例化页面
- 通过API创建时
  - 创建流水线：
  - 通过模板实例化流水线：

**Why is this needed**:
- 提升极端情况下的前端响应时间及可用性
- 避免流水线编排过大，导致底层压力
- 可以将编排数据录入大数据平台，进行二次分析（单个json过大会导致无法使用kafaka）

**Comment by iccengan** [comment]
bash插件需特殊考虑 @zanyzhao
