### ISSUE TITLE
feature: 流水线列表接口新增过滤没有权限流水线字段

### ISSUE THREAD

**Issue by stubenhuang** [Tencent/bk-ci#3876]
流水线列表接口新增过滤没有权限流水线字段

**Comment by irwinsun** [comment]
@zanyzhao @iccengan 此需求的来源？

**Comment by iccengan** [comment]
> @zanyzhao @iccengan 此需求的来源？

APP端后台返回的视图流水线列表需过滤掉无权限的流水线
