### ISSUE TITLE
腾讯代码分析(最新)-新告警判定时间不支持变量

### ISSUE THREAD

**Issue by IsCjf** [Tencent/bk-ci#3881]
**What would you like to be added**:
希望腾讯代码分析(最新)-新告警判定时间，可以支持流水线变量，这样一个模板可以实例化不同类型的流水线。
**Why is this needed**:
多个仓库共用一个流水线模板，新告警判定时间不一致，实例化流水线不能编辑，不同的时间就需要不断地修改模板，不方便。

**Comment by carrywang05** [comment]
后续新问题判定时间功能会进行升级，建议不要过于依赖该功能。
