### ISSUE TITLE
支持Job级别的rebuild功能

### ISSUE THREAD

**Issue by xyc-cn** [Tencent/bk-ci#389]
场景
拉取code review状态，然后在bash里判断是否满足条件

出错了重试bash的判断毫无意义，需要重新拉取code review

**Comment by irwinsun** [comment]
我们正在开发的有一个功能是 issue #342  支持整条流水线全部重跑

同时有在规划一个按job级别的重试

**Comment by irwinsun** [comment]
#1507

**Comment by MikeoPerfect** [comment]
> #1507

请问是否支持自动的rebuild, 这种似乎是在失败之后，除非手动点击rebuild才会触发Job rebuild，事实上很多流水线都是定时触发或者git事件触发，很难care到哪些需要手动点击rebuild，希望支持自动的rebuild

**Comment by zanyzhao** [comment]
如果加了Job rebuild后，也可以在Job里增加一个开关，用来关闭“插件重试”

**Comment by iccengan** [comment]
环境被破坏后，Job级别的rebuild有必要。
如：
1. Job 下 Task1 生成 `a文件`
2. Task2（bash插件）对 `a文件` 做某操作，并把 `a文件` 删除，再继续执行 bash 内余下指令。
3. Task2 在执行余下指令时失败
4. 此时如果仅支持插件重试，Task2 已经获取不到 `a文件`

上述场景可通过 Stage重试 来满足，但 Stage重试 会再次执行已成功的 Job，可能会增加额外的耗时。

**Comment by zanyzhao** [comment]
增加“Stage重试入口”，点击后弹出两个选项：
- 重新运行本Stage下所有Job
- 重新运行所有失败Job
