### ISSUE TITLE
提供修改流水线基础设置的OpenApi

### ISSUE THREAD

**Issue by iccengan** [Tencent/bk-ci#3893]
### 用户场景：
模板实例化的流水线无法通过api修改流水线标签、描述等基础信息。使用`pipeline_edit`接口时，会报：“Pipeline: Template can not be edit”。

### 原因：
`pipeline_edit`接口目前的逻辑控制了流水线编排以及基础设置。当目标流水线是模板实例，直接报错返回“Pipeline: Template can not be edit”。但模板实例实际上是可以修改基础设置的。

### 期望：
提供新的OpenApi，仅修改目标流水线的基础设置。

**Comment by royalhuang** [comment]
path 路径有参数冲突，现网apigw这边暂时无法调用，将在 #4480 补充修复（灰度后就能恢复接口） @iccengan
