### ISSUE TITLE
bug: 研发商店的模板，编辑页面红线不提示拦截

### ISSUE THREAD

**Issue by ddlin0719** [Tencent/bk-ci#3911]
ms/process/api/user/pipelines/{projectId}/{pipelineId}接口返回的templateId是对应T_TEMPLATE_PIPELINE表的srcTemplate，不是真实的templateId

希望把真实的templateId也返回

**Comment by carlyin0801** [comment]
已在https://github.com/Tencent/bk-ci/pull/4228修复
