### ISSUE TITLE
agent在启动worker后一段时间后任务仍未执行执行时上报错误状态到服务端

### ISSUE THREAD

**Issue by necrohuang** [Tencent/bk-ci#3927]
agent启动worker执行Job任务，当work进程因为网络或其他原因问题无法认领任务时，worker进程已经退出，但流水线相应的Job处于挂起状态，要到job超时（900分钟）后才会超时错误，等待时间太长。
agent侧可以根据可以捕捉到的信息，在agent在启动worker后一段时间后任务仍未执行执行时，将相应的状态和日志上报到服务端

**Comment by irwinsun** [comment]
目前已经实现 workerBuildFinish?
