### ISSUE TITLE
远程触发这个流水线插件支持get方式

### ISSUE THREAD

**Issue by xuxin3101** [Tencent/bk-ci#3962]
现在远程触发这个组件只支持post方式，导致某些只支持get方式的webhook无法触发这个组件而触发流水线的运行，希望能够支持get的方式，让组件更加灵活

**Comment by zanyzhao** [comment]
远程触发时无法获取触发人相关信息，有一定的安全隐患，后续可能会下架。如果有更复杂的触发流水线需求，可以考虑用API
