### ISSUE TITLE
增加键值对变量类型

### ISSUE THREAD

**Issue by shandianling** [Tencent/bk-ci#398]
执行流水线时，对于用户看到是键值(可理解的描述)
但对于编辑者，则能拿能对应的value，可以是整数也可以是字符串。或者全是字符串，这样通用些。
![image](https://user-images.githubusercontent.com/3283999/71431586-d338e200-270d-11ea-8a0f-4ef398d82cd6.png)
参数配置时填写：
【全停全启】--> restart_all
【重新加载】--> reload_all
【仅解压】    --> unpack
例如：用户看到上面三个选项，用户选择 【全停全启】时，则拿到 其对应的值: “restart_all ”

**Comment by irwinsun** [comment]
@zanyzhao

**Comment by zanyzhao** [comment]
合理的需求，就跟html的select组件一样，有Key/Value

**Comment by irwinsun** [comment]
![image](https://user-images.githubusercontent.com/16686129/82184386-2bb98780-991a-11ea-9fd4-9357d17d1c26.png)

 效果是，使用=号分隔 key(界面展示的选项内容)=value（传给启动的真正的值)

**Comment by irwinsun** [comment]
![image](https://user-images.githubusercontent.com/16686129/82184634-8b179780-991a-11ea-99ad-49c76d8ccdeb.png)
前端需要做下适配处理处理，将当前的key,value 根据=号来做拆分和展示
