### ISSUE TITLE
模板实例化的流水线删除再从回收站复原，在模板列表中找不到，也无法更新

### ISSUE THREAD

**Issue by jerrybean** [Tencent/bk-ci#4012]
**What happened**:
如题
**What you expected to happen**:
恢复的流水线能在模板实例化列表中看到，可以更新到模板任意版本。
**How to reproduce it (as minimally and precisely as possible)**:
1. 创建一个模板
2. 实例化一条流水线
3. 删除2中创建的流水线
4. 回收站复原删除的流水线
5. 模板实例化列表找不到这条流水线，流水线本身也没法编辑、升级
**Anything else we need to know?**:

**Environment**:
- bk-ci version (use `cat VERSION` in installed dir):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by zanyzhao** [comment]
确实是个隐晦的BUG，我们放到5月份修一下

**Comment by irwinsun** [comment]
目前删除流水线会一起删除流水线的模板绑定关系。
需要新增一个DELETED字段标识模板绑定关系处于被删除， 用于解决已删除的流水线仍然会出现在模板实例列表中
![image](https://user-images.githubusercontent.com/16686129/120410590-d82fa580-c385-11eb-9f60-dda226ab6e52.png)
