### ISSUE TITLE
API: 补齐代码库服务的V3版openAPI

### ISSUE THREAD

**Issue by zanyzhao** [Tencent/bk-ci#4081]
**What would you like to be added**:
目前代码库服务的相关API缺失，需补齐
**Why is this needed**:
刚需

**Comment by joshuaton** [comment]
需要此api，使用场景：
已有一个流水线模板，实例化模板的时候，有一个输入参数是代码仓库，代码仓库是之前通过工蜂api创建好的，所以需要一个蓝盾代码库api创建一下，才能在流水线读取到。
