### ISSUE TITLE
feat: 增加流水线重试接口

### ISSUE THREAD

**Issue by sherlockZ** [Tencent/bk-ci#4097]
**What would you like to be added**:

像 start 和 stop 接口一样支持 rebuild（重试）

**Why is this needed**:

因为蓝盾支持各种各样的启动方式，有很多情况，比如 Git 监听启动，启动的时候会带上很多 Git 的参数，这些参数手动启动的时候是基本没办法构造的，尤其是以 mr_accept 作为触发的流水线，想要在 Git 那边重新触发几乎不可能，如果因为一些外部因素，流水线运行失败了，需要人工去执行重试，因此希望可以通过重试的接口

**Comment by irwinsun** [comment]
#4225

**Comment by irwinsun** [comment]
已经实现
 v3_app_build_retry
v3_user_build_retry
