### ISSUE TITLE
gateway部署文档错误太多了

### ISSUE THREAD

**Issue by hzliu** [Tencent/bk-ci#41]
consul的binary改为766目的是啥？专门留个后门么？
rpm修改权限为755目的是啥？谁想执行这个？

**Comment by irwinsun** [comment]
权限过大是部署说明的错误。我们修正一下。
consul并不是我们提供的程序，可以自行从consul的官方网站下载。

**Comment by hzliu** [comment]
请问将consul设置为全局可写的意义是啥？
