### ISSUE TITLE
feature:多个分支ABCD触发了流水线，并且B分支触发了多次的场景，希望：ABCD之间不会互相影响，但是B触发的多次流水线仅保留最后一次。

### ISSUE THREAD

**Issue by ivanovskywang** [Tencent/bk-ci#411]
**Is your feature request related to a problem? Please describe.**
git插件监听master分支的mr，多个子分支ABCD触发了流水线，并且B分支由于反复修改触发了多次流水线B1、B2、B3。

**Describe the solution you'd like**
希望流水线ACD能够正常运行结束，而B的三条流水线，仅保留B3能够运行，B1和B2都终止运行。
**Describe alternatives you've considered**

**Additional context**

**Comment by keyihao** [comment]
+1 
希望支持某个分支的MR下多次修改触发多次流水线运行的情况下，仅保留最新一次的流水线运行，自动终止前面未完成的流水线

**Comment by iccengan** [comment]
不终止当前正在运行的构建，但会将同分支触发的构建从队列中提出。

**Comment by yhaoyan** [comment]
求加速实现
![image](https://user-images.githubusercontent.com/8141873/99255887-8b540980-284f-11eb-925d-a65b9535b1c5.png)

这个是devops很正常的一个诉求

**Comment by iccengan** [comment]
更新：需求需重新评估。CI平台做的是持续集成，原则是每次提交都需要触发构建，让业务方能关注每一次提交所产生的构建。现有这个需求主要原因是部分业务构建机资源不足，导致过多产生过多排队构建。
这个需求有个弊端，如以下场景：
甲在同分支下依次提交了a、b、c三次commit，乙在同分支下提交了d一次commit。按此需求，甲的b、c两次commit会在队列中被踢掉，保留乙提交的d commit。当b、c两次commit有问题，由于commit对应的构建被踢掉，具体问题无法直观从构建中暴露，并会将问题算在乙提交的d commit头上。违背了CI原则。

**Comment by yhaoyan** [comment]
上述举例有点问题。只涉及到了commit提交场景

流水线上如果没有问题出现，那么多次的提交，会导致大量中间资源的消耗，而且会降低整体的执行效率。
如，明明只需要最新的d，但却还得等待 b和c 的执行

另外有很多时候流水线不只是处理commit，可能是作为子流水线处理诸如某个流程，例如环境准备等，也是会存在重复执行的问题

这里的能力是个可选的，应该是一个选择项满足不同的需求会好些，并不会违背CI的情况

**Comment by iccengan** [comment]
属于git触发场景功能。
开关放在【Git事件触发】的MR Request Hook配置下。

**Comment by iccengan** [comment]
排队中被取消的构建需输出日志：
因【Git事件触发】插件中，MR Request Hook设置了【同源同目标分支触发时，只保留最新触发的构建】配置，该次构建已被新触发的任务覆盖。
