### ISSUE TITLE
feat: 蓝盾安卓app支持obb下载

### ISSUE THREAD

**Issue by JamesHuang0331** [Tencent/bk-ci#4129]
我们的安卓apk使用了obb，但是蓝盾安卓app无法直接下载obb。希望对于obb文件增加下载的按钮。

![image](https://user-images.githubusercontent.com/7420251/117462602-667c5b80-af81-11eb-827d-e9c660692e2f.png)

**Comment by iccengan** [comment]
内部需求，转tapd跟进
