### ISSUE TITLE
流水线名称目前只支持15个中英文字符，太短

### ISSUE THREAD

**Issue by linview** [Tencent/bk-ci#4131]
**What would you like to be added**:
增加流水线命名长度到32或64字符，目前只支持15个中英文字符太短了。

**Why is this needed**:
为了使流水线命名更具备可读性和可管理。一般命名流水线
为了有效管理部门的CI/CD流水线，通常我会建议采用统一风格的英文命名，如： PPG_UT_newsletters_master 
这里的命名规则是： <部门>_<类型>_<工程项目>_<分支>

这样通过流水线名称就可以很直观理解流水线的用途和范围

**Comment by irwinsun** [comment]
目前前端页面限制 是40个字符，后台限制是64个字符。
见程序：
https://github.com/Tencent/bk-ci/blame/master/src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/utils/PipelineUtils.kt#L53
