### ISSUE TITLE
希望补充读取工蜂里Merge Request的webhook里多出来的字段信息

### ISSUE THREAD

**Issue by jessehardy** [Tencent/bk-ci#4135]
在Merge Request合入时调用的webhook里，蓝盾目前读取到的信息只有源分支名和源commit id，没有带合入之后的commit id。
然而这个信息在工蜂的hook回调里是有这个信息的：
    "merge_type": "Merge",
    "merge_commit_sha": "deec3c8406923f38b3d1f01756147a3acf1aa041",
    "url": "http://xxxxxx/merge_requests/2036",
    "action": "merge",
    "extension_action": "merge"
如果把merge_type和merge_commit_sha读取到Env变量中，就能得到合入后的commit id信息

使用场景是这样：
我希望能在一条流水线里，同时拿到一次MR合入的源分支名，和合入之后的commit id
这样可以拿源分支名做一些逻辑，然后拿commit id去出包
现在不能稳定的做到，只能设置Push和MR两个hook，分别拿分支名和commit id，而且这里也有bug导致两个hook的触发顺序是不一定的。这样两次触发很容易因为连续提交导致信息对应错误。

**Comment by mingshewhe** [comment]
环境变量增加BK_REPO_GIT_WEBHOOK_MR_MERGE_TYPE和BK_REPO_GIT_WEBHOOK_MR_MERGE_TYPE属性，分别对应merge_type和merge_commit_sha变量
