### ISSUE TITLE
job depends 依赖两个任务，被依赖的其中一个任务跳过，则当前任务跳过

### ISSUE THREAD

**Issue by jerrybean** [Tencent/bk-ci#4151]
**What happened**:
有三个 job A,B,C。其中 C 依赖 A、B。
某些情况下 A 或 B 会跳过，自定义变量全部满足时才运行。
这种情况下 C 直接会被跳过。

**What you expected to happen**:
C 不被跳过，job depends 只影响流水线的 job 运行，跳过由用户控制。

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- bk-ci version (use `cat VERSION` in installed dir):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by irwinsun** [comment]
设计如此 
![Uploading image.png…]()

https://github.com/Tencent/bk-ci/issues/111#issuecomment-809865873
