### ISSUE TITLE
https访问蓝盾无法下载构件

### ISSUE THREAD

**Issue by iccengan** [Tencent/bk-ci#4165]
### 现象：
https访问蓝盾无法下载构件，需切换成http才可以

**Comment by irwinsun** [comment]
原因：后台读取的配置的域名带有指定http协议， 导致返回的report地址是http形式， 但是前端访问的却是通过https， 导致浏览器针对https站点拒绝了http的请求而无法访问
![image](https://user-images.githubusercontent.com/16686129/120615881-4f9b2d00-c48b-11eb-933a-4961886c8650.png)拼接
![image](https://user-images.githubusercontent.com/16686129/120615357-c7b52300-c48a-11eb-8eff-c1205bb14b04.png)

**Comment by irwinsun** [comment]
重复 #4796

**Comment by irwinsun** [comment]
在#4796 跟进，此处关
