### ISSUE TITLE
人工审核，自定义参数显示优化

### ISSUE THREAD

**Issue by fayewong-v5** [Tencent/bk-ci#4180]
**What would you like to be added**:
- 在描述前，增加“中文名称”字段，支持用户输入自定义变量对应的中文名，不超过20 个字（hover时仍然展示描述）
- 在进行审核界面，变量名优先展示中文名，若未配置，则展示变量的英文名

**Why is this needed**:
方便审核用户理解变量

**Comment by royalhuang** [comment]
已经发布生产，手动补关issue
