### ISSUE TITLE
【流水线插件】系统日志结构优化

### ISSUE THREAD

**Issue by fayewong-v5** [Tencent/bk-ci#4191]
**What would you like to be added**:
系统默认打印的日志，如入参、安装信息、输出等，按组汇聚，默认收起：
- 入参组名为：Input
- 安装信息组名为：Install plugin
- 输出信息组名为：Output
- group 默认折叠

其他优化：
- 如下所示的 save file 打印为 debug 日志
![image](https://user-images.githubusercontent.com/54432927/118103904-0700ce80-b40d-11eb-8753-a80f89c51535.png)
- 插件执行结束后如下所示的日志优化
![image](https://user-images.githubusercontent.com/54432927/118105398-ecc7f000-b40e-11eb-8dcb-b2854dc47b6e.png)
  - 执行成功时，不需要显示任何信息
  - 执行失败时，根据失败类型显示不同的提示信息，日志颜色为红色：
    - 失败类型为 USER，提示：Error: Process completed with exit code xxx. Please check your input or service.
    - 失败类型为 THIRD_PARTY，提示：Error: Process completed with exit code xxx.  Please contact the third-party service provider.
    - 失败类型为 PLUGIN，提示：Error: Process completed with exit code xxx. Please contact the plugin developer.
    - 失败类型为 SYSTEM，提示：Error: Process completed with exit code xxx.  Please contact DevOps-helper.
  - 执行取消时，提示：Run cancelled by xxx，日志颜色为黄色

**Why is this needed**:
方便用户快速关注执行日志

**Comment by hingbong** [comment]
`执行成功时，不需要显示任何信息`这个是连`message`都不显示吗

**Comment by hingbong** [comment]
> `执行成功时，不需要显示任何信息`这个是连`message`都不显示吗

我先按需求去掉了

**Comment by hingbong** [comment]
> 系统默认打印的日志，如入参、安装信息、输出等，按组汇聚，**`默认收起`**

这个好像是bkLog组件控制的，这边好像修改不了

**Comment by fayewong-v5** [comment]
group 默认收起功能在新issue中实现 #4833
