### ISSUE TITLE
单节点的重试按钮设计不合理，容易导致使用错误。

### ISSUE THREAD

**Issue by songpeiyan** [Tencent/bk-ci#4201]
![image](https://user-images.githubusercontent.com/16401374/118217116-67444e80-b4a7-11eb-88a4-a828a50ec798.png)
这个重试按钮很容易误导，建议增加关闭的配置方法。

场景是这样：我们在MR流水线中，因为代码有错，这里编译出错。然后，这里就出现了重试按钮。
点击重试按钮，竟然编译通过了。理论上不应该通过，因为这个MR的代码确实有错。

查了一下原因是这样：这次MR确实代码有问题，编译时出错的。点击这个重试按钮时，只会运行这个“构建replay包”一个节点，“拉取GIT（命令行）”这个节点是不会重新运行的。而流水线是所有MR共用的，所以点击重试时，该容器已经被其他MR使用了，所以，重试时编译的代码根本不是这次MR的代码。

正确的做法是，点击 stage后面的重试按钮。
但是，这个节点上的重试，还是很容易误导的，强烈建议增加可以关闭这个按钮的配置。

**Comment by irwinsun** [comment]
编译环境下依赖构建机上的工作空间，容易发生变化， 建议把编译环境下的插件重试按钮 关闭，因为确实极易出错。
而在无编译环境下可以保留重试按钮

**Comment by zanyzhao** [comment]
Duplicate of #2175
