### ISSUE TITLE
git触发器支持提交人白名单，黑名单支持*通配符

### ISSUE THREAD

**Issue by Bacra** [Tencent/bk-ci#422]
只有指定成员的提交，才触发流水钱构建

**Comment by zanyzhao** [comment]
什么人需要被排除，场景是？

**Comment by Bacra** [comment]
有一个自动编译，并ci结果的任务（接入的是其他ci系统）。任务commit的时候，使用了一个机器人账号。我们想针对这个机器人账号，在蓝盾配置一个特定的流水线任务

**Comment by zanyzhao** [comment]
还是不理解为什么这个机器账号产生的commit就要被`特殊对待`😂

**Comment by Bacra** [comment]
机器人会在处理后，将结果commit到版本库。蓝盾需要针对这次commit，触发后续的部署任务。
如果没有白名单，蓝盾会对所有人的commit执行部署任务，很浪费资源

**Comment by zanyzhao** [comment]
可以描述下你们的git工作流程，我理解为不同人设置不同的分支就可以解决

**Comment by Bacra** [comment]
开发在master对源文件修改，触发另外一个CI系统；
在CI系统中，使用固定帐号，进行编译。并将结果提交到master分支；
蓝盾捕获到这个提交之后，进行部署操作。

这个是预想的工作流，但实际上，

* 开发提交源文件修改的时候，就会触发蓝盾进行部署
* 两次提交都在master，项目本身不适合分支
* 项目源文件和编译结果目录比较多，也有交叉。路径的过滤规则也比较难实现

所以，如果能通过限制只有那个固定帐号的commit才会触发蓝盾部署操作，就最方便了

**Comment by zanyzhao** [comment]
> 在CI系统中，使用固定帐号，进行编译。并将结果提交到master分支；

编译出的产物是什么，为什么要放会代码库？

**Comment by Bacra** [comment]
这个库本身是一个公共lib，被各种服务以submodule引用。

库里面一部分文件是协议proto文件，对应的编译出产物是二进制desc文件。
proto文件开发中要看，desc文件上层服务运行需要。而proto到desc的编译，又要经过各种检查，理论上不能直接信任。

为了简化/加快上层服务的编译，desc文件就直接入库了。

**Comment by zanyzhao** [comment]
> 库里面一部分文件是协议proto文件，对应的编译出产物是二进制desc文件。

假如有一个专门用来存放desc二进制文件的制品库，我们针对这个制品库专门做个触发器，是不是也可以满足你的需求？

**Comment by irwinsun** [comment]
![Uploading image.png…]()
