### ISSUE TITLE
feat: 流水线插件新增“失败时可跳过”的选项

### ISSUE THREAD

**Issue by zanyzhao** [Tencent/bk-ci#4245]
**What would you like to be added**:
流水线插件新增“失败时可跳过”的选项
**Why is this needed**:
部分插件的失败结果已经通过第三方系统特殊处理过，希望能继续执行当前流水线流程，避免浪费

**Comment by Jimmy01010** [comment]
这个功能现在已经实现了把？
![ld](https://user-images.githubusercontent.com/47855499/119448806-68f1fa00-bd64-11eb-82c3-cba4b485793d.png)

**Comment by zanyzhao** [comment]
> 这个功能现在已经实现了把？
> ![ld](https://user-images.githubusercontent.com/47855499/119448806-68f1fa00-bd64-11eb-82c3-cba4b485793d.png)

没有，这里的“失败时继续”是自动的，而我希望增加的“失败时可跳过”是手动的，开启后，在失败的插件上会出现“跳过”按钮，由人来决定是否跳过

**Comment by zanyzhao** [comment]
本插件运行失败时：
- 自动跳过
- 手动跳过
- 自动重试
- 手动重试

**Comment by irwinsun** [comment]
此功能：
1、 存量历史的流水线默认开启手动重试（保持体验不变）、默认不开启手动跳过
2、新增流水线插件默认不开启手动重试、手动跳过
