### ISSUE TITLE
PR 显示 CI 失败，但是跳转到 tencent blueking devops 提示 404

### ISSUE THREAD

**Issue by chengweiv5** [Tencent/bk-ci#4272]
**What happened**:

提交 PR 的时候，CI 提示失败，并且详细信息页面 404

**What you expected to happen**:

希望详细页面正常，能看到详细失败信息

**How to reproduce it (as minimally and precisely as possible)**:

打开 https://github.com/Tencent/bk-ci/pull/4271

可以看到 CI 失败，点击 details，进入后，点击跳转到 tencent blueking devops 查看详细，但是跳转的页面提示 404

**Comment by irwinsun** [comment]
你好，是git commit的提交规范性问题，详细见git commit规范：
https://github.com/Tencent/bk-ci/blob/master/CONTRIBUTING.md#git%E6%8F%90%E4%BA%A4%E8%A7%84%E8%8C%83

关于这个错误是腾讯CI的持续集成流水线对提交规范检查不通过，目前还未对外公开，

> 打开 #4271
> 
> 可以看到 CI 失败，点击 details，进入后，点击跳转到 tencent blueking devops 查看详细，但是跳转的页面提示 404
![image](https://user-images.githubusercontent.com/16686129/119757080-03724a80-bed7-11eb-9e24-42daa093d362.png)

**Comment by chengweiv5** [comment]
提交之前看了这个的，所以才会增加 "docs: "，所以现在没明白要怎么操作？需要开一个 issue？commit 和 issue 关联才行吗？还是说把 "docs: " 改成 "bug: "？

**Comment by irwinsun** [comment]
docs: 这个前面的标识不是强制的
主要是commit信息 缺少关联的issue号 
![image](https://user-images.githubusercontent.com/16686129/119843949-97c1c900-bf3a-11eb-99ca-7855e0f42854.png)

该次提交没有关联到相应的issue， 所以你需要重新创建个分支， 或者reset掉你之前提交的分支的commit，重新提交commit 关联到该issue

**Comment by chengweiv5** [comment]
好的。

**Comment by chengweiv5** [comment]
PR 已更新。
