### ISSUE TITLE
feat: 日志脱敏

### ISSUE THREAD

**Issue by fayewong-v5** [Tencent/bk-ci#4273]
**What would you like to be added**:
## 需求
当流水线/YAML 中引用到凭据时，日志需脱敏，即打印到日志中的凭据内容需显示为 ******。

例如，密码类型的凭据 A，值为 12345，则此流水线日志中的 12345 显示为 ******

## 说明
- 仅处理当前流水线引用到的凭据内容
- 不针对特定插件，所有插件日志都统一脱敏

补充：
- agent上报日志遇到网络失败时自动重试
- 下载接口增加性能监控
- 下载接口的头部增加\"转义，支持文件名中包含双引号

**Why is this needed**:
脱敏，避免凭据泄露

**Comment by irwinsun** [comment]
通过对比业界实现方式，是通过对输出的字符串与密钥库中的字符串进行对比，如果匹配就会进行屏蔽。

action 输出的日志：
![image](https://user-images.githubusercontent.com/16686129/149053849-fc4d6baa-3cdd-4ce3-b569-45be44c6512b.png)

yml配置：
![image](https://user-images.githubusercontent.com/16686129/149053907-550c5f9b-cd8a-4000-845f-0c4e35408d04.png)

secrets.SIGNING_KEY 的值就是12345， 因此也将上一行的输出也进行了屏蔽（猜中密码的利器）

而当yml中没有配置使用任何secrets时，上述逻辑不会生效，12345也不会被屏蔽。

结论： 当流水线配置中有引用到secrets密钥库的，则才会启用日志脱敏功能。
