### ISSUE TITLE
流程控制支持“包含(include)”的关系

### ISSUE THREAD

**Issue by iccengan** [Tencent/bk-ci#429]
流水线里1-1添加复选框变量，当选中多于一个值时，流程控制的【自定义变量全部满足时执行】满足其一条件也无法生效。
![image](https://user-images.githubusercontent.com/10875468/71499840-589ecc80-289d-11ea-98e2-2ea0e718028d.png)
![image](https://user-images.githubusercontent.com/10875468/71499866-710ee700-289d-11ea-8045-c98ef338c25d.png)

**Comment by lsj9383** [comment]
提供给蓝盾官方的优化建议：

对于复选框这样的场景，可以考虑针对复选框里面的数据自动生成变量，且选中的值为1，未选中的值为0.

例如：
复选框自定义变量名:  key
支持的值为: op1, op2, op3
选择了op1 和 op3
则蓝盾创建了以下值:
key: op1,op3
key_op1: 1
key_op2: 0
key_op3: 1

**Comment by lsj9383** [comment]
目前我个人用了一个bash插件来专门处理这样的情况，会对复选框生成我所需要的流水线变量。

例如针对上述案例，下述代码可以作为参考：

function apply_pipline_checkbox_vars() {
    prefix=$1
    string=$2
    array=${string//,/ }
    for var in ${array[@]}
    do  
        setEnv "${prefix}${var}" 1
    done
}

apply_pipline_checkbox_vars "key_" ${key}

**Comment by iccengan** [comment]
Duplicate of #1747
