### ISSUE TITLE
bug: 插件切换版本时部分表单不应该变

### ISSUE THREAD

**Issue by zanyzhao** [Tencent/bk-ci#4304]
**What happened**:
切换插件版本时部分字段被重置，比如：
- 插件别名
- 流程控制选项
**What you expected to happen**:
不是task.json里定义的字段不应该被重置

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- bk-ci version (use `cat VERSION` in installed dir): 1.5.0
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by zhenlinyang** [comment]
Let me urge this bug, it has not been fixed for more than a year.
