### ISSUE TITLE
feat: 规范化Pipeline/Stage/Job/Task的构建状态

### ISSUE THREAD

**Issue by irwinsun** [Tencent/bk-ci#4315]
当前BuildStatus中状态比较多，但有缺少对Pipeline、Stage、Job、Task级别清晰的界限，导致可能存在混用的可能。
## Pipeline 状态
<google-sheets-html-origin>

KEY | Description | Display Name
-- | -- | --
QUEUE | 初始状态：队列中等待调度，在准备执行前会切换为QUEUE_CACHE | 队列中
QUEUE_CACHE | 中间状态：进入执行队列，可以启动 | 待执行
RUNNING | 中间状态：运行中 | 运行中
CANCELED | 最终态：取消 | 取消
STAGE_SUCCESS | 最终态： 当Stage人工审核 取消运行时，是一个成功的状态 | 阶段性完成 （成功）
SUCCEED | 最终态：成功 | 成功
FAILED | 最终态：失败 | 失败
TERMINATE | 最终态： 处于RUNNING状态的Pipeline因环境异常而被强制终止 | 终止 （失败）
QUEUE_TIMEOUT | 最终态：队列中等待调度导致的超时 | 排队超时

</google-sheets-html-origin>

## Stage 状态
<google-sheets-html-origin>

KEY | Description | Display Name
-- | -- | --
QUEUE | 初始状态：队列中等待调度，在准备执行前会切换为QUEUE_CACHE | 队列中
QUEUE_CACHE | 中间状态：进入执行队列，可以启动 | 待执行
RUNNING | 中间状态：运行中 | 运行中
REVIEWING | 中间状态：stage处于 人工审核中 | 审核中
PAUSE | 中间状态：当Stage人工审核 等待审核时 | 暂停执行
CANCELED | 最终态：取消 | 取消
SUCCEED | 最终态：成功 | 成功
FAILED | 最终态：失败 | 失败
TERMINATE | 最终态： 处于RUNNING状态的Stage因环境异常而被强制终止 | 终止 （失败）
SKIP | 最终态：跳过不执行 | 跳过
UNEXEC | 最终态：从未执行，可能构建失败导致的结束，后面未执行 | 从未执行（不参与最终成功/失败状态运算）
QUEUE_TIMEOUT | 最终态：队列中等待调度导致的超时 | 排队超时
STAGE_SUCCESS | 最终态： 当Stage人工审核 取消运行时，是一个成功的状态 | 阶段性完成 （成功）

</google-sheets-html-origin>

## Job状态

<google-sheets-html-origin>

KEY | Description | Display Name
-- | -- | --
QUEUE | 初始状态：队列中等待调度，在准备执行前会切换为QUEUE_CACHE | 队列中
QUEUE_CACHE | 中间状态：进入执行队列，可以启动 | 待执行
LOOP_WAITING | 中间状态：轮循等待中 互斥组抢锁轮循 |  互斥锁轮循等待中
DEPENDENT_WAITING | 中间状态：等待依赖的job完成才会进入准备环境 |  依赖等待
PREPARE_ENV | 中间状态：准备环境中，构建机正在启动 | 准备环境中
RUNNING | 中间状态：运行中 | 运行中
PAUSE | 中间状态：插件暂停执行时，会将Job的状态也设置为暂停 |  暂停执行
CANCELED | 最终态：取消 | 取消
SUCCEED | 最终态：成功 | 成功
FAILED | 最终态：失败 | 失败
TERMINATE | 最终态： 处于RUNNING状态的JOB因环境异常而被强制终止 | 终止 （失败）
SKIP | 最终态：跳过不执行 | 跳过
UNEXEC | 最终态：从未执行，可能构建失败导致的结束，后面未执行 | 从未执行（不参与最终成功/失败状态运算）
QUEUE_TIMEOUT | 最终态：队列中等待调度导致的超时 | 排队超时
HEARTBEAT_TIMEOUT | 最终态：构建过程中，Agent与服务端失联超过2分钟 | 心跳超时（失败）

</google-sheets-html-origin>

## Task状态

<google-sheets-html-origin>

KEY | Description | Display Name
-- | -- | --
QUEUE | 初始状态：队列中等待调度，在准备执行前会切换为QUEUE_CACHE | 队列中
QUEUE_CACHE | 中间状态：进入执行队列，可以启动 | 待执行
RETRY | 中间状态：设置了失败重试，进入执行队列 | 待重试
RUNNING | 中间状态：运行中 | 运行中
CALL_WAITING | 中间状态：用于启动构建环境插件等待构建机回调启动结果| 等待构建机回调 （运行中）
REVIEWING |  中间状态：人工审核插件或质量红线配置了人工审核  并处于待审核 |  待审核（运行中）
PAUSE | 中间状态：插件设置了暂停执行 | 暂停执行
REVIEW_ABORT | 最终态：人工审核插件或质量红线配置了人工审核 并点了驳回/终止 |  人工审核驳回（失败）
REVIEW_PROCESSED | 最终态：人工审核插件或质量红线配置了人工审核 并点了通过 |  人工审核通过（成功）
CANCELED | 最终态：取消 | 取消
SUCCEED | 最终态：成功 | 成功
FAILED | 最终态：失败 | 失败
TERMINATE | 最终态： 处于RUNNING状态的插件因环境异常而被强制终止 | 终止 （失败）
SKIP | 最终态：跳过不执行 | 跳过
EXEC_TIMEOUT | 最终态：执行时间超过配置的超时时间 | 执行超时（失败）
UNEXEC | 最终态：从未执行，可能构建失败导致的结束，后面未执行 | 从未执行（不参与最终成功/失败状态运算）
QUEUE_TIMEOUT | 最终态：队列中等待调度导致的超时 | 排队超时
QUALITY_CHECK_FAIL | 最终态：被质量红线拦截后直接失败（未设置人工审核） |  被质量红线拦截（失败）

</google-sheets-html-origin>

**Comment by zanyzhao** [comment]
信息已收集到官网：https://docs.bkci.net/services/pipelines/pipeline-build-detail/status
