### ISSUE TITLE
对很久以前的历史构建进行备注修改时，页面会卡住很久。且期望修改完成后不刷新整个页面。

### ISSUE THREAD

**Issue by iccengan** [Tencent/bk-ci#4324]
### 现象：
该流水线有500+次构建，对很久之前的历史构建进行备注修改时，整个页面会卡住很久。
![image](https://user-images.githubusercontent.com/10875468/120621916-ee765800-c490-11eb-8600-26ff70e7948d.png)

当完成修改并确定后，整个页面会刷新。需要重新往下拉到刚完成修改的构建记录。
![image](https://user-images.githubusercontent.com/10875468/120621902-ea4a3a80-c490-11eb-9584-dd2ec8c3111e.png)

**Comment by irwinsun** [comment]
![image](https://user-images.githubusercontent.com/16686129/129658663-7b34c435-ad3c-4a5d-bfd3-a1438bee53fe.png输入都会卡
