### ISSUE TITLE
选择插件界面，当插件不适用于当前job时，增加hover提示

### ISSUE THREAD

**Issue by fayewong-v5** [Tencent/bk-ci#4379]
**What would you like to be added**:
当插件不适用于当前job时，hover提示：当前插件适用于LInux/Windows/macOS/无编译环境JOB，请在对应JOB下使用。
![image](https://user-images.githubusercontent.com/54432927/121290807-d2a00580-c919-11eb-88e2-7604e1240fc3.png)

当无权限安装插件时，hover提示：
![image](https://user-images.githubusercontent.com/54432927/126443836-6a5240f5-438a-4ac3-af0c-3b7742a9aba0.png)

**Why is this needed**:

**Comment by iccengan** [comment]
Duplicate of #1268
