### ISSUE TITLE
研发商店增加配置文件插件？

### ISSUE THREAD

**Issue by MikeoPerfect** [Tencent/bk-ci#44]
不知道现在有没有直接在构建流程中，拉取对应的配置文件，如果是测试的就拉取测试配置，如果是正式的就拉取正式配置，做到全局统一管理？

**Comment by irwinsun** [comment]
没太明白你说的是？ 从你的描述上来说，你说的这些配置其实是跟你插件在运行时有关的，应该由插件本身解决。 流水线是不知道你运行的是测试还是生产。可以通过流水线变量传递到你的插件中自主决定
