### ISSUE TITLE
跨项目归档文件拉取功能

### ISSUE THREAD

**Issue by taohuifa** [Tencent/bk-ci#4484]
希望支持跨项目归档文件的拉取, 不要跨项目归档构件的推送(我知道有, 不好用)

**Comment by irwinsun** [comment]
推送与拉取在同一个操作人眼里其实是一样的， 但对于团队项目来讲，推送和拉取是不一样的。

假设有 团队项目P1， 与个人项目P2

从P2 来看，P2他想拉取P1的制品，直接在P2项目中配置一条流水线拉，用起来很爽。
但对于P1的团队管理者来说，他不知道P2（或者是其他人）在另外一个项目下拉取了什么制品。特别是在一些特别大的项目下，从这一点来看，拉取是存在泄密风险的。
