### ISSUE TITLE
【拉取git插件】pre-merge选项不应对MR Accept事件生效

### ISSUE THREAD

**Issue by iccengan** [Tencent/bk-ci#4485]
### 为什么做：
MR Accept事件触发流水线，此时代码已完成合并。【拉取git】插件拉下来的代码已经是合并过后的代码，没有必要再合并。pre-merge应只对 MR事件生效。
目前逻辑，当用户在代码库设置了合并代码后删除源分支。执行【拉取git】插件会因找不到源分支而报错。

**Comment by mingshewhe** [comment]
插件已修复
