### ISSUE TITLE
MR来源支持排除规则

### ISSUE THREAD

**Issue by ErWeiWang** [Tencent/bk-ci#449]
# MR hook触发时，支持排除该hook的源分支，以支持实现不同源分支发起MR执行不同的流水线线
## git 触发器，mr事件中增加排除指定命名规则的 ${hookSourceBranch}

**Comment by irwinsun** [comment]
@zanyzhao

**Comment by ErWeiWang** [comment]
@@where@@

**Comment by ErWeiWang** [comment]
@@where@@

**Comment by ljw7630** [comment]
很正常的场景：
比如的分支是由某些自动化工具发起的（比如定时生成changelog，定时打tag，这个时候去触发MR完整执行一遍是不合理的。更要命的是，这些工具执行完之后往往会删除来源分支，就会导致流水线执行失败）

另外一个场景是：我修改了一些文档。 但是又不想触发流水线。那我如果分支名字叫做 doc/xxx 的时候， 就别给我执行这个流水线了

**Comment by zanyzhao** [comment]
![image](https://user-images.githubusercontent.com/1629409/81421690-6e45cc00-9184-11ea-9cfa-445f06a7938d.png)
如果只是文档场景（文档在统一的目录下），用`排除以下路径`不就够了？

**Comment by ljw7630** [comment]
> 如果只是文档场景（文档在统一的目录下），用`排除以下路径`不就够了？

我觉得。其实只要思考：“遵循某些命名规范的branch是否允许跳过MR触发执行” 这个诉求是不是合理的就行了。

你提的这个，我也很容易找到反例：如果我的仓库，有很多各种各样的纯文本格式，如 .md, .txt, .csv, .tex  分布在仓库的各个地方，没法穷举 ，又怎么办呢
