### ISSUE TITLE
流水线构建页面插件能力

### ISSUE THREAD

**Issue by jerrybean** [Tencent/bk-ci#4515]
**What would you like to be added**:
流水线构建执行的页面支持插件能力，允许业务自定义一些区块进行展示。
**Why is this needed**:
蓝盾提供了丰富的API，我们可以基于这些API构建自己的工具，但是工具没有流水线执行页面直观。
比如我们希望流水线的构建页面发布的代码库地址、最新提交人信息。也希望在构建页面能看到常见插件报错的解决办法。也希望展示当前流水线使用的模板以及是否模板的最新版本。这些蓝盾的API已经有了这些功能，希望能够蓝盾构建页面支持插件，由业务方提供对应的插件，这些插件的执行只需要当前流水线的信息及当前用户的用户态接口token即可。

**Comment by zanyzhao** [comment]
已经有了，我们叫它“微扩展”
