### ISSUE TITLE
Job超时时间可以小于原子超时时间

### ISSUE THREAD

**Issue by a351399739** [Tencent/bk-ci#4527]
用户在修改流水线原子执行超时时候，比如A原子设置0，但是job设置了900，导致job已经查耗时失败了，A原子的超时设置无效，导致任务执行失败，这种是否可以在用户修改原子的时候加校验
![image](https://user-images.githubusercontent.com/23499622/123569996-f7411c00-d7f9-11eb-8d2e-fd196fbedd4c.png)
![image](https://user-images.githubusercontent.com/23499622/123570004-fad4a300-d7f9-11eb-8fa5-0cdae1db1082.png)

**Comment by irwinsun** [comment]
理论上来讲这个是合理的，
但相信我，加上这个校验后，如果的插件过多之后，各个插件耗时累计，操作者会疯掉的。
比如一个Job有10个插件， Job的插件为900分钟， 那么这10个插件的时间加起来不能超过900分钟， 如何合理分配对于操作者是一个考验， 比如某些插件可能是动态允许在一定时间范围内的，不一定局限在10分钟内失败。

当然你提议的只是校验一下单个插件超时不能超过Job的超时时间，但这个并不是一个好的解决办法 ，如果实在对超时非常敏感，还是需要花点心思去自行规划，这里就宽松点不做校验了。
