### ISSUE TITLE
bug: 跨脚本环境变量内容丢失换行符

### ISSUE THREAD

**Issue by nnns1989** [Tencent/bk-ci#4537]
![image](https://user-images.githubusercontent.com/16128865/123610364-1ad48880-d833-11eb-8b4a-1416b2dc9981.png)
上一个bash中通过setEnv设置了环境变量，其中包含换行，在同bash中打印变量正常
下一个bash中，echo打印环境变量，发现换行符全部变为空格

**Comment by iccengan** [comment]
setEnv 目前不支持换行符。详见：#1056

**Comment by irwinsun** [comment]
setEnv有大量的历史使用背景，无法再继续迭代兼容，请用最新的方式来拿来操作。

# 通过::set-variable命令字设置/修改全局变量(当前步骤不生效)
# echo "::set-variable name=var_name::var_value"
# 在后续的插件表单中使用${{variables.var_name}}引用这个变量

# 通过::set-output命令字设置当前步骤的输出(当前步骤不生效)
# echo "::set-output name=output_name::output_value"
# 在后续的插件表单中使用${{jobs.<job_id>.steps.<step_id>.outputs.output_name}}引用这个输出，其中job_id和step_id在对应的Job和Task上配置
