### ISSUE TITLE
流水线通知markdown格式标签不转义引号时，消息内容会被截断

### ISSUE THREAD

**Issue by iccengan** [Tencent/bk-ci#4543]
### 现象：
配置：
![image](https://user-images.githubusercontent.com/10875468/123637203-53cf2600-d850-11eb-9237-312a8e10954c.png)
消息通知被截断：
![image](https://user-images.githubusercontent.com/10875468/123637314-73fee500-d850-11eb-8cfb-9ac5db7d5b9a.png)

当给`<font color="red">我是红色</font>`的引号加上转义符时：`<font color=\"red\">我是红色</font>`，消息能正常发送：
![image](https://user-images.githubusercontent.com/10875468/123637491-a9a3ce00-d850-11eb-9d5d-1b51bb2758fb.png)

**Comment by yongyiduan** [comment]
ext中已解决引号截断问题
