### ISSUE TITLE
流水线执行历史添加备注的权限问题

### ISSUE THREAD

**Issue by FeeAlan** [Tencent/bk-ci#455]
现象：无法添加备注
原因：没有开通项目的编辑权限

建议：执行历史添加备注只是一个很常规的操作，但是需要的权限级别较高，和修改整个项目的配置是同一个权限。由于项目负责人配置好相关设置后不想其他组内同事修改，防止出现问题，所以一般不会给编辑权限，但是执行历史又需要添加备注，这里麻烦调整下添加备注的权限级别，或者去掉添加备注需要的权限。

**Comment by irwinsun** [comment]
备注其实也是非常 重要的，不希望都能修改，特别是在流水线已经跑完了，如果一个只有查看权限的人随意对流水线历史备注进行修改，那可能跟会产生一些误会。

如果有添加备注的需求，可以通过在流水线运行中使用
setEnv "BK_CI_BUILD_REMARK"  "你想要的备注"
设置备注

**Comment by irwinsun** [comment]
原权限为“编辑”
修改为“执行”
