### ISSUE TITLE
支持跨项目引用构建机集群（环境）

### ISSUE THREAD

**Issue by fayewong-v5** [Tencent/bk-ci#4582]
**What would you like to be added**:
构建机支持跨项目引用：
- 环境上可以设置允许哪些项目使用
  - 允许分享的项目个数上限为：100
- 设置后，开通权限的项目可以选到对应环境
- 流水线执行时，agent 和项目解绑，允许多个项目共用

页面交互：
1、环境管理页面，增加设置tag，管理共享环境的项目
![image](https://user-images.githubusercontent.com/54432927/159243730-29139d73-06cf-4cdc-a7a8-5a4fd2b3d988.png)
- 当前项目默认可用，不可移除
- 可以添加项目
- 已添加的项目分页展示
- 当前项目的操作人、操作时间 为 环境的最近修改人、最近修改时间
2、添加项目
![image](https://user-images.githubusercontent.com/54432927/159243970-de3a306f-961b-4d35-b70f-afc975669200.png)
- 弹出框添加
- 项目列表中，已添加的项目灰掉不需要重复添加
3、流水线选择环境界面
![image](https://user-images.githubusercontent.com/54432927/159833562-f231edd3-03f8-4558-9471-409d05211e30.png)
- 增加查看入口，点击跳转到对应的环境
- 非当前项目下的环境，展示来源和分享人
4、按环境别名输入环境界面
![image](https://user-images.githubusercontent.com/54432927/159833599-c3e65746-c83b-4f09-a9eb-ab985e4688ca.png)
- 支持输入项目，可以使用变量占位。非必填，不填则默认为当前项目
- 后端需校验用户输入的项目下的环境是否允许使用

**Why is this needed**:
可以跨项目使用构建机，减少重复导入构建机的工作量

**Comment by irwinsun** [comment]
注意：该功能仅能减少构建机导入次数，减少构建Agent进程数量， 并不能提升构建机的并发性能，因为这个构建机自身硬件限制的。
