### ISSUE TITLE
【BUG】主流水线调用子流水线时，主流水线被终止时，子终止线不会自动终止

### ISSUE THREAD

**Issue by shandianling** [Tencent/bk-ci#459]
当A流水线调用B子流水线时，如果用户终止了A流水线，但子流水线，并不会自动终止。
使用“子流水线调用”插件如下：
![image](https://user-images.githubusercontent.com/3283999/71612624-991f8280-2bdc-11ea-9572-798c51851028.png)

**Comment by irwinsun** [comment]
问题是存在的，感谢反馈。

新插件上这个是一个遗漏点， 暂时通过插件市场来修改，
github这里先针对原内置的插件进行修复

**Comment by irwinsun** [comment]
研发商店中发的子流水线新插件无法终止问题已经修复
