### ISSUE TITLE
feat: 插件系统使用"私有配置"渲染自定义前端占位符

### ISSUE THREAD

**Issue by vuuv** [Tencent/bk-ci#4598]
**What would you like to be added**:
1. 插件"私有配置"应该引入变量用途字段, 默认为"插件后端使用", 保持前向兼容性, 新增"自定义前端"类型, 用于定向渲染前端页面.
2. 在每次变更"私有配置"时, 保存后, 应当在新打开插件配置界面时生效.
3. 可选: 插件测试阶段能快速修改"私有配置".
4. 可选: 自定义前端的渲染占位符及默认值. 可以事先在task.json声明.

**Why is this needed**:
目前插件的私有配置仅适用于插件后端代码, 在插件运行时可用.
CodeCC域名可配置, 因此需要插件系统能支持自定义前端的"私有配置"渲染.

**Comment by vuuv** [comment]
需求起源: #4526

**Comment by vuuv** [comment]
初步讨论:
1. 后端store: 新增api提供自定义配置前端框架使用. 应该引入用途字段区分, 仅当配置为供前端使用的配置才能暴露.
2. 前端框架: 提供传递"私有配置"的机制. 从后端store api获取用户配置的"私有配置", 并传递到插件自定义前端. 
3. 插件: 改造自定义前端网页, 根据新规范获取所需的"私有配置" key.

**Comment by fayewong-v5** [comment]
#4600 中完成
