### ISSUE TITLE
流水线发布体验插件不支持设置版本描述

### ISSUE THREAD

**Issue by aaron-go** [Tencent/bk-ci#460]
发布体验通常都要写更新内容的，流水线的发布体验插件不支持，发布后还需要到体验里再修改，不是很方便，希望可以支持。

**Comment by irwinsun** [comment]
版本体验插件与内部系统交互，该需求在插件库中开发，暂未在github上开源，目前已经安排插件开发实现

**Comment by freyzheng** [comment]
转达内部版本实现
