### ISSUE TITLE
流水线在第三方构建机上支持并发构建

### ISSUE THREAD

**Issue by zanyzhao** [Tencent/bk-ci#463]
如题

**Comment by eternalsea** [comment]
同个流水线在第三方构建集群中的单个构建机应该也要一起考虑支持并发构建

**Comment by irwinsun** [comment]
构建机上agent本身是支持并发的，是否支持并发理应由业务决定。
一般会在工作空间上的资源（文件）互斥的问题导致无法并发，或者并发会因为资源互斥的问题而无法并发，这里面的细节是业务层面要解决的问题， 
如果由平台来处理将会是采用工作空间复制来解决这个问题，但可能带来另外的问题：
占用构建机额外的空间。

**Comment by zanyzhao** [comment]
如果用户不指定WORKSPACE时，我们应该支持并发构建场景

**Comment by irwinsun** [comment]
> 如果用户不指定WORKSPACE时，我们应该支持并发构建场景

目前绝大部分用户默认已经不指定WORKSPACE，使用默认值，所以把这个当成一个自动开启并发构建的条件，需要考虑对当前存量用户会造成影响。

**Comment by kingzjw** [comment]
单条条流水的多次触发虽然可以用私人集群来支持，但是在构建机有多条流水线在工作时候的，在设置并发数大于2情况下，可能是会出现问题的
