### ISSUE TITLE
 快捷启动流水线的提议

### ISSUE THREAD

**Issue by zlvb** [Tencent/bk-ci#4672]
例如我有一个流水线P1，有ABC三个启动参数，这三个参数较为复杂，但大多数情况下ABC为固定的几个值

此时，我新建了流水线P2、P3、P4，它们的功能是将P1作为子流水线调用，并且自动选择相应的参数，而P2、P3、P4本身是不可填写参数的

那么我希望，当我点击P2启动按钮时，立即启动构建，而不是跳转到参数选择界面，例如：

点这个
<img width="269" alt="企业微信截图_16262313487760" src="https://user-images.githubusercontent.com/1246583/125555869-b299a86e-9ab6-4e7c-a9a9-67a43c42765b.png">
出现这个
<img width="261" alt="企业微信截图_16262314065094" src="https://user-images.githubusercontent.com/1246583/125555874-b176e126-af70-4c38-9e3f-4ad9579f7157.png">
而不是出现这个
<img width="970" alt="企业微信截图_20210714105746" src="https://user-images.githubusercontent.com/1246583/125555878-a336cb7d-8430-4f8f-a068-000bb5c5f785.png">
让我再点击一次执行。我并没有参数需要填写，我也禁止了跳过任何步骤，这个界面的跳转并且重复点击执行，是多余的

**Comment by iccengan** [comment]
点击执行后打开流水线执行预览页面有两个目的：
1. 期望引导用户填入构建信息，给每次构建赋予构建目的。目前构建号是无法协助用户定位目标构建的。好比提交代码，每次commit是需要commit msg的，相对的持续集成也是需要build msg的。
2. 之前点击直接触发流水线属于设计缺陷，每次构建我们是期望引导用户检查流水线的执行编排的。
