### ISSUE TITLE
插件若配置了*.latest，当失败重试时，应该以*下最新的版本执行

### ISSUE THREAD

**Issue by fayewong-v5** [Tencent/bk-ci#4675]
**What would you like to be added**:
- 插件若配置了*.latest，当失败重试时，应该以*下最新的版本执行
- 快照页面，版本展示配置+实际使用的版本，如 1.latest（1.1.7）

**Why is this needed**:
当插件问题导致的失败时，在插件fix后，可以通过重试继续执行

**Comment by irwinsun** [comment]
怎么实现都有理
- 我想重试就按之前执行的版本重试，不希望被新版本带来潜在的影响（缺少新版所必须的参数等等）
- 我想重试是因为插件当前版本出问题，出个新版本重试解决这个问题。

**Comment by deepjia** [comment]
> 怎么实现都有理
> 
> * 我想重试就按之前执行的版本重试，不希望被新版本带来潜在的影响（缺少新版所必须的参数等等）
> * 我想重试是因为插件当前版本出问题，出个新版本重试解决这个问题。

关于「缺少新版所必须的参数等等」，私以为：
1、从插件角度，按规范的话，主版本号不变的情况下，插件应保持兼容性
2、从用户角度，*.latest本身代表用户未指定次版本号和修订号，或者说指定始终使用特定主版本号下的最新版本

**Comment by irwinsun** [comment]
> > 怎么实现都有理
> > 
> > * 我想重试就按之前执行的版本重试，不希望被新版本带来潜在的影响（缺少新版所必须的参数等等）
> > * 我想重试是因为插件当前版本出问题，出个新版本重试解决这个问题。
> 
> 关于「缺少新版所必须的参数等等」，私以为： 1、从插件角度，按规范的话，主版本号不变的情况下，插件应保持兼容性 2、从用户角度，*.latest本身代表用户未指定次版本号和修订号，或者说指定始终使用特定主版本号下的最新版本

从我个人角度是完整同意你的观点，这类问题导致是插件本身的兼容性做得不够好。

 插件开发规范上已经指明了，插件开发者对于兼容版本是有义务保证兼容性[上架/升级插件版本号要求](https://docs.bkci.net/store/plugins/upload-plugin#tian-xie-cha-jian-xiang-guan-xin-xi-shang-chuan-cha-jian-fa-bu-bao)
<img width="958" alt="image" src="https://user-images.githubusercontent.com/16686129/162117907-684c6cef-7d4f-477a-be74-4bccdd9be711.png">


但回过头来想，用户希望在第一次跑的时候是什么版本，重试的时候也以当时的版本来运行，本身也是合理。 但换另一个角度来看，用户重试时，可能是希望用新的插件修正版本来解决失败的问题，因为可能当前的插件版本本身存在问题导致无论 怎么重试都无法解决问题。

所以才说怎么实现都有理，但怎么实现也都会有问题无法调解，这也是这个issue一直保持现状没有做改变。
