### ISSUE TITLE
通过变量修改“推荐版本号”

### ISSUE THREAD

**Issue by sunhr** [Tencent/bk-ci#469]
因为蓝盾不支持像`RDM`那种多条流水线共享同一个自增`BuildNo`，所以我们采用其他方式自己实现了类似功能，在原子中通过脚本自行修改了`BuildNo`，但是修改之后“推荐版本号”并没有随之变化，希望可以加入这个功能

**Comment by irwinsun** [comment]
目前BuildNo的逻辑限制只能通过界面设置了3种策略 锁定，每次+1， 成功时才+1
![image](https://user-images.githubusercontent.com/16686129/71662178-87301200-2d8b-11ea-9433-912a1155e7ef.png)

初期考虑用户自行设置可能会带来混乱的风险

**Comment by irwinsun** [comment]
@zanyzhao  考虑下这个功能是否放开

**Comment by zanyzhao** [comment]
多条流水线共享同一个自增BuildNo会有问题吧，比如并发时有可能设置相同的BuildNo @sunhr

**Comment by sunhr** [comment]
@zanyzhao 之前的经验来看`RDM`的共享自增`BuildNo`没有出现过并发的问题，在蓝盾上，我们通过在流水线中访问自己的`redis`读取并自增`BuildNo`，因为做了加锁处理，也没有并发问题。

目前的痛点是，我们自己在某个原子中修改了`BuildNo`后，这个修改没有同步反馈到执行历史页的`推荐版本号`，我们的测试同学在列表页中查找某个版本号的安装包很困难，所以希望可以在流水线结束的时候更新一下`推荐版本号`。

**Comment by JiangJie** [comment]
我们的做法是将build version写入svn，同时保证多条流水线相同任务的时候排队来规避并发问题，不过确实没办法显示在app版本号或者推荐版本号一列，希望能支持。比如构建过程中写入一个特定的文件或者设置一个特定的变量，然后蓝盾读取之后展示出来。

**Comment by zanyzhao** [comment]
BuildNo的设置是在启动的时候由执行人指定，就一定会出现这种问题，我们内置了另一个变量叫BK_CI_BUILD_NUM，再结合 #635 这个特性，应该可以替换掉推荐版本号功能了。

**Comment by JiangJie** [comment]
> BuildNo的设置是在启动的时候由执行人指定，就一定会出现这种问题，我们内置了另一个变量叫BK_CI_BUILD_NUM，再结合 #635 这个特性，应该可以替换掉推荐版本号功能了。

BK_CI_BUILD_NUM不就是第一列的构建号吗，构建过程能改？

**Comment by iccengan** [comment]
利用自增型流水线变量解决。
