### ISSUE TITLE
MacOS Linux选择完第三方节点保存后就变成按节点别名 构建失败

### ISSUE THREAD

**Issue by Njf851165278** [Tencent/bk-ci#475]
![企业微信截图_15779588124327](https://user-images.githubusercontent.com/52986252/71661344-e2143a00-2d88-11ea-9576-b5a6f54d8503.png)
![企业微信截图_15779568414792](https://user-images.githubusercontent.com/52986252/71661345-e2143a00-2d88-11ea-8bb5-bd9146dc339e.png)
![企业微信截图_15779568633653](https://user-images.githubusercontent.com/52986252/71661346-e2acd080-2d88-11ea-803d-03410965a712.png)
![企业微信截图_15779581984770](https://user-images.githubusercontent.com/52986252/71661347-e2acd080-2d88-11ea-834b-1360753e45ab.png)

**Comment by irwinsun** [comment]
问题出在：
1. 在新增Job时，选择了构建机之后保存点执行
问题不会出现在:
1. 对已经问题的Job进行修改后，不会再复现 

@Roy9102

**Comment by fayewong-v5** [comment]
已修复
