### ISSUE TITLE
设置流水线备注信息，空格会被截断

### ISSUE THREAD

**Issue by zhengxiaoxu** [Tencent/bk-ci#4783]
**What happened**:
设置流水线备注信息时，空格会被截断，如下，【版本】二字不见了

1. 流水线启动，填写备注信息
![image](https://user-images.githubusercontent.com/2034218/126961781-bb553802-149c-48ef-adbe-c758388980af.png)

2. 在节点中设置备注信息为第一步中的值
setEnv "BK_CI_BUILD_REMARK" ${Remark}

3. 构建完成，备注栏只有 Xcode11
![image](https://user-images.githubusercontent.com/2034218/126961858-f9d506cd-74c7-41c9-a234-78e8ab1d20f1.png)

**What you expected to happen**:
空格不截断

**How to reproduce it (as minimally and precisely as possible)**:
please refer to above

**Anything else we need to know?**:
n/a

**Environment**:
- bk-ci version (use `cat VERSION` in installed dir):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by irwinsun** [comment]
setEnv "BK_CI_BUILD_REMARK" "${Remark}"

这样，空格被截断是因为没有用双引号保护， shell的语法你懂的，空格会被当成另外的参数

@zhengxiaoxu

**Comment by zhengxiaoxu** [comment]
> setEnv "BK_CI_BUILD_REMARK" "${Remark}"
> 
> 这样，空格被截断是因为没有用双引号保护， shell的语法空格间的内容会被当成多个参数
> 
> @zhengxiaoxu

收到，这里我按上述方式处理。已经不截断了，感谢！
