### ISSUE TITLE
如何删除回收站中的流水线工程

### ISSUE THREAD

**Issue by hujingguang** [Tencent/bk-ci#4841]
如何清空回收站中的流水线，导致无法删除模版

**Comment by irwinsun** [comment]
不需要清空回收站也可以删除模板，
模板只要保证当前的流水线实例化数量为0，即可删除

**Comment by hujingguang** [comment]
> 不需要清空回收站也可以删除模板，
> 模板只要保证当前的流水线实例化数量为0，即可删除

之前的模版已经关联了一个流水线，现在因为无法删除这个流水线导致无法删除模版。

**Comment by irwinsun** [comment]
这个bug已经在v1.7版本修复, 目前是否还有？
