### ISSUE TITLE
Large amount of log files overflows the hard disk space

### ISSUE THREAD

**Issue by juvenalluo** [Tencent/bk-ci#488]
One of our Windows build machine suddenly had a large amount of log files on some day. They are located at <top>/agent/logs folder, filename is "agent-2019-12-27-<num>". Each file is 102 MB+, the system seems to generate one per second. When the free hard disk becomes so small, the pipeline git fetch would fail. Please investigate. Thanks!.

**Comment by irwinsun** [comment]
hi, @juvenalluo 

在这里给您使用上的小建议： 请不要将构建机安装在您的数据盘，避免和数据盘抢空间，让您的构建数据也更安全。

每个用户的构建机的空间不一样，构建产生的日志量不一样，现有机器配置都比较高，现有占用10GB是比较合理的，较小会导致出现问题时因为日志被过早清理而无法排查. 

当前逻辑：
当前每个压缩日志文件最多100MB，可能会多一点，视构建日志量决定，无法100%精确。
每个 agent-xxxx.log.gz 文件最多保留30天。
当所有agent-xxxx.log.gz 文件总和超过10GB， 则会自动清理掉最旧的文件。
基于此我们考虑将清理日志逻辑放到devopsDaem(golang)中后台定时处理，并提供配置项让用户自己自己去修改占用大。
