### ISSUE TITLE
支持Stage/Job/Task粒度的循环操作

### ISSUE THREAD

**Issue by imagebreaker** [Tencent/bk-ci#489]
**希望支持Stage/Job/Task粒度的循环操作**

在某些场景下, 譬如: 使用代码检查工具检查项目个分支时, 需要对每个分支执行检出, 构建操作. 流水线不支持循环, 则无法达到目的.

希望对流水线中部件的流程控制上增加循环功能.

**Comment by irwinsun** [comment]
@zanyzhao

**Comment by zanyzhao** [comment]
已排期插件的重试功能 #548 

Job/Stage重试有较大的风险，暂时不予支持
