### ISSUE TITLE
人工审核插件支持超时继续执行流水线

### ISSUE THREAD

**Issue by jerrybean** [Tencent/bk-ci#4899]
部分流水线非关键路径步骤，我们希望人工审核来检查流水线是否继续执行。
目前设置了超时时间和失败时继续，但是超时后没法继续。
希望超时后继续执行流水线。

**Comment by fayewong-v5** [comment]
人工审核用于不能自动化执行，需要人手动干预的场景，这种情况需要审核人明确确认OK，才能执行后续步骤。超时继续执行和人工审核的初衷的相悖的。

题主描述的场景，是否可以明确下规范，"非关键路径"在哪些场景下必须要执行，哪些场景下不需要，有了规范之后，按照入参来控制，或者不同场景使用不同流水线
