### ISSUE TITLE
增加sdk支持从环境名称获取机器的ip列表

### ISSUE THREAD

**Issue by linyapppp** [Tencent/bk-ci#490]
传入环境名称，在插件里可以获取到这个环境的机器ip，以便在自己的插件里获取机器ip进行其他操作

**Comment by irwinsun** [comment]
@carlyin0801

**Comment by irwinsun** [comment]
环境将仅限于组建构建机集群， 不会再包含 IDC测试机集群，该需求没有实质意义，暂时关闭
