### ISSUE TITLE
建议支持  source branch hook 事件监听

### ISSUE THREAD

**Issue by ldaysjun** [Tencent/bk-ci#491]
因为   触发流水线。  一个服务一条流水线。 如果A->master 会被监听，同样B-master的事件也会被触发。   造成多余的流水线触发。  比较痛，希望能支持。

**Comment by irwinsun** [comment]
@zanyzhao

**Comment by zanyzhao** [comment]
可否解释下为什么不同的分支合入master需要不同的处理流程

**Comment by iccengan** [comment]
该issue为源分支的监听
关联需求 #449 为源分支的排除
