### ISSUE TITLE
设置项目的流水线默认显示列

### ISSUE THREAD

**Issue by cosinuswx** [Tencent/bk-ci#499]
目前流水线的显示列修改只会影响本机，不能应用到整个项目。比如“推荐版本号”比“构建号”更有意义，希望显示列的修改能应用整个项目，或者将默认显示的“构建号”替换为“推荐版本号”。

![image](https://user-images.githubusercontent.com/6874119/71720035-2b34be80-2e5b-11ea-89ef-2d87fb25777c.png)

**Comment by zanyzhao** [comment]
构建号是系统内置字段，默认必须有。
不过我们可以把推荐版本号作为默认显示列 @lockiechen
