### ISSUE TITLE
Could not download guava.jar (com.google.guava:guava:21.0) 

### ISSUE THREAD

**Issue by damondengxin** [Tencent/bk-ci#50]
w: /root/bkci/src/backend/common/common-api/src/main/kotlin/com/tencent/devops/common/api/pojo/Zone.kt: (32, 17): Parameter 'name' is never used

> Task :common:common-service:compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':common:common-service:compileKotlin'.
> Could not resolve all files for configuration ':common:common-service:compileClasspath'.
   > Could not download guava.jar (com.google.guava:guava:21.0)
      > Could not get resource 'http://mirrors.cloud.tencent.com/nexus/repository/maven-public/com/google/guava/guava/21.0/guava-21.0.jar'.
         > Could not GET 'http://mirrors.cloud.tencent.com/nexus/repository/maven-public/com/google/guava/guava/21.0/guava-21.0.jar'.
            > Read timed out
   > Could not download commons-lang.jar (commons-lang:commons-lang:2.6)
      > Could not get resource 'http://mirrors.cloud.tencent.com/nexus/repository/maven-public/commons-lang/commons-lang/2.6/commons-lang-2.6.jar'.
         > Could not GET 'http://mirrors.cloud.tencent.com/nexus/repository/maven-public/commons-lang/commons-lang/2.6/commons-lang-2.6.jar'.
            > Read timed out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 42s
111 actionable tasks: 101 executed, 10 up-to-date

**Comment by irwinsun** [comment]
是否是你那边编译机无法连接到 http://mirrors.cloud.tencent.com  这个Maven仓库。
可以选择其他公有/私有的Maven仓库。

**Comment by irwinsun** [comment]
配置在gradle.properties  line.35
MAVEN_REPO_URL=http://mirrors.cloud.tencent.com/nexus/repository/maven-public
可以修改为你自己的maven仓库

**Comment by damondengxin** [comment]
配置的这个地址，应该公网访问你们的仓库太慢了，我这网速是没问题的

**Comment by irwinsun** [comment]
我们对maven仓库没有特殊的要求，一切依赖都可以从已知的公有云仓库下载到。如果太慢，可以考虑一下换其他的源或者你的私有代理仓库.
