### ISSUE TITLE
蓝盾插件里配置禁止手动重试

### ISSUE THREAD

**Issue by Jimmy01010** [Tencent/bk-ci#5011]
**场景**
1.有些插件不支持单独重试，如依赖上一级插件的输出构建和环境，但环境可能会被销毁，此时如果单独重试插件，插件就会异常；
2.针对上述情况，也没有很好的办法告知用户不可重试的情况，额外增加用户调试时间。

**需求**
1.期望可以在插件里提供配置，灰掉（禁止）手动重试功能。

**Comment by iccengan** [comment]
已经支持
