### ISSUE TITLE
【微扩展】环境变量bug fix

### ISSUE THREAD

**Issue by fayewong-v5** [Tencent/bk-ci#5023]
问题：
1、添加变量后，在 “所有” 条件下不展示
2、测试环境和正式环境变量同名时，会相互覆盖

预期：
1、搜索条件不要有默认值，用户进入时展示全部环境变量
![image](https://user-images.githubusercontent.com/54432927/149253087-152e5113-36a3-43aa-b412-0f0046564d4d.png)

2、测试环境和正式环境变量可以同名不同值

**Comment by vhwweng** [comment]
转内部需求
