### ISSUE TITLE
希望流水线中的文字过滤不要进行后台过滤

### ISSUE THREAD

**Issue by jacky15** [Tencent/bk-ci#5098]
**What would you like to be added**:
![image](https://user-images.githubusercontent.com/8501367/132176070-efacf387-c393-45f0-8909-fdb220e49979.png)

**Why is this needed**:
希望此处是否可以不做权限的过滤，而是直接前端全量搜索所有流水线，原因有两个：

1. 目前输入一个字符做一次后台权限过滤请求，搜索的效率大幅降低; 
2. 即使此处全量搜索得到没有权限的流水线，也可以通过跳转后的页面进行拦截，更适合收敛逻辑

**Comment by irwinsun** [comment]
前端搜索是需要提前把整个项目的数据都加载到前端浏览器缓存起来。
1、管理缓存是比较费劲的事，要考虑过期失效，你的同事其他帐号新增了流水线等数据同步刷新等问题，bug点非常多。
2、前端搜索仅适合于小项目流水线条数不多的场景，当缓存数据记录条越来载多，对于前端的组件都是存在性能瓶颈。
3、未必所有人都有强烈的搜索场景，帮用户缓存数据通常都是浪费的。
