### ISSUE TITLE
版本体验不支持设置为公开

### ISSUE THREAD

**Issue by aaron-go** [Tencent/bk-ci#513]
目前的版本体验不支持设置为公开，如果需要在整个部门或者公司发布体验的话，需要添加几百人的名单，非常不合理。

**Comment by zanyzhao** [comment]
指定可见范围的版本体验功能需要一个较大的改动，我们正在重构移动端APP，在年后应该可以上线一个更棒的版本体验服务

**Comment by zanyzhao** [comment]
这个需求是腾讯公司内部需求，已转内部跟进，这边先关单。
