### ISSUE TITLE
拉取代码插件的凭证没有传递给下游插件

### ISSUE THREAD

**Issue by iccengan** [Tencent/bk-ci#5185]
### 现状：
拉取代码插件执行成功，但下游插件如bash插件拉代码时（如`go get`或`pod install`等等）会报以下错误：
`fatal:could not read Username for “http://git.xxx.com” ： Device not configured`

**Comment by mingshewhe** [comment]
推荐使用https://github.com/TencentBlueKing/ci-checkout插件，目前checkout插件已经支持凭证传递
