### ISSUE TITLE
http header name应该是不区分大小写

### ISSUE THREAD

**Issue by hingbong** [Tencent/bk-ci#5191]
bkrepo在上传时使用header携带元数据，但是header应该不区分大小写，而根据元数据搜索区分大小写
[4.2 Message Headers](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2)

http的规定是header的key不区分大小写，http2的头压缩功能会把key转成小写，okhttp就会这样做，这样调接口归档的时候，元数据通过header传输，buildNo会被转成buildno，但是通过bkrepo的搜索接口搜索的时候，查询参数的key却是大小写敏感的，导致查询不到需要的数据

**Comment by irwinsun** [comment]
确实是个问题
