### ISSUE TITLE
feat: 移除${} 模板语法,改用${{}}

### ISSUE THREAD

**Issue by irwinsun** [Tencent/bk-ci#5197]
**What happened**:
早期蓝盾设计的 ${} 模板替换语法 ，与Shell脚本本身的 ${} 变量替换请求冲突了。 在Shell的一般情况下，$var 与${var} 并没有啥不一样。但是用 ${ } 会比较精确的界定变量名称的范围。 但正因蓝盾提供的${}模板替换语法执行的优先级比Bash的变量替换高，导致会出现提前替换。

- [x] 前端组件使用${{}}替换${}
- [x] 后端移除${}支持，存在风险，会影响现有用户的构建脚本，此TODO暂时仅作公示，但不做改动

**Comment by iccengan** [comment]
![企业微信截图_16318630175171](https://user-images.githubusercontent.com/10875468/133740966-afbfcdca-4148-428f-9f4a-54bc1ecfade8.png)
![image](https://user-images.githubusercontent.com/10875468/133741055-b06fc6de-35dc-4fd7-853d-4664e6bfe14d.png)

官方提供复制的流水线变量统一更改为：${{ }}
1. 引用变量
2. 插件输出变量

**Comment by lockiechen** [comment]
人员选择器支持变量格式修改

**Comment by iccengan** [comment]
![image](https://user-images.githubusercontent.com/10875468/141750051-061afa44-dfea-487e-8d72-734db256eaa4.png)

**Comment by irwinsun** [comment]
开源版没有这个问题
