### ISSUE TITLE
流水线编辑通知消息模板不支持动态环境变量设置

### ISSUE THREAD

**Issue by lyg211314** [Tencent/bk-ci#523]
蓝盾流水线设置通知消息时获取不到流水线bash脚本动态设置的环境变量，可以关注一下这块，这样没法对错误消息进行指定人员消息管理控制了
![企业微信截图_15780504792146](https://user-images.githubusercontent.com/8748310/71814330-09d00e80-30b7-11ea-8636-b9019b20b56b.png)
![企业微信截图_15780507115055](https://user-images.githubusercontent.com/8748310/71814375-28cea080-30b7-11ea-918e-2d37c1d8b978.png)

**Comment by lj654548718** [comment]
hello, lyg, 我这边试了是ok的
看是不是变量设置问题，后面加个shell来echo ${startUser}看有没有值
