### ISSUE TITLE
svn代码库触发支持post-commit、lock-commit、pre-commit事件

### ISSUE THREAD

**Issue by iccengan** [Tencent/bk-ci#5307]
### 需求：
svn事件钩子支持post-commit、lock-commit、pre-commit事件。流水线的【svn事件触发】插件需支持以上三种事件。
![企业微信截图_16339585022367](https://user-images.githubusercontent.com/10875468/136797841-cde4d211-0b59-4440-9977-4f2ae4f588c8.png)

**Comment by mingshewhe** [comment]
> **需求场景**：使用流水线更新地形关卡时，有些地形可能被其他人锁住。所以需要在地形关卡被解锁的同时，触发流水线重新更新。

工蜂目前svn没有lock commit事件，后续可能会增加上，所以这功能目前暂时实现不了
