### ISSUE TITLE
论流水线模板的常量与手动触发执行时使用最近一次构建参数值 在实例化中运用的冲突

### ISSUE THREAD

**Issue by irwinsun** [Tencent/bk-ci#535]
在流水线模板：
1. 设置手动触发 设置「手动触发执行时使用最近一次构建参数值 」
![image](https://user-images.githubusercontent.com/16686129/71868417-fff6eb80-3148-11ea-88a8-45b483f8f5e4.png)
2. 在流水线常量中设置的值。
![image](https://user-images.githubusercontent.com/16686129/71868585-acd16880-3149-11ea-87c0-2d5362aa2903.png)
3. 实例化：
![image](https://user-images.githubusercontent.com/16686129/71868603-ca9ecd80-3149-11ea-9f17-79b7eb079d59.png)

结果：
以上步骤2修改生成的流水线常量只对实例化的流水线的第一次构建有效，
后续进行修改将无法生效，因为步骤1上的选项导致每次构建只能用第1次的变量值。而且是常量无法修改。

**Comment by zanyzhao** [comment]
将现在的“手动触发执行时使用最近一次构建参数值”改为*手动触发执行时自动回填最近一次构建参数值*

**Comment by irwinsun** [comment]
手动触发执行时自动回填最近一次构建参数值的意思是：

但凡是在手动触发预览看不见的“变/常量”，都不允许使用上一次构建的参数值。 看不见的即为非必填的，用户不需要关注的，也就不会有修改的可能，就不会出现上一次构建与本次构建不相同的场景。

需要修正2处： 
流水线模板实例管理--批量更新：
1。模板中设置“执行时显示”的选项，需要支持更新到实例。（前端传递参数，后端更新接口支持参数)

2。后端获取启动manualStartupInfo根据required =true 决定用上一次构建参数回填，
