### ISSUE TITLE
流水线增加回收站功能

### ISSUE THREAD

**Issue by zanyzhao** [Tencent/bk-ci#542]
建议在流水线列表页面增加回收站功能，回收站有以下特性：

- 点击删除流水线，自动进入“回收站”
- 在回收站中30天的流水线才会真正删除
- 在30天内，对流水线有"编辑"权限的人可以恢复流水线
- 恢复后的流水线自动添加“恢复时间戳”到流水线名称里

**Comment by jsonwan** [comment]
> 建议在流水线列表页面增加回收站功能，回收站有以下特性：
> 
> * 点击删除流水线，自动进入“回收站”
> * 在回收站中30天的流水线才会真正删除
> * 在30天内，对流水线有"编辑"权限的人可以恢复流水线
> * 恢复后的流水线自动添加“恢复时间戳”到流水线名称里

最新讨论结果：在30天内，项目管理员可以恢复流水线
