### ISSUE TITLE
使用体验反馈

### ISSUE THREAD

**Issue by zhuozhuo** [Tencent/bk-ci#543]
Hello，使用了一段时间蓝鲸CI平台，挺满意的，不过有几点小的体验反馈下，如果开发兄弟有空看能否加上。

1. 在发布版本体验市，有个体验结束日期，默认是一天。这里如果晚上发体验版本，第二天组内测试人员还没安装体验就过期了，这里能否默认时间放长呢比如5天？或者自己能够设置默认时长，不用每次都进行设置。

2. 在发布完成后的发布详情-基础信息中有个二维码。扫码下载已成为习惯，这里能否做个下载二维码功能呢？

**Comment by zanyzhao** [comment]
1好搞，我们尽快调整下
2本来就有的，是不是你没权限，可以私聊我：devops-helper
