### ISSUE TITLE
支持查看流水线执行成功率、平均构建耗时等构建指标

### ISSUE THREAD

**Issue by iccengan** [Tencent/bk-ci#5453]
### 场景：
对当前流水线构建的成功率和时长进行数据关注，用于指导效能团队在构建成功率和构建效率上提升。针对一些耗时不断增加的插件能及时告警，或者找到问题出现的时间点。

### 思路：
- 新版控制台Dash Board
- 数据度量
- 流水线详情页

**Comment by iccengan** [comment]
关联需求：#4434

**Comment by zanyzhao** [comment]
已通过内部数据API提供，不做业务需求跟进
