### ISSUE TITLE
支持跨项目共享/移动/复制流水线、模版等资源

### ISSUE THREAD

**Issue by yyfrankyy** [Tencent/bk-ci#546]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
使用多起来，一个产品内会划分多个项目，而项目之间又有一些共享的编译模版、访问凭证、流水线（代码可能一样，不同分支或者构建流程）；另外在整理大项目流水线的时候，可以方便的移动整理。

**Describe alternatives you've considered**
模版发布到商店可以解决一部分模版共享的问题，但是移动就做不到了。

**Additional context**
No.

**Comment by iccengan** [comment]
相似需求：#999

**Comment by irwinsun** [comment]
移动流水线的目的是什么呢？ 以及操作的频率是什么样的，需要很频繁的移动吗？
移动操作理解为（copy + remove)：
1. 将流水线从Project A copy to Project B
2. 将流水线从Project A remove

在频率不高的场景下，其实是可以这么操作：
- Project A 将流水线转为模板 使用自由模式，并上架研发商店
- Project B 从商店安装后将模板生成流水线， 到此，已经完成移动操作的第1步(copy)
- 将Project A中的模板从商店下架并删除。 完成移动操作的第2步(remove)

**Comment by irwinsun** [comment]
见 #1030 使用导入导出功能迁移流水线
