### ISSUE TITLE
【MR为同源同目标分支时，等待队列只保留最新触发的任务】配置调整为停止之前同源同分支的构建

### ISSUE THREAD

**Issue by iccengan** [Tencent/bk-ci#5475]
### 现象：
Git事件触发，当事件类型为MR hook时，并勾选了【MR为同源同目标分支时，等待队列只保留最新触发的任务】配置，仅对排队中的构建任务生效（即正在进行中的`同源同分支构建`继续执行，只剔除排队中的`同源同分支构建`）。

### 期望：
对 正在执行中的`同源同分支构建`也生效，即立即停止构建，减少构建资源浪费。

### 待办：
先对存量用户进行调研。

**Comment by mingshewhe** [comment]
流水线运行设置已有分组这个功能，配置为，分组名:
```
${{BK_CI_PIPELINE_ID}}_${{ BK_CI_HOOK_SOURCE_BRANCH}}_${{ BK_CI_HOOK_TARGET_BRANCH }}
```
<img width="1491" alt="image" src="https://user-images.githubusercontent.com/22971705/179391514-702f183f-720d-4374-80dd-2f97fc9cf589.png">
