### ISSUE TITLE
插件增加高级流程控制选项-自动重试

### ISSUE THREAD

**Issue by zanyzhao** [Tencent/bk-ci#548]
增加失败时自动重试的特性，开启后可设置如下两个参数：
- 自动重试次数（最多5，默认1）
- ~~自动重试间隔~~

增加这个特性后需要在”失败时继续“旁边加Tips：`如果同时开启了”失败时重试“，我们将优先尝试重试，如果所有重试都失败后才会继续`

**Comment by irwinsun** [comment]
蓝盾流水线评论: 已部署到灰度环境

**Comment by irwinsun** [comment]
蓝盾流水线评论: 开发已自测通过，已发布到测试服，请测试团队测试

**Comment by irwinsun** [comment]
蓝盾流水线评论: 已部署到灰度环境
