### ISSUE TITLE
可配置出档构建的哪些步骤环节无法被终止

### ISSUE THREAD

**Issue by kimiliu-honor** [Tencent/bk-ci#550]
考虑到部分业务在出档构建的某些环节步骤终止会导致出档出现异常，建议新增“可配置出档构建的哪些步骤环节无法被终止”。
功能点：可以直接配置一个通用的规则，适用于该业务线下的所有分支流水线，如单个流水线分别配置，可能会有遗漏，且操作上也会比较麻烦

**Comment by irwinsun** [comment]
需求分两点： 
1. 业务线下 批量设置并且不可更改， 可以用流水线模板化约束模式（已经有了）
2. 无法被终止，即使被取消也继续执行，这个功能本来也有，有在规划中@zanyzhao

**Comment by zanyzhao** [comment]
嗯，可以结合“即使取消也运行”的特性配合一起来实现这种场景
