### ISSUE TITLE
bk-ci源码如何打成slim包

### ISSUE THREAD

**Issue by DavidChanSunshine** [Tencent/bk-ci#5532]
1.bkci目前部署采用的是slim包，但是gradle工程打出的包是fatjar的方式；
2.对于slim包如何单个微服务打包，如何单个微服务部署？

**Comment by irwinsun** [comment]
> 1.bkci目前部署采用的是slim包，但是gradle工程打出的包是fatjar的方式； 2.对于slim包如何单个微服务打包，如何单个微服务部署？

这个过程是完全开源的在github actions中运行着，slim包大概原理是并没有对gradle编译做任何的魔改，
只是对gradle编译完后的的各个服务模块的fatjar解压并识别出的公共依赖jar，删除重复的jar。

[打包过程](https://github.com/Tencent/bk-ci/blob/master/.github/workflows/release.yml)

[如何bk-ci-slim.sh](https://github.com/Tencent/bk-ci/blob/master/scripts/bk-ci-slim.sh)
