### ISSUE TITLE
job启动时检查工作空间路径是否合法，如是非法路径直接失败

### ISSUE THREAD

**Issue by iccengan** [Tencent/bk-ci#5555]
### 现象：
如下图，当工作空间输入的流水线变量不存在时，工作空间会以非法路径`${xxx}`作为子目录，Job下的插件有可能会执行失败。如bash插件里的`setEnv`依赖工作空间的路径，会导致`setEnv`不成功。
![image](https://user-images.githubusercontent.com/10875468/141886018-34df46b5-8aea-4bb3-bcfa-8dcaea18e690.png)

### 期望：
启动Job时，检查工作空间路径是否合法（如果有流水线变量，校验替换流水线变量之后的值），如果不合法（包含`$` `{` `}`特殊字符），Job启动失败，输出错误：
“工作空间路径含非法字符，请检查路径：/xxx/xxx/xxxx”

**Comment by levinlinx** [comment]
需要先替换变量，最后的工作空间如果出现非常字符则报错。

**Comment by irwinsun** [comment]
做了校验判断，只要操作系统允许创建的都是合法的。
比如在Linux下， mkdir '/root/${xxxxx}'  是能合法创建该目录，所以不能就一定认为${xxxx} 是不合法的，就认定用户是将他期望替换成一个真实的变量值。 

 并且此类问题在用户侧完全是可规避，不是常见的操作，不建议在平台侧做过多的限制约束。
