### ISSUE TITLE
开源版质量红线

### ISSUE THREAD

**Issue by DavidChanSunshine** [Tencent/bk-ci#5585]
我看1.5.7版本的部署包里有quality的服务，我如何才能在页面上看到质量红线的功能？

**Comment by irwinsun** [comment]
连接上数据库，执行以下sql
use devops_ci_project;

update `T_SERVICE` set `status`='ok', `deleted`= false where `english_name`='Gate';

**Comment by DavidChanSunshine** [comment]
@irwinsun 你好 谢谢你的回答这个问题已经解决，还有个问题，就是这个质量红线关于iam权限的问题该如何操作啊，我看权限里面都没有质量红线的资源可以关联

**Comment by irwinsun** [comment]
@fitzcao 关注补充下Quality的权限Json

**Comment by irwinsun** [comment]
> @irwinsun 你好 谢谢你的回答这个问题已经解决，还有个问题，就是这个质量红线关于iam权限的问题该如何操作啊，我看权限里面都没有质量红线的资源可以关联

质量红线目前开源部分还没有真正验证过，所以目前暂时关闭，所以如果提前使用可能会有一些问题

**Comment by irwinsun** [comment]
@terlinhe @JamiKX1 另关注下这个之前提的问题 fix: 开源版质量红线相关异常 #1579

**Comment by irwinsun** [comment]
#1579
