### ISSUE TITLE
在每个任务阶段，可以直接有查看报告和日志的入口

### ISSUE THREAD

**Issue by chenlijuan3** [Tencent/bk-ci#5589]

**Comment by irwinsun** [comment]
![image](https://user-images.githubusercontent.com/16686129/143398569-59601630-a8e2-4444-ba25-c24026660a74.png)

请问 是哪个版本的？ 这个功能你那没有吗

**Comment by chenlijuan3** [comment]
希望在
![image](https://user-images.githubusercontent.com/19179572/144381521-64d751cc-e45a-406c-8eb2-a3ea792ee295.png)
就能点击查看报告，不需要点击进去，然后再切换到报告

**Comment by iccengan** [comment]
不在流水线编排的task上添加入口，保持现逻辑：点开日志滑窗后，可切换至报告。
