### ISSUE TITLE
希望可以有开源的插件管理的地方

### ISSUE THREAD

**Issue by Ben-zl** [Tencent/bk-ci#562]
在实际使用中发现，复杂的构建流程往往需求配合很多操作才能完成，我们在实际使用过程也写了一些相关的插件来实现对应的功能，希望官方可以有一个开源的插件管理的地方可以供大家把这些插件共享出来

**Comment by irwinsun** [comment]
现在我们有一个 https://github.com/ci-plugins 组织，准备将一些可以完全公开的插件放到上面来
