### ISSUE TITLE
feat:凭证管理的名称支持特殊符号

### ISSUE THREAD

**Issue by noonhorse** [Tencent/bk-ci#5634]
背景：

当前的凭证管理有较大限制，在部分构建场景下需要用到的名称中有 `-`，但是当前系统限制了不可用。

希望名称支持 `·`、`-`、`.` 等符号

视图：
![image](https://user-images.githubusercontent.com/4952447/143579879-d1c8268b-1933-440b-be74-36fe282bb65c.png)

**Comment by irwinsun** [comment]
这个限制的早期背景是： 希望凭证作为环境变量导入，而环境变量的命名要求有此限制。

**Comment by iccengan** [comment]
@noonhorse 什么场景下凭证名称必须使用`-`、`.`等特殊字符？
