### ISSUE TITLE
流水线列表页筛选条件优化

### ISSUE THREAD

**Issue by fitzcao** [Tencent/bk-ci#5660]
当前的筛选条件包含中间态，导致搜索不生效。 需优化为只能对最终态进行筛选
![image](https://user-images.githubusercontent.com/22310235/144049104-5d68676f-f92c-4e5b-9122-4c8d2441de09.png)

**Comment by kurisu777** [comment]
能否支持通过构建ID或错误码筛选查询构建的流水线，历史列表构建次数较多，查询时翻半天找不到，慢的要命
