### ISSUE TITLE
环境踢掉了有问题的机器节点之后，重跑流水线仍会跑到踢掉的那台机器节点

### ISSUE THREAD

**Issue by ChampGao** [Tencent/bk-ci#5713]
**What happened**:
![image](https://user-images.githubusercontent.com/12290506/144955958-73aa4ac7-c773-44f1-af18-5383d3a4e6e1.png)

在这里踢掉了有问题的机器节点之后，重跑流水线仍会跑到踢掉的那台机器节点。
希望重跑的时候从环境列表里选择一台新的机器
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- bk-ci version (use `cat VERSION` in installed dir):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by irwinsun** [comment]
目前的调度逻辑是：

组建为构建集群后，Job寻找构建节点的算法如下：

最高优先级的agent:
最近构建机中使用过这个构建机 （构建空间 +  当前没有任何任务 优先）
当前没有任何构建机任务（当前没有任何任务）
次高优先级的agent:
最近构建机中使用过这个构建机 （构建空间优先）
当前有构建任务，但是构建任务数量没有达到当前构建机的最大并发数 
第三优先级的agent:
当前没有任何构建机任务
第四优先级的agent:
当前有构建任务，但是构建任务数量没有达到当前构建机的最大并发数
最低优先级：
都没有满足以上条件的


但上述在重试时应该是忽略了检测这台之前用过的构建机是否还仍然属于这个集群

**Comment by irwinsun** [comment]
review了代码确认目前版本没有此问题：
https://github.com/Tencent/bk-ci/blob/ec8972488bdc0037d290346cd8e8a81ad7523bed/src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/service/dispatcher/agent/ThirdPartyAgentDispatcher.kt#L295
1、随时从接口获取环境中的构建机列表（无缓存）
<img width="1303" alt="image" src="https://user-images.githubusercontent.com/16686129/162963067-4bbf6e27-5bdb-416b-b80c-a2b250fbd05f.png">

2、 取最近10次构建机和当前环境下的构建机交集（之前被选中过的，但被移除出环境的构建机不在交集内）
<img width="1287" alt="image" src="https://user-images.githubusercontent.com/16686129/162963616-275a0f45-e6df-4cc7-8d21-fa11e528c0ce.png">

**Comment by ChampGao** [comment]
您的来信已经收到，我会尽快回复您的邮件，感谢您的来信。——高文冠
