### ISSUE TITLE
docker demo流水线执行提示没有maven

### ISSUE THREAD

**Issue by letianchang** [Tencent/bk-ci#5749]
您好，https://hub.docker.com/r/blueking/bk-ci 我们按照文档部署了bk-ci的docker demo，在执行第一次流水线任务，编译java包时，提示
![image](https://user-images.githubusercontent.com/18129518/145507605-b541f20f-02b9-4139-928a-962d211370d9.png)
没有maven，请问这个应该怎么解决

**Comment by irwinsun** [comment]
该镜像已经不维护，新版本正在重做中
