### ISSUE TITLE
优化前端标签页的标题

### ISSUE THREAD

**Issue by Boxie5** [Tencent/bk-ci#5761]
**What would you like to be added**:

修改流水线的详情页面的title属性

**Why is this needed**:

这样能在浏览器的标签页上就能看到打开的标签也是属于哪个流水线

现状:
在同一个浏览器中打开多个标签页，不同标签中是蓝盾的不同流水线时，标签页上的标题都是【蓝盾DevOps平台】，不方便快速定位页面。

**Comment by iccengan** [comment]
【流水线详情页】
流水线名称#构建号 · 项目名称 - 蓝盾

【流水线构建列表页】
流水线名称 · 项目名称 - 蓝盾

【各个服务】
服务名称 · 项目名称 - 蓝盾
