### ISSUE TITLE
【API】build_list接口提供历史构建更新时间字段，并支持构建列表按更新时间排序

### ISSUE THREAD

**Issue by iccengan** [Tencent/bk-ci#5774]
### 需求：
1. `build_list`增加构建 `update_time` 字段，当单次构建数据有更新时（如构建开始、构建结束、备注修改、rebuild等），都将刷新 `update_time` 字段
2. 支持按update_time正序/倒序返回build_list数据

**Comment by irwinsun** [comment]
```sql
ALTER TABLE T_PIPELINE_BUILD_HISTORY ADD COLUMN `UPDATE_TIME` datetime NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
```

1、程序无需处理，确保更新时都能自动更新。
2、相应接口的DTO增加读取该字段
