### ISSUE TITLE
Backend编译出错

### ISSUE THREAD

**Issue by letianchang** [Tencent/bk-ci#5776]
![image](https://user-images.githubusercontent.com/18129518/145783579-643bb75f-f293-4214-ba2f-33c78b7d24b8.png)
执行gradle clean build时提示上图错误，请问该如何解决

**Comment by irwinsun** [comment]
你使用的gradle 版本可能与平台要求的不相符。
代码已经提供了gradlew脚本，建议用他来编译吧
