### ISSUE TITLE
bug: git事件触发选择锁定提交，就一定回写commit check

### ISSUE THREAD

**Issue by mingshewhe** [Tencent/bk-ci#5820]
目前git事件触发选择锁定提交，可以不勾选回写commit check，导致锁定没有生效

![image](https://user-images.githubusercontent.com/22971705/146546799-557f94f4-be4c-4a76-9c89-573a0af3187e.png)

**Comment by mingshewhe** [comment]
merge accept事件不应该锁mr

**Comment by vhwweng** [comment]
关联需求： https://github.com/Tencent/bk-ci/issues/6341
