### ISSUE TITLE
java开发ci插件的时候，根据demo打印日志，info级别也是红色，且中文乱码，请问哪里有faq或是文档

### ISSUE THREAD

**Issue by chi-bin** [Tencent/bk-ci#5911]

**Comment by chi-bin** [comment]
经过task.json中添加-Dfile.encoding=UTF-8已经解决中文乱码问题，但是红色问题仍未解决

**Comment by irwinsun** [comment]
红色的字在插件内是用 System.out.print或者用 Log.info  输出的吗

**Comment by irwinsun** [comment]
[使用common-exec组件PumpStreamHandler对控制台的错误流进行解析](https://github.com/Tencent/bk-ci/blob/ab4114b829d8024a11c3af98f603bed62b734f16/src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/utils/CommandLineUtils.kt#L129)
