### ISSUE TITLE
feature: 子流水线调用插件，下拉框支持输入和选择

### ISSUE THREAD

**Issue by zhanxu33** [Tencent/bk-ci#593]
子流水线调用插件需要支持
1. 下拉框支持列表选择
2. 下拉框支持手动输入单个值
3. 下拉框支持手动输入多个值，使用逗号分隔

**Comment by irwinsun** [comment]
蓝盾流水线评论:  @irwinsun 开发已自测通过，已发布到测试服，请测试团队测试

**Comment by irwinsun** [comment]
蓝盾流水线评论: 已部署到灰度环境

**Comment by irwinsun** [comment]
蓝盾流水线评论:  @irwinsun 开发已自测通过，已发布到测试服，请测试团队测试

**Comment by irwinsun** [comment]
蓝盾流水线评论: 已部署到灰度环境
