### ISSUE TITLE
feature:运行锁定支持只保留最新构建

### ISSUE THREAD

**Issue by dolly1945** [Tencent/bk-ci#595]
部分场景下，一个构建流水线只有最新的一个构建有意义。
当多个构建任务被自动触发时，应该有选项控制，只保留最新构建，较旧的构建自动中止。

**Comment by irwinsun** [comment]
这个建议手动处理哈，运行中的任务终止存在一些风险，我们不希望自动帮用户做这种破坏性的操作。
不过目前我们支持对排队中的构建进行终止，只保留一个最新的排队任务。看能否满足你的需求。
