### ISSUE TITLE
蓝鲸CI拉取gitlab代码构建完毕，会有一个更新记录

### ISSUE THREAD

**Issue by leockio** [Tencent/bk-ci#6011]
蓝鲸CI拉取gitlab代码构建完毕，会有一个更新记录，具体在构建机器的 哪个路径下有该更新记录的log
麻烦可以处理一下嘛
![image](https://user-images.githubusercontent.com/70870773/149439204-683e7151-2b75-4284-ab7b-b4f75be5a902.png)

**Comment by leockio** [comment]
关键就是想从服务器文件内找到这个含有代码更新记录的这个文件

**Comment by hingbong** [comment]
这个是使用类似`git log`的方式获取记录之后直接推到服务端存储，构建机应该没有另外存储

**Comment by leockio** [comment]
> 这是使用类似`git log`的方式获取直接推送到服务端存储，机器应该没有另外存储之后

jenkins 好像有类似日志在服务器端存储的吧，想读取那个文件

**Comment by irwinsun** [comment]
> > 这是使用类似`git log`的方式获取直接推送到服务端存储，机器应该没有另外存储之后
> 
> jenkins 好像有类似日志在服务器端存储的吧，想读取那个文件

我猜一下你想要的：
想拿构建日志吗？bkci是将构建机产生的日志上报给BKCI的服务端，并存储在ES 或 服务端本地以Lucene索引文件方式存储（根据你部署的配置决定存储方式）。 直接点开详情就可以看到了。 
<img width="810" alt="image" src="https://user-images.githubusercontent.com/16686129/164132264-a57c5ff5-d623-479b-9c14-eb612df4c27c.png">
