### ISSUE TITLE
模板里面设置版本号带有“/”无法进行删除

### ISSUE THREAD

**Issue by guoyangping** [Tencent/bk-ci#6023]
![image](https://user-images.githubusercontent.com/10875468/154431974-30e45507-a076-41ad-b0ab-78afe4cee261.png)

**What happened**:
[文件：模板保存版本删除失败.mp4]
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- bk-ci version (use `cat VERSION` in installed dir):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by irwinsun** [comment]
名称需要做URLEncode

**Comment by vhwweng** [comment]
关联需求： https://github.com/Tencent/bk-ci/issues/6353
