### ISSUE TITLE
fix: Upgrade log4j 2.17.0 to 2.17.1

### ISSUE THREAD

**Issue by JamieSlome** [Tencent/bk-ci#6030]
Hey there!

I belong to an open source security research community, and a member (@oivrip) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by irwinsun** [comment]
@JamieSlome Thanks a lot ，I had  added a security.md already
 and@oivrip can contact me by emailto irwinsun@tencent.com

**Comment by JamieSlome** [comment]
@irwinsun - when possible, could you kindly confirm the patch commit SHA against the report:

https://huntr.dev/bounties/bd8a8d2f-ef85-46de-892c-2ae5d242733e/

Let me know if you have any questions or trouble doing so! ❤️
