### ISSUE TITLE
agent 执行时间过长

### ISSUE THREAD

**Issue by flychord** [Tencent/bk-ci#6037]
大家好，我发现的问题是这样的： 
       1.5.7版本的agent 在执行java编译的过程中要10分钟左右，docker build要十几分钟，但是直接在服务器执行，都只要2分钟，这样一来，整个流程下来通常要20分钟以上，这个要怎么优化呢，我也发现在执行日志中大量的心跳连接，加起来大概有五六分钟的样子，为什么会这么频繁

**Comment by irwinsun** [comment]
方便 的话提供下日志文件

**Comment by flychord** [comment]
更换了agent服务配置

**Comment by flychord** [comment]
更换了服务配置
