### ISSUE TITLE
流水线列表最新执行时间不是按照最新的时间排序

### ISSUE THREAD

**Issue by guoyangping** [Tencent/bk-ci#6040]
**What happened**:
流水线列表最新执行时间不是按照最新的时间排序
![企业微信截图_1642496813553](https://user-images.githubusercontent.com/62585286/149919245-ef969162-7167-48f6-854d-a487d8cf787b.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
希望能正常按照最新时间来排序
**Anything else we need to know?**:

**Environment**:
- bk-ci version (use `cat VERSION` in installed dir):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by irwinsun** [comment]
目测是当时历史数据的问题，
