### ISSUE TITLE
插件突出执行失败的错误类型，引导用户咨询对应责任人

### ISSUE THREAD

**Issue by iccengan** [Tencent/bk-ci#6068]
### 期望：
官方脚本插件执行失败时，突出错误类型（平台错误、插件错误、第三方错误、用户错误）。对应错误类型需要输出问题联系人，引导用户咨询正确责任人。

输出
“错误码: ${error_code}. 错误类型: ${error_type_chinese}. ${message}” / 
“Error code: ${error_code}. Error type: ${error_type}. ${message}”
${message} = 
if 平台错误：“请联系蓝盾助手DevOps-helper协助定位”
if 插件错误：”请联系插件开发者${plugin_author}协助定位“
if 用户错误：”请检查插件配置是否有误“
if 第三方错误：”请联系该插件所属第三方服务的助手协助定位“

针对第三方错误，后续需对具体插件进行文案优化：”请联系${第三方服务助手}“

**Comment by Zzyyyyyyyy** [comment]
【期望插件日志报错可以有标准输出格式】
标准格式建议：
1：错误代码
2：错误原因
3：解决方案

**Comment by Zzyyyyyyyy** [comment]
希望能体现“助手服务边界”（日志能明确体现出是用户脚本逻辑问题，需用户自行定位解决）

**Comment by reggieisrunning** [comment]
+ 文案
```
Fail to run the plugin because of error(Process exited with an error: 1)

if 平台错误：“请联系蓝盾助手DevOps-helper协助定位”
if 插件错误：”请联系插件开发者${plugin_author}协助定位“
if 用户错误：”请检查脚本代码逻辑是否正确“
if 第三方错误：”请联系该插件所属第三方服务的助手协助定位“
错误类型：${error_type_chinese} / Error Type: ${error_type}
错误代码：${error_code} / Error Code: ${error_code}
这个问题也许可以从BASH_FAQ中找到答案
========问题排查Tips========
XXXXX
```
+ 样例图：
![image](https://user-images.githubusercontent.com/82890468/165492621-2c2f8a9b-ba1c-4567-81ea-4df7df64b976.png)

+ 修改注意点：
1. 按照如上文案进行调整
2. 「问题排查指引」-> 「问题排查tips」
3. 红框处内容里面字体颜色变为白色
![image](https://user-images.githubusercontent.com/82890468/165492857-6f9f7b9a-002a-457a-b96c-cb0a19334081.png)

**Comment by reggieisrunning** [comment]
if 平台错误：“【ERROR】请联系蓝盾助手DevOps-helper协助定位” / “[ERROR] Please contact BKCI Assistant DevOps-helper to assist in locating”
if 插件错误：”【ERROR】请联系插件开发者${plugin_author}协助定位“ / ”[ERROR] Please contact the plugin developer ${plugin_author} to assist in locating“
if 用户错误：”【ERROR】请检查脚本代码逻辑是否正确“ / ”[ERROR] Please check the script code logic is correct“
if 第三方错误：”【ERROR】请联系该插件所属第三方服务的助手协助定位“ / ”[ERROR] Please contact the assistant of the third-party service to which the plugin belongs to assist in locating“
错误类型：${error_type_chinese} / Error Type: ${error_type}
错误代码：${error_code} / Error Code: ${error_code}
这个问题也许可以从BASH_FAQ中找到答案 / This question may be answered from BASH_FAQ
========问题排查Tips======== / ========Troubleshooting Tips========
当脚本退出码非0时，执行失败。可以从以下路径进行分析：
1. 根据错误日志排查
2. 在本地手动执行脚本。如果本地执行也失败，很可能是脚本逻辑问题；如果本地OK，排查构建环境（比如环境依赖、或者代码变更等）


When the script runs with a non-zero exit code, Analyze by:
1. Check according to the error log
2. Manually run the script locally. If running the script locally also fails, it is likely to be a script logic problem; if running the script locally is successful, please check the build environment (such as environment dependencies, or code changes, etc.)

**Comment by reggieisrunning** [comment]
英文版tips文案修改为
When the script runs with a non-zero exit code, Analyze by:
1. Check according to the error log
2. Manually run the script locally. If running the script locally also fails, it is likely to be a script logic problem; if running the script locally is successful, please check the build environment
