### ISSUE TITLE
希望代码库能支持关联企业版工蜂

### ISSUE THREAD

**Issue by wenchao-h** [Tencent/bk-ci#6088]
**What would you like to be added**:
希望代码库能支持关联企业版工蜂
**Why is this needed**:
![image](https://user-images.githubusercontent.com/33511440/151117535-2fcd25bc-7f0c-472f-bd46-184540f595d4.png)
企业版工蜂域名是个性化的，通常为企业名称-git.code.tencent.com，添加代码库时无法通过校验，希望能支持一下

**Comment by irwinsun** [comment]
目前这个功能是针对工蜂腾讯公有云版本做的，有域名的限制。
但后台对接的都是同一套工蜂接口协议，不受影响， 需要前端支持，放开域名匹配

**Comment by iccengan** [comment]
后台添加校验：
如果用户填入的git域名非腾讯工蜂服务，报错提示：“TGit仅支持腾讯工蜂代码库”
