### ISSUE TITLE
流水线执行期间所更改的流水线变量，重试时应重置为第一次执行前的值

### ISSUE THREAD

**Issue by guoyangping** [Tencent/bk-ci#6090]
### 现象：
流水线配置了默认变量var，默认值为0。流水线有三个插件串行排列：`步骤A`、`步骤B`、`步骤C`。执行流水线，执行过程中`步骤B`将var的值更改为1，`步骤C`执行失败。此时rebuild流水线，`步骤A`打印出来的var值是1。

### 期望：
上诉场景下，`步骤A`打印的var值应是默认值0。rebuild的含义是重新执行本次构建，所有入参应保持与第一次执行前一致。

**Comment by iccengan** [comment]
产品侧建议：
针对每次重试的变量单独存储一份。流水线详情页后续规划支持查看每次重试的流水线编排，需要用到每次重试的信息。
