### ISSUE TITLE
gateway  install  fail 

### ISSUE THREAD

**Issue by mikeeastin** [Tencent/bk-ci#6145]
nginx: [emerg] invalid number of arguments in "upstream" directive in /usr/local/openresty/nginx/conf/vhosts/devops.bkrepo.upstream.conf:1

**Comment by mikeeastin** [comment]
[root@jszx-test scripts]# sh ./render_tpl -m ci ../support-files/templates/gateway*
render ../support-files/templates/gateway#core#auth.conf -> /data/bkee/ci/gateway/core/auth.conf
render ../support-files/templates/gateway#core#devops.server.conf -> /data/bkee/ci/gateway/core/devops.server.conf
render ../support-files/templates/gateway#core#lua#init.lua -> /data/bkee/ci/gateway/core/lua/init.lua
render ../support-files/templates/gateway#core#server.common.conf -> /data/bkee/ci/gateway/core/server.common.conf
render ../support-files/templates/gateway#core#vhosts#devops.bkrepo.upstream.conf -> /data/bkee/ci/gateway/core/vhosts/devops.bkrepo.upstream.conf


[root@jszx-test sbin]# ./nginx -t
nginx: [emerg] invalid number of arguments in "upstream" directive in /usr/local/openresty/nginx/conf/vhosts/devops.bkrepo.upstream.conf:1
nginx: configuration file /usr/local/openresty/nginx/conf/nginx.conf test failed
[root@jszx-test sbin]# cat /usr/local/openresty/nginx/conf/vhosts/devops.bkrepo.upstream.conf
upstream {
server ;
}

**Comment by irwinsun** [comment]
sorry, there are a workaround:

1、edit scripts/bkenv.properties 
2、 search `BK_REPO_HOST` AND  `BK_REPO_GATEWAY_IP` , then set 127.0.0.1

**Comment by mikeeastin** [comment]
thanks very mush , it works

**Comment by irwinsun** [comment]
It's a bug ,we will fix it.
