### ISSUE TITLE
插件执行前暂停功能优化

### ISSUE THREAD

**Issue by fayewong-v5** [Tencent/bk-ci#6210]
**What would you like to be added**:
1、增加 BK_CI_OPERATOR， 当插件暂停后，继续时，值为操作继续的用户。仅在当前  step 下有效

2、当插件入参没有任何值，在继续时填写的入参未生效问题fix

**Why is this needed**:

**Comment by chi-sk** [comment]
## 需求
- 希望蓝盾流水线执行完某个stage的时候可以暂停下来，等用户想要继续执行的时候可以手动继续执行。
- 如果有多条执行中的流水线实例被暂停了，可以批量的触发继续执行，比如通过接口调用的形式。
- 不希望通过在stage末尾添加暂停插件来实现流水线stage的暂停。

通过插件插件来实现流水线的暂停会存在一些困难，（比如添加人工审批插件），这样如果用户忘记在当前stage的最后添加暂停插件，流水线就会一直执行下去，而且这种方式暂停后不支持多条流水线的批量触发继续执行，不符合预期。

**Comment by fayewong-v5** [comment]
> ## 需求
> * 希望蓝盾流水线执行完某个stage的时候可以暂停下来，等用户想要继续执行的时候可以手动继续执行。
> * 如果有多条执行中的流水线实例被暂停了，可以批量的触发继续执行，比如通过接口调用的形式。
> * 不希望通过在stage末尾添加暂停插件来实现流水线stage的暂停。
> 
> 通过插件插件来实现流水线的暂停会存在一些困难，（比如添加人工审批插件），这样如果用户忘记在当前stage的最后添加暂停插件，流水线就会一直执行下去，而且这种方式暂停后不支持多条流水线的批量触发继续执行，不符合预期。

stage准入目前已经支持了 人工审核，配置下即可达到你想要的效果
