### ISSUE TITLE
插件图标无法正常显示

### ISSUE THREAD

**Issue by chenshanb3** [Tencent/bk-ci#6220]
自己开发的插件图标显示异常

<img width="638" alt="image" src="https://user-images.githubusercontent.com/96278502/156087887-854e5270-2679-4c19-bbfc-dd4fbf001bf5.png">

<img width="328" alt="image" src="https://user-images.githubusercontent.com/96278502/156087736-bf5d7762-8115-4e65-9f85-ac87bdb50832.png">

![code](https://user-images.githubusercontent.com/96278502/156087813-00de058b-d32f-4690-b9b7-ccabd063022e.png)

**Comment by chenshanb3** [comment]
版本：v1.7.27

**Comment by chenshanb3** [comment]
经测试发现图标是黑白的时候就会显示异常

<img width="343" alt="image" src="https://user-images.githubusercontent.com/96278502/156088115-8a2019cb-0368-43d1-9389-4eb68191f48d.png">

**Comment by chenshanb3** [comment]
透明底的黑色图标

<img width="154" alt="image" src="https://user-images.githubusercontent.com/96278502/156090452-d48e49d7-a7cd-4b56-a174-ce3544a149ee.png">

**Comment by lockiechen** [comment]
@chenshanb3 这边会是把icon转化成base64存起来，能辛苦你检查一下页面元素，把图片的base64地址贴出来看一下么

**Comment by chenshanb3** [comment]
> @chenshanb3 这边会是把icon转化成base64存起来，能辛苦你检查一下页面元素，把图片的base64地址贴出来看一下么

你说的是数据库里的这的icon吗

<img width="914" alt="image" src="https://user-images.githubusercontent.com/96278502/156505207-4d00ddcb-23a4-4d26-927d-98ff48876169.png">

**Comment by chenshanb3** [comment]
> @chenshanb3 这边会是把icon转化成base64存起来，能辛苦你检查一下页面元素，把图片的base64地址贴出来看一下么

data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAABwUlEQVR42rWUSyhEYRTHDeVZ1pJCMSwkSiSLyXIWM82j0WiaZgrZslFiccNGkYWIhaRkKUtSlCxEZkzUbNh4LdQsvJKo63emj67mDiPc+nXO+c7/nu98j3uzsv7jcbvddWDLQGcTrWlS07RskpdwDdZ0RXw+X5XH4xHdFX5OisDr9baQ3EU0jh1KV4j8IIzCHrpWM8GIFKBgEzb2RaEImnrsMLoxs3UfImjUdd2Cf4pfa6KxQhzXIlr86CeB3+8vZfCRWcLYEGzDCnG3EcaWXS7XpmhECw9QZmy3i6QOR/hz2CXsk/hGZDIppuKYeqfHWGgVNHUSldI68ZlxeXRSQf5cTldOTrRoBrBrSYHdbs9jIBEIBIpV+/sIc7GTckKG/eknng6Hw/lqP0MOh6OQsRsZey8UIbkQDAaLVOtT0AYHhkI7xO10NoNdlJexs7LhyULyqFlkD44RNiOIM6NXtV9OhyVyUcl1Ep9gG2RymCdXkHIFRCgvIJhQRdahD3qJt2QMjdy3C9F+9x3JXYnCPbzIkmADXiGhLmR1Rh+vtKuWqqsCz+LLnnzsxw//Bn64g1u66PjVr8XpdNZkvJS/eN4AsQ/5lpPLsZkAAAAASUVORK5CYII=

**Comment by chenshanb3** [comment]
> @chenshanb3 这边会是把icon转化成base64存起来，能辛苦你检查一下页面元素，把图片的base64地址贴出来看一下么

经常也会变成这种图标

<img width="412" alt="image" src="https://user-images.githubusercontent.com/96278502/156505378-7679fefc-e487-4324-a78e-f765520648c1.png">

**Comment by chenshanb3** [comment]
@lockiechen 上面的不是透明底黑色的图标，这个才是
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAADAFBMVEUAAAAAADMAAGYAAJkAAMwAAP8AMwAAMzMAM2YAM5kAM8wAM/8AZgAAZjMAZmYAZpkAZswAZv8AmQAAmTMAmWYAmZkAmcwAmf8AzAAAzDMAzGYAzJkAzMwAzP8A/wAA/zMA/2YA/5kA/8wA//8zAAAzADMzAGYzAJkzAMwzAP8zMwAzMzMzM2YzM5kzM8wzM/8zZgAzZjMzZmYzZpkzZswzZv8zmQAzmTMzmWYzmZkzmcwzmf8zzAAzzDMzzGYzzJkzzMwzzP8z/wAz/zMz/2Yz/5kz/8wz//9mAABmADNmAGZmAJlmAMxmAP9mMwBmMzNmM2ZmM5lmM8xmM/9mZgBmZjNmZmZmZplmZsxmZv9mmQBmmTNmmWZmmZlmmcxmmf9mzABmzDNmzGZmzJlmzMxmzP9m/wBm/zNm/2Zm/5lm/8xm//+ZAACZADOZAGaZAJmZAMyZAP+ZMwCZMzOZM2aZM5mZM8yZM/+ZZgCZZjOZZmaZZpmZZsyZZv+ZmQCZmTOZmWaZmZmZmcyZmf+ZzACZzDOZzGaZzJmZzMyZzP+Z/wCZ/zOZ/2aZ/5mZ/8yZ///MAADMADPMAGbMAJnMAMzMAP/MMwDMMzPMM2bMM5nMM8zMM//MZgDMZjPMZmbMZpnMZszMZv/MmQDMmTPMmWbMmZnMmczMmf/MzADMzDPMzGbMzJnMzMzMzP/M/wDM/zPM/2bM/5nM/8zM////AAD/ADP/AGb/AJn/AMz/AP//MwD/MzP/M2b/M5n/M8z/M///ZgD/ZjP/Zmb/Zpn/Zsz/Zv//mQD/mTP/mWb/mZn/mcz/mf//zAD/zDP/zGb/zJn/zMz/zP///wD//zP//2b//5n//8z///8SEhIYGBgeHh4kJCQqKiowMDA2NjY8PDxCQkJISEhOTk5UVFRaWlpgYGBmZmZsbGxycnJ4eHh+fn6EhISKioqQkJCWlpacnJyioqKoqKiurq60tLS6urrAwMDGxsbMzMzS0tLY2Nje3t7k5OTq6urw8PD29vb8/PwgKWLDAAAADUlEQVR42mNgGAXUBwABVgABtqE0xQAAAABJRU5ErkJggg==

**Comment by lockiechen** [comment]
> > @chenshanb3 这边会是把icon转化成base64存起来，能辛苦你检查一下页面元素，把图片的base64地址贴出来看一下么
> 
> 你说的是数据库里的这的icon吗
> 
> <img alt="image" width="914" src="https://user-images.githubusercontent.com/96278502/156505207-4d00ddcb-23a4-4d26-927d-98ff48876169.png">

是的

**Comment by carlyin0801** [comment]
已再https://github.com/Tencent/bk-ci/issues/6285这个issue里解决了这个问题，后续可以关注这个issue
