### ISSUE TITLE
svn插件不推荐使用

### ISSUE THREAD

**Issue by mikeeastin** [Tencent/bk-ci#6237]
bk-ci  : release-1.7版本
使用内置svn-check 插件，提示 该插件已不推荐使用

2022.03.02 10:29:37,783|aec87e7d-8418-4210-93ba-df53d3e5a0fc| [NIO-2 task-3]  INFO c.t.d.p.e.s.PipelineRuntimeService       1911 b-9adefb0dfa5b47eb95ac714b841e383e|UPDATE_TASK_STATUS|Checkout SVN|FAILED|yejiafa|2199002
2022.03.02 10:29:37,796|aec87e7d-8418-4210-93ba-df53d3e5a0fc| [NIO-2 task-3]  INFO c.t.d.p.e.s.v.EngineVMBuildService       533  ENGINE|b-9adefb0dfa5b47eb95ac714b841e383e|Agent|END_TASK|j(1)|e-a230e71fa1284e41ad5b82722f3c14e6|FAILED|type=USER|code=2199002|msg=该插件已不推荐使用,Fail to get the repo([repositoryHashId=8R68, repositoryName=null, repositoryType=ID])]
2022.03.02 10:29:37,798|aec87e7d-8418-4210-93ba-df53d3e5a0fc| [rContainer-1]  INFO c.t.d.p.e.c.CallBackControl              155  passport|p-14421f7b97be4a95a194d2a72ccc228c|b-9adefb0dfa5b47eb95ac714b841e383e|BUILD_TASK_END|null|e-a230e71fa1284e41ad5b82722f3c14e6|callback
2022.03.02 10:29:37,913|aec87e7d-8418-4210-93ba-df53d3e5a0fc| [Container-12]  INFO .p.e.c.c.c.i.StartActionTaskContainerCmd 279  ENGINE|b-9adefb0dfa5b47eb95ac714b841e383e|completeClaimBuildTask|CONTAINER_POST_TASK|stage-2|j(1)|end-1000

**Comment by irwinsun** [comment]
是的，只是不推荐使用，但仍然可以使用，报错应该是SVN拉代码出错了吧。
