### ISSUE TITLE
feature: 流水线变量命名规范

### ISSUE THREAD

**Issue by irwinsun** [Tencent/bk-ci#624]
当前未做限制，任意字符都可命名，存在用户误导的情况：
用户使用了中文名命名，因中文名命名在shell的环境变量不被支持，导致执行出错
需要做：
1. 前端在流水线编辑/ 流水线模块编辑 页面限制用户定义 变量/常量 的命名字符规则为  [A-Za-z_] [A-Za-z_0-9]+
2. 后台保存接口做如上规则限制  [A-Za-z_] [A-Za-z_0-9]+ ， 如不合法，保存失败。

**Comment by irwinsun** [comment]
蓝盾流水线评论: 已部署到灰度环境

**Comment by hingbong** [comment]
[CodePullSvn.vue](https://github.com/Tencent/bk-ci/blob/master/src/frontend/devops-pipeline/src/components/AtomPropertyPanel/CodePullSvn.vue#L159)
这里生成的变量名不符合此规范
