### ISSUE TITLE
更新研发商店插件输出参数使用说明

### ISSUE THREAD

**Issue by fayewong-v5** [Tencent/bk-ci#6380]
**What would you like to be added**:
![image](https://user-images.githubusercontent.com/54432927/159234306-679a81a1-c484-4cfb-8d07-5a1af8b88528.png)
将如上使用说明修改为：
通过表达式${{ jobs.<job_id>.steps.\<step-id\>.outputs.\<output-var-name\> }} 访问，如 ${{ jobs.job1.steps.step1.outputs.a }}

**Why is this needed**:

**Comment by vhwweng** [comment]
转内部
