### ISSUE TITLE
第一步vue编译devops-nav，执行npm run public:external报错

### ISSUE THREAD

**Issue by xiaoda-008** [Tencent/bk-ci#640]
Install webpack to start bundling: 
  $ npm install --save-dev webpack

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! devops-nav@1.0.1 public: `npm run dll && webpack --mode production`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the devops-nav@1.0.1 public script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-19T06_16_22_837Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! devops-nav@1.0.1 public:external: `cross-env NODE_ENV=external npm run public --`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the devops-nav@1.0.1 public:external script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-19T06_16_22_865Z-debug.log

# debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/bin/npm', 'run', 'public:external' ]
2 info using npm@6.13.4
3 info using node@v10.18.1
4 verbose run-script [ 'prepublic:external',
4 verbose run-script   'public:external',
4 verbose run-script   'postpublic:external' ]
5 info lifecycle devops-nav@1.0.1~prepublic:external: devops-nav@1.0.1
6 info lifecycle devops-nav@1.0.1~public:external: devops-nav@1.0.1
7 verbose lifecycle devops-nav@1.0.1~public:external: unsafe-perm in lifecycle true
8 verbose lifecycle devops-nav@1.0.1~public:external: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/data/bk-ci/src/frontend/devops-nav/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr
/bin:/root/bin
9 verbose lifecycle devops-nav@1.0.1~public:external: CWD: /data/bk-ci/src/frontend/devops-nav
10 silly lifecycle devops-nav@1.0.1~public:external: Args: [ '-c', 'cross-env NODE_ENV=external npm run public --' ]
11 silly lifecycle devops-nav@1.0.1~public:external: Returned: code: 1  signal: null
12 info lifecycle devops-nav@1.0.1~public:external: Failed to exec public:external script
13 verbose stack Error: devops-nav@1.0.1 public:external: `cross-env NODE_ENV=external npm run public --`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid devops-nav@1.0.1
15 verbose cwd /data/bk-ci/src/frontend/devops-nav
16 verbose Linux 3.10.0-957.27.2.el7.x86_64
17 verbose argv "/usr/bin/node" "/bin/npm" "run" "public:external"
18 verbose node v10.18.1
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error devops-nav@1.0.1 public:external: `cross-env NODE_ENV=external npm run public --`
22 error Exit status 1
23 error Failed at the devops-nav@1.0.1 public:external script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
~

**Comment by zhanxu33** [comment]
可以按下面的顺序在 `src\frontend` 下面执行
1. npm install -g yarn
2. yarn install
3. yarn start
4. yarn public -s nav // 这个参数是模块名，还可以是pipeline，ticket等
