### ISSUE TITLE
麻烦帮忙支持一下在脚本获取到Task的名称，因为有时候的确需要再错误处理里面知道具体的task名称，并做相应的处理

### ISSUE THREAD

**Issue by knt09** [Tencent/bk-ci#645]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by fayewong-v5** [comment]
bash插件里$name可以获取到当前步骤的名称，这个ok吗？
