### ISSUE TITLE
使用https访问平台时，导入windows构建机界面，下载agent链接应为https

### ISSUE THREAD

**Issue by fayewong-v5** [Tencent/bk-ci#6474]
**What happened**:
使用https访问平台时，导入windows构建机界面，下载agent链接为http协议，无法下载

**What you expected to happen**:
使用https访问平台时，导入windows构建机界面，下载agent链接应为https

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by irwinsun** [comment]
配置问题，非程序问题。
