### ISSUE TITLE
请问后端如何在IDEA中启动起来进行调试

### ISSUE THREAD

**Issue by xbsummer** [Tencent/bk-ci#6477]
请问后端代码，在IDEA中已经编译好了， 如何启动起来， 直接在IDEA里面进行接口断点调试。

**Comment by irwinsun** [comment]
1、开发机需要安装好Consul
2、开发机需要能有一个连得上的MySQL、Redis、RabbitMQ

这块文档还没整好，在外部调试还是有点费劲，因为微服务较多，互相都可能存在依赖关系，所以如果全部在本机启动的话，不太现实，我先说一种方法，启动整合后的后台微服务boot-assembly 微服务（整合所有微服务，除了公共构建机dockerhost和无编译环境buildless模块, 启动有点慢）。

- 复制启动所需配置文件：
   -    将 support-files/templates/下的 所有#etc#.*.yml文件复制到一个特定目录，假设是 /data/bkci/etc目录下
- 对所有配置文件进行改名 （可选）：
   -  mv #etc#ci#common.yml  common.yml  其他文件也类似操作
 - 修改配置中的选项，必改通用配置 common.yml 和 对应微服务配置 application-xxx.yml  xxx为你要调试的微服务，这里是application-assembly.yml 

- 在idea配置 AssemblyApplication.kt 的启动参数：
```
 -Dservice-suffix=bk-ci
-Dspring.config.location=file:/data/bkci/etc/common.yml,file:/data/bkci/etc/application-assembly.yml
-Dservice.log.dir=/data/bkci/logs/assembly
```
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/16686129/161370975-d41ea313-cd65-440e-af6f-95cd472170c9.png">


还有另一种方式是只启动某个微服务，比如 process. 操作方式与上述类型，只是配置文件不同而已。
但需要先有一台CVM先把整个蓝盾服务部署（假设为测试集群A）并启动，并与你要调试的模块在同一个consul注册中心，以便你本地开发启动的服务能注册到测试集群A
- 1、把测试集群A旧要调试的微服务停止
- 2、 在Idea启动要调试的微服务，并成功注册上 测试集群A
- 3、开始测试

**Comment by irwinsun** [comment]
蓝盾的整个平台链条很较长，从前端到后台到底层控制Agent全都涉及
1、产品前端Web
2、流水线服务后台
3、构建机调度程序
4、go编写的Agent程序

 社区目前还是只有少数同学熟悉这套开发流程并能独立调试， 有一定的开发学习门槛， 以及开发调试的成本， 需要投入时间摸索

**Comment by xbsummer** [comment]
谢谢，我先按照你说的试试。 有问题再请教。
