### ISSUE TITLE
feat: 原生适配 Apple M系列Mac构建机

### ISSUE THREAD

**Issue by irwinsun** [Tencent/bk-ci#6495]
背景：
现有devopsAgent 同时支持在 Intel CPU 和Apple M序列 CPU的Mac机型上运行。 但一些较底层的业务编译场景可能会受到影响，比如使用cmake编译器进行编译，会导致在M序列的Mac构建机上编译出来制品仍然属于X86_64架构，而非Arm64构架。
以下几个变量比较明显受到影响：
https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_ARCHITECTURES.html
https://cmake.org/cmake/help/latest/variable/CMAKE_HOST_SYSTEM_PROCESSOR.html
https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_ARCHITECTURES.html

期望： 

- [ ]  原生适配Apple M系列的Mac构建机的devopsAgent程序。

- [ ]  验收标准， 简单在构建中使用Shell执行 uname -m 获得 arm64 而非 x86_64

发布：
<img width="817" alt="image" src="https://user-images.githubusercontent.com/33863729/169788331-746d228f-42f0-4d04-80d4-3536259f48ae.png">
这个需求发布时，需要在保存agentjre的地方添加 linux_arm64 ,linux_mips64 ,macos_arm64三个文件夹，文件夹下存放响应架构的jre才可正常使用。

注意：
因为macos的telegraf的监控指标采集中的 **CPU,DISK** 两个指标的采集依赖于 shirou的cgo开启具体可以参考
https://github.com/influxdata/telegraf/issues/1484
https://github.com/influxdata/telegraf/issues/4801
这两个issue
所以如果需要macos构建机的   **CPU,DISK** 两个指标 需要在对应架构如amd64和arm64上的macos机器使用mackfile中的 **build_macos** 自行编译，编译后放于保存agent的路径即可

**Comment by hingbong** [comment]
这个页面能不能做成配置文件渲染，可以添加linux arm64/mips之类的，根据文件名的规则去下载构建机

**Comment by irwinsun** [comment]
> 这个页面能不能做成配置文件渲染，可以添加linux arm64/mips之类的，根据文件名的规则去下载构建机

是的，目前就是要借这个需求，完善按架构下载。 目前内部开始有一些非标的系统，单独维护也存在一定的维护成本。

**Comment by irwinsun** [comment]
<img width="403" alt="image" src="https://user-images.githubusercontent.com/16686129/163947422-8e80ef26-3325-4f61-8edb-b7659a3f77d6.png">
