### ISSUE TITLE
执行历史界面，支持部分字段能在流水线执行过程中展示

### ISSUE THREAD

**Issue by iccengan** [Tencent/bk-ci#650]
### 现状：
构建历史列表页面，以下字段被赋值后 只能在流水线**执行完成**后才能展示

### 期望：
构建历史列表页面，以下字段被赋值后 在流水线**执行过程中**也能展示

- [x] 【源材料】

- [x] 【触发方式】

- [ ] 【备注】

**Comment by zanyzhao** [comment]
Duplicate of #2981

**Comment by zrms** [comment]
目前只能在流水线结束后备注状态；流水线running过程中，备注字段始终是空白；但是实际上我们经常有需求想在构建过程中一目了然地观察构建过程中暴露出来的一些关键信息及状态；特别是步骤比较复杂，构建过程比较长的流水；点开日志看固然可以，但是日志冒多太多太快，做不到一目了然的观测；我觉得这个技术上应该能实现，而且性价比非常高! 期待排期！

**Comment by iccengan** [comment]
> 目前只能在流水线结束后备注状态；流水线running过程中，备注字段始终是空白；但是实际上我们经常有需求想在构建过程中一目了然地观察构建过程中暴露出来的一些关键信息及状态；特别是步骤比较复杂，构建过程比较长的流水；点开日志看固然可以，但是日志冒得太多太快，做不到一目了然的观测；我觉得这个技术上应该能实现，而且性价比非常高! 期待排期！

了解，我们技术侧评估下

**Comment by iccengan** [comment]
@zrms 已排入v1.8迭代

**Comment by zrms** [comment]
感谢！
