### ISSUE TITLE
能否支持一下DinD

### ISSUE THREAD

**Issue by anan-lee** [Tencent/bk-ci#651]
**Is your feature request related to a problem? Please describe.**
目前的编译环境都是docker环境，但是在实际使用中需要对编译的包到环境中快速验证一下可用性（比如集成测试），那么需要一些其他环境，比如一个redis或者mysql资源
但是这一块目前不能在ci中闭环，目前只能用其他方式闭环

**Describe the solution you'd like**
期望能支持Dind的方式，可以在编译环境中拉取和创建新的docker环境

**Describe alternatives you've considered**

**Additional context**

**Comment by fayewong-v5** [comment]
#1181

**Comment by iccengan** [comment]
后续我们会支持 CVM 的构建机方案，可以内置 mysql、redis 等常见服务。#2095
