### ISSUE TITLE
webhook Message变量移除emoji字符 

### ISSUE THREAD

**Issue by linjun-ddddd** [Tencent/bk-ci#652]

**Comment by zanyzhao** [comment]
不推荐在变量里使用emoji，但因为utf8mb4问题，导致流水线名称中也无法包含emoji，这个确实不好，需要改下

**Comment by iccengan** [comment]
关联需求：#759

**Comment by mingshewhe** [comment]
mysql编码由server端、client端(JDBC)、表、字段决定，server端现在已经是utf8mb4格式，表的编码在创建表的时候设置，修改utf8mb4改动太大，所以修改client端支持utf8mb4，把需要支持emoji格式的字段改成utf8mb4格式。

## client端修改
1. application.xml中增加

   ```yaml
   spring:
       datasource:
             initSql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
   ```

2. 重启服务

## 字段修改

1. 查看字段编码格式

   ```sql
   SHOW FULL COLUMNS FROM table_name
   ```

2. 修改编码

   ```sql
   ALTER TABLE table_name CHANGE column_name column_name VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
   ```
3. 注意事项
- 字段长度
由于从utf8升级到了utf8mb4，一个字符所占用的空间也由3个字节增长到4个字节，但是我们当初创建表时，设置的字段类型以及最大的长度没有改变。例如，你在utf8下设置某一字段的类型为TINYTEXT, 这中字段类型最大可以容纳255字节，三个字节一个字符的情况下可以容纳85个字符，四个字节一个字符的情况下只能容纳63个字符，如果原表中的这个字段的值有一个或多个超过了63个字符，那么转换成utf8mb4字符编码时将转换失败，你必须先将TINYTEXT更改为TEXT等更高容量的类型之后才能继续转换字符编码
- 索引
在InnoDB引擎中，最大的索引长度为767字节，三个字节一个字符的情况下，索引列的字符长度最大可以达到255，四个字节一个字符的情况下，索引的字符长度最大只能到191。如果你已经存在的表中的索引列的类型为VARCHAR(255)那么转换utf8mb4时同样会转换失败。你需要先将VARCHAR(255)更改为VARCHAR(191)才能继续转换字符编码

**Comment by irwinsun** [comment]
改动db影响较大， 建议先只做过滤emoji字符的功能，避免因该字段导致存储失败。

**Comment by irwinsun** [comment]
根据用户不同的数据库字符，开源版本本身是支持ut8mb4， 可能有部分用户使用较老的utf8字符集，而hook的message过滤掉emoji可以理解
