### ISSUE TITLE
流水线不支持事务

### ISSUE THREAD

**Issue by wq57fan** [Tencent/bk-ci#653]
目前流水线是不支持事务吗？假如别人误操作，流水线升级发布执行失败，整个Stage或者job都不会进行回滚？这个后续能否考虑一下优化，谢谢。

**Comment by irwinsun** [comment]
流水线负责向各个业务插件触发，把整个流程串起来，每个具体业务行为逻辑是各业务开发自己控制，是做发布，还是做编译，业务要不要回滚，这是需要在创建流水线时业务自己要考虑，并把它集成进流水线插件提供回滚流水线。换句话说，平台无法得知每个业务回滚逻辑
