### ISSUE TITLE
流水线模板能够支持同时下拉选择代码库和构建分支

### ISSUE THREAD

**Issue by Bobkong** [Tencent/bk-ci#656]
目前自定义流水线模板，可以单独支持下拉选择代码库 或 下拉选择构建分支，但是无法做到下拉选择的代码库后刷新代码库中的所有分支供用户选择。
目前我的解决措施只能是下拉选择代码库，手动输入构建分支。但是如果能够同时下拉选择，体验会好很多，并且防止输入分支名错误等情况的出现。

**Comment by iccengan** [comment]
关联需求：#1130
