### ISSUE TITLE
自定义变量展开“字符串类型”变量后，再展开“单选框/复选框”变量会导致布局错乱

### ISSUE THREAD

**Issue by iccengan** [Tencent/bk-ci#6566]
### 现象：
自定义变量展开某“字符串类型”变量后，再展开“单选框/复选框”变量会导致布局错乱

### 复现路径：
先展开某字符串类型变量
![image](https://user-images.githubusercontent.com/10875468/163786867-a0afea43-803e-46b7-8ce7-e26c48fdadfa.png)
再展开单选框/复选框类型变量
![image](https://user-images.githubusercontent.com/10875468/163786479-f3612b3f-8637-418e-bec4-d8fdfe15fd27.png)

**Comment by lockiechen** [comment]
无法复现
