### ISSUE TITLE
构建资源变量macos环境无默认值

### ISSUE THREAD

**Issue by guoyangping** [Tencent/bk-ci#6567]
**What happened**:
流水线1-1构建选择构建资源变量选择macos环境时无下拉默认值
![image](https://user-images.githubusercontent.com/62585286/163795352-3eec4963-9d99-40dd-a2ef-ed2b19cd458c.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- bk-ci version (use `cat VERSION` in installed dir):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by irwinsun** [comment]
调用RESTful接口是

ms/store/api/user/pipeline/container/projects/bkdevops/oss/MACOS?buildType=MACOS

正确的应该是要拿  私有构建机

buildType=THIRD_PARTY_AGENT_ID
