### ISSUE TITLE
远程触发无法识别调起哪条流水线，且被调的流水线无法知道调用源在哪里

### ISSUE THREAD

**Issue by iccengan** [Tencent/bk-ci#6583]
### 用户需求背景：
一、拿到一条远程调用链接，里面是没有pipelineid信息的，没法知道是用来远程调用哪条流水线，只能凭记忆或口口相传，或者打开一条条流水线去找

二、一条流水线频繁被远程调用，没法排查，是哪里触发的调用，只能通过经验来逐个排查

**Comment by reggieisrunning** [comment]
计划先在远程触发的场景下，增加调用者的source IP

**Comment by reggieisrunning** [comment]
返回增加两个数据：`pipelineId`和`projectId`

**Comment by reggieisrunning** [comment]
总结一下信息：
1. 在返回中增加`projectId`、`pipelineId`、`buildId`，将token加到header中，去除`id`;
2. 在`远程触发`组件的日志打印中增加请求的`source IP`，文案`本次远程调用的来源IP是[x.x.x.x]`;

**Comment by mingshewhe** [comment]
原来远程触发插件接口如下:
![image](https://user-images.githubusercontent.com/22971705/173526958-e3037dd5-7314-4816-b98b-76098014fec6.png)
原来的定义存在几个问题：
1. token 明文放在请求url中，应该放在请求头中
2. url中无法知道触发的流水线Id是哪一条
3. 原来接口只返回一个buildId

### 解决方案：
请求url改成：ms/process/api/external/pipelines/{projectId}/{pipelineId}/remote/build -H "Content-Type: application/json" -H "X-TOKEN: $token" 
接口返回值增加：pipelineId,projectId
source IP可以从请求头reaip获取

### 实现方式:
老接口保持不变，新增一个接口，接口定义如下
```
@ApiOperation("远程触发构建")
    @POST
    @Path("/{projectId}/{pipelineId}/remote/build")
    fun remoteBuild(
        @ApiParam("projectId", required = true)
        @PathParam("projectId")
        projectId: String,
        @ApiParam("pipelineId", required = true)
        @PathParam("pipelineId")
        pipelineId: String,
        @ApiParam("远程认证信息", required = true)
        @HeaderParam("X-TOKEN")
        token: String,
        @ApiParam("请求Ip", required = true)
        @HeaderParam("realip")
        realIp: String?,
        @ApiParam("启动参数", required = true)
        values: Map<String, String>
    ): Result<BuildId>
```

**Comment by mingshewhe** [comment]
> 原来远程触发插件接口如下: ![image](https://user-images.githubusercontent.com/22971705/173526958-e3037dd5-7314-4816-b98b-76098014fec6.png) 原来的定义存在几个问题：
> 
> 1. token 明文放在请求url中，应该放在请求头中
> 2. url中无法知道触发的流水线Id是哪一条
> 3. 原来接口只返回一个buildId
> 
> ### 解决方案：
> 请求url改成：ms/process/api/external/pipelines/{projectId}/{pipelineId}/remote/build -H "Content-Type: application/json" -H "X-TOKEN: $token" 接口返回值增加：pipelineId,projectId source IP可以从请求头reaip获取
> 
> ### 实现方式:
> 老接口保持不变，新增一个接口，接口定义如下
> 
> ```
> @ApiOperation("远程触发构建")
>     @POST
>     @Path("/{projectId}/{pipelineId}/remote/build")
>     fun remoteBuild(
>         @ApiParam("projectId", required = true)
>         @PathParam("projectId")
>         projectId: String,
>         @ApiParam("pipelineId", required = true)
>         @PathParam("pipelineId")
>         pipelineId: String,
>         @ApiParam("远程认证信息", required = true)
>         @HeaderParam("X-TOKEN")
>         token: String,
>         @ApiParam("请求Ip", required = true)
>         @HeaderParam("realip")
>         realIp: String?,
>         @ApiParam("启动参数", required = true)
>         values: Map<String, String>
>     ): Result<BuildId>
> ```
新的方案:
url保持不变，接口也保持不变，返回参数增加projectId，pipelineId，日志输出sourceIp
