### ISSUE TITLE
流水线需求权限控制需求

### ISSUE THREAD

**Issue by txekodong** [Tencent/bk-ci#6584]
背景：
    1. 流水线执行前，stage/job/task等可以去除勾选，跳过执行，但是在项目中的使用规则对部分流水线不允许跳过执行，目前无法实现。
    2. 流水线某些步骤执行失败后可以跳过，去勾选“失败时继续”可以不允许跳过，但是编辑此规则不需要管理员。
需求：
    1. 【高】对指定的流水线（或者配置到节点），必须按照执行，不允许“去勾选”
    2. 【中】流水线插件“流程控制选项”，由管理员配置。

**Comment by irwinsun** [comment]
@txekodong 请问是腾讯内部的同学吗

**Comment by txekodong** [comment]
是的，这是我提的，之前2000拉的一个同学让我在上面提需求的。



董亚宾 ekodong DevOps平台组员工 腾讯
 ----------回复的邮件信息----------
 ***@***.***&gt; 于2022年4月21日(周四) 晚上7:59写道:

  


@txekodong 请问是腾讯内部的同学吗

**Comment by irwinsun** [comment]
沟通后可以通过模板统一管控解决。
