### ISSUE TITLE
希望可以批量添加人员

### ISSUE THREAD

**Issue by jessehardy** [Tencent/bk-ci#659]
现在添加人员页面只能一个一个输入，然后鼠标点选，不支持粘贴分号分隔的人员名单，对于建立新项目会很麻烦。
如果能批量添加，那就方便很多。

如果能按照组织架构，自动同步一个用户组，这样有人入职离职的时候不需要手动去操作，那就更理想了。

**Comment by iccengan** [comment]
Duplicate of #2148
