### ISSUE TITLE
插件执行时长是否可以支持1个月或者更久?

### ISSUE THREAD

**Issue by juddliang** [Tencent/bk-ci#661]
这边的业务偏AI一些，推荐、搜索的业务，整个流程比较长，从需求到上线估计要20多天到一个月，中间会关联一些自己开发的工具，比如ABtest平台，模型训练平台，模型评估评测平台等.我们想开发一个插件接入流水线,但是蓝盾的流水线插件最长超时时间只支持7天,我们的插件执行可能需要1到2个月.是否可以支持?

**Comment by iccengan** [comment]
插件及Job长时间运行会占用CI平台大量资源。推荐使用Stage审核功能来满足上述需求。
