### ISSUE TITLE
【蓝鲸社区版7.0】流水线添加新的 linux job 时，没有默认的构建资源、镜像，且打开配置页时报错

### ISSUE THREAD

**Issue by fayewong-v5** [Tencent/bk-ci#6692]
**What happened**:
![image](https://user-images.githubusercontent.com/54432927/167243202-de54c337-8bc5-41c4-878d-aa2c2b7d0e26.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- bk-ci version (use `cat VERSION` in installed dir):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by stubenhuang** [comment]
fix in #4935
