### ISSUE TITLE
1.8.0无法创建项目

### ISSUE THREAD

**Issue by chenshanb3** [Tencent/bk-ci#6698]
版本：v1.8.0
问题：创建项目时提示无法创建可用的数据源

<img width="977" alt="image" src="https://user-images.githubusercontent.com/96278502/167328988-5f0d304b-ac00-4ee6-84bc-8ebd7c744f4d.png">

**Comment by irwinsun** [comment]
v1.8.1 已经修复这个问题
https://github.com/Tencent/bk-ci/releases/tag/v1.8.1
