### ISSUE TITLE
流水线增加版本管理功能

### ISSUE THREAD

**Issue by zanyzhao** [Tencent/bk-ci#671]
- 流水线执行历史
![image](https://user-images.githubusercontent.com/1629409/74346608-c7eb6400-4dea-11ea-966c-bef629867bd0.png)

- 流水线编辑页
![image](https://user-images.githubusercontent.com/1629409/74346640-d33e8f80-4dea-11ea-812a-4ff67efba7e1.png)

- 版本列表右滑框
![image](https://user-images.githubusercontent.com/1629409/74346662-dd608e00-4dea-11ea-9112-7636f1f712fd.png)

**Comment by fayewong-v5** [comment]
查看编排历史入口如图所示，点击右滑出版本列表：
![image](https://user-images.githubusercontent.com/54432927/80095404-73a6f200-859a-11ea-97e2-eeaf9fdd2d8e.png)

**Comment by iccengan** [comment]
如果流水线没有变更，保存时不要生成新的编排号。

**Comment by iccengan** [comment]
历史构建内添加快捷按钮：恢复为当前编排

**Comment by yhaoyan** [comment]
期望这里有对于每个流水线的历史版本

大概几点，优先级高到低。难度低到高

1. 修改人
2. 单次修改内容
3. 和历史任意版本比较
4. 回滚到指定版本

**Comment by fabio-he** [comment]
main.dll.js?v=0.29655255453833584:1 GET http://test.devops.oa.com/ms/process/api/user/pipelines/test-01/p-3778bcc6d2764cdc9b4fa566af53ca4f/version?page=1&pageSize=15 404 (Not Found)
![image](https://user-images.githubusercontent.com/56472792/112596765-36508180-8e47-11eb-8660-a06d1175a9cc.png)
![版本报404](https://user-images.githubusercontent.com/56472792/112596821-4a947e80-8e47-11eb-8bb9-eab58f08377b.png)

**Comment by irwinsun** [comment]
此特性由社区用户行行开发，目前与设计上是存在出入的，考虑该功能在社区大量用户已经在实际生产中运行，将会影响到用户，
版本的时间关系，暂时只做必要的代码和数据简化，不做大的调整。 如做大调整需要进行周全的数据迁移方案方可操作。

@zanyzhao @iccengan @fayewong-v5

**Comment by iccengan** [comment]
优化编排更新的提示状态：#4022
