### ISSUE TITLE
蓝盾构建是使用私有maven仓库

### ISSUE THREAD

**Issue by gaoxuande** [Tencent/bk-ci#6724]
蓝盾使用maven构建java项目时，如何更换使用私有的maven仓库（nexus）

**Comment by irwinsun** [comment]
你这个问题这个可以看下maven官方的介绍 https://maven.apache.org/settings.html

一般是把settings.xml 放到2个位置，
The Maven install: ${maven.home}/conf/settings.xml
A user's install: ${user.home}/.m2/settings.xml

但还有第三方方式，就是用命令指定

mvn --settings  your_settings.xml

**Comment by gaoxuande** [comment]
> 你这个问题这个可以看下maven官方的介绍 https://maven.apache.org/settings.html
> 
> 一般是把settings.xml 放到2个位置， The Maven install: ${maven.home}/conf/settings.xml A user's install: ${user.home}/.m2/settings.xml
> 
> 但还有第三方方式，就是用命令指定
> 
> mvn --settings your_settings.xml
> 
> 在CI环境里，建议用第三方方式。

我使用的蓝盾的公共构建机，在哪里更换这个公共构建机的settings.xml文件呢

**Comment by irwinsun** [comment]
> > 你这个问题这个可以看下maven官方的介绍 https://maven.apache.org/settings.html
> > 一般是把settings.xml 放到2个位置， The Maven install: ${maven.home}/conf/settings.xml A user's install: ${user.home}/.m2/settings.xml
> > 但还有第三方方式，就是用命令指定
> > mvn --settings your_settings.xml
> > 在CI环境里，建议用第三方方式。
> 
> 我使用的蓝盾的公共构建机，在哪里更换这个公共构建机的settings.xml文件呢

如果非要改环境，建议自己定义构建镜像，集成到镜像里。

**Comment by irwinsun** [comment]
制作镜像的文档：https://github.com/TencentBlueKing/BKDocs/blob/master/ZH/6.0/%E6%8C%81%E7%BB%AD%E9%9B%86%E6%88%90%E5%B9%B3%E5%8F%B0/%E4%BA%A7%E5%93%81%E7%99%BD%E7%9A%AE%E4%B9%A6/Services/Store/docker-build.md
