### ISSUE TITLE
日志组件优化相关功能

### ISSUE THREAD

**Issue by zanyzhao** [Tencent/bk-ci#678]
- [x] job日志展示优化
- [x] 换行符自动换行，超过一定宽度自动换行
- [x] 日志增加搜索功能
- [x] 日志右键事件，双击选择文本
- [x] 下载日志优化，增加下载进度条

**Comment by zhanxu33** [comment]
日志二期优化相关功能：
1. job日志展示优化
2. 日志数据接入websocket
3. 单行文本多种颜色展示，换行符自动换行，超过一定宽度自动换行
4. 日志分享功能，改成在每一行后面显示一个icon，鼠标悬浮的时候显示
5. 日志增加搜索功能
6. 日志右键事件，双击选择文本
7. 下载日志优化，增加下载进度条

**Comment by irwinsun** [comment]
蓝盾流水线评论: 开发已自测通过，已发布到测试服，请测试团队测试

**Comment by irwinsun** [comment]
蓝盾流水线评论: 已部署到灰度环境
