### ISSUE TITLE
feat: stream支持github

### ISSUE THREAD

**Issue by tangruotian** [Tencent/bk-ci#6799]
**目标**
stream服务支持github各类事件触发以及接口实现

**具体实现**
参照stream已有的tgit版实现
- StreamGitTransferService 提供前端数据的接口
- BaseAction github触发相关的各类事件
- StreamGitApiService github触发需要的各类接口

**Comment by mingshewhe** [comment]
@Florence-y 
common-github-sdk新增以下接口:
- [ ] [Get a repository](https://docs.github.com/en/rest/repos/repos#get-a-repository)
- [ ] [Get repository content](https://docs.github.com/en/rest/repos/contents#get-repository-content)
- [ ] [List repositories for the authenticated user](https://docs.github.com/en/rest/repos/repos#list-repositories-for-the-authenticated-user)
- [ ] [Create or update file contents](https://docs.github.com/en/rest/repos/contents#create-or-update-file-contents)

repository服务plugin-github模块新增以下接口
- ServiceGithubRespoitoryResource，接口中封装方法调用上面方法


@liuandhisgithub 
common-github-sdk新增以下接口
- [ ]  [List commits](https://docs.github.com/en/rest/commits/commits#list-commits)
- [ ] [Get a commit](https://docs.github.com/en/rest/commits/commits#get-a-commit)
- [ ] [List branches](https://docs.github.com/en/rest/branches/branches#list-branches)
- [ ] [Get a branch](https://docs.github.com/en/rest/branches/branches#get-a-branch)
- [ ] [Get a pull request](https://docs.github.com/en/rest/pulls/pulls#get-a-pull-request)
- [ ] [List pull requests files](https://docs.github.com/en/rest/pulls/pulls#list-pull-requests-files)
- [ ] [Get a tree](https://docs.github.com/en/rest/git/trees#get-a-tree)
- [ ] [Create a check run](https://docs.github.com/en/rest/checks/runs#create-a-check-run)
- [ ]  [Update a check run](https://docs.github.com/en/rest/checks/runs#update-a-check-run)

repository服务plugin-github模块新增以下接口
- ServiceGithubCommitsResource
- ServiceGithubBranchResource
- ServiceGithubPRResource
- ServiceGithubDatabaseResource
- ServiceGithubCheckResource
