### ISSUE TITLE
减少不必要的构建任务

### ISSUE THREAD

**Issue by yhd4711499** [Tencent/bk-ci#686]
有这样一个需求场景：
同一个repo，设置了push触发构建。当已有自动触发的构建任务（A）在运行时，此时再push，将会开始新的构建任务（B），然后再一次push，又开始了新的任务（C）。此时一共有ABC三个任务同时运行，而B其实是多余的。

期望这里能够优化，增加一个队列模式【仅一个且保持最新】，达到这样的效果：
触发构建（A）时，如果已有相同条件触发的构建任务正在运行，则创建构建任务A放入队列。如果A在执行前又有相同条件触发的构建任务B来了，则删掉A，换成B。
这样就不会构建中间的任务，而且保证最后构建是最新的提交。

**Comment by irwinsun** [comment]
这个已经是有的了，如下图，通过调整队列数量为1，可保持永远只有一个最新的构建排队，老的自动被移除队列。
![image](https://user-images.githubusercontent.com/16686129/76542198-9c2dcd80-64bf-11ea-9478-ee30aa326e61.png)

**Comment by yhd4711499** [comment]
我试试，谢谢！
