### ISSUE TITLE
日志不支持进度条

### ISSUE THREAD

**Issue by legendtang** [Tencent/bk-ci#691]
**Describe the bug**
像这样的进度条无法在日志的 bash 插件的输出展示。比如 https://github.com/tqdm/tqdm 的实现
![image](https://raw.githubusercontent.com/tqdm/tqdm/master/images/tqdm.gif)
![image](https://user-images.githubusercontent.com/1352729/74534698-45d87800-4f6f-11ea-8f1a-295c0cff40cf.png)

**To Reproduce**
使用 tqdm 打印进度条

**Expected behavior**
正确显示进度条

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by iccengan** [comment]
日志终端不是交互式的，无法打印插件执行中的实时状态。
