### ISSUE TITLE
删除流水线支持配置 是否将其构建机里的文件自动清理

### ISSUE THREAD

**Issue by iccengan** [Tencent/bk-ci#697]
### 场景：
流水线里配置了私有构建机，且工作空间是默认的 [Agent安装目录]/workspace/[流水线id]。则删除该流水线时，能自动清理 xxx/[流水线id] 路径下的文件。

### 描述：
如果没有联动删除功能，用户会在删除流水线后不知道要删除第三方构建机workspace下的哪个子目录。很多人删流水线的时候不会去删目录，到最后磁盘满了才去删除，这时候却没办法很方便地找到具体是哪个目录对应被删除的流水线。

**Comment by YangKa** [comment]
相同诉求，现在人肉存储删除很痛苦，对于删除的任务完全无法追踪。
希望能增加能力之一：
1.增加流水线删除联动删除构建机对于文件下数据能力
2.增加开发api查询项目下所有流水任务 id列表，这样使用方可以写个脚本定期匹配删除

**Comment by zanyzhao** [comment]
> 1.增加流水线删除联动删除构建机对于文件下数据能力
> 2.增加开发api查询项目下所有流水任务 id列表，这样使用方可以写个脚本定期匹配删除

1的风险太大，一旦删错，构建机就废了
2的话目前有这个API，可以咨询下devops-helper，或者到API文档里找找
