### ISSUE TITLE
使用openapi获取项目报错 ： curl http://devops.xxx.com/ms/openapi/api/apigw/v3/projects?access_token=xxx

### ISSUE THREAD

**Issue by hujingguang** [Tencent/bk-ci#6986]
{
  "status" : 400,
  "message" : "Parameter specified as non-null is null: method com.tencent.devops.openapi.resources.apigw.v3.ApigwProjectResourceV3Impl.list, parameter userId"
}

根据官方文档并未说明需要提交userId字段，

![image](https://user-images.githubusercontent.com/11848843/173484706-a080990f-97b0-495d-97d7-89bbef9151e3.png)

**Comment by irwinsun** [comment]
文档问题，缺少相应字段
需要加一个头：

X-DEVOPS-UID: 你的用户id

**Comment by yongyiduan** [comment]
文档已加
