### ISSUE TITLE
流水线重试stage提示构建不存在

### ISSUE THREAD

**Issue by xunkd** [Tencent/bk-ci#7027]
![image](https://user-images.githubusercontent.com/107660746/174206764-3e498454-3cbf-485b-bb72-f3f2b9632425.png)
流水线取消后重试stage出现构建不存在，等待一段时间后恢复正常

**Comment by irwinsun** [comment]
这个属于提示信息不正确。 正确的提示应该是“构建已经启动，请不要重复点击”
