### ISSUE TITLE
[Feature Request] `::set-variable / ::set-output` 支持多行文本输入

### ISSUE THREAD

**Issue by lyngai** [Tencent/bk-ci#7059]
**What would you like to be added**:

`::set-variable / ::set-output` 支持多行文本输入

**Why is this needed**:

需求场景是需要从 linux 编译环境动态生成 message，作为参数传入 `无编译环境-人工审核` 插件，或 `新建合并请求插件`。目前 `::set-variable / output` 并不支持多行文本的输入，只能通过将换行符替换为转义字符（`\n`）的方式输入。
在前述的两个场景下，因无法执行文本替换的指令，导致无法将明文的 `\n` 还原为换行符。

**Comment by fayewong-v5** [comment]
可以先用研发商店中的 RunScript 插件
format_multiple_lines "::set-output name=content_a::$content"

**Comment by lyngai** [comment]
> 可以先用研发商店中的 RunScript 插件 format_multiple_lines "::set-output name=content_a::$content"

可行
