### ISSUE TITLE
pref:job中运行的插件结束后可根据配置项决定是否主动kill插件对应的进程

### ISSUE THREAD

**Issue by carlyin0801** [Tencent/bk-ci#7090]
**问题：** 有些比较吃内存的插件遇到异常后还没有完全退出的时候因为插件配置了重试而又拉起一个进程，新进程运行的过程会发生OOM
**解决方案：** 如果插件开发者在插件的task.json中配置的finishKillFlag的值为true，那么job中运行的插件结束后应主动kill插件对应的进程（配置DEVOPS_DONT_KILL_PROCESS_TREE标识的插件除外）

**Comment by irwinsun** [comment]
#4224
