### ISSUE TITLE
git事件触发插件增加“可指定特定人”触发

### ISSUE THREAD

**Issue by roninjiang** [Tencent/bk-ci#7138]
![image](https://user-images.githubusercontent.com/88226119/176616765-cde3c5f5-861d-4deb-8807-5184b5ce06f4.png)

如上图所示，有些流水线只希望特定的人员触发，
当前的状态是为了让特定人员触发，需要把团队里面其他的人都排除掉，很麻烦

我希望增加一个选项，限定只让“指定的人”触发流水线

**Comment by reggieisrunning** [comment]
作为流水线用户
我希望：
    在使用“git事件触发器”时
    1. 可以指定具体的提交人来触发流水线构建
这样我就可以：
    1. 只用填写“指定的提交人”，无需枚举排除所有的不可触发的提交人
