### ISSUE TITLE
流水线插件默认前端组件

### ISSUE THREAD

**Issue by WCJ-Chance** [Tencent/bk-ci#7148]
如何改造流水线插件（非自定义前端）默认前端组件，相关代码在哪里？

**Comment by lockiechen** [comment]
@WCJ-Chance 相关的代码路径：
/bk-ci/src/frontend/devops-pipeline/src/components/AtomPropertyPanel/atomMixin.js
/bk-ci/src/frontend/devops-pipeline/src/components/AtomPropertyPanel/AtomContent.vue
/bk-ci/src/frontend/devops-pipeline/src/components/AtomPropertyPanel/NormalAtomV2.vue

**Comment by WCJ-Chance** [comment]
> @WCJ-Chance 相关的代码路径： /bk-ci/src/frontend/devops-pipeline/src/components/AtomPropertyPanel/atomMixin.js /bk-ci/src/frontend/devops-pipeline/src/components/AtomPropertyPanel/AtomContent.vue /bk-ci/src/frontend/devops-pipeline/src/components/AtomPropertyPanel/NormalAtomV2.vue

Thx
