### ISSUE TITLE
feat: 流水线构建执行页面中task显示运行中的耗时

### ISSUE THREAD

**Issue by reggieisrunning** [Tencent/bk-ci#7153]
我作为：会出现单task耗时长的蓝盾流水线用户

我希望：
    1. 在流水线构建执行页面就可以显示“当前运行中”的task的执行耗时

这样我就可以：
    1. 直接在页面上关注到当前task的执行时长，从而判断是否需要检查task是否正常，而不是点进日志，通过看开始时间和当前时间进行二次判断

预期效果：
![image](https://user-images.githubusercontent.com/82890468/176818359-c55bdf0c-b155-422c-b8fd-9a1724c965c6.png)

**Comment by irwinsun** [comment]
后台已经返回了开始时间戳，前端自行计算后并根据当前时间的秒针动态++++++++++
