### ISSUE TITLE
[优化] 回收站内流水线，列表中首列的流水线名称表单无法调整宽度，导致流水线名称缩略显示无法看到。

### ISSUE THREAD

**Issue by VarOne92** [Tencent/bk-ci#7157]

**Comment by reggieisrunning** [comment]
我作为：
       需要恢复回收站中流水线的蓝盾流水线用户

我希望：
       1. 回收站中流水线名称展示宽度可以变长，并可以由用户调整回收站流水线列表的宽度

这样我就可以：
       1. 一眼看到我想要恢复的流水线，方便我定位进而恢复流水线

**Comment by fabio-he** [comment]
目前还不支持忽略大小写

**Comment by fabio-he** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
