### ISSUE TITLE
【蓝盾】【产品-无需评审会】feat: 版本体验更新人员名单时，额外通知新增人员当前体验版本的信息

### ISSUE THREAD

**Issue by reggieisrunning** [Tencent/bk-ci#7234]
我作为：
        版本体验的维护者

我希望：
        1. 当体验组、体验人员更新时，会对新增的人员通知一次当前版本体验的提示信息

这样我就可以：
        1. 让新增的人员收到版本体验的信息通知，从而更快的下载包，而无需我人工的去通知新增的人员
 
期望的验收标准：
        1. 当体验组、体验人员名单添加人员时，只有新增的人员可以收到版本体验信息通知
        2. 过期的版本体验不发送通知(add@20220808)

**Comment by EchoQT** [comment]
已设定的被通知人员部分的变更相关处理逻辑要补全说明

**Comment by reggieisrunning** [comment]
> 已设定的被通知人员部分的变更相关处理逻辑要补全说明

已设定的被通知人员处理逻辑打算与之前保持一致

当前生产环境上的版本体验是：
1. 人员名单是由管理员指定的，并不是邀请制，已设定的人员被去除时，不会通知被去除；
2. 创建一个体验强关联一个客户端包，不可修改，所以一个体验的包下载信息不会有更新；
3. 在名单中的人才可以下载，但如果被去除前已经下载了包，去除就没有意义了；
所以这里理解的是：
1. 如果从人员名单中被去除掉，是管理员认为这个人不应该在这个体验中，可以阻断他后续去下载；
2. 人员被去除后，再通知其被去除掉这个体验，感觉会有骚扰；

**Comment by EchoQT** [comment]
ok，这次说明白了
