### ISSUE TITLE
bug: 构建通知勾选启用企业微信群通知出现排序错乱问题

### ISSUE THREAD

**Issue by guoyangping** [Tencent/bk-ci#7260]
**What happened**:
![image](https://user-images.githubusercontent.com/62585286/179211497-9d4caedb-d58f-449c-9760-427286d94586.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- bk-ci version (use `cat VERSION` in installed dir):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by vhwweng** [comment]
转内部需求，该单子关闭
