### ISSUE TITLE
由于同一条流水线需要根据参数支持不同的构建资源，所以希望”指定构建资源“可以支持输入框

### ISSUE THREAD

**Issue by ivanxwwu** [Tencent/bk-ci#730]
由于同一条流水线需要根据参数支持不同的构建资源，所以希望”指定构建资源“可以支持输入框

**Comment by iccengan** [comment]
@ivanxwwu “指定构建资源”已支持输入框
![image](https://user-images.githubusercontent.com/10875468/83528234-72fb6700-a51b-11ea-9944-f504efb73363.png)
