### ISSUE TITLE
[蓝盾][产品-已评审]云托管构建资源支持Windows公共构建机

### ISSUE THREAD

**Issue by fayewong-v5** [Tencent/bk-ci#7402]
作为
开发

我希望
蓝盾的云构建资源，除了Linux、macOS外，支持：
- Windows Server 2022
- Windows Server 2019

以便于
- 进行项目构建时，无需自行维护windows第三方构建机，减少如个人构建机IOA上下线导致断网等问题的维护成本
- 降低构建机成本

期望的验收标准
1、UI方式下，添加  Windows Job 时可以选中对应资源类型：
<img width="514" alt="image" src="https://user-images.githubusercontent.com/54432927/184152104-07e90d1b-1263-4a93-bc18-511362d5c7cc.png">

2、code方式下，可以通过 runs-on 关键字指定：
```
job1:
  runs-on: windows-2022
```

**Comment by EchoQT** [comment]
只要devcloud支持该服务，我们就可以在公司内部环境快速集成该服务。
但同时，外部版本里面其实还是没有办法集成这个服务的对吧。注意这种情况仍然不要在代码上分版本支持。
