### ISSUE TITLE
git监听事件能否动态支持增量git仓库

### ISSUE THREAD

**Issue by ivanxwwu** [Tencent/bk-ci#744]
我们的场景是这样的
开发语言是go，，使用gomod方式编译
每个服务独立仓库
希望在每个服务增加git tag的时候触发流水线，
但是每次增加新服务的时候，，就需要在流水线新增一个“git事件监听插件",比较麻烦
这个插件能否支持监听git group下的所有服务？

**Comment by zanyzhao** [comment]
如果只是CI场景的话，可以试下内部的工蜂CI
