### ISSUE TITLE
网关解析url的query参数失败

### ISSUE THREAD

**Issue by freyzheng** [Tencent/bk-ci#746]
网关的url_util.lua工具类，在解析不带参数的url的时候回报错。
错误如下：
2020/02/24 12:37:05 [error] 42111#42111: *338948588 lua entry thread aborted: runtime error: conf/lua/util/url_util.lua:27: bad argument #1 to 'find' (string expected, got nil)
stack traceback:
coroutine 0:
        [C]: in function 'find'
        conf/lua/util/url_util.lua:27: in function 'Split'
        conf/lua/util/url_util.lua:51: in function 'parseUrl'
        /usr/local/openresty/nginx/conf/lua/auth/auth_app.lua:21: in function </usr/local/openresty/nginx/conf/lua/auth/auth_app.lua:1>, client: 9.198.131.169, server: v2-dev.bkdevops.qq.com, request: "GET /experience/api/app/experiences/list HTTP/1.1", subrequest: "/auth/app", host: "*"****
2020/02/24 12:37:05 [error] 42111#42111: *338948588 auth request unexpected status: 500, client: 9.198.131.169, server: ********, request: "GET /experience/api/app/experiences/list HTTP/1.1", host: "*****"

**Comment by irwinsun** [comment]
蓝盾流水线评论: 已部署到灰度环境
