### ISSUE TITLE
关于流水线的问题,构造机无法执行命令

### ISSUE THREAD

**Issue by lilirui520** [Tencent/bk-ci#75]
下面是构造机 agent.log
![image](https://user-images.githubusercontent.com/11851179/63421453-2e468980-c43b-11e9-8a22-abe76a8d75e4.png)

**Comment by irwinsun** [comment]
1.确认下/data/bkee/bkci/gateway/lua/init.lua 上的redis和/data/bkee/etc/bkci/common.yml里面配置的是否一致
2. Redis必须要有密码
