### ISSUE TITLE
流水线执行失败通知需要展示最后执行的插件名字，因此请预设全局变量获取失败前最后执行插件的名字

### ISSUE THREAD

**Issue by oyc502** [Tencent/bk-ci#750]
流水线执行失败通知需要展示最后一个插件名字，不然的话执行失败看消息通知完全不知道是什么原因
因此需要预设全局变量以获取失败前最后执行插件的名字，以便流水线通知可以加上这个最后执行插件名字，这样我们就可以简单判断流水线执行失败的原因了

**Comment by ErWeiWang** [comment]
# 强烈支持，期待平台快速上线该功能。

- 要不流水线那么多插件，执行异常大家都要每个人都去点击，太耗费大家的工作

**Comment by zanyzhao** [comment]
增加“失败插件别名”的系统变量，内置到“流水线失败时通知”里

**Comment by iccengan** [comment]
关联需求：
#929 
#755 
#620

**Comment by fayewong-v5** [comment]
在流水线状态转为失败前，设置全局变量 BK_CI_BUILD_FAIL_TASK：
1、失败的TASK信息格式：[编号]JOB别名-TASK别名
2、若有多个并发JOB失败，使用英文分号分隔

示例：
BK_CI_BUILD_FAIL_TASK=[2-1-3]单元测试-junit测试;[2-3-1]代码检查-pylint
