### ISSUE TITLE
[蓝盾][产品-无需评审会]feat：私有化版本对齐蓝鲸 footer 和 title 规范2.0

### ISSUE THREAD

**Issue by fayewong-v5** [Tencent/bk-ci#7505]
**What would you like to be added**:
按照蓝鲸 footer 和 title 规范2.0，优化蓝盾/制品库私有化版本页面footer 和 title：

1、title规范（注意竖线前后有空格）
中文：<平台名称> | 腾讯蓝鲸智云 | <服务>
英文：<平台英文名称> | Tencent BlueKing | <服务英文名>

注：
- 蓝盾平台名称中文名为“持续集成平台-蓝盾”，英文名为“BK-CI”
- 制品库中文名为“制品库”，英文名为“BK-REPO”
- **本issue仅规范各服务首页，进入资源详情后的页面另开issue优化**

示例：
- 持续集成平台-蓝盾 | 腾讯蓝鲸智云 | 首页
- 持续集成平台-蓝盾 | 腾讯蓝鲸智云 | 流水线
- 持续集成平台-蓝盾 | 腾讯蓝鲸智云 | 凭证管理
- 持续集成平台-蓝盾 | 腾讯蓝鲸智云 | 环境管理
- 制品库 | 腾讯蓝鲸智云

2、footer 规范
<img width="480" alt="image" src="https://user-images.githubusercontent.com/54432927/187343121-e906a4b3-20f2-4e63-b5c2-e815dd5b5b03.png">

注：
- 技术支持：https://wpa1.qq.com/KziXGWJs?_type=wpa&qidian=true
- 社区论坛：https://bk.tencent.com/s-mart/community/
- 产品官网：https://bk.tencent.com/index/
- 版本号为当前环境部署的蓝盾版本号
- 仅在首页添加 footer

**Why is this needed**:
蓝鲸v6/v7 统一规范要求

**Comment by EchoQT** [comment]
ok

**Comment by fabio-he** [comment]
![image](https://user-images.githubusercontent.com/56472792/188775251-91cc509a-86f0-46cb-a5a6-21a9592ee1f6.png)

**Comment by fabio-he** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
