### ISSUE TITLE
【蓝盾】【产品-已评审】蓝盾APP的流水线中，构建产物支持obb和apks下载

### ISSUE THREAD

**Issue by reggieisrunning** [Tencent/bk-ci#7507]
### 背景：
在海外Google Play商店上架的游戏包有两种格式：
1. apk+obb: 2021年8月前使用的格式。安装apk后，只需要将obb下载放置到「\<shared-storage\>/Android/obb/\<package-name\>/」路径下即可正常运行；
2. aab: 2021年8月后使用的格式。aab只能在google play上传发布后，通过商店界面正式安装；本地调试安装必须连电脑使用bundletool工具进行。目前找到一种其他方法去实现：将aab转为apks，再使用工具安装apks。目前研发正在研究如何在蓝盾app上安装apks；

### 我作为：
蓝盾APP流水线用户

### 我希望：
1. 在蓝盾APP的android客户端上下载流水线构建产物时，可以下载”obb扩展包“或”apks包“

### 这样我就可以：
1. 无需额外操作将obb、apks传到手机上，直接从蓝盾app下载安装；

#### 当前的情况：
- 只允许下载apk和ipa，其他格式不允许下载
<img width="604" alt="image" src="https://user-images.githubusercontent.com/82890468/187339479-dc1a6b41-7809-445e-ab51-bca5d0b0ee4d.png">

#### 期望的效果
- 短期内，在流水线的构建产物列表中，先放开obb和apks的下载能力，用户下载后，自行操作安装，减少“必须通过别的途径将obb或apks包传输到手机上”的步骤，直接从流水线可以获取到产物
(注：apk+obb一步直接安装会在“版本体验”优化中体现)

**Comment by EchoQT** [comment]
需要合起来使用的几种文件格式，产出物列表是否也把这种情况合在一条记录上，不仅便于提供一起下载、一起安装的功能，也能直观的表达出这两个东西是永远在一起的，在形式上可以认为是一个东西。

**Comment by EchoQT** [comment]
ok

**Comment by fayewong-v5** [comment]
下载已支持
