### ISSUE TITLE
【stream】notices关键字下的receivers和ccs 字段支持每个item中指定多个用户，使用逗号分隔

### ISSUE THREAD

**Issue by fayewong-v5** [Tencent/bk-ci#7592]
**What would you like to be added**:
notices关键字下的receivers和ccs 字段支持每个item中指定多个用户，使用逗号分隔

**Why is this needed**:
目前流水线变量为 string类型，receivers和ccs 值为数组，在未支持函数的情况，无法进行接收人的参数化

**Comment by tangruotian** [comment]
涉及到改动的关键字有
notices下 receivers，ccs，chat-id
reviews下 reviewers
gate下的 gatekeepers

**Comment by yongyiduan** [comment]
需要支持变量形式传入
