### ISSUE TITLE
当前stage 人工审核进入审核流程以及审核驳回时，审核通知发送给触发人，希望提供开关来控制此特性

### ISSUE THREAD

**Issue by daveliu114** [Tencent/bk-ci#7704]
fcd这边是通过批量包装流水线来进行审批的，如果每条流水线都发送消息给触发人，首先会对触发人接收过多信息不友好，其次fcd已经内嵌了蓝盾，不希望用户直接去蓝盾原生页面上操作，如果发送了此消息，会给操作人进入蓝盾原生页面的入口。 建议考虑一下我们这种特殊场景的诉求。

**Comment by fayewong-v5** [comment]
#7971 中优化
