### ISSUE TITLE
bugfix: 获取Svn文件接口对Codecc的FilePath参数特殊处理

### ISSUE THREAD

**Issue by linjun-ddddd** [Tencent/bk-ci#774]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by irwinsun** [comment]
蓝盾流水线评论:  @irwinsun 开发已自测通过，已发布到测试服，请测试团队测试

**Comment by irwinsun** [comment]
蓝盾流水线评论: 已部署到灰度环境

**Comment by irwinsun** [comment]
蓝盾流水线评论:  @irwinsun 开发已自测通过，已发布到测试服，请测试团队测试

**Comment by irwinsun** [comment]
蓝盾流水线评论: 已部署到灰度环境
