### ISSUE TITLE
bugfix: 质量红线指标不生效 &源材料不显示

### ISSUE THREAD

**Issue by linjun-ddddd** [Tencent/bk-ci#787]
1. 加了命名空间，源材料不显示问题
2. codecc删除多余文件、日志
3. 红线搜索指标不生效
4. worker部分exception调整

**Comment by irwinsun** [comment]
蓝盾流水线评论:  @irwinsun 开发已自测通过，已发布到测试服，请测试团队测试

**Comment by irwinsun** [comment]
蓝盾流水线评论: 已部署到灰度环境
