### ISSUE TITLE
feature：流水线被删除后，无法感知、无法查询、无法恢复

### ISSUE THREAD

**Issue by yoferzhang** [Tencent/bk-ci#791]
**Is your feature request related to a problem? Please describe.**
流水线项目被其他管理员删除了，无法感知到删除时间点，而且不知道是谁删掉的，无法询问删除原因。

**Describe the solution you'd like**
1.删除流水线通知管理员
2.做一个已删除流水线列表，有删除时间和操作人。
3.能恢复流水线，或者能复制已删除的流水线。

**Comment by iccengan** [comment]
可考虑放入操作日志，如新版蓝盾的 通知中心-站内信 里

**Comment by iccengan** [comment]
1 & 2：#672
3：#542
