### ISSUE TITLE
【产品-无需评审会】【研发商店】按关键字搜索插件时，支持根据插件英文标识搜索

### ISSUE THREAD

**Issue by fayewong-v5** [Tencent/bk-ci#7917]
**What would you like to be added**:
研发商店按照关键字搜索插件时，目前仅支持按照名称和简介进行模糊匹配，希望根据插件的英文标识也可以匹配到插件（模糊匹配）
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/54432927/199392073-821fdf5b-5818-4a73-9b3d-e93483ce472f.png">

**Why is this needed**:
在流水线 code 化场景（stream服务）下，用户在YAML中通过插件英文标识引用插件，当看到 YAML 配置希望了解对应插件的功能时，会到研发商店搜索插件，此时需要根据英文标识来搜索。
<img width="606" alt="image" src="https://user-images.githubusercontent.com/54432927/199392324-8e833375-8d1f-421c-8d16-c866c7edd4bf.png">

**Comment by EchoQT** [comment]
ok
