### ISSUE TITLE
feature：流水线构建号支持全局唯一

### ISSUE THREAD

**Issue by osblow** [Tencent/bk-ci#793]
我们希望跨流水线维护一个构建号，每次构建成功自动加1

**Comment by iccengan** [comment]
@osblow 能描述下具体的需求场景吗？
有几个疑问：
1. 跨流水线的构建号用在什么地方？
2. 是否指定的某几条流水线构建才需要+1？
3. 构建开始+1、构建结束+1还是构建结束且成功才+1？
