### ISSUE TITLE
【蓝盾】【产品-无需评审会】feat:质量红线默认通知人改为流水线触发人

### ISSUE THREAD

**Issue by carrywang05** [Tencent/bk-ci#7934]
**What would you like to be added**:
为了更好地知会到相关人，质量红线终止后会默认通知流水线执行人。需要进行以下修改：
1、质量红线被拦截后的默认通知人改为流水线触发人；
2、以下文案修改为：“请输入通知人员，支持输入流水线变量。默认发给流水线触发人”
<img width="528" alt="image" src="https://user-images.githubusercontent.com/46527215/200331316-7f0a748d-e449-4990-9d46-5cc7220a8292.png">

**Why is this needed**:
流水线执行人目前存在问题，具体请见 https://github.com/Tencent/bk-ci/issues/7933

**Comment by EchoQT** [comment]
ok
