### ISSUE TITLE
Bug:流水线变量设置了执行时不显示，但是子流水线调用时仍会全部展示

### ISSUE THREAD

**Issue by carrywang05** [Tencent/bk-ci#7936]
**What happened**:
第一步：将流水线变量AA和BB设置为执行时不显示。（主要是为了执行时更加便利快捷，执行人不用关心所有变量）
<img width="640" alt="image" src="https://user-images.githubusercontent.com/46527215/200458514-d81a89ce-9ff0-4c06-8e6c-b690d7aabd27.png">
第二步：执行流水线时可以看到，AA和BB不展示；
<img width="909" alt="image" src="https://user-images.githubusercontent.com/46527215/200458781-8322a381-476e-4595-b373-5a93f6cd4d10.png">
第三步：执行子流水线调用插件时，AA和BB又都冒出来了。
<img width="810" alt="image" src="https://user-images.githubusercontent.com/46527215/200459173-4543a269-52b8-4b38-b62b-9710dd63f178.png">

**What you expected to happen**:
执行子流水线调用插件时，设置为执行时不展示的AA和BB不需要展示出来，与单独执行流水线时保持一致。

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- bk-ci version (use `cat VERSION` in installed dir):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by irwinsun** [comment]
我感觉不是问题，执行时不展示不代表就一定不能赋值（比如API调用、子流水线调用）
而考虑子流水线调用也有灵活性的要求，可能其希望能修改启动参数

**Comment by mingshewhe** [comment]
如果希望始终使用子流水线的变量，可以把参数后面的勾去掉，就会一直使用子流水线的配置
