### ISSUE TITLE
【蓝盾人工审核插件】支持群通知

### ISSUE THREAD

**Issue by Larrisali** [Tencent/bk-ci#7980]
**What would you like to be added**:
希望人工审核插件可以支持群通知：
<img width="304" alt="企业微信截图_58260399-de36-45db-a08f-5ac5526a000f" src="https://user-images.githubusercontent.com/44602092/201566569-1609da0b-6e25-4166-9aa4-d812ad07c6d0.png">

**Why is this needed**:
背景：我们有统一的上线群，希望审批流程在群里@负责同学，进行审批

**Comment by fayewong-v5** [comment]
#7971 中优化
