### ISSUE TITLE
【蓝盾-评审会已评审】【PAC】feat：关联工蜂代码库时，支持开启 Pipeline as Code 模式

### ISSUE THREAD

**Issue by fayewong-v5** [Tencent/bk-ci#8115]
【目标】
支持代码库开启 Pipeline as Code 模式

【需求详情】
关联工蜂代码库到蓝盾时，支持开启 PAC 模式（Pipeline as Code）
1、关联工蜂代码库时，若尚未授权，需先进行授权
<img width="400" alt="image" src="https://user-images.githubusercontent.com/54432927/206349289-c136e180-5317-4bd3-b010-e35e2316b2a0.png">
- 增加授权用途说明
- 一期若开启 PAC，需进行 OAUTH 授权。预留权限对接接口，后续可能会扩展授权方式

2、授权后开启界面如下：
<img width="400" alt="image" src="https://user-images.githubusercontent.com/54432927/206656763-57aecc31-c079-477c-9493-bb47e28d5070.png">
- 若选中的代码库已开启过 PAC，则提示已开启过，可以通过“查看流水线”入口跳转至对应的流水线列表
<img width="400" alt="image" src="https://user-images.githubusercontent.com/54432927/206658348-a38c58ab-410a-4c4f-b174-5eb9fa6b0c3c.png">

3、选中代码库，打开 PAC 开关：
<img width="400" alt="image" src="https://user-images.githubusercontent.com/54432927/207770488-1c39a66e-a70c-447d-ab22-061dbcdc7060.png">
- 点 「确定」 后，后台检查代码库默认分支 .ci 目录下是否有 YAML 文件，如果有，参考同步规则 #8130 同步流水线到蓝盾

**Comment by EchoQT** [comment]
ok
