### ISSUE TITLE
无法将项目名称的小写字母改为大写

### ISSUE THREAD

**Issue by zanyzhao** [Tencent/bk-ci#812]
会提示项目已存在
![image](https://user-images.githubusercontent.com/1629409/76159323-3e655280-615a-11ea-8475-9c35b24adb2b.png)

**Comment by Roy9102** [comment]
@irwinsun 这个是后端较验接口哈，需要后端处理一下

**Comment by irwinsun** [comment]
此为后端db字段project_name的问题， 需要更改为 utf8mb4_bin

**Comment by irwinsun** [comment]
蓝盾流水线评论:  @irwinsun 开发已自测通过，已发布到测试服，请测试团队测试

**Comment by irwinsun** [comment]
蓝盾流水线评论: 已部署到灰度环境
