### ISSUE TITLE
【蓝盾】【产品-无需评审会】增加“最近使用的流水线”功能及相关优化

### ISSUE THREAD

**Issue by reggieisrunning** [Tencent/bk-ci#8183]
# 需求背景：
在流水线组灰度过程中，有部分用户反映不容易找到流水线、操作繁琐，收集反馈后分析的主要原因有以下几点：
1. 之前用户的视图中包含有30~80条流水线，通过滚动鼠标“下拉加载”方式实现翻页。但现在默认为列表的分页模式，默认展示10条，用户需要点击来进行翻页，操作成本略有增加；
2. 用户因为习惯需求流水线大致位置，滚动后然后肉眼定位具体流水线位置。新版上来后，默认的列表模式打破了原有使用习惯，一时间不适应；
3. 当前卡片尺寸与之前有差异，一页展示内容变少，打破了原有使用习惯，一时间不适应；
4. 虽然用户所在项目使用了“项目视图”进行分类，但个体用户只关注“项目视图”下的“自己需要使用的流水线”，并不关注视图内其他流水线，且之前视图功能较深，很少有用户养成创建“个人视图”的习惯；

# 需求目标：
1. 方便用户定位到自己需求的流水线；
2. 强化“收藏”功能（一种笼统的、类似于“我常用的流水线”的快速添加流水线进组的方式）；

# 需求：
1. 增加“最近使用的流水线”功能，以跟“我收藏的流水线”一样的特殊组形式存在；
![image](https://user-images.githubusercontent.com/82890468/209044420-2312c4e5-caa5-497b-93ac-ef0d40bb83ca.png)
2. “最近使用的流水线”的相关规则：
    - 只要对流水线有「查看、编辑、执行」任一操作，均认为是“最近使用的流水线”；
    - 只展示最近使用的30条流水线；
    - 如某条“最近使用的流水线”即便被放到回收站，也需要出现在“最近使用的流水线”中，除非被彻底删除掉；
3. 进入「项目-流水线列表首页」的相关改动：
     ![image](https://user-images.githubusercontent.com/82890468/209045983-0569bc9a-048b-4b3b-91e9-34417ddecac2.png)
    - 当”最近使用的流水线“为空时，则默认展示的为”全部流水线“；
    - 当”最近使用的流水线“不为空时，则默认展示的为”最近使用的流水线“；
4. 收藏功能提示强化：
    - 将“收藏”按钮从overflow中提出来，与“执行”并列，协助用户快速建立“我的常用”
    ![image](https://user-images.githubusercontent.com/82890468/209045861-06d79fc0-c6c0-448c-8dc0-bc742b423d2c.png)
    ![image](https://user-images.githubusercontent.com/82890468/209045886-2f3a7902-3aed-4157-a856-209e52a14dd5.png)
5. 列表展示数量优化：
    - 默认展示10个改为50个；

**Comment by EchoQT** [comment]
ok
