### ISSUE TITLE
feature: iOS客户端 -- 用户无法区别构件列表存在同名但不同路径的文件

### ISSUE THREAD

**Issue by HahnSC** [Tencent/bk-ci#823]
如构件归档在
文件1:  ./folderA/fileA
文件2: ./folderB/fileA 
此时在 Web 页面可以通过路径判断，而手机客户端就无法区别了，列表中存在两个 fileA 
建议下面标注构件的相对路径。

**Comment by iccengan** [comment]
内部需求内部跟进。新版app解决。
