### ISSUE TITLE
启动流水线preview界面时偶现Cannot read property 'xx' of null/undefined

### ISSUE THREAD

**Issue by zanyzhao** [Tencent/bk-ci#824]
![image](https://user-images.githubusercontent.com/1629409/76200534-c451ce00-622c-11ea-95a0-002d043599a3.png)

**Comment by irwinsun** [comment]
![image](https://user-images.githubusercontent.com/16686129/76208328-6b893200-623a-11ea-9291-a6723140ec55.png)
