### ISSUE TITLE
feature: Git事件触发插件的配置项可根据事件类型改变

### ISSUE THREAD

**Issue by iccengan** [Tencent/bk-ci#826]
需求背景：【Git事件触发插件】的事件类型选择为【Tag Push Hook】时，【监听以下目标分支】和【排除以下目标分支】等配置项仍为可视状态，给用户带来歧义。

解决方案：
配置项支持 根据选择的事件类型来展示配置项。如事件类型选择为【Tag Push Hook】后，配置项应展示【监听以下Tag名称】，而不再展示【监听以下目标分支】和【排除以下目标分支】，因为这两个配置项不会对【Tag Push Hook】类型造成影响。

关联需求：#727

**Comment by irwinsun** [comment]
蓝盾流水线评论:  @irwinsun 开发已自测通过，已发布到测试服，请测试团队测试

**Comment by irwinsun** [comment]
蓝盾流水线评论: 已部署到灰度环境
