### ISSUE TITLE
【蓝盾-无需评审会】perf：流水线删除后的展示优化

### ISSUE THREAD

**Issue by fayewong-v5** [Tencent/bk-ci#8270]
1、已删除的流水线，在除了「最近使用的流水线」之外的其他分组中，在列表的最后展示。而不是现网这样和活跃流水线一起排序
<img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/212827398-191bf8da-c61b-4c3a-9baa-16e0df76f9f8.png">

2、在「最近使用的流水线」组下，已删除的流水线去掉「移出分组」入口（这个分组不是用户手动管理的，无需移出操作）
<img width="600" alt="image" src="https://user-images.githubusercontent.com/54432927/212827719-0c95465c-8bcf-40f0-807c-9213c5a2f92a.png">

**Comment by EchoQT** [comment]
ok

**Comment by vuuv** [comment]
建议在批量管理可以批量移出已删除流水线。
