### ISSUE TITLE
流水线使用研发商店发布的镜像作为公共构建机启动不了

### ISSUE THREAD

**Issue by dhLai** [Tencent/bk-ci#839]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by irwinsun** [comment]
蓝盾流水线评论:  @irwinsun 开发已自测通过，已发布到测试服，请测试团队测试

**Comment by irwinsun** [comment]
蓝盾流水线评论: 已部署到灰度环境
