### ISSUE TITLE
feature: 增加一个修改约束模式流水线实例的路径

### ISSUE THREAD

**Issue by frellica** [Tencent/bk-ci#846]
场景：团队内使用流水线时，为了方便统一修改更新，半强制要求大家选择”约束模式“从模板创建流水线。当有个别流水线内的变量需要修改时，目前正确的方法是先打开流水线模板，再找到对应实例，点击编辑。实际操作中，经常容易第一反应进入流水线的编辑界面，即`/console/pipeline/项目名/p-流水线ID/edit`这个路径，进行修改，而约束模式下该界面是禁止修改的。

希望可以在该界面直接修改流水线变量。
或者，可以在该界面增加一个到`/console/pipeline/项目名/template/模板ID/createInstance/实例ID#p-流水线ID`，即正确的修改流水线变量的界面的捷径链接，类似 #370

**Comment by zanyzhao** [comment]
Duplicate of #370
