### ISSUE TITLE
feature：增加流水线编辑和执行详情页的小地图

### ISSUE THREAD

**Issue by zanyzhao** [Tencent/bk-ci#848]
![image](https://user-images.githubusercontent.com/1629409/76421977-77fabf80-63df-11ea-9041-c1e9f5064e00.png)

**Comment by irwinsun** [comment]
蓝盾流水线评论: 开发已自测通过，已发布到测试服，请测试团队测试

**Comment by irwinsun** [comment]
蓝盾流水线评论: 已部署到灰度环境
