### ISSUE TITLE
快速退出功能

### ISSUE THREAD

**Issue by 18383510230** [Tencent/bk-ci#85]
右上角用户按钮加入了快速退出功能，退出功能仅在对接了蓝鲸登录系统后才有用
![image](https://user-images.githubusercontent.com/38147689/63562105-ef294d00-c58e-11e9-9dd5-eb56e022c91a.png)

**Comment by zanyzhao** [comment]
目前bk-ci独立搭建时确实没有较好的权限管理，只是对接了配套蓝鲸统一登录实现的账号管理。
最近我们正准备做一个简化版的Auth，在不对接蓝鲸社区版的情况下也可以正常使用简单的权限管理，敬请期待
