### ISSUE TITLE
插件参数支持包含特殊字符的变量嵌套替换

### ISSUE THREAD

**Issue by carlyin0801** [Tencent/bk-ci#873]
插件参数支持包含特殊字符的变量嵌套替换，比如插件参数data对应的值是"{\"dataKey\":\"abc_${testEnv}\"}"，data的值里面包含变量testEnv，如果变量testEnv是类似"{\"test\":1}"这样的json串时，要求data的值进行变量替换后也能正常解析成为标准的json串。

**Comment by irwinsun** [comment]
蓝盾流水线评论: 已部署到灰度环境
