### ISSUE TITLE
feature: 内置代码插件支持新的源材料显示方式

### ISSUE THREAD

**Issue by linjun-ddddd** [Tencent/bk-ci#879]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by irwinsun** [comment]
蓝盾流水线评论: 开发已自测通过，已发布到测试服，请测试团队测试

**Comment by irwinsun** [comment]
蓝盾流水线评论: 已部署到灰度环境
