### ISSUE TITLE
流水线带执行权限的用户没有备注权限

### ISSUE THREAD

**Issue by busha1994** [Tencent/bk-ci#881]
现象：只有执行权限的开发者无法添加备注
原因：没有开通项目的编辑权限

建议：该问题已有人提过一单，https://github.com/Tencent/bk-ci/issues/455，
执行历史添加备注只是一个很常规的操作，但是需要的权限级别较高，和修改整个项目的配置是同一个权限。由于项目负责人配置好相关设置后不想其他组内同事修改，防止出现问题，所以一般不会给编辑权限，但是执行历史又需要添加备注。该单子之前回复是可以通过在流水线运行中使用
setEnv "BK_CI_BUILD_REMARK" "你想要的备注"，设置备注。

我认为这样不太合理，因为备注并不是一个固定的参数，不同人编译的不同包是不一样的，备注自然也不一样，而提供的方法需要去改bash插件，即便这里可以改，我保存编译后，为了不影响后面人编译包备注问题我还得再改回来，否则后面的人编译出的包备注会同上一个一样。这样的操作极其冗余，希望能够把备注功能和编辑权限剥离开来，让有执行权限的人也可以进行备注。

希望能够支持上这个功能，谢谢~

**Comment by zanyzhao** [comment]
目前已经是“执行人”可以修改执行历史备注了哈，你可以确认下
Duplicate of #455
