### ISSUE TITLE
希望可以在流水线构建触发参数里设置必填

### ISSUE THREAD

**Issue by waqq77** [Tencent/bk-ci#900]
蓝盾流水线，设置构建触发参数时，希望能有个勾选项【必填】，必填的参数留空的话无法继续执行。
如图所示，像git_branch这个参数一样，有个红点表示必填
![image](https://user-images.githubusercontent.com/7361366/76933053-3ad68600-6927-11ea-9ce6-50eff61e39e3.png)

**Comment by iccengan** [comment]
必填属性去除，通过正则校验入参来满足此需求。#2018
