### ISSUE TITLE
接口需求: 批量实例化及更新实例的变量值

### ISSUE THREAD

**Issue by mk-qi** [Tencent/bk-ci#903]
通过模版创建的流水线, 模板更新后, 可以批量更新实例的模板版本, 但是实例化过程中模板中设定的一些变更的值 需要每一个实例点进去进行更新 ,我们目有有200个实例. 期望 能提供接口.

**Comment by claudexie** [comment]
附议~

**Comment by irwinsun** [comment]
接口已有实现
