### ISSUE TITLE
模板更新之后，更新到所有的实例时对应的实例的推荐版本号都被回退到模板的版本号，而不是流水线的的

### ISSUE THREAD

**Issue by bstsnail** [Tencent/bk-ci#915]
![image](https://user-images.githubusercontent.com/16055826/77040350-b7826680-69f2-11ea-9b84-ff510d015944.png)
![image](https://user-images.githubusercontent.com/16055826/77040385-c701af80-69f2-11ea-9729-77cf82fadec4.png)

**Comment by fayewong-v5** [comment]
构建号也一样被重置，类似这些实例里可能会被修改的值，不应该在更新时被模板修改

**Comment by royalhuang** [comment]
补充修复推荐版本号的执行时可见同步问题

**Comment by irwinsun** [comment]
蓝盾流水线评论: 开发已自测通过，已发布到测试服，请测试团队测试

**Comment by irwinsun** [comment]
蓝盾流水线评论: 已部署到灰度环境
