### ISSUE TITLE
bug:流水线插件全部执行完成后，构建无法自动终止

### ISSUE THREAD

**Issue by linkamen** [Tencent/bk-ci#927]
bug:流水线插件全部执行完成后，构建无法自动终止

**Comment by irwinsun** [comment]
这个有具体的信息不

**Comment by irwinsun** [comment]
e.engine.pipeline.build.element.finish 这个Exchange是用于作度量的一个逻辑
是一个比较特殊的处理，不属于流程核心部分，将拆分出来作为可选项。一般不需要追加。

**Comment by irwinsun** [comment]
蓝盾流水线评论: 开发已自测通过，已发布到测试服，请测试团队测试

**Comment by irwinsun** [comment]
蓝盾流水线评论: 已部署到灰度环境
