### ISSUE TITLE
失败的流水线支持手动结束，不允许再重试插件

### ISSUE THREAD

**Issue by jerrybean** [Tencent/bk-ci#933]
问题：
执行失败的流水线插件始终可以重试。
期望：
失败的流水线支持手动锁定，锁定后不允许重试，类似执行过程中被人为取消。
背景：
某个发布环境失败，人工介入后发现有问题。但是开发人员经过几个小时之后误操作点击了重试，导致发布了有问题的包。

**Comment by iccengan** [comment]
你的意思是：
1. 全局锁定（对流水线设置后，流水线不允许被重试）？
2. 插件锁定（单个插件可进行配置是否锁定）？
3. 还是插件执行失败后，才对插件进行锁定？
个人认为方案1比较通用，适用场景多，并且人为操作的成本最低，方案2其次，方案3不合理。

**Comment by jerrybean** [comment]
流水线目前失败后右上角可以rebuild。希望支持一个按钮类似锁定，不允许再被重试

**Comment by zanyzhao** [comment]
有点像lock build的意思，那谁有权限去设置lock呢？lock之后允不允许unlock，谁可以unlock？

**Comment by irwinsun** [comment]
> 问题：
> 执行失败的流水线插件始终可以重试。
> 期望：
> 失败的流水线支持手动锁定，锁定后不允许重试，类似执行过程中被人为取消。
> 背景：
> 某个发布环境失败，人工介入后发现有问题。但是开发人员经过几个小时之后误操作点击了重试，导致发布了有问题的包。

从背景来看是某岗位人员拥有了 生产发布流水线的“执行”权限造成的。流水线权限本身已经细化“执行，编辑，查看”，需要项目管理员再次梳理下项目下人员的权限分配。 

另外有权限的人点错后可以马上取消，除非点击重试的人员不清楚自己点击了rebuild。

建议可在rebuild按钮触发时增加二次确认，相信可以减少无意识的操作。

**Comment by irwinsun** [comment]
另：关闭 手动重试有该特性 #2175 可以根据自身流水线特点，在编排时就确认是否允许被重试

**Comment by irwinsun** [comment]
> > 问题：
> > 执行失败的流水线插件始终可以重试。
> > 期望：
> > 失败的流水线支持手动锁定，锁定后不允许重试，类似执行过程中被人为取消。
> > 背景：
> > 某个发布环境失败，人工介入后发现有问题。但是开发人员经过几个小时之后误操作点击了重试，导致发布了有问题的包。
> 
> 从背景来看是某岗位人员拥有了 生产发布流水线的“执行”权限造成的。流水线权限本身已经细化“执行，编辑，查看”，需要项目管理员再次梳理下项目下人员的权限分配。
> 
> 另外有权限的人点错后可以马上取消，除非点击重试的人员不清楚自己点击了rebuild。
> 
> 建议可在rebuild按钮触发时增加二次确认，相信可以减少无意识的操作。#1620

目前Rebuild按钮因支持失败Job重试 #389， 出现二次弹框，所以不需要再做二次确认
![image](https://user-images.githubusercontent.com/16686129/119108347-aef04a80-ba52-11eb-9d7c-da5d98a7eae7.png)

**Comment by irwinsun** [comment]
失败插件的重试功能目前仍然有大量使用场景，特别是在发布部署阶段。 
暂时不会关闭 失败插件的重试功能， 防止 误触问题还得从 权限管理入手
