### ISSUE TITLE
feature: 新增通用头部X-DEVOPS-APP-CODE

### ISSUE THREAD

**Issue by freyzheng** [Tencent/bk-ci#946]
该头部是用作openpai的鉴权使用，通过appCode来判断是否具有接口的访问权限。

**Comment by irwinsun** [comment]
蓝盾流水线评论: 开发已自测通过，已发布到测试服，请测试团队测试

**Comment by irwinsun** [comment]
蓝盾流水线评论: 已部署到灰度环境

**Comment by irwinsun** [comment]
蓝盾流水线评论: 开发已自测通过，已发布到测试服，请测试团队测试

**Comment by irwinsun** [comment]
蓝盾流水线评论: 已部署到灰度环境
