### ISSUE TITLE
流水线job中包含状态为SKIP的插件，job执行完后总时间显示的是SKIP插件前面的所有插件执行时间之和

### ISSUE THREAD

**Issue by carlyin0801** [Tencent/bk-ci#948]
流水线job中包含状态为SKIP的插件，job执行完后总时间显示的是SKIP插件前面的所有插件执行时间之和
![image](https://user-images.githubusercontent.com/5268164/77290774-d72dcd80-6d17-11ea-9cf9-f2efef47c2bc.png)

**Comment by irwinsun** [comment]
蓝盾流水线评论: 开发已自测通过，已发布到测试服，请测试团队测试

**Comment by irwinsun** [comment]
蓝盾流水线评论: 已部署到灰度环境
