### ISSUE TITLE
safari不支持解析类似2020/3-23这种日期格式，而chrome是支持的，统一改成2020/3/23

### ISSUE THREAD

**Issue by lockiechen** [Tencent/bk-ci#949]
流水线安装包趋势页面，对日期解析方式存在不兼容问题，导致safari无法展示流水线安装包趋势

![image](https://user-images.githubusercontent.com/33082528/77293379-288c8b80-6d1d-11ea-83d6-c5bc8ddfc91c.png)

**Comment by irwinsun** [comment]
蓝盾流水线评论: 开发已自测通过，已发布到测试服，请测试团队测试

**Comment by irwinsun** [comment]
蓝盾流水线评论: 已部署到灰度环境
