### ISSUE TITLE
流水线选择镜像界面，手动输入镜像时，对应凭证支持可输入变量

### ISSUE THREAD

**Issue by fayewong-v5** [Tencent/bk-ci#952]
### 作为
流水线构建镜像变量化，通过模版控制时

### 我希望
流水线选择镜像界面，手动输入镜像时，对应凭证支持可输入变量

### 以便于
凭证设置为变量，供其他项目使用模版时传入自己项目下的凭证

**Comment by irwinsun** [comment]
蓝盾流水线评论: 已部署到灰度环境
