### ISSUE TITLE
怎么部署网关啊，没看明白，我是小白

### ISSUE THREAD

**Issue by bihaiyu** [Tencent/bk-ci#957]
部署并启动bk-ci网关
网关主要是配置文件和lua脚本，所以只需要将网关gateway的外链到nginx的conf目录
1. 拷贝nginx代码到部署目录 - cp -r {{code}}/gateway __INSTALL_PATH__/__MODULE__/
2. 外链部署目录到nginx的config - rm -rf /usr/local/openresty/nginx/conf && ln -s __INSTALL_PATH__/__MODULE__//gateway /usr/local/openresty/nginx/conf

看不懂啊~~~~怎么拷贝啊，__INSTALL_PATH__/__MODULE__/这个路径是哪来的啊

**Comment by durendel** [comment]
配置文件里有配置

**Comment by bihaiyu** [comment]
__INSTALL_PATH__/__MODULE__/
在哪个配置文件里啊？求科普

**Comment by bihaiyu** [comment]
> 
> 
> 配置文件里有配置
在哪个配置文件里啊？求科普

**Comment by durendel** [comment]
scripts/bkenv.properties其实就是一个安装目录，保持统一就行，渲染配置文件的时候用

**Comment by durendel** [comment]
> > 配置文件里有配置
> > 在哪个配置文件里啊？求科普

scripts/bkenv.properties其实就是一个安装目录，保持统一就行，渲染配置文件的时候用
