### ISSUE TITLE
我想尝试下这个应用，请问V1版本是稳定版本吗

### ISSUE THREAD

**Issue by durendel** [Tencent/bk-ci#960]
想体验试用下，请问v1和default哪个是稳定版本

**Comment by irwinsun** [comment]
你好，是的，v1配套的镜像是https://hub.docker.com/repository/docker/blueking/bk-ci如果只是体验，可以拉这个镜像体验

**Comment by durendel** [comment]
> 你好，v1分支是旧版本，
> v1配套的镜像是https://hub.docker.com/repository/docker/blueking/bk-ci
> 如果只是体验，可以拉这个镜像体验

请问现在有稳定版本吗可以使用吗

**Comment by irwinsun** [comment]
当前v2的bug还有点多，不太稳定，如果想直接用，v1的镜像那块是可以的

**Comment by zanyzhao** [comment]
经过一段时间打磨，你可以试下我们的[Release](https://github.com/Tencent/bk-ci/releases)中包含的版本

**Comment by durendel** [comment]
> 经过一段时间打磨，你可以试下我们的[Release](https://github.com/Tencent/bk-ci/releases)中包含的版本

好的
