### ISSUE TITLE
部署网关启动是出错

### ISSUE THREAD

**Issue by coeur-cai** [Tencent/bk-ci#963]
错误描述：在网关部署阶段，执行./sbin/nginx启动时，报以下错误
[root@localhost nginx]# ./sbin/nginx
nginx: [emerg] open() "/usr/local/openresty/nginx/conf/devops.server.conf" failed (2: No such file or directory) in /usr/local/openresty/nginx/conf/nginx.conf:55

说是没有找到devops.server.conf配置文件，查看了下这个目前下确实没有这个配置文件，像upstream.conf、init.conf、devops.proxy.conf文件都有

**Comment by zanyzhao** [comment]
可以参考[网关部署文档](https://github.com/Tencent/bk-ci/blob/master/docs/install/gateway.md)，里面有提到：
![image](https://user-images.githubusercontent.com/1629409/79869417-e5086880-8413-11ea-8a06-5876353e86c1.png)

**Comment by mikeeastin** [comment]
[root@jszx-test sbin]# ./nginx  -t 
nginx: [emerg] invalid number of arguments in "upstream" directive in /usr/local/openresty/nginx/conf/vhosts/devops.bkrepo.upstream.conf:1
nginx: configuration file /usr/local/openresty/nginx/conf/nginx.conf test failed
[root@jszx-test sbin]# cat /usr/local/openresty/nginx/conf/vhosts/devops.bkrepo.upstream.conf
upstream  {
    server ;
}

**Comment by mikeeastin** [comment]
[root@jszx-test scripts]# sh ./render_tpl -m ci ../support-files/templates/gateway*
render ../support-files/templates/gateway#core#auth.conf -> /data/bkee/ci/gateway/core/auth.conf
render ../support-files/templates/gateway#core#devops.server.conf -> /data/bkee/ci/gateway/core/devops.server.conf
render ../support-files/templates/gateway#core#lua#init.lua -> /data/bkee/ci/gateway/core/lua/init.lua
render ../support-files/templates/gateway#core#server.common.conf -> /data/bkee/ci/gateway/core/server.common.conf
render ../support-files/templates/gateway#core#vhosts#devops.bkrepo.upstream.conf -> /data/bkee/ci/gateway/core/vhosts/devops.bkrepo.upstream.conf
