### ISSUE TITLE
feat: 杜绝浪费，在Job上增加相关特性，避免不必要的开销

### ISSUE THREAD

**Issue by zanyzhao** [Tencent/bk-ci#970]
## 作为
CI平台的构建机管理员

## 我希望
能够为每个项目分配Job耗时的配额

## 以便于
- 约束普通用户合理分配Job

## 期望的验收标准
- [ ] 为每个项目增加Job最大并发数限制
- [ ] 为每个项目增加公共构建机的Job时长配额

**Comment by irwinsun** [comment]
优化定时任务规则，去掉秒
有关联issue #1487
