### ISSUE TITLE
PR merged事件触发与代码回推需求

### ISSUE THREAD

**Issue by breezelxp** [Tencent/bk-ci#979]
### 作为
DevOps 团队里的Dev，要实践持续部署流水线

### 我希望
1. 流水线的触发插件能够支持PR merged动作触发流水线。
2. 可以支持auth认证，能够将流水线里的代码回推到github。

### 以便于
- 自动合github中的代码。并进行CI集成。

### 期望的验收标准
- 有PR合入，触发代码分支自动合并，在流水线的最后，将合并后的代码回退主库。

**Comment by zanyzhao** [comment]
问题2我们确认一下 @fayewong-v5 ，问题1的话，PR Merge不就等于目标分支的commit push事件吗？ @breezelxp

**Comment by breezelxp** [comment]
@zanyzhao pr merge 是独立的事件，和commit push 没关系。

**Comment by iccengan** [comment]
@breezelxp ok哈，我们先研究一下github的API。

**Comment by irwinsun** [comment]
与api无关系，回推可直接使用git push原生指令
