### ISSUE TITLE
feature: Gitlab webhook 触发流水线的 api

### ISSUE THREAD

**Issue by hingbong** [Tencent/bk-ci#984]
### 期望的验收标准
- 一个 api 能够让 Gitlab 在 webhook 中触发蓝盾流水线

**Comment by irwinsun** [comment]
OK, 我们将现有使用的接口发出来

**Comment by irwinsun** [comment]
蓝盾流水线评论: 开发已自测通过，已发布到测试服，请测试团队测试

**Comment by irwinsun** [comment]
蓝盾流水线评论: 已部署到灰度环境
