### ISSUE TITLE
流水线常量和模板常量使用

### ISSUE THREAD

**Issue by taohuifa** [Tencent/bk-ci#990]
作为
使用devops的程序员

我希望
流水线中增加常量功能, 模板里的常量希望在同步实例时能编辑流水线的常量

以便于
更好使用模板来生成各种差异的实例流水线

**Comment by zanyzhao** [comment]
如果能在流水线实例中编辑，那不就是“流水线变量”吗？目前是有流水线变量的。

**Comment by irwinsun** [comment]
常量可编辑的话。。其实就是变量， 变量是原有功能，无需新增
