### ISSUE TITLE
【回调需求】回调post报文中添加流水线和插件变量信息

### ISSUE THREAD

**Issue by betty1126** [Tencent/bk-ci#991]
1. BUILD_START事件的回调中期望拿到构建号（数字序号）。
2. 报文中期望拿到流水线中能够引用到的变量和插件的输入输出变量值。
3. 回调管理：能够以流水线为单位设置回调，可视化当前配置的回调，并支持删除。

**Comment by irwinsun** [comment]
可以看一下这个需求已经实现： https://github.com/Tencent/bk-ci/issues/6014

但关于界面暂时不考虑实现，还是以接口方式来增删修改
