### ISSUE TITLE
支持跨项目复制/迁移流水线

### ISSUE THREAD

**Issue by goldhillpaladin** [Tencent/bk-ci#999]
### 作为
DevOps 团队里的Dev，要实践持续部署流水线

### 我希望
支持跨项目复制或迁移流水线

### 以便于
- 让不同项目的开发人员共享流水线
- 当项目发生变更时，原项目的流水线可以复用在新项目上

### 期望的验收标准
- 项目A 的流水线可以无损复制或迁移到 项目B

**Comment by iccengan** [comment]
潜在问题：流水线涉及到很多资源权限，如代码库、环境管理、凭证管理等。流水线复制/迁移后，如何在新项目内处理这些资源权限？是否也要提供迁移资源的功能？

**Comment by iccengan** [comment]
这个需求我们可以分开三步完成：
1. 支持流水线导出为yaml文件，参考#1030。
2. 支持将项目下多条流水线导出为一个yaml文件，方便批量修改流水线，以及为后续复制/迁移项目下流水线作准备。
3. 流水线跨项目迁移。

**Comment by irwinsun** [comment]
导入导出其实更适用于跨系统间的，比如从印象笔记导出，再到有道笔记导入。

BK-CI本身提供的模板+研发商店的方式来使用，是可以满足跨项目共享这个场景的。
